### ISSUE TITLE
hist! does not support log scale: suggestion

### ISSUE THREAD

**Issue by walra356** [MakieOrg/Makie.jl#1016]
The suggestion is to introduce an automated log0 value in the function plot!(plot::Hist).
Example:
![image](https://user-images.githubusercontent.com/69215586/120393943-0f289b80-c333-11eb-96f4-efe195d4f850.png)
Minimal code sample:
```
using GLMakie
GLMakie.activate!()
data = abs.(randn(500))
f = Figure(resolution=(500,300))
ax = Axis(f[1,1],yscale=log10)
hist!(ax,data;bins=25,normalization=:probability)
f
```
![image](https://user-images.githubusercontent.com/69215586/120394425-ae4d9300-c333-11eb-8a34-272eb9f360c5.png)

**Comment by ParadaCarleton** [comment]
Related suggestion that might be easy to implement if you're already adding log axes: [Rootograms](https://arxiv.org/pdf/1605.01311.pdf).
