### ISSUE TITLE
How to properly forward attributes in recipes?

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#1019]
In MeshViz.jl I am copying/pasting the list of attributes to inner recipes, and I am probably doing something wrong. What is the recommended method to define a local set of attributes shared by a collection of recipes and a global set of attributes that any Makie plot usually sets? For example, I am calling `colormap` a general attribute and MeshViz.jl defines specific attributes as seen here: https://github.com/JuliaGeometry/MeshViz.jl/blob/master/src/MeshViz.jl

If you check the other files in the repository you will see the redundancy. There must be a better approach that I am not aware of.

**Comment by filchristou** [comment]
are there any updates how to handle such cases ?

**Comment by SimonDanisch** [comment]
Not really... The main blocker is, that it's not really clear how an API for that should look like. If you can help figuring out that API, you could really help moving this forward! :)

**Comment by filchristou** [comment]
I still don't know how to have common attributes shared between a collection of `recipe`s, but currently I am using the following code to forward attributes between different recipes.
I actually use it to wrap already implemented recipes around new ones.

Let's say there is already a recipe called `MyOldRecipePlot`. 
Then I normally define my new recipe with new attributes:
```julia
@recipe(MyNewRecipePlot) do scene
    Attributes(
        mynewattr1 = nothing,
        mynewattr2 = nothing,
    )
end
```

And I implement the recipe to forward attrbute-specific namedtuples to other recipes:
```julia
function Makie.plot!(myNewRP::MyNewRecipePlot) where {T,R}
    # do and plot my new stuff
    # forward attributes to another recipe
    myoldrecipeplott!(myNewRP, myNewRP[:arg1][]; NamedTuple(Makie.attributes_from(MyOldRecipePlot, myNewRP))...)
    return myNewRP
end
```

In order for this to work I also need to define
```julia
Base.NamedTuple(attrs::Makie.Attributes) = NamedTuple([pattr.first => pattr.second isa Attributes ? pattr.second : pattr.second[] for pattr in attrs])
```
, which I think it's a little bit of type piracy.
Do you think such a method could lie directly on the Makie package ?

**Comment by lassepe** [comment]
@juliohm, could you x-ref the PR that fixed this?

**Comment by juliohm** [comment]
This was a question of usage. The current documentation is improved.
