### ISSUE TITLE
Mouse Rotation of Axis3 - is chaotic in WGLMakie

### ISSUE THREAD

**Issue by georgematheos** [MakieOrg/Makie.jl#1027]
When making the following 3D plot using an `Axis3` in WGLMakie, when I use the mouse to try to reorient the axis, the figure begins rotating in 3D in a chaotic manner.

When I make the same plot in GLMakie, the resulting figure is controlled fairly smoothly by the mouse.  (The glitchy WGLMakie version looks identical to the GLMakie version before I try to reorient it with the mouse.)

I also tried making the same plot using `Axis3D` (rather than `Axis3`) in WGLMakie, and the issue does not arise (it is controlled smoothly by the mouse).

As an aside, In my opinion the mouse control is more natural using `Axis3D` in WGLMakie than GLMakie using Axis3.  The GLMakie + Axis3 mouse rotation is pretty good, but the figure rotates faster than the mouse motion appears, which feels a bit less natural than the Axis3D rotation.  But GLMakie+Axis3's mouse control is certainly good enough for controlling the figure, unlike in WGLMakie+Axis3.

I am testing this on MacOS; I used WGLMakie v0.3.10 and tested it in Chrome and Safari; I used GLMakie v0.3.3.

Test code:
```julia
using WGLMakie # or GLMakie
using Distributions

let k = 20,
    xs = 0:0.01:1,
    ys = 0:1/k:1
        surface(xs, ys, [pdf(Binomial(k, x), k*y) for x in xs, y in ys], axis=(type=Axis3,)) 
        # to use Axis3D, just remove the `axis=(type=Axis3,)`
end
```

**Comment by ffreyer** [comment]
This has been fixed some time ago.
