### ISSUE TITLE
Add method for annotations! with tuples

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#1037]
Some functions like `annotations!` currently require users to manipulate `GeometryBasics.Point` explicitly to create the coordinates. A more user-friendly experience would consist of not exporting `Point` or `Vec` and making sure that all plotting functions are described in terms of Julia basic types (tuples and arrays of tuples).

**Comment by bjarthur** [comment]
`text!` works similarly but doesn't require `Point`.  so similarly that i'm not sure what the difference is.

**Comment by asinghvi17** [comment]
We could easily define a `convert_arguments` on the annotations type which converts a `Vector{<: Tuple{<: Tuple{<: Real, <: Real}, <: Any}` or so to a `Vector{Point2f, Any}`.  Would that suffice for your usecase?

**Comment by asinghvi17** [comment]
[This example] shows how you can hook `volumeslices` up to a slider.  As for the axis scale - you should look at the [Axis3 docs](https://docs.makie.org/stable/examples/blocks/axis3/)!  

Basically you can update the positions by `plt[:update_yz][](v)` where `v` is the value you want the slice to be at.  It's not really documented, which we should fix...

**Comment by jkrumbiegel** [comment]
Annotations is just Text and since Text uses scatterlike argument conversion you can pass normal tuples etc to it.
