### ISSUE TITLE
`violin` plot causes GeometricBasics error in some cases

### ISSUE THREAD

**Issue by hexaeder** [MakieOrg/Makie.jl#1060]
I experience this bug multiple times using my real data. Here is the shortes example a could come up with. 
```julia
import Pkg; Pkg.activate(temp=true); Pkg.add("GLMakie")
x = [0, 0, 0, 0, 0]
y = [0.005892723718152748,
     0.00244090848555345,
     0.390786030647279,
     0.0019340779802412555,
     0.00039171093997181217]
violin(x,y)
```
yields
```
ERROR: More than 1 intersections can't be handled currently. Found: [13, 390, 14, 389, 189, 214, 190, 213, 191, 212, 192, 211, 193, 210], Point{2, Float32}[[-0.0, 0.015115301], [0.0, 0.0191938], [-0.0, 0.3740232], [0.0, 0.37810168], [-0.0, 0.3781017], [0.0, 0.3821802], [-0.0, 0.38218015]]
```

It seems like the problem is that there are ⏳-like shapes which have 2 intersections according to `self_intersections` from GeometryBasics.jl. Is this a bug over there? I have no idea about computer graphics, but intuitively I'd think of intersection as crossing rather than contact points...
```julia
julia> points = Point2f0.([(-1.0,-1.0),
                           (0.0,0.0),
                           (-1.0,1.0),
                           (1.0,1.0),
                           (0.0,0.0),
                           (1.0,-1.0),
                           (-1.0,-1.0)])
julia> poly(points) # same error
julia> self_intersections(points)
([1, 5, 2, 4], Point{2, Float32}[[0.0, -0.0], [0.0, 0.0]])
```
<img width="300" alt="grafik" src="https://user-images.githubusercontent.com/35867212/122889714-51963480-d343-11eb-906e-a8f96dca7f00.png">

**Comment by jkrumbiegel** [comment]
Yeah maybe that intersection code could be amended so it doesn't include these as intersections. I don't know how it works exactly but I think it should be safe to ignore cases like you showed without having to expect problems with triangulation.

**Comment by hexaeder** [comment]
The example above is an even more special case because it involes multiple endpoints. Maybe one should look at the intersection between endpoint and line first. Having this an intersection also results in unexpected behaviour in `poly`...
```julia
p = Point2f0.([(0, -1), (0,  1), (1, 1), (0, 0), (1, -1), (0, -1)])
scatterlines(p)
poly!(p)
```
<img width="300" alt="grafik" src="https://user-images.githubusercontent.com/35867212/122901781-27963f80-d34e-11eb-948f-8f0787a302d6.png">

maybe: count AB-CD only as an intersection if CE intersects the infitite extension of AB
<img width="400" alt="grafik" src="https://user-images.githubusercontent.com/35867212/122900358-e81b2380-d34c-11eb-8bde-7e6bb40d43e7.png">

**Comment by jkrumbiegel** [comment]
yes that's what I thought as well, if you feel up to it you could try amending the intersection algorithm in that way

**Comment by juliohm** [comment]
I would like to point out that writing a robust intersection algorithm is not an easy task. We did spend a lot of time in Meshes.jl implementing functions that work well in single and double floating point precision (for 2D segments): https://github.com/JuliaGeometry/Meshes.jl/blob/57e56611bb3a4683d1d6409c1f09141a4df8fc09/src/intersections/segments.jl#L25

Feel free to copy the code over to GeometryBasics.jl. Alternatively, Makie.jl could depend on Meshes.jl to avoid similar geometric processing issues in the future.

**Comment by ffreyer** [comment]
Doesn't error anymore
