### ISSUE TITLE
Error on unsupported keyword arguments

### ISSUE THREAD

**Issue by ericphanson** [MakieOrg/Makie.jl#1076]
I think this is a known problem but I can't find an issue for it so I figured I'd make one. If the user passes a keyword argument that doesn't get picked up anywhere on the pipeline, it should result in an error. Otherwise, they think they are doing something that they aren't (recent example: https://github.com/JuliaPlots/AlgebraOfGraphics.jl/issues/216).

**Comment by SimonDanisch** [comment]
Yeah, the refactor to make this happen should be pretty close, and the next thing I want to work on..

**Comment by ffreyer** [comment]
Closed by #3626 / Makie v0.21

**Comment by maxfreu** [comment]
For plots it works, but what about Figure, Axis or Legend?

```julia
fig = Figure(;noproblem=false)
ax = Axis(fig[1,1])
scatter!(ax, [1], [1]; label="foo")
Legend(fig[2,1], ax; thisshoulderror="but it does not")
ax2 = Axis(fig[3,1]; butthiserrors="and I don't know why it errors here but not for Figure or Legend")
```
Was this in scope of the PR or is it a completely different issue?

**Comment by jkrumbiegel** [comment]
They don't share this infrastructure, so it's a different issue, even though for the user it's the same effect. We should improve messages for Blocks as well. I wasn't aware that `Legend` could swallow wrong keywords.
