### ISSUE TITLE
CairoMakie: coarse text placement

### ISSUE THREAD

**Issue by hexaeder** [MakieOrg/Makie.jl#1084]
Font placement in CairoMakie seems to happen on a pixel level which leads to weird wobbles in animations, especially for non-mono fonts

![cairo_sans](https://user-images.githubusercontent.com/35867212/123785483-df8c9500-d8d8-11eb-8e78-caee0de05944.gif)
![ciaro_mono](https://user-images.githubusercontent.com/35867212/123785485-e0252b80-d8d8-11eb-9989-e7686a4ded66.gif)
![gl_mono](https://user-images.githubusercontent.com/35867212/123785486-e0bdc200-d8d8-11eb-8a75-be7f1721dfca.gif)
![gl_sans](https://user-images.githubusercontent.com/35867212/123785488-e0bdc200-d8d8-11eb-96cb-07f5fd06afda.gif)

produced by:
```julia
import Pkg
Pkg.activate(; temp=true)
Pkg.add("GLMakie")
Pkg.add("CairoMakie")

using GLMakie
using CairoMakie

set_theme!(resolution=(350,80))

function create_anim(file, font)
    x = Node(0.0)
    position = @lift Point($x, 0.0)
    textsize = 35
    fig, ax, p = text(file; position, textsize, font)
    hidespines!(ax); hidedecorations!(ax)
    xlims!(ax, -0.2, 3); ylims!(ax, 0, 2)
    record(fig, file, range(0,1, length=300)) do newx
        x[] = newx
    end
end

GLMakie.activate!()
create_anim("gl_sans.gif", "Dejavu sans")
create_anim("gl_mono.gif", "JuliaMono")
CairoMakie.activate!()
create_anim("cairo_sans.gif", "Dejavu sans")
create_anim("ciaro_mono.gif", "JuliaMono")

```

**Comment by jkrumbiegel** [comment]
It's not Makie, it's Cairo. There are some topics about subpixel glyph placement https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/2 I've even filed issues about it somewhere, and I think I was told at the time that options had been merged into master but not released. The thing is that Cairo's development is very very slow now, so I'm not sure if we can get this feature soon. I guess the only remedy would be to render the video at higher resolution and downsample from there, although it wouldn't be perfect.

**Comment by hexaeder** [comment]
Ahh thanks for the explanation! So I might just use GLMakie or live with the wiggels until a new cairo gets released ^^

**Comment by ffreyer** [comment]
Seems fixed to me
