### ISSUE TITLE
CairoMakie: Allow to rasterize the content of an axis

### ISSUE THREAD

**Issue by Kolaru** [MakieOrg/Makie.jl#1088]
PDF output of some plots sometimes make PDF readers struggle down the line (e.g. highly detailed density maps or transparency issues).

So it would be awesome to be able to mark some axis as to be rasterized when saved, so that their content is just a bitmap image. This would hoepfully solve most of the PDF issues while keeping most of the figure top quality.

**Comment by jkrumbiegel** [comment]
This is a good idea, I was wondering if it makes more sense to do this per plot or per scene (axis). You might have a detailed contour plot with lines on top that should stay crisp, for example.

**Comment by Kolaru** [comment]
In order to avoid transparency issues, I think it has to be done per axis.

If one needs a crisp plot on top of a rasterized one, maybe it is good enough/reasonnable to document it can be done by stacking an unrasterized axis on top of the rasterized one.

**Comment by lhupe** [comment]
matplotlib has [a similar feature](https://matplotlib.org/stable/gallery/misc/rasterization_demo.html?highlight=rasterize); they rasterize per `Artist`. I guess that would be equivalent to rasterizing per plot in Makie.

**Comment by ffreyer** [comment]
@asinghvi17 Didn't you work on a `rasterize` attribute at some point? Did that get finished and does it close this?

**Comment by asinghvi17** [comment]
Yes, this now exists and is a per-plot attribute.
