### ISSUE TITLE
Contourf  for 2d  triangular meshes

### ISSUE THREAD

**Issue by dimaZloy** [MakieOrg/Makie.jl#1096]
Hi!

I have some arbitrary 2d domain (triangulated) and defined by Mesh Nodes and Triangles and 
mesh([ Mesh.xNodes Mesh.yNodes], Triangles, color = colors, shading = false ) works fine. 
But contourf doesn't work, so I just wonder if contourf is limited only for rectangular regular domains? 

Dmitry

**Comment by SimonDanisch** [comment]
What's the contourf supposed to do? `contourf(colors)` and then map the result of that to the mesh?

**Comment by dimaZloy** [comment]
Exactly.

**Comment by dlfivefifty** [comment]
`contourf(::Matrix, ::Matrix, ::Matrix)` is also missing (i.e. instead of triangular meshes, quad meshes). In this case
```julia
surface(x, y, 0*x, color=z)
```
seems to do what I would expect `contourf(x, y, z)` to do.

**Comment by jkrumbiegel** [comment]
There's tricontourf now, does that fix the original issue?

**Comment by ffreyer** [comment]
Since nobody complained I assume it does
