### ISSUE TITLE
Linesegments - Missing corners in segment drawing

### ISSUE THREAD

**Issue by paurierap** [MakieOrg/Makie.jl#1119]
I noticed a weird behavior when plotting segments with corners with ```linesegments```. The issue is that the corners seem to be rounded only if we explicitly provide a color for the segments and are otherwise missing. To exemplify this, if we want to draw the triangle {(0,0), (0,1), (1,1)}, then
```julia
using Makie
segments = [0.0 0.0; 
            0.0 1.0; 
            0.0 1.0; 
            1.0 1.0; 
            1.0 1.0; 
            0.0 0.0]
color = [:red, :red, :red]
fig = Figure()
ax1 = Axis(fig[1,1]) 
ax2 = Axis(fig[1,2])
linesegments!(ax1, segments, color=:red, linewidth=5) # Missing corners
linesegments!(ax2, segments, color=color, linewidth=5) # Round corners
```
![corners](https://user-images.githubusercontent.com/64323465/125601449-e22f26ac-a395-40a2-9daf-e87b073e30ba.png)

The last two differ just from the "filling" in the corners, which is almost imperceptible at default linewidth. Is this an intended feature or just a bug with colors?

**Comment by jkrumbiegel** [comment]
It's an intended hack. I did this because I assumed that linesegments with differing colors per segment were meant to form long lines with changing hues. And they look pretty bad if the segments are not visually connected. The round line caps give the appearance of connected lines. This should be a user setting I think, but GLMakie never supported different line caps so there is no option in Makie to set this which CairoMakie could respect.

**Comment by SimonDanisch** [comment]
Hm, I think `linesegments` should never connect :D That's the whole point of that plot type... If one needs connected lines, one should use `lines`... To be fair, I think linesegments may be used in some places, where it would be nice to have the lines connect...

**Comment by jkrumbiegel** [comment]
We can qualify that this should only be done for `Lines` then (the method is the same as for linesegments. Or we don't do it at all, but then the quality of some plots will suffer. Ideally, we introduce both line-joins and line-caps settings, but that's easy in CairoMakie and probably hard in GLMakie.

**Comment by SimonDanisch** [comment]
We should add line joints/caps to the plot type and implement them in CairoMakie, and warn for now in GLMakie ;) 
It's definitely not impossible to also implement them in GLMakie, just a bit of work.

**Comment by paurierap** [comment]
> Hm, I think `linesegments` should never connect :D That's the whole point of that plot type... If one needs connected lines, one should use `lines`... To be fair, I think linesegments may be used in some places, where it would be nice to have the lines connect...

I get your point, but still trying with ```lines``` gives pointy edges and does not connect and the end at (0,0) neither...
```julia
using Makie
segments = [0.0 0.0; 
            0.0 1.0; 
            0.0 1.0; 
            1.0 1.0; 
            1.0 1.0; 
            0.0 0.0]
color = [:red, :red, :red]
fig = Figure()
ax1 = Axis(fig[1,1]) 
ax2 = Axis(fig[1,2])
lines!(ax1, segments, color=:red, linewidth=5)
lines!(ax2, segments, color=color, linewidth=5)
```

![corners](https://user-images.githubusercontent.com/64323465/125613569-53e7fe46-5255-4eaa-b244-fd8dfd512248.png)

**Comment by ffreyer** [comment]
The behavior is the same now in 0.21 and you can control which `linecap` and `joinstyle` is used with the respective attributes
