### ISSUE TITLE
Rendering of stairs plot is distorted when zoomed out

### ISSUE THREAD

**Issue by robsmith11** [MakieOrg/Makie.jl#1129]
It's great that you've added a stairs plot -- it's super useful for time series.

I've noticed that the rendering seems to be a bit off unless I zoom in.  The horizontal lines seem to be be drawn with a minimum length that is too wide, so they end up sticking out.  For example, it's very noticeable in the following plot (especially near the mouse pointer):
![s](https://user-images.githubusercontent.com/22622548/125913678-68c95ddc-02ea-4a0d-b99a-dc6494d9167b.png)

As a side note, I think `step=:post` may be a more common use case to use as the default.

**Comment by robsmith11** [comment]
I was just trying out Makie again.  GLMakie still has problems with stairs, but I see the rendering is perfect with WGLMakie.

**Comment by SimonDanisch** [comment]
Can you add a minimal working example?

**Comment by jkrumbiegel** [comment]
You can do any line plot from random data like the one above, at some degree of horizontal "squishing" you get these spikes at the tips.

**Comment by robsmith11** [comment]
`stairs(cumsum(randn(10^3)))` should do it

**Comment by robsmith11** [comment]
@SimonDanisch is that patch still a viable workaround that I could apply locally without breaking anything else?
I'd like to switch to Makie from Plotly, but I use this kind of plot all the time, so it's the one thing stopping me.

**Comment by jkrumbiegel** [comment]
@ffreyer is this by chance also part of your line rendering fixes?

**Comment by ffreyer** [comment]
No, but I think I figured out what the problem is at least. I'll see if I can fix it

**Comment by SimonDanisch** [comment]
There is https://github.com/MakieOrg/Makie.jl/pull/2255 which you can try

**Comment by robsmith11** [comment]
@ffreyer 
That looks way better!  Thanks so much for the work you've been doing on refining lines plotting.

It's not easy to find, but if I take a screenshot at a certain density and then zoom into the screenshot, I can occasionally find these small artifacts where the stair extends slightly too far  (in this example look at the top-right corner of the top-most stair):
![s](https://user-images.githubusercontent.com/22622548/221470721-b41d16ba-5107-4fa7-b37e-33ff57843c90.png)
It's really nitpicking, so might not be possible or worth addressing.  As is, it's already a huge improvement.
