### ISSUE TITLE
Indistinguishable regions for maximum values and missing values using contourf

### ISSUE THREAD

**Issue by melodyjulia** [MakieOrg/Makie.jl#1169]
I try to plot a filled contour and find it can't show a region with same maximum values, especially CairoMakie makes it like a region with missing values. The sample code is below:

############################
using CairoMakie

var = zeros(Union{Float32,Missing},(20,20))
var[3:7,5:15] .= missing
var[13:17,5:15] .= 1

fig = Figure()
ax1 = Axis(fig[1,1])
c1 = contourf!(ax1,1:20,1:20,var)
Colorbar(fig[2,1],c1,vertical=false)
current_figure()
############################

**Comment by ffreyer** [comment]
missing and max look different now
