### ISSUE TITLE
allow for single color by number

### ISSUE THREAD

**Issue by hexaeder** [MakieOrg/Makie.jl#1178]
I found myself in a situation where i'd like to use the number+colorrange interface to colormaps for a single color. This fails currently. There is a workaround for GLMakie but i could't get it to work on CairoMakie... ideas?

``` julia
using GLMakie
GLMakie.activate!()

lines([(0,0), (1,1)], color=1, colorrange=(0,2))
# ERROR: program 69 not linked

lines([(0,0), (1,1)], color=[1], colorrange=(0,2))
# wrapping color as workaround works

using CairoMakie
CairoMakie.activate!()

f = lines([(0,0), (1,1)], color=1, colorrange=(0,2))
save("cairo.png", f)
# no method matching red(::Int64)

f = lines([(0,0), (1,1)], color=[1], colorrange=(0,2))
save("cairo.png", f)
# assertion error, length(positions) !== length(colors)
```

Edit: Well for my usecase I've solved it using the `interpolated_getindex` directly... feel free to close this issue if you think this isn't a feature worth implementing.

**Comment by ffreyer** [comment]
This has been fixed
