### ISSUE TITLE
ylabelrotation/rotate_ylabel for Axis

### ISSUE THREAD

**Issue by knuesel** [MakieOrg/Makie.jl#1187]
It would be nice to have a `ylabelrotation` attribute for `Axis` (or maybe a boolean `rotate_ylabel` to complement `flip_ylabel`): sometimes the y label is very short (for example just one symbol) and looks bad rotated 90°.

**Comment by davibarreira** [comment]
Indeed! I've tried doing this manually, but didn't figure it out. Any examples on how to do this? I've tried:
```
ax.elements[:yaxis].attributes[:ylabelrotation]=10
```
with no success.

**Comment by jkrumbiegel** [comment]
Inside yaxis is another elements field, that has the label text object which has a rotation attribute

**Comment by davibarreira** [comment]
If anyone else wants to know how to do it, here it is:
`ax.elements[:yaxis].elements[:labeltext].attributes[:rotation]=20.0`
Thanks @jkrumbiegel !
