### ISSUE TITLE
Convenient way to access the current color cycle

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#1198]
With the new themeing functionalities we can now set our own default color cycle for plotting. That is very nice and important for using Makie for an entire paper's plots.

A functionality of PyPlot.jl that I find very convenient, is that they allow accessing the colors of the set up color cycle via giving as color the values `"C0", "C1", ...`. Can we have something analogous in Makie.jl? I am aware of course I could have a global variable like `COLORS` and index that one, e.g. `COLORS[1]...`. But this script is a bit less transferable to a co-worker. With the "C0" stuff they could run my plotting scripts without necessarily having to go through my themeing process.

Or is this simply too low priority, because truth be told the `COLORS[1]` route isn't that bad.

**Comment by SimonDanisch** [comment]
Would this be related?
https://github.com/JuliaPlots/Makie.jl/issues/1178
I mean, as soon as you create a custom order via "C0", you stop cycling, so I guess the above issue could give you what you want?

**Comment by jkrumbiegel** [comment]
I think the way to go would be something like `color = Cycled(1)` and then the part that connects attributes to cyclers would look up the correct value in the cycle

**Comment by mkborregaard** [comment]
Just FYI in Plots you can just pass an Integer (`color = 2`) and then dispatch does the rest. Not sure I like it, but there it is.

**Comment by Datseris** [comment]
Seems like Cycled(1) is the way to go, although via multiple dispatch I don't see why just 1 could be used like in Plots. I would vote against strings like "C1" anyways, only in python you should have 1000 if states at the start of a function, not in Julia ;)

**Comment by jkrumbiegel** [comment]
I have implemented the `Cycled` way here https://github.com/JuliaPlots/Makie.jl/pull/1248

Here's a docs preview section:

http://makie.juliaplots.org/previews/PR1248/documentation/theming/#manual_specification_of_a_cycled_attribute

> I don't see why just 1 couldn't be used like in Plots

Because this needs to work for any attribute, and we don't know if `Int`s are used for other purposes, which would then conflict. I have ideas for enabling categorical colormap lookup with `Int`s for example, which is different from cycling.

**Comment by Datseris** [comment]
Sure, anyways I think Cycled is great and intuitive, no reason to be ultra greedy! #1248 should close this issue
