### ISSUE TITLE
[DOC] how to change default color cycle with themeing?

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#1199]
The docs have 

![image](https://user-images.githubusercontent.com/19669089/128363072-6d36cc77-287f-4578-baba-8f5aa61f6785.png)

but they don't clarify (1) whether this should be given to an axis or the general theme and (2) how to actually set a new cycle. Is it just `color = [:red, :blue, :green] ` or do I need to involve the `palette` keyword somehow?

**Comment by Datseris** [comment]
e.g. this doesn't change color cycle
```julia
set_theme!(
    rowgap = 5,
    colgap = 5,
    fontsize = 20,
    backgroundcolor = :black, # "#212946",
    cycle = :color,
    color = [:red, :blue, :green],
    Axis = (
        xgridcolor = :white,
        ygridcolor = :white,
        backgroundcolor = :black, # "#212946",
        xgridwidth=0.35,
        ygridwidth=0.35,
        xtickalign=0,
        ytickalign=0,
        xtickcolor = :white,
        ytickcolor = :white,
        bottomspinecolor = :white,
        topspinecolor =:white,
        leftspinecolor =:white,
        rightspinecolor =:white,
        xlabelcolor = :white,
        ylabelcolor = :white,
        xlabelsize = 24,
        ylabelsize = 24,
        xticklabelcolor = :white,
        yticklabelcolor = :white,
        xgridvisible = true,
        ygridvisible = true,
    ),
)
```

**Comment by piever** [comment]
I think `set_theme!(palette = (color = [:red, :blue, :green],)` does what you want, it is at the very end of [this page](http://makie.juliaplots.org/dev/theming.html#Palettes), maybe it could appear more prominently in the docs?

**Comment by Datseris** [comment]
I think instead of having a comment in the code block that is kind of in a mix between human language and computer code, to really have just the computer code. Don't say `pallets: ...`. Have the command set:
```julia
set_theme!(
palette = (color = [:red, :blue, :green],
marker = [:circle, :rect, :utriangle, :dtriangle],
)
```

The human language can be missleading (at least it missled me already)

**Comment by ffreyer** [comment]
Are the docs sufficient now?
https://docs.makie.org/stable/explanations/theming/themes#cycles
