### ISSUE TITLE
WGLMakie text position change when zooming

### ISSUE THREAD

**Issue by cadoubs** [MakieOrg/Makie.jl#1202]
When zooming in 3D (and  rotating on top view) the text does not follow 3D lines. 
The applied scale factor seems different.

This happens only on WGLMakie 0.4.4, not on GLMakie 0.15.0
Julia 1.7.0.β3.0

**Comment by SimonDanisch** [comment]
Yeah... https://github.com/JuliaPlots/GraphMakie.jl/issues/27#issuecomment-890328078
