### ISSUE TITLE
Zero byte image is created when saving fails

### ISSUE THREAD

**Issue by rikhuijzer** [MakieOrg/Makie.jl#1229]
When trying to save an SVG image via the GLMakie backend, a 0-byte image is still created. I suspect this is a kind of bug, because it seems to me very counter-intuitive. 

I would say that it's better to not save a file when the image creation fails. Feel free to close this issue if you don't agree! :smile:

**Comment by jkrumbiegel** [comment]
I agree, but maybe that's a FileIO bug then? GLMakie should just fail for svg, maybe you can take a look at what point the 0-byte file is created.

**Comment by ffreyer** [comment]
Closing as outdated/can't reproduce since there is no example
