### ISSUE TITLE
Feature Request: Gantt Charts

### ISSUE THREAD

**Issue by hdavid16** [MakieOrg/Makie.jl#1237]
The only Julia package that I know of that currently supports Gantt charts is VegaLite.jl (https://www.queryverse.org/VegaLite.jl/stable/examples/examples_barcharts/#Gantt-Chart-(Ranged-Bar-Marks)-1). 

It would be great to have CairoMakie support for these plots.

**Comment by jkrumbiegel** [comment]
```julia
task_starts = [0, 3, 5, 10]
task_ends = [3, 6, 9, 12]
task_positions = [1, 2, 1, 2]

barplot(task_positions, task_ends, fillto = task_starts,
    direction = :x)
text!("task " .* string.(1:4),
    position = Point2f0.(
        (task_starts .+ task_ends) ./ 2,
        task_positions
    ),
    color = :white,
    align = (:center, :center)
)
current_figure()
```

gives this

![grafik](https://user-images.githubusercontent.com/22495855/130203997-45eccd7d-e0ea-454a-812c-223695ff7655.png)

**Comment by hdavid16** [comment]
Looks like a great starting point. Thanks!

**Comment by hdavid16** [comment]
I've built on what you showed @jkrumbiegel to get more features in the gantt chart, in case it helps anybody. 

It could also be nice to get it int he d

```julia

```

**Comment by hdavid16** [comment]
@jkrumbiegel should this issue be closed or do you think there should be a dedicated recipe for gantt charts?
