### ISSUE TITLE
Crash during scroll of linked images.

### ISSUE THREAD

**Issue by RainerHeintzmann** [MakieOrg/Makie.jl#1240]
I tried playing with displaying two images in a grid layout, generated with locked `aspect = DataAspect()` and linked via
`linkxaxes!(ax_im, ax_im2)` and noticed two things: 1. The behaviour seems odd upon scrolling. The lower image does not zoom in as expected but rather its display range was decreasing. 2. After a while of scrolling, I get the following error:
```julia
GLFWError (PLATFORM_ERROR): WGL: Failed to make context current: Das Handle ist ungültig. 
Stacktrace:
 [1] _ErrorCallbackWrapper(code::Int32, description::Cstring)
   @ GLFW ~\.julia\packages\GLFW\BWxfF\src\callback.jl:43
 [2] MakeContextCurrent
   @ ~\.julia\packages\GLFW\BWxfF\src\glfw3.jl:694 [inlined]
 [3] make_context_current
   @ ~\.julia\packages\GLMakie\rXGL8\src\drawing_primitives.jl:46 [inlined]
 [4] fps_renderloop(screen::GLMakie.Screen, framerate::Float64)
   @ GLMakie ~\.julia\packages\GLMakie\rXGL8\src\rendering.jl:26
 [5] renderloop(screen::GLMakie.Screen; framerate::Float64)
   @ GLMakie ~\.julia\packages\GLMakie\rXGL8\src\rendering.jl:48
 [6] renderloop(screen::GLMakie.Screen)
   @ GLMakie ~\.julia\packages\GLMakie\rXGL8\src\rendering.jl:41
 [7] (::GLMakie.var"#50#52"{GLMakie.Screen})()
   @ GLMakie .\task.jl:406
```
Any idea how to fix this?

**Comment by RainerHeintzmann** [comment]
I played a bit with standard figures and could not reproduce the problems in scrolling etc.. Therefore I suspect that this problem arises from some running condition during scrolling. Any idea how to track such a problem down? Its hard since no part of the stack points to some of my code. Maybe deactivating bits of and and see whether the problem persists...
Any other ideas?

**Comment by ffreyer** [comment]
Closing this as outdated/not reproducible/possibly fixed
