### ISSUE TITLE
`contour(::Matrix)` and `contour!(::Axis, ::Matrix)` are undocumented

### ISSUE THREAD

**Issue by kimlaberinto** [MakieOrg/Makie.jl#1249]
It seems like `contour(::Matrix)` and `contour!(::Axis, ::Matrix)` are undocumented on the stable and dev branches.
http://makie.juliaplots.org/stable/plotting_functions/contour.html

I'm planning to do a PR on this to document this as well as include examples in the docs if it would be helpful

**Comment by kimlaberinto** [comment]
See PR #1250

**Comment by ffreyer** [comment]
Not anymore
