### ISSUE TITLE
Add ctrl-click to camera docs

### ISSUE THREAD

**Issue by ggggggggg** [MakieOrg/Makie.jl#1268]
I'm trying to see if Makie can replace my usage of pyplot, which is highly interactive (think make many plot windows, switch between them, zoom in on interesting things). I found in a discourse post that `ctrl-leftclick` zooms back out, but I couldn't find it in the documentation. The closest I found was this page http://makie.juliaplots.org/v0.15.2/documentation/cameras/ but it doesn't include crtl-click.

**Comment by ffreyer** [comment]
That is an `Axis` thing which is actually documented http://makie.juliaplots.org/dev/examples/layoutables/axis/#limit_reset.

The (new) 3d camera has something similar which defaults to the `home` key, the other cameras do not.

**Comment by ffreyer** [comment]
Also part of Camera3D now and Axis3 after merging #4131. (Current Axis3 doesn't have translations so a limits reset doesn't make sense)
Closing as completed
