### ISSUE TITLE
process_interaction example broken

### ISSUE THREAD

**Issue by ggggggggg** [MakieOrg/Makie.jl#1270]
The example using `MyInteraction` struct is broken here: http://makie.juliaplots.org/v0.15.2/examples/layoutables/axis/index.html#function_interaction

Problems I found
1. The line `    if interaction.use_left_click && event.type === MouseEventTypes.leftclick` uses the wrong field name `use_left_click`, the correct field name is `allow_left_click`.
2. For every key press, I get two events, one which changes the state as intended, and a second which changes the state to `(false,false)` independent of what key I pressed. The second event is probably due to reporting "all keys have been picked up".

Here is a working version
```
mutable struct MyInteraction
    allow_left_click::Bool
    allow_right_click::Bool
end

function MakieLayout.process_interaction(interaction::MyInteraction, event::MouseEvent, axis)
    if interaction.allow_left_click && event.type === MouseEventTypes.leftclick
        println("Left click in correct mode")
    end
    if interaction.allow_right_click && event.type === MouseEventTypes.rightclick
        println("Right click in correct mode")
    end
end

function MakieLayout.process_interaction(interaction::MyInteraction, event::KeysEvent, axis)
    isempty(event.keys) && return # key releases cause KeysEvents as well, we will get an empty KeysEvent that we don't want to respond to
    interaction.allow_left_click = Keyboard.l in event.keys
    interaction.allow_right_click = Keyboard.r in event.keys
end

register_interaction!(ax, :left_and_right, MyInteraction(false, false))
```

**Comment by ffreyer** [comment]
Has been fixed
