### ISSUE TITLE
brain is missing?

### ISSUE THREAD

**Issue by AshtonSBradley** [MakieOrg/Makie.jl#1276]
the layout example ran fine for me last week. Now the brain doesn't appear. There is no error about a missing asset, so presumably there is a problem in plotting?

<img width="735" alt="Screen Shot 2021-08-30 at 10 26 58 AM" src="https://user-images.githubusercontent.com/24194258/131267300-96de1f5c-d1a4-4001-af62-ba3306334a21.png">

**Comment by SimonDanisch** [comment]
Hm looks like a WGLMakie bug...probably an error in JS, which only gets shown in the JS console...

**Comment by AshtonSBradley** [comment]
I should have said I was using CairoMakie in Pluto... not sure if that is useful

**Comment by ffreyer** [comment]
It's back
