### ISSUE TITLE
Lift calls callback twice on construction

### ISSUE THREAD

**Issue by j-fu** [MakieOrg/Makie.jl#1303]
Hi, 
when constructing an observable via `lift`, the callback function `f` is called twice:

https://github.com/JuliaPlots/Makie.jl/blob/84d552d6470fd5480baff0d89d932687e8b1cc09/src/interaction/nodes.jl#L9

however, the calculation behind may be expensive. Is there way to prevent this ?

**Comment by j-fu** [comment]
I replaced `Makie.lift(f,o)` by `map(f,o)` in my code. As I understand, 
`Base.map(f,::AbstractObservable)` acts as a constructor:
https://juliagizmos.github.io/Observables.jl/stable/#Base.map-Union{Tuple{F},%20Tuple{F,Observables.AbstractObservable,Vararg{Any,N}%20where%20N}}%20where%20F 
and it seems that this would spare the call currently used for observable construction in `lift`.

**Comment by ffreyer** [comment]
Has been fixed
