### ISSUE TITLE
each `Layoutable` should have its own `Scene`

### ISSUE THREAD

**Issue by goretkin** [MakieOrg/Makie.jl#1308]
This was mentioned my @jkrumbiegel on Slack around the topic of rotating an `Axes`. 

related [discourse](https://discourse.julialang.org/t/permute-x-and-y-axes-of-a-makie-axis/67826/2) and [slack](https://app.slack.com/client/T68168MUP/C8RQUU2KH/thread/C67TK21LJ-1631106154.060600) (will become "dead" shortly)

**Comment by ffreyer** [comment]
That's the case now
