### ISSUE TITLE
LaTeX lines rendered incorrectly when using `text`

### ISSUE THREAD

**Issue by Kolaru** [MakieOrg/Makie.jl#1309]
For example the bar of the sqrt:

```julia
text(L"\sqrt{2}")
```

![image](https://user-images.githubusercontent.com/17861033/132726102-597b7da4-c0c6-42e0-93c7-5474b901b575.png)

Using `space=:data` put the line at the correct place with the correct length, but an incorrect thickness:

```julia
text(L"\sqrt{2}", space=:data)
```

![image](https://user-images.githubusercontent.com/17861033/132726294-ea00dec9-7c1a-4d01-a5f4-ed175b69ee2c.png)

I think it's a Makie bug because using it in labels work just fine.

Examples generated with CairoMakie.

First reported in https://github.com/Kolaru/MathTeXEngine.jl/issues/28

**Comment by jkrumbiegel** [comment]
Yeah this is because the `linesegments` need to be inversely projected first and I didn't have time to figure out how. If anybody feels like it, this would be the place https://github.com/JuliaPlots/Makie.jl/blob/master/src/basic_recipes/text.jl#L162

**Comment by ffreyer** [comment]
A temporary fix for GLMakie and probably WGLMakie would be to pass the camera matrices directly like I did for [DataInspector](https://github.com/JuliaPlots/Makie.jl/blob/5b4eb3b47f3dfe85550904aebd5085f4f0809bb3/src/interaction/inspector.jl#L289). I.e. something along the lines of 
```julia
linesegments!(
    ax, 
     map(pos -> project(
        camera(ax.scene).projectionview[],
        Vec2f(widths(pixelarea(ax.scene)[])),
        apply_transform(transform_func_obs(plot)[], pos)
    ), positions), # this should be changed to update when any of those Observables update
    projection = camera(ax.scene).pixel_space,
    view = Mat4f0(I),
    projectionview = camera(ax.scene).poixel_space,
    ...
)
```

**Comment by jkrumbiegel** [comment]
will be fixed by https://github.com/JuliaPlots/Makie.jl/pull/2020 if it goes through as is

**Comment by ffreyer** [comment]
Is fixed
