### ISSUE TITLE
scatter docstring must display its keyword arguments

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#1311]
https://makie.juliaplots.org/stable/examples/plotting_functions/scatter/#scatter

I'm genuinely concerned that the 2nd most important plotting function (second only to `lines`) doesn't show its input arguments. I thought this was automated and all plotting function did this automatically...?

**Comment by Datseris** [comment]
(I was searching this to find the keyword for marker edge color and width, as its different than PyPlots markeredgecolor)

**Comment by ffreyer** [comment]
And it does!
