### ISSUE TITLE
Cannot `delete!` a `Textbox`

### ISSUE THREAD

**Issue by AayushSabharwal** [MakieOrg/Makie.jl#1354]
I'm trying to build a small(ish) GUI, for which I need to change a menu based on what is selected in the plot. I can `delete!` everything in the menu, except the `Textbox`es. Consider this mockup:
```julia
julia> using GLMakie
julia> fig = Figure()
julia> tb = fig[1, 1] = Textbox()
```
![image](https://user-images.githubusercontent.com/23384717/135623336-51ec21e6-1273-456d-b220-2ab1423f924d.png)

Now, after running `delete!(tb)`

![image](https://user-images.githubusercontent.com/23384717/135623383-3b8c8842-b6e1-4949-8c05-8b9627b5a738.png)

The border for the `Textbox` goes away, but the text itself remains and is editable. Is there any other way to remove `Textbox`es from a figure or toggle their visibility?

I'm currently on Julia 1.6.2 with GLMakie v0.4.6

**Comment by ffreyer** [comment]
This was fixed
