### ISSUE TITLE
Intermittent crashing (`X Error`) when using `GLMakie`

### ISSUE THREAD

**Issue by AayushSabharwal** [MakieOrg/Makie.jl#1376]
Recently when I use GLMakie I get one of two X Errors when I try to plot something. This usually happens on the first plot, but occasionally in the middle of a session too. It causes the entire Julia REPL to crash, which is of course annoying.

Error 1:
```
X Error:  BadAlloc
  Request Major code 152 (GLX)
  Request Minor code 5 ()
  Error Serial #0
  Current Serial #138
```

Error 2:
```
X Error:  BadWindow
  Request Major code 152 (GLX)
  Request Minor code 16 ()
  ResourceID 0x6000009
  Error Serial #0
  Current Serial #179
```

Reproducing:
It's intermittent, but usually this does the trick:
```julia
julia> using GLMakie
julia> lines([(1, 2), (3, 4)])
```

Environment:
Julia 1.6.2, GLMakie v0.4.6
[Project.toml and Manifest.toml](https://gist.github.com/AayushSabharwal/e6ac0c90350b2518a34351ca7431fdd4)

(Below copied from `neofetch`)
```
OS: EndeavourOS Linux x86_64 
Host: Predator PH315-51 V1.26 
Kernel: 5.14.9-arch2-1 
Shell: zsh 5.8 
Terminal: kitty 
CPU: Intel i5-8300H (8) @ 4.000GHz 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
```

I use NVIDIA-prime, so I run julia using `prime-run julia -O 3 -t 8`. Usually I have a sysimage loaded too, but this error occurs without that as well

Output of `prime-run glxinfo | grep OpenGL`:
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 470.74
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 470.74
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 470.74
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

Output of `pacman -Qe | grep nvidia`:
```
nvidia 470.74-5
nvidia-installer-dkms 3.3.9-1
nvidia-prime 1.0-4
nvidia-settings 470.74-1
```

I've tried to provide everything useful I could think of. If there's anything I'm missing, I'll gladly add it too.

**Comment by ffreyer** [comment]
Closing this as outdated/probably fixed
