### ISSUE TITLE
How to use transparency with functions like mesh poly 

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [MakieOrg/Makie.jl#1379]
When searching the documentation for `transparency` I have not found an explanation or tutorial on how to use it. Mostly it says 
` transparency=false`. I tried setting it to `true` and I've tried using a scalar like `0.5` thinking it could mean half transparent, but it did not seem to do anything (no error message either). 

Can you share how to use transparency and perhaps add documentation on it (I can help too if you let me know how this works). 

Thanks. 

Code I tried:  

```julia
] add Makie@0.15.2 GLMakie@0.4.6
```

```julia
using GLMakie, GeometryBasics

V=Point3f[(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0), (2, 1, 1), (2, 0, 1)]
F=QuadFace{Int}[(1, 2, 3, 4), (2, 3, 5, 6)] 

f = Figure()
ax=Axis3(f[1, 1], aspect = :data, xlabel = "x label", ylabel = "y label", zlabel = "z label", title = "Title")
poly!(GeometryBasics.Mesh(V, F), strokewidth=5,shading=true, transparency=0.5)
f
```

**Comment by Kevin-Mattheus-Moerman** [comment]
I see thanks @ffreyer so like this: 
```julia
poly!(GeometryBasics.Mesh(V, F), strokewidth=5,shading=true,color = RGBAf0(1, 0, 0, 0.25),transparency=true)
```
That seems to work partially. It is odd though that the transparency is only for the mesh faces. I cannot for instance see mesh edges or the axis lines through the mesh.

**Comment by ffreyer** [comment]
Closing since OIT has been added.
