### ISSUE TITLE
Incorrect cell size delimiting in JupyterLab and WGLMakie

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#1396]
To reproduce:
```
using IJulia; jypyterlab()
```

Then, open a new notebook and in a new code cell do:
```
using WGLMakie
fig, ax = lines(rand(10))
lines!(ax, rand(10))
fig
```

I get:
![image](https://user-images.githubusercontent.com/19669089/137913030-db589f46-3dbb-4a21-b1fc-6b0b910e362d.png)

The cells are almost entirely hidden. I believe jupyter lab doesn't understand the plot size, and thus doesn't propagate this to the cell size, so the cell has only 1 line (which is the minimum).

I cannot manually increase the output cell size.

**Comment by functorism** [comment]
I can confirm this behavior in both Jupyter Notebook and Jupyter Lab
![2021-11-07-141357_1316x612_scrot](https://user-images.githubusercontent.com/17207277/140661552-602acb61-8a85-44f7-8667-5619513f0876.png)

**Comment by AnselmJeong** [comment]
I've met this same issue a while ago, and it has not been properly dealt with.

I'm just curious whether using WGLMakie would allow me to use interactive feature of GLMakie in JupyterLab notebook.
