### ISSUE TITLE
title above two columns with xaxisposition=:top

### ISSUE THREAD

**Issue by briochemc** [MakieOrg/Makie.jl#1397]
Overall title (using `Label`) is placed on top of the axis instead of top of the protusion of the x-axis ticks and labels. MWE:

```julia
f = Figure()
ax1 = Axis(f[1,1], xaxisposition=:top, xlabel="variable 1")
ax2 = Axis(f[1,2], xaxisposition=:top, xlabel="variable 2")
Label(f[1, 1:2, Top()], "overall title", color=:red)
```

gives

<img width="396" alt="Screen Shot 2021-10-20 at 1 17 18 pm" src="https://user-images.githubusercontent.com/4486578/138016974-16eef225-47d4-49de-8a09-85d78d215a3e.png">

Obvious workaround is to move the red title up with padding, but I thought maybe it should automatically be placed above the protrusions of the xaxis if it is on top?

**Comment by ffreyer** [comment]
@jkrumbiegel Is this a bug, a reasonable feature request or something that's working as intended/a wont-fix?

**Comment by briochemc** [comment]
I'm not sure if it worked at the time but now one can simply use 

```julia
Label(f[0, 1:2], "overall title", color=:red)
```

instead to get 

![supertitle_makie](https://github.com/user-attachments/assets/d537ca19-5e96-49dd-80f3-d7e417b1babd)

so I think this can be safely closed.

**Comment by jkrumbiegel** [comment]
The original issue was also due to user error as `Top()` would have ignored the other elements' protrusions.
