### ISSUE TITLE
Automatic colorbar limit setting error when min=max

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [MakieOrg/Makie.jl#1400]
The animation below shows that when the colorbar limits are automatically chosen there is an error when there is no variation in the color data i.e. when the max=min. When the minima and maxima are equal to within some tolerance, perhaps the colorbar limits should then default to have limits of min=mean-1 and max=mean+1 or something similar, either way, this type of thing can happen often so it would be nice if it can gracefully handle it. 

In this example I modulate `zs` such that it is scaled by `s` which is set by the slider and can be made zero such that the color bar issue will occur: 
```julia
using GLMakie

xs = range(0, 10, length = 25)
ys = range(0, 15, length = 25)
fig = Figure()
sl = Slider(fig[2, 1], range = 0:0.1:3, startvalue = 1)
zs = lift(sl.value) do s
    convert(Float64,s).*[cos(x) * sin(y) for x in xs, y in ys]
end
titleString = lift(sl.value) do s
    "Step: "*string(s)
end
ax = Axis(fig[1, 1], title = titleString)
hm=heatmap!(xs, ys, zs,colormap = Reverse(:Spectral))
Colorbar(fig[1, 2],hm,label = "Values")
fig
```

![Peek 2021-10-22 16-06](https://user-images.githubusercontent.com/8392709/138478554-2aea1c17-be4e-4ba7-81b3-32ed2af7f5d8.gif)

**Comment by Kevin-Mattheus-Moerman** [comment]
@SimonDanisch note I propose a fix: 

> When the minima and maxima are equal to within some tolerance, perhaps the colorbar limits should then default to have limits of min=mean-1 and max=mean+1

**Comment by ffreyer** [comment]
This got fixed at some point
