### ISSUE TITLE
Every `display()` adds a new screen to `scene.current_screens` in GLMakie and CairoMakie

### ISSUE THREAD

**Issue by ffreyer** [MakieOrg/Makie.jl#1402]
Example:

```julia
scene = Scene()
scene.current_screens
# 1-element Vector{AbstractScreen}:
#  GLMakie.Screen(...)
display(scene)
scene.current_screens
# 2-element Vector{AbstractScreen}:
#  GLMakie.Screen(...)
#  GLMakie.Screen(...)
```

This happens in GLMakie and CairoMakie, but not WGLMakie. I didn't test the new backend. In GLMakie these screens are identical (===), in CairoMakie they are not.

I'm on master, i.e. https://github.com/JuliaPlots/Makie.jl/tree/78820311c9b45347f0937caf8b31a25bbc27dd73

**Comment by SimonDanisch** [comment]
I think this shouldn't be happening anymore!
