### ISSUE TITLE
Multiple axes performance issues

### ISSUE THREAD

**Issue by MichaelHatherly** [MakieOrg/Makie.jl#1420]
When plotting numerous axes into a figure with:

```julia
function example(n, m)
	figure = Figure()
	axes = Axis[]
	for i in 1:n, j in 1:m
		pos = figure[i, j]
		ax, pt = scatter(pos, 1:10, rand(10))
		push!(axes, ax)
	end
	linkaxes!(axes...)
	return figure
end

times = [@timed(example(n, n)) for n in 1:10]
```

performance appears to not scale too well. A single `Axis` takes roughly 0.078s while a grid of 100 linked axes takes 35s. I'd assume this might be related to the comment in https://github.com/JuliaPlots/Makie.jl/issues/1335#issuecomment-932880717 about the amount of relayouts per axis perhaps?

![image](https://user-images.githubusercontent.com/6144086/139642234-f51d2132-2c71-49d5-a285-c29aba1c9424.png)

**Comment by jkrumbiegel** [comment]
You could defer relayouting by adding the axes without layout positions, then assigning them while the layout update mechanism is turned off.

```julia
n = 10

@time begin
    f = Figure()

    axs = map(Iterators.product(1:n, 1:n)) do (i, j)
        Axis(f)
    end

    linkaxes!(axs...)

    with_updates_suspended(f.layout) do
        f[1:n, 1:n] = axs
    end

    f
end

@time begin
    f = Figure()

    axs = map(Iterators.product(1:n, 1:n)) do (i, j)
        Axis(f[i, j])
    end

    linkaxes!(axs...)

    f
end
```

**Comment by jkrumbiegel** [comment]
Ah this also works, just wrapping it with `with_updates_suspended`

```julia
@time begin
    f = Figure()

    with_updates_suspended(f.layout) do

        axs = map(Iterators.product(1:n, 1:n)) do (i, j)
            Axis(f[i, j])
        end

        linkaxes!(axs...)
    end
    
    f
end
```

**Comment by MichaelHatherly** [comment]
Thanks, that appears to have helped out a fair bit. Is `with_updates_suspended(f.layout)` considered public API that's stable for use?

**Comment by SimonDanisch** [comment]
I sure hope that we'll come up with something better... But maybe we can make it a somewhat stable hack, @jkrumbiegel ?

**Comment by jkrumbiegel** [comment]
Well I'm not sure if it's a hack, I've had this function in GridLayoutBase for a while. The thing is, with all these Observables, updates are synchronous. So each time you add an object to a layout, the whole thing is solved anew, and every other object must update accordingly. Just that if you know you're going to add multiple objects, you can wait with the GridLayout solve until all objects are added. That's what's going on here, you can't really make that behavior implicit though.

But we can probably improve the time it takes an Axis to react to a relayout. That probably triggers too much stuff right now.

**Comment by SimonDanisch** [comment]
>That's what's going on here, you can't really make that behavior implicit though.

Well, as an example, we could have a construction phase and only calculate layouts on display... Or something like that ;)

**Comment by ffreyer** [comment]
I get 3.7s for the last 10x10 case so I assume this is fixed
