### ISSUE TITLE
textsize/fontsize inconsistency

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#1422]
When setting a theme, one uses the kwarg `fontsize`.
When creating a Label, one uses the kwarg `textsize`.

They each give the most sense in their current context, but I feel that it is the opposite of user-friendly to have these two things, which mean the same from the user-perspective, to have different kwargs.

Because changing a kwarg is breaking, I suggest that the two kwargs should give the same result in both contexts, aka be aliases of eachother.

**Comment by andrewwinters5000** [comment]
I think that this can be resolved as the `textsize` keyword argument has been removed in #2387
