### ISSUE TITLE
Docs: Add small preview of plot up top so user doesn't have to scroll down when browsing?

### ISSUE THREAD

**Issue by IanButterworth** [MakieOrg/Makie.jl#1424]
What you first see when landing on each plot type page lacks a visual example given they're further down the page.

To save the user having to scroll down on each example, perhaps a preview could be shown beside the plot type name? i.e. here to the right of "boxplot"

<img width="1253" alt="Screen Shot 2021-11-02 at 4 08 46 PM" src="https://user-images.githubusercontent.com/1694067/139944781-b35ef417-f337-4572-87ce-8620b1c61da1.png">

**Comment by ffreyer** [comment]
This has sort of happened. Attributes are now at the bottom, so you get to examples more quickly. The overview page also shows you miniatures directly
