### ISSUE TITLE
GLMakie slow update of displayed image

### ISSUE THREAD

**Issue by MariusDrulea** [MakieOrg/Makie.jl#1426]
I have the code bellow, a figure is created and the image inside the figure (the observable x) is updated in a for loop.
`28.948570 seconds (293.42 k allocations: 9.009 GiB, 3.88% gc time)`
We have about 28 seconds in total so it takes about 0.28 seconds to update and refresh the displayed image. If we have 3 such images to display in a subplot this takes about 1 second. Now we add loops to process recorded sequences and the resulted overall runtime is pretty high. Given the large number of allocations reported by @time, looks like this can be significantly improved.

```
##
x = Observable(rand(2000, 2000))
fig2, ax2, plotobj2 = plot(x)

##
@time begin
for i in 1:100
    x[] = rand(2000, 2000)
    ax2.title = "animation tutorial $i" 
    sleep(0.01)
end
end
##
```

**Comment by SimonDanisch** [comment]
I think this uses a heat map which is much slower than image

**Comment by MariusDrulea** [comment]
Likely, I close it as I no longer use heatmap. I only use image now. Will re-open if I observe this issue with image as well.
