### ISSUE TITLE
alpha for `contourf`?

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/Makie.jl#1431]
any way to set an `alpha` (transparency) for the `contourf` so I can draw points over it?

also, to precisely define the colors I needed to create my own custom `ColorScheme`. this doesn't seem to accept `alpha`'s.
```
my_colormap = ColorSchemes.Dark2_5
myscheme = ColorScheme([my_colormap[1], my_colormap[2]])
contourf!(alc, ma, dt_prediction, 
levels=[-1.1, 0.5, 1.1], color=:black, colormap=myscheme, alpha=0.2)
```

![image](https://user-images.githubusercontent.com/30643894/140437893-b65580e2-4710-42ee-aa76-7e313094b0c9.png)

**Comment by ffreyer** [comment]
You can do `colormap = RGBAf.(myscheme, 0.2)`. You can also move scatter markers forward with `translate!(plot, 0, 0, 1)`

**Comment by SimonEnsemble** [comment]
@ffreyer thanks a ton.

not closing yet b/c would be great to add this to the docs? or does this belong in `ColorSchemes`...? I wonder.

![image](https://user-images.githubusercontent.com/30643894/140592301-c65b505d-801a-4097-9128-c1e51bff25a0.png)

**Comment by ffreyer** [comment]
The color docs mention this now
