### ISSUE TITLE
transparent heatmap

### ISSUE THREAD

**Issue by goretkin** [MakieOrg/Makie.jl#1449]
```julia
using GLMakie

fig = Figure()
ax = Axis(fig[1, 1], title = "Demo")
heatmap!(ax, rand(10, 10), colormap=:reds, alpha=0.5)
heatmap!(ax, rand(15, 15), colormap=:greens, alpha=0.5)
fig
```

displays
<img width="402" alt="image" src="https://user-images.githubusercontent.com/581043/142008035-9cbe177b-c525-40bc-9a38-7c8bf5284b11.png">

There was a recent comment on slack saying it should be possible to do e.g. `colormap=(:red, 0.5)`, but that causes an error.

**Comment by ffreyer** [comment]
Has been fixed
