### ISSUE TITLE
Colormap value clipping does not work in colored scatter

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#1464]
MWE
```julia
using GLMakie
x = rand(1000)
y = rand(1000)
z = rand(1000)
z[1:100] .= -99
fig = Figure(); display(fig)
ax = Axis(fig[1,1])
sc = scatter!(ax, x, y; 
    color = z, colormap = :viridis, colorrange = (0, 1),
    lowclip = :red,
)
Colorbar(fig[1,2], sc)
```

![image](https://user-images.githubusercontent.com/19669089/142625314-8cf5cd64-e349-480f-8e0c-18c61e8d14a0.png)

I would expect to see red points and a red triangle in the colormap. 

If this is not allowed in scatter, can you please document how to do it for scatter with other means? I got this example from the documentation of `Colorbar` page.

**Comment by ffreyer** [comment]
It does now
