### ISSUE TITLE
Rotating Scene in CairoMakie is not working properly

### ISSUE THREAD

**Issue by davibarreira** [MakieOrg/Makie.jl#1476]
I was trying to rotate a plot (and axis) to produce a visualization like this one below:
![image](https://user-images.githubusercontent.com/6407557/143333206-cf0b4206-8a6f-4d2f-864c-08b232fcd80d.png)
I've posted the question and the following answer was given:
```julia
fig = Figure()
b = Axis(fig[1, 1])
scene = Scene(fig.scene)
campixel!(scene)
ax = Axis(scene, bbox = MakieLayout.BBox(-100, 100, -100, 100))

for s in (scene, ax.scene)
    Makie.rotate!(s, Vec3f(0,0,1), -pi/4)
    translate!(s, Vec3f(300, 300, 100))
end
fig
```
Unfortunately, this does not work on CairoMakie. As pointed out by @ffreyer who posted this solution: "This works for me in GLMakie but CairoMakie still has two problems - text gets transformed differently and disappears, and the background pane of the rotated axis doesn’t draw over the normal axis. I think these are things that need to fixed in CairoMakie though."

**Comment by ffreyer** [comment]
Text rotation has been fixed so I assume this can be closed
