### ISSUE TITLE
Is there a way to show data point with png image using WGLMakie?

### ISSUE THREAD

**Issue by yuehhua** [MakieOrg/Makie.jl#1479]
I found a way to do this is from [this stackoverflow](https://stackoverflow.com/questions/65075372/how-to-plot-data-points-with-small-pieces-of-png-images-in-julia-or-in-makie-jl).
But it is only for GLMakie. I want it to show on web using WGLMakie.
Is there any other way to do this? Or is there any plan to add this new feature to WGLMakie?

**Comment by jkrumbiegel** [comment]
Could be that this feature just hasn't made it to WGLMakie yet, but as far as I know GLMakie and WGLMakie are supposed to share more and more code in the future. So it would probably not be much effort to transfer the implementation over.

**Comment by SimonDanisch** [comment]
This should be implemented for WGLMakie now, at least for a single image marker
