### ISSUE TITLE
Text transformations

### ISSUE THREAD

**Issue by ffreyer** [MakieOrg/Makie.jl#1483]
I noticed in #1482 that the model matrix for screen-space text is applied after the the view and projection matrix. I.e. it goes `(pixel_space * model) * (projection * view * text.position)` in GLMakie. This means that `translate!()` acts in pixel units for text and the y direction (or x?) is inverted. 
Should we change this to be model first, like usual?

**Comment by jkrumbiegel** [comment]
That sounds reasonable, it actually sounds very weird how it's implemented right now. That's probably because we don't have any test cases with model matrices other than identity.

**Comment by ffreyer** [comment]
Thanks for not posting an example me. Code looks fixed to me though
