### ISSUE TITLE
zlabel in Axis3 causes plot to vanish

### ISSUE THREAD

**Issue by stelmo** [MakieOrg/Makie.jl#1492]
Hi, I am using CairoMakie (v.0.6.6) and noticed that the `zlabel` attribute in `Axis3` causes the plot to vanish if it is a LaTeXString. This is not a priority for me, but I thought I should let you know that something is broken. Here is a MWE:

```julia
using CairoMakie, LaTeXStrings

fig = Figure(font = fontpath, fontsize = 24)
ax = Axis3(
    fig[1,1],
    xlabel = L"x_1",
    ylabel = L"x_2",
    # zlabel = L"causes issues",
    aspect = :data,
    perspectiveness = 0.5,
    elevation = π / 9,
)
xs = LinRange(0, 10, 100)
ys = LinRange(0, 15, 100)
zs = [cos(x) * sin(y) for x in xs, y in ys]
surface!(ax, xs, ys, zs)
fig
```

ps. Makie is awesome :)

**Comment by asinghvi17** [comment]
Just to ping from the other thread: this appears to be mostly fixed on the current master
![iTerm2 sRF00r](https://user-images.githubusercontent.com/32143268/166400528-825a7d32-5699-4949-9123-e001405a2153.png)
although the y label's rotation is still off.

**Comment by ffreyer** [comment]
Yea, looks like it's fixed
