### ISSUE TITLE
[feature request] LaTeXString Legend entry is not defined

### ISSUE THREAD

**Issue by HenriDeh** [MakieOrg/Makie.jl#1495]
It is currently impossible to use LaTeXStrings in Legend entries. It would be nice so I'm opening this issue. Here's a MWE:
```
using CairoMakie, LaTeXStrings
fig = Figure()
Legend(fig[1,1], [LineElement(color = :black, linestyle = :dash), LineElement(color = :black, linestyle = :dash)],[L"x_t", L"y_t"])
fig
```

**Comment by fatteneder** [comment]
Issue seems to be fixed on `master`:
![image](https://user-images.githubusercontent.com/26469701/197044786-507d4fd0-38ee-4721-9dd8-e9e248359f1c.png)

Mind closing?
