### ISSUE TITLE
resize figure resolution to fit contents so that there is no padding / margin

### ISSUE THREAD

**Issue by goretkin** [MakieOrg/Makie.jl#1523]
Some image editing programs have a command to crop to content. Can the same be done with Makie?

```julia
using Makie
fig = Makie.Figure(
    figure_padding = 0,
#   resolution = (800, 700),
)
ax = Axis(fig, title="solution workspace")
fig[1, 1] = ax

hidedecorations!(ax)
ax.titlevisible=false
heatmap!(ax, rand(8, 7))
ax.aspect = Makie.DataAspect()
Makie.tightlimits!(ax)

display(fig)

@show Makie.GridLayoutBase.tight_bbox(fig.layout)
```

produces a letter-boxed image, because the default resolution is `(800, 600)`. 

The new `resize_to_layout!` is not for this case, as far as I can tell.
https://github.com/JuliaPlots/Makie.jl/blob/4898ff43046d7571f002ce24c66d03653668bacc/src/figures.jl#L144

**Comment by ndgnuh** [comment]
I stumbled on this issue while searching for ways to remove the white margin around the figure.
Thanks for the `figure_padding` xD.

For your issue, you can set `width` and `height` for `Axis`.
```julia
let fig = Figure(figure_padding=0)
    ax = Axis(fig[1, 1], width=700, height=800, aspect=DataAspect())
    
    heat = heatmap!(ax, rand(7, 8))
    
    hidedecorations!(ax)
    Makie.tightlimits!(ax)
    resize_to_layout!(fig)
    save("/tmp/test.png", fig)
    fig
end
```

Here's the result:
![test](https://github.com/MakieOrg/Makie.jl/assets/33273948/6cb9d035-6ea9-4c71-ba05-d94597cd1379)
Perfectly sized, as all things should be.

**Comment by jkrumbiegel** [comment]
Good example, I think this can be closed :)
