### ISSUE TITLE
How I can change axes, once they are in GridLayout? 

### ISSUE THREAD

**Issue by jaehongpark-neuro** [MakieOrg/Makie.jl#1529]
I'm trying the gridlayout tutorial in the Makie document.

As the layout being defined in the sub_grid in the following example and lines!(), I thought GridLayout can be recognized as an array of axes.

But once I pass the sub_grid element in xlims! function, it does not work. 

ERROR: LoadError: MethodError: no method matching xlims!(::GridPosition, ::Tuple{Int64, Int64})
Closest candidates are:
  xlims!(::Any, ::Any, ::Any) at C:\Users\hongs\.julia\packages\Makie\xbI6d\src\makielayout\layoutables\axis.jl:1189 
  xlims!(::Scene, ::Tuple{Real, Real}) at C:\Users\hongs\.julia\packages\Makie\xbI6d\src\shorthands.jl:100
  xlims!(::Axis, ::Any) at C:\Users\hongs\.julia\packages\Makie\xbI6d\src\makielayout\layoutables\axis.jl:1155  

if I hit sub_grid[1,1].layout, then returns
GridLayout[2, 1] with 2 children
 ┣━ [1, 1] Axis
 ┗━ [2, 1] Axis

So, how I can access these axes to modify their attributes, such as limits or something?

figure = Figure(resolution = (1000,600))
spcolor = :black

sub_grid = GridLayout()
sub_grid[1:2,1] = [Axis(figure) for i in 1:2]
figure.layout[1,1] = sub_grid

lines!(sub_grid[1,1],time_down,air_down,color=:red,linewidth=2)
xlims!(sub_grid[1,1],0,20)

**Comment by visr** [comment]
Looks like you are looking for the `contents` / `content` functions, see https://makie.juliaplots.org/stable/documentation/figure/index.html#retrieving_objects_from_a_figure.

**Comment by davidAdeshinaArungbemi** [comment]
Need this thanks!

**Comment by ffreyer** [comment]
@jkrumbiegel Is this something we want to consider supporting? (I.e. `sub_grid[1, 1]` being some kind of Block-like object that can be used as the related Block?)

**Comment by jkrumbiegel** [comment]
No, I think that gets too complicated. Better to extract the objects out first

**Comment by ffreyer** [comment]
Ok, closing this then (use content instead)
