### ISSUE TITLE
allow for different line widths in lines

### ISSUE THREAD

**Issue by lazarusA** [MakieOrg/Makie.jl#1541]
At the moment is possible to do several lines at once by [NaN separation](https://makie.juliaplots.org/stable/examples/plotting_functions/lines/index.html). Different colours also works, however passing a set of values for different line widths is not supported, as in linesegments. It would be nice to have this feature for lines, which in all my tests is the fastest one to plot thousands of lines at once.

**Comment by rveltz** [comment]
Yes, here is the MWE I have in mind:

```julia
using GLMakie
x=LinRange(0,2pi,100)
lines(x, sin.(x), linewidth = 0.19) # works
lines(x, sin.(x), linewidth = collect(x)) # does not
```

we get:

```
julia> lines(x, sin.(x), linewidth = collect(x)) # does not
Error showing value of type Makie.FigureAxisPlot:
ERROR: MethodError: Cannot `convert` an object of type Vector{Float32} to an object of type Float32
```

**Comment by lazarusA** [comment]
I was thinking more like:

```julia
using GLMakie
points = [Point2f(0.0, 0.0), Point2f(0.0, 1.0), Point2f(NaN, NaN),
    Point2f(1.0, 0.0), Point2f(1.0, 1.0)]
lines(points; color = [1, 1, 1, 2, 2], linewidth = 5)
```
this one works, but this one

```julia
points = [Point2f(0.0, 0.0), Point2f(0.0, 1.0), Point2f(NaN, NaN),
    Point2f(1.0, 0.0), Point2f(1.0, 1.0)]
lines(points; color = [1, 1, 1, 2, 2], linewidth = [2,5])
#lines(points; color = [1, 1, 1, 2, 2], linewidth = [2,2,2,5,5]) # does not work also
```
fails.

**Comment by SimonDanisch** [comment]
Different linewidth in connected lines is a bit cumbersome... linesegments supports it though, since it doesn't need to worry about joins.

**Comment by lazarusA** [comment]
yes `linesegments` works at some level. In my case it crashes my Julia session for large numbers whereas `lines` is completely ok and fast. Bottom line, I was just wondering about the possibilities. For now I'm adding a transparency for small line widths which helps hiding a little bit those lines.

**Comment by SimonDanisch** [comment]
> In my case it crashes my Julia session for large numbers whereas lines is completely ok and fast

Oh thats pretty weird...Linesegments should be way more efficient...

**Comment by lazarusA** [comment]
ahh, plus I forgot to mention my lines are not straight ones, which is the use case of line segments.

**Comment by rveltz** [comment]
> Different linewidth in connected lines is a bit cumbersome... linesegments supports it though, since it doesn't need to worry about joins.

How come, `Plots.jl` provides it

**Comment by jkrumbiegel** [comment]
Can you show an example of Plots.jl? I can imagine that it works if segments separated by NaNs have constant linesegments, otherwise the Cairo/vector graphics limitations should apply.

**Comment by rveltz** [comment]
https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/tutorials/Swift-Hohenberg1d/#d-Swift-Hohenberg-equation-(Automatic)

**Comment by SimonDanisch** [comment]
>How come, Plots.jl provides it

I didn't say it's impossible 🤷 And as I said, with linesegments it's pretty easy, wouldn't be surprised if that's what plots does for different linewidths. Maybe there could be a hybrid to just start a new connected line with every linewidth change...

>yes linesegments works at some level. In my case it crashes my Julia session for large numbers whereas lines is completely ok and fast

Can you open an issue with an MWE? That must be a bug!

**Comment by rveltz** [comment]
I see,  should I write my own using dispatch on `linewidth`?

**Comment by SimonDanisch** [comment]
>https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/tutorials/Swift-Hohenberg1d/#d-Swift-Hohenberg-equation-(Automatic)

Hm, that does look like proper connected joints though... I guess our best bet to support that right now, would be via `bands` or generating our own mesh...

**Comment by SimonDanisch** [comment]
Although, when I look at it again, it looks like the scatter markers hide all the joints, so can't really tell if they have proper joints... So, I guess with a scatter like that, one may get away with linesegments

**Comment by rveltz** [comment]
```
Plots.plot(x, sin.(x), linewidth = vcat(ones(50), 10 .*ones(50)))
```
![Screen Shot 2022-01-05 at 12 15 29](https://user-images.githubusercontent.com/1591812/148208989-97e5157d-dc96-4170-ab78-b43d60ec47ef.png)

**Comment by jkrumbiegel** [comment]
Ok so you see that it's actually all linesegments, no joins. Which makes sense

**Comment by vchuravy** [comment]
I just ran into this, and the NaN requirement is kinda frustrating.

I wanted to reproduce the plot in https://discourse.julialang.org/t/seven-lines-of-julia-examples-sought/50416/197?u=vchuravy with CairoMakie.

**Comment by vchuravy** [comment]
In case anyone is interested, the solution using line segments looks roughly:

```julia
	function chaseplot!(ax, points, linewidth; kwargs...)
		# Use linesegments, but this requires quite a bit of data munging
		linewidths = similar(linewidth, 0)
		segments = similar(points, 0)
		push!(segments, points[1])
		push!(linewidths, linewidth[1])
		for i in 2:(length(points)-1)
			push!(segments, points[i]) # end prior
			push!(linewidths, linewidth[i-1])
			
			push!(segments, points[i]) # start next
			push!(linewidths, linewidth[i])
		end
		push!(segments, points[end])
		push!(linewidths, linewidth[end-1])
		linesegments!(ax, segments, linewidth=linewidths; kwargs...)
	end
	function chaseplot!(ax, xs, ys, linewidth; kwargs...)
		points = [Point2(x, y) for (x, y) in zip(xs, ys)]
		chaseplot!(ax, points, linewidth; kwargs...)
	end
```
