### ISSUE TITLE
Remote server WGLMakie stopped working

### ISSUE THREAD

**Issue by h-spiess** [MakieOrg/Makie.jl#1542]
Hey,

I have been using WGLMakie on a remote server for quite some time.

I access the server via ssh with vscode and forward port 9284.

When plotting with WGLMakie...
```
using WGLMakie
x, y = randn(10), randn(10)

scatter(x, y)
```

... nothing appears and the plot is not showing up. This has not happened before. Unfortunately, I can't check if this is due to my ssh server setup.

`[276b4fcb] WGLMakie v0.4.7`

I have only updated vscode to 1.6 in the meantime (and rolled back to 1.5 to check but this also didn't work).

Thanks :)

**Comment by SimonDanisch** [comment]
I heard, that there were some problems with the automatic vscode port forwarding... 
There is also a chance, that this [PR ](https://github.com/SimonDanisch/JSServe.jl/pull/105) made it stop working...
To check you can try reverting that config change by running this code before anything else:
```julia
using JSServe
JSServe.configure_server!(
listen_url="0.0.0.0", # or "127.0.0.1"
listen_port=9284, )
```

**Comment by h-spiess** [comment]
Thanks. I will try that next, bc. ...

... I tried WGLMakie in VSCode locally and this does not work too. Can this be reproduced?

**Comment by SimonDanisch** [comment]
Huh, I also don't get a plot anymore. This may be a regression in VSCode...

**Comment by SimonDanisch** [comment]
Disabling the plotpane & using `JSServe.browser_display()` does still work... This shows the plot in the browser..
