### ISSUE TITLE
Regression using `Orthographic` projection

### ISSUE THREAD

**Issue by t-bltg** [MakieOrg/Makie.jl#1572]
Thanks for the hard work done towards `0.16`.

Here is a regression observed:

```julia
using GeometryBasics
using GLMakie

main() = begin
  X = [0. 1 1 2; 1 1 2 2; 0 0 1 1]
  Y = [1. 1 1 1; 1 0 1 0; 0 0 0 0]
  Z = [1. 1 1 1; 1 0 1 0; 0 0 0 0]
  C = [.5 1. 1. .5; 1. .5 .5 .1667; .333 .333 .5 .5]

  xyz = reshape([X[:] Y[:] Z[:]]', :)
  fig, ax, plt = fap = poly(
    connect(xyz, Point{3}),
    connect(1:length(X), TriangleFace);
    color=C[:], strokewidth=1
  )

  cam = cam3d!(ax.scene, projectiontype=Makie.Orthographic)
  update_cam!(ax.scene, cam)  # <== needed with 0.16.1, not with 0.15.3

  target_aspect = 1 ./ widths(Makie.data_limits(ax.scene))
  target_aspect /= sum(target_aspect) / length(target_aspect)
  scale!(ax.scene, target_aspect...)

  save("poly3d.png", fap)
end

main()
```

0.15.3
---
![poly3d-1 6 5](https://user-images.githubusercontent.com/13423344/148695326-8cf53b8d-0db4-4751-b7f1-62a87c804717.png)

0.16.1
---
![poly3d-1 7 1](https://user-images.githubusercontent.com/13423344/148695335-3a04249e-1855-4c95-b235-fbb425550857.png)

1. ~~An extra `update_cam!(ax.scene, cam)` is needed to get the `Orthographic` proj in `0.16.1`, else it remains as `Perspective`.~~ ==> fixed by https://github.com/JuliaPlots/Makie.jl/pull/1573.
2. The view is not isometric anymore.
3. ~~The zooming factor seems incorrect.~~ ==> solved by adding `center!(ax.scene)` before `save(...)`

EDIT: Here are the numbers:

**0.15.3**
(w, h, near, far, aspect, cam.zoom_mult[]) = (1.7950313f0, 1.3275752f0, 0.25438568f0, 7.63157f0, 1.3521127f0, 1.526314f0)

**0.16.1**
(w, h, near, far, aspect, cam.zoom_mult[]) = (1.1760564f0, 0.8697917f0, 0.1f0, 100.0f0, 1.3521127f0, 1.0f0)

**Comment by ffreyer** [comment]
I think it's still isometric. If you rotate the plot a bit you get the same as before. My guess would be that some changes happened with bounding box calculations and as a result the default eyeposition and lookat changed a little

**Comment by ffreyer** [comment]
Closing this since there isn't actually anything wrong with Orthographic.
