### ISSUE TITLE
Broken camera rotation with upvector Z = 0

### ISSUE THREAD

**Issue by da-mi** [MakieOrg/Makie.jl#1600]
Manual 3D camera rotation seems broken if I define upvector Z coordinate to be exactly 0:

``` julia
using GLMakie
using GeometryBasics

scene = Scene()
solid = FRect3D(Vec3f0(-20,-10,0), Vec3f0(40,20,1))
mesh!(scene, solid, color = :red)

cam = cam3d!(scene)
center!(scene)
cam.upvector[] = Vec3f0(1, 0, 0)     #broken camera rotation
#cam.upvector[] = Vec3f0(1, 0, 1e-10)  #OK

update_cam!(scene, cam)
scene
```
Once I try to rotate the camera, the image disappears and the `cam.eyeposition` and `cam.upvector` become Vectors of `NaN`.

**Comment by SimonDanisch** [comment]
The up vector needs to be orthogonal to `lookat - eyeposition` .. Maybe you're breaking that assumption?

**Comment by da-mi** [comment]
Also manually setting all the parameters with
``` julia
cam.eyeposition[] = Vec3f0(0,0,100)
cam.lookat[] = Vec3f0(0, 0, 0) 
cam.upvector[] = Vec3f0(1, 0, 0)
```
the issue is not solved. 
Note that initially the scene is correctly rendered, it breaks when I rotate the 3d camera with mouse/keyboard, both with `Perspective` or `Orthographic` projections.

**Comment by ffreyer** [comment]
Try setting `cam.attributes.fixed_axis[] = false`. That fixes `(0, 0, +-1)` as one rotation axis if it's true.

**Comment by da-mi** [comment]
Setting `cam.attributes.fixed_axis[] = false` solved the issue.

Please note that, despite documentation and docstring report the opposite, this attribute seems to be initialized to `true`:
https://github.com/JuliaPlots/Makie.jl/blob/a18808900e1d5a472aa3e15cc4b1252da65f7194/src/camera/camera3d.jl#L129
