### ISSUE TITLE
Specify `text` anchor in screen coordinates

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#1638]
I want to be able to draw a text in the top-right corner of my plot. `text!` is the best option for this. The problem is that, according to the documentation, one cannot specify the anchor point of the text in screen coordinates, only data coordinates: https://makie.juliaplots.org/stable/examples/plotting_functions/text/index.html 

But it becomes very tedious to try and estimate what the top-right corner of my data is to get the anchor point. It would be much simpler if a keywrod `anchor = :screen`, with values identical to `space`, was allowed.

**Comment by SimonDanisch** [comment]
This should make it work:
https://github.com/JuliaPlots/Makie.jl/pull/1596
It's pretty close to getting merged...
Meanwhile you can play with:
```julia
sspace = campixel(ax.scene)
text!(sspace, ...)
```
https://makie.juliaplots.org/stable/tutorials/scenes/index.html#interaction_with_axis_layouts

**Comment by Datseris** [comment]
Thanks!
The suggestion didn't work though, I did:

```
    sspace = GLMakie.campixel(ax.scene)
    

    GLMakie.text!(sspace, labels[i];
        align = (:right, :top), 
        position = (1, 1),
    )
```
but the text was nowhere to be found.

**Comment by Datseris** [comment]
What does `position` mean if I use `sspace`? Maybe I shouldn't use 1,1 (which I assumed is the top right corner)

**Comment by SimonDanisch** [comment]
campixel -> space is in pixels...If you click on the docs linked, you should find camrelative, which has (1,1) at the top corner

**Comment by SimonDanisch** [comment]
screen space is usually pixel space in Makie, that's why my example used campixel

**Comment by asinghvi17** [comment]
You should be able to use `space = :relative` within `text`, as shown here
https://docs.makie.org/stable/examples/plotting_functions/text/index.html#relative_space
