### ISSUE TITLE
italic textit `\textit` doesn't work

### ISSUE THREAD

**Issue by Moelf** [MakieOrg/Makie.jl#1680]
currently this seems to error:
```julia
begin
	f = Figure(fontsize = 18)
	Axis(f[1, 1],
	    title = L"\frac{x + y}{\sin(k^2)}",
	    xlabel = L"\sum_a^b{xy}",
	    ylabel = L"\textit{ATLAS}"
	)
	f
end
```
with
```
TeXParseError: unexpected error while parsing

at position 8 (string index 8)

\textit{ATLAS}

^

Stack before

[1] TeXExpr :expr
```

nor does something like:
```julia
text!(L"ATLAS \text{Preliminary}"; position=(1.5, 1100))
```
work, this one throws errors:
```
TeXParseError: unexpected error while parsing

at position 12 (string index 12)

ATLAS \text{Preliminary}

^

Stack before

[1] TeXExpr :expr

├─ TeXExpr :char

│ └─ 'A'

├─ TeXExpr :char

│ └─ 'T'
```

but both examples work in just LaTeXString or displayed in Pluto.

**Comment by Moelf** [comment]
in fact everything like `\boldsymbol{}` doesn't work, I just realized it may be a whitelist sort of thing in Makie that everything is in house?

**Comment by ffreyer** [comment]
Makie uses https://github.com/Kolaru/MathTeXEngine.jl, though we are currently holding back on updating because of some text layouting issues. MakieTeX was an earlier sort of brute force attempt at rendering tex.

For text you can use `L"$math text$ normal text"` instead of `L"math text \text{normal text}"`.

**Comment by Moelf** [comment]
yeah but how can I have `\textit{}` or `\boldsymbol{}`? I guess it's a limitation in MathTexEngine.jl I can transfer issues there

**Comment by Moelf** [comment]
fixed by up stream
