### ISSUE TITLE
REPL can be extremely slow after plotting with GLMakie

### ISSUE THREAD

**Issue by rafaqz** [MakieOrg/Makie.jl#1683]
Its hard to make an MWE for this, as it doesn't happen the first few times, or completely predictably after that.

But after displaying a large, detailed 1000*1000 heatmap in GLMakie.jl, showing another object in the REPL can take 20s. It doesn't seem to happen (or as much) with a lower resolution heatmap.

I could profile this with ProfileView.jl, producing this output from a function that plot and array with makie then displays the array in the repl:
![2022-02-18-152554_1920x1080_scrot](https://user-images.githubusercontent.com/2534009/154703519-9fdc587d-de4f-4b14-993c-c66822279f46.png)

Nearly all of the time is in glfw3.jl, SwapBuffers line 696. The GLMakie.jl window was mostly sitting idle during this time, displaying the heatmap.

**Comment by rafaqz** [comment]
The weird thing is that this is happening _after_ the plot has rendered. Are there constant updates happening even with no changes? 

I'm wondering if it has anything to do with my opengl terminal (alacritty). It doesn't seem to affect the vscode REPL.

**Comment by SimonDanisch** [comment]
I see...Maybe the renderloop doesn't quit correctly.
Can you try:
```julia
screen = display(figure)
...
GLMakie.destroy!(screen)
```

**Comment by rafaqz** [comment]
What's slow is displaying the array after showing the heatmap:

```julia
using Makie, GLMakie
A = rand(1000, 1200)
Makie.heatmap(A)
display(A)
```
But this takes essentially no CPU time at all. Its either all GPU or some task waiting problem. For me it takes about 30 seconds to display the heatmap in the repl with the GLMakie window open, and shows all in glfw3.jl in ProfileView.

My suspicion is that each number string being streamed to the opengl terminal are during `show` is triggering a refresh of some sort in GLFW, although I'm not sure if that makes sense.

**Comment by rafaqz** [comment]
Running that code with 4000 * 2000 matrix pretty much kills my laptop.

**Comment by SimonDanisch** [comment]
What platform is this? What terminal?

**Comment by SimonDanisch** [comment]
And does the MWE reproduce consistently for you?

**Comment by SimonDanisch** [comment]
For me `display(A)` is instant

**Comment by rafaqz** [comment]
The heatmap renders nearly instantly, so I don't think this is #1427. 

Its after rendering but before closoing the GLMakie window that everything is still slow. GLMakie appears to just be doing nothing but ProfileView shows all the time in GLFW, as above.

It seems to reproduce pretty consistently now. I think the issue was making it big enough. 

My terminal is alacritty, which is opengl based. Running on Manjaro linux, with i3 on a T14 laptop with an Nvidia GeForce MX330.

The open GLMakie window also slows firefox to some extent, but not as much as the terminal.

**Comment by rafaqz** [comment]
Ah interesting. This probably is just #1427 then.

I'm wondering what the threshold is, maybe GPU memory? The difference between a 500*1000 heatmap and a 1000*1000 heatmap is huge.

**Comment by axsk** [comment]
I run into similar problems with VSCode on MacOS,
after plotting from the REPL VSCode becomes pretty laggy.
The WindowServer process is running at around 30% CPU the whole time after the plot.
When I close the plot pane everything is back to normal. Not sure if this is related though.

**Comment by SimonDanisch** [comment]
I think #2336 should close this!
