### ISSUE TITLE
Contour plots are failing in macOS ARM

### ISSUE THREAD

**Issue by Mixpap** [MakieOrg/Makie.jl#1708]
Hi! 
Trying to make a contour plot using GLMakie in a mac-os m1 arm system (julia version macOS ARM) gives this error.
`ERROR: UndefVarError: libisoband not defined`

Julia version: 1.7.2
GLMakie version:  GLMakie v0.5.4

**Comment by SimonDanisch** [comment]
I guess this needs a PR to add m1 support: https://github.com/JuliaPackaging/Yggdrasil/blob/master/I/isoband/build_tarballs.jl

**Comment by SimonEnsemble** [comment]
I get the same error when I call `contourf` on my Mac with M1 silicon. :( 
`test()` gives
`UndefVarError: libisoband not defined`

```
function test()
	fig = Figure(resolution=(520, 400))
	ax  = Axis(fig[1, 1], 
		xlabel="analyte, Kₐpₐ⁰", ylabel="interferent, Kᵢpᵢ⁰",
		title="P.D.F. of gas compositions", xticklabelrotation=π/2,
		aspect=DataAspect()
	)
	
	Kₐpₐ⁰s = range(0.0, 4, length=100)
	Kᵢpᵢ⁰s = range(0.0, 4, length=100)

	pdfs = [Kₐpₐ⁰ * Kᵢpᵢ⁰ 
		for Kₐpₐ⁰ in Kₐpₐ⁰s, Kᵢpᵢ⁰ in Kᵢpᵢ⁰s]
	cp = contourf!(Kₐpₐ⁰s, Kᵢpᵢ⁰s, pdfs, colormap=reverse(ColorSchemes.ice))
	Colorbar(fig[1, 2], cp, label="density")
	fig
end
```

**Comment by ffreyer** [comment]
I'm guessing this was fixed since there was no more activity here

**Comment by asinghvi17** [comment]
Yes, I can confirm this works on M1 now.
