### ISSUE TITLE
Zooming linked axes is slow

### ISSUE THREAD

**Issue by jtrakk** [MakieOrg/Makie.jl#1719]
Zooming the first axis propagates to the others but I'd guess it takes >300ms.

```jl
using WGLMakie

fig = Figure()
for i in 1:5
  ax = WGLMakie.Axis(fig[i,1])
  density!(ax, rand(1_000))
end
for a1 in fig.content
  linkaxes!(fig.content[1], a1)
end
fig
```

**Comment by jkrumbiegel** [comment]
The tick-finding algorithm was very slow and should be much better once this is merged https://github.com/JuliaPlots/PlotUtils.jl/pull/136

That should remove most of the slowness here, although there's also this PR https://github.com/JuliaPlots/Makie.jl/pull/1672 which makes it a bit better. If it's still too slow after those two, one could make slightly more complicated optimizations leveraging that the axes are all linked, but it would be nice being able to avoid that for now

**Comment by t-bltg** [comment]
@jtrakk, can you update to `PlotUtils@1.1.4` and try out ?

**Comment by jtrakk** [comment]
It's much better now, maybe 50 ms (just eyeballing it).
