### ISSUE TITLE
Inconsitencies in colorrange

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#1737]
I know of three plotobjects that have colorranges : heatmaps, contourf, and contour.

Currently, there is a different way to specify the colorrange for all three of them:
1) heatmaps have an attribute `colorrange`, which is a tuple
2) contours have an attribute `colorrange`, which is a vector
3) contourfs have an attribute `_computed_levels`, which is a vector of each level.

Could this not be unified? I feel like they should all be tuples, with contourf's having their `_computed_levels` from a new attribute `colorrange`, and their existing attribute `levels`.

There are two reasons to do this. First of all, internal consistency is just always nice. Secondly, I am trying to implement a `sync_colorranges!` function that sets the same limits for all heatmaps, contours and countourfs passed to it. It would be nice to make it general, as opposed to having three special cases.

**Comment by ffreyer** [comment]
They should all be tuples now
