### ISSUE TITLE
poly with rectangle and stroke only draws three sides

### ISSUE THREAD

**Issue by malthesr** [MakieOrg/Makie.jl#1742]
The `poly` function with a `Rect` and stroke only draws three sides of the rectangle:

```julia
using GLMakie
poly([Rect(1, 1, 1, 1)], color=:transparent, strokewidth = 10, strokecolor = :black)
```
![rect](https://user-images.githubusercontent.com/25851939/157849847-ba878795-2488-42f8-a32f-612686b921bb.png)

Seems different from, but maybe related to #321?

Makie v0.16.5, GLMakie v0.5.4.

**Comment by malthesr** [comment]
It might just be a matter of adding an extra `1` at the end of [this](https://github.com/malthesr/Makie.jl/blob/master/src/conversions.jl#L163) line. I get a precompile failure on the current master that I don't understand though, so I can't confirm and submit a PR right now.

**Comment by SimonDanisch** [comment]
Did you dev a backend, MakieCore and Makie?

**Comment by ffreyer** [comment]
This was fixed
