### ISSUE TITLE
magic keyword args

### ISSUE THREAD

**Issue by SimonDanisch** [MakieOrg/Makie.jl#178]
For clarity, I'm right now just representing attributes in Makie exactly in the way the backend / makie itself will consume them.
To improve usability, I plan to preprocess the keyword args to allow e.g.:

```Julia
xlims = (0, 1) -> limits = FRect(...)
```
The plan is to just put this preprocessing into the Attribute type constructor, or at a similar place!
We'll need to figure out what magic kw args we want to support and then implement it ;)

**Comment by ffreyer** [comment]
Closing as outdated
