### ISSUE TITLE
volume plot bug with axis values that are not in increasing order

### ISSUE THREAD

**Issue by alexriss** [MakieOrg/Makie.jl#1781]
A volume plot with axis values that aren't sorted in increasing order give erroneous results. Consider this example:

```julia
using GLMakie
let
      x = 12:-1:1
	  y = z = 1:10
	  f(x, y, z) = x^2 + y^2 + z^2
	  vol = [f(ix, iy, iz) for ix in x, iy in y, iz in z]
	  fig, ax, _ = volume(vol; colorrange = (minimum(vol), maximum(vol)), transparency = true,
	     figure = (; resolution = (1200, 800)),  axis = (; type = Axis3))
	  display(fig)
end
```

<img src="https://user-images.githubusercontent.com/1452525/159793722-d2ec499a-d6a4-4f37-a076-6db42986b6de.png" width="500" />

The largest values (yellow) are shown for small values of x, but according to the used function large values of all variables should give the highest values. In the plot, the x-axis values seem to be sorted in increasing order but with the actual plot being left alone.

Same behavior for the other axes.

GLMakie v0.5.5

**Comment by ffreyer** [comment]
If you access the `vol` matrix you find the largest value at `v[1, 10, 10]` which matches the (1, 10, 10) coordinate in the plot. So that's working as intended as far as I can tell
