### ISSUE TITLE
WGLMakie - Comma does not render properly in Pluto notebook

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#1877]
![msedge_0Yb5FP0nbp](https://user-images.githubusercontent.com/61620837/166679697-bd50aae1-bba8-4cda-bb6b-11b698a4b704.gif)

**Comment by SimonDanisch** [comment]
Yeah something is racy about updating the font cache... On second render, it should work fine ... Still need to find some time to properly fix this.
