### ISSUE TITLE
[bug] [performance] @recipe macro using `image` allocates many times more memory than the individual image plots

### ISSUE THREAD

**Issue by kunzaatko** [MakieOrg/Makie.jl#1881]
When you create a recipe and `@time` the produced function, It allocates more memory than the individual plots in the recipe.

# MyImage
Here is a simple test case, where I wrap the `Image` plot in `MyImage`:
```julia
using Makie
using Images

@recipe(MyImage) do scene
    Attributes()
end


function Makie.plot!(
    ims::MyImage{<:Tuple{<:AbstractArray{<:Colorant}}})

    image!(ims, ims[1])
    return ims
end
```
Using the original `Image`
```
julia> @time image(img[:,:,1])
  0.032395 seconds (46.04 k allocations: 38.614 MiB, 36.75% gc time)
```
and the resulting function from the recipe
```
julia> @time myimage(img[:,:,1])
  1.120143 seconds (25.21 M allocations: 1.444 GiB, 63.09% gc time)
```

# MyScatter
The ratio between the wrapped and original allocated memory is not the same for different plotting function, but it exists for them also.
```
julia> x = rand(Point2, 100000);
```
And the same wrapping in the recipe:
```julia
@recipe(MyScatter) do scene
    Attributes()
end

function Makie.plot!(
    scat::MyScatter{<:Tuple{Any}})

    scatter!(scat, scat[1])
    return scat
end
```
Using the original `Scatter`
```
julia> @time scatter(x)
  0.050758 seconds (1.75 M allocations: 54.679 MiB, 30.36% gc time)
```
and the wrapped `MyScatter`
```
julia> @time myscatter(x)
  0.085370 seconds (2.64 M allocations: 81.918 MiB, 40.18% gc time)
```

**Comment by asinghvi17** [comment]
A lot of the time in `myimage` is likely spent in compilation.  Using `BenchmarkTools.jl`'s `@benchmark` macro (this basically runs a bunch of iterations of a given command, and provides statistical data on them) after running each recipe once to compile them,

```julia
julia> @benchmark image($(rand(RGBAf, 10, 10)))
BenchmarkTools.Trial: 685 samples with 1 evaluation.
 Range (min … max):  6.740 ms … 14.305 ms  ┊ GC (min … max): 0.00% … 40.80%
 Time  (median):     6.975 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   7.295 ms ±  1.204 ms  ┊ GC (mean ± σ):  2.44% ±  7.24%

  ▃█
  ███▅▄▆▄▃▃▂▂▁▂▂▁▂▁▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂ ▂
  6.74 ms        Histogram: frequency by time        13.9 ms <

 Memory estimate: 3.08 MiB, allocs estimate: 50792.

julia> @benchmark myimage($(rand(RGBAf, 10, 10)))
BenchmarkTools.Trial: 610 samples with 1 evaluation.
 Range (min … max):  7.413 ms … 16.019 ms  ┊ GC (min … max): 0.00% … 39.44%
 Time  (median):     7.850 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   8.206 ms ±  1.314 ms  ┊ GC (mean ± σ):  2.32% ±  7.13%

  █▄
  ███▆▆▆▇▅▄▃▃▃▃▃▃▂▃▂▁▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂▂▁▂▂ ▃
  7.41 ms        Histogram: frequency by time        15.2 ms <

 Memory estimate: 3.23 MiB, allocs estimate: 52956.

```

We can see that although the `myimage` times are slightly higher (~0.7ms) than the `image` times, this is pretty much expected, since you are constructing only 1 Plot object in `image`, but 2 in `myimage`.

Similarly, benchmarking `myscatter`, 

```julia
julia> @benchmark scatter($x)
BenchmarkTools.Trial: 117 samples with 1 evaluation.
 Range (min … max):  38.886 ms … 46.822 ms  ┊ GC (min … max): 0.00% … 13.79%
 Time  (median):     41.580 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   42.745 ms ±  3.345 ms  ┊ GC (mean ± σ):  6.95% ±  6.54%

  ▂▄▇ ▃█▂                                            ▃▅▃▇▇▂
  ███████▃▅▃▁▁▁▁▃▁▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▃▃██████▅▇ ▃
  38.9 ms         Histogram: frequency by time        46.7 ms <

 Memory estimate: 49.46 MiB, allocs estimate: 1561001.

BenchmarkTools.Trial: 64 samples with 1 evaluation.
 Range (min … max):  73.045 ms … 80.994 ms  ┊ GC (min … max): 0.00% … 7.09%
 Time  (median):     79.468 ms              ┊ GC (median):    7.59%
 Time  (mean ± σ):   78.293 ms ±  2.696 ms  ┊ GC (mean ± σ):  6.03% ± 3.32%

                                                █ ▃▂▃
  ▅▇▅▅▇▅▁▁▁▁▁▁▁▁▁▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇▇█▇███▅▅▄▄▅▅▄▅ ▁
  73 ms           Histogram: frequency by time          81 ms <

 Memory estimate: 76.62 MiB, allocs estimate: 2454485.
```

This is a significant difference, and I'm not quite sure why.  Will do more tests and get back to you on that.

Also, if you want to measure time to display, you should time `display(myplot(...))`; what we are timing right now is simply the construction of the plot object.

**Comment by kunzaatko** [comment]
> A lot of the time in myimage is likely spent in compilation.

I am afraid that this is not the case... You see, I ran the command before to avoid compilation time polluting the output of `@time`. And also for the record, `@time` also states the portion of time used for compilation:
```
julia> @time myscatter(x)
  0.248897 seconds (2.80 M allocations: 89.877 MiB, 31.90% gc time, 39.17% compilation time)
```
> Using BenchmarkTools.jl's @benchmark macro (this basically runs a bunch of iterations of a given command, and provides statistical data on them) 
I am aware of `BenchmarkTools.jl` but I think that memory allocation, unlike execution time, is fully deterministic (am I not right?). 

You know, I am only concerned with the allocations, since they are most probably the cause of the additional time spent in execution. 
> We can see that although the myimage times are slightly higher (~0.7ms) than the image times, this is pretty much expected, since you are constructing only 1 Plot object in image, but 2 in myimage.
And about the image... That there are 2 plots instead of one is true. It does not explain this though, I am afraid. In that case, there would be a set amount of allocation added to any size of argument (right?). Not happening here....
I get the same result when trying with 10×10 random pixels. 

```
julia> @time image(rand(RGB, (10,10)))
  0.012163 seconds (40.35 k allocations: 2.251 MiB)

julia> @time myimage(rand(RGB, (10,10)))
  0.012382 seconds (42.88 k allocations: 2.420 MiB)
```

But when the size of the data is larger... It is a completely different story. 
```
julia> @time image(rand(RGB, (1024,1024)))
  0.054724 seconds (45.74 k allocations: 50.599 MiB, 45.58% gc time)

julia> @time myimage(rand(RGB, (1024,1024)))
  2.019710 seconds (25.21 M allocations: 1.456 GiB, 69.21% gc time)
```
Therefore, I deduce that the difference in allocation memory is somehow proportional to the data size (Am I right in deducing this?). I can make a graph, co that we know how many times more are data points allocated in in the recipe.

Can you, please, try it yourself, so that it is clear that this does not happen only for me? (@asinghvi17) Thanks :)

**Comment by asinghvi17** [comment]
This is definitely an interesting result!  I have an exam tomorrow but will definitely investigate this over the weekend.  

It would be great if you could make that kind of graph, it would definitely help us to understand what the scaling looks like.

**Comment by kunzaatko** [comment]
> It would be great if you could make that kind of graph,
Will do. Also later though. I agree that it could help clear things out, in particular if it is in linear relation (that would look like the data to be passed and copied over several times.) Good luck with your exam!

**Comment by kunzaatko** [comment]
Here is the graph of allocations made with and without the recipe

![Scatter_mems](https://user-images.githubusercontent.com/56647779/167271826-12a2a30e-b58b-4e25-aa3e-4b7580b6e268.png)

Some interesting points:
1) The recipe plot does not allocate more memory than ordinary `Scatter` with few data points... This is very counterintuitive (since as you already mentioned there are two plots stored in the recipe and only one in the ordinary). Really don't know why this is happening...
2)  The coefficient of the linear relation is not a whole number, which would imply that the issue is not in copying over data or something similar.

Here is in addition a graph, when I elementwise delete the initial value (the one with a plot of an empty array of points). It is (as expected) fully linear with the coefficient `1.5470773633167723`.

![Scatter_mems_without_plot](https://user-images.githubusercontent.com/56647779/167272027-5555ebd4-9c00-4442-a199-1ddf6e37e0e7.png)

@asinghvi17 Do you know of anybody among the Makie developers who can help make the first point clear and shine some more light on, why this would be happening?

**Comment by kunzaatko** [comment]
The second point makes me think that the problem is not with the datapoints but rather with some kind of inner attribute that is defined for every point. Maybe if I do a similar graph for the image recipe, it will give a lead on what exactly...

**Comment by MariusDrulea** [comment]
another issue with unexpected big memory allocations related to `image`: https://github.com/JuliaPlots/Makie.jl/issues/1692

**Comment by SimonDanisch** [comment]
Closed by https://github.com/MakieOrg/Makie.jl/pull/2770
