### ISSUE TITLE
Per-plot custom inspector function

### ISSUE THREAD

**Issue by tecosaur** [MakieOrg/Makie.jl#1902]
Hi All,

For starters, I'd like to say that I've been having a great experience using Makie so far. Kudos for creating such a nifty plotting package!

I'm currently trying to have an inspector which makes available some ancillary data on the particular data points of a scatter plot. I.e.
```
| x | y | extra |
|---+---+-------|
| 1 | 2 | hey   |
| 2 | 1 | there |
...
```
When hovering over the `(1, 2)` point it would be great if I could have an inspector show `"hey"`, etc.

This is something that can't really be accomplished with text labels, as when I have thousands of data points it gets a bit much.

Looking at https://makie.juliaplots.org/v0.15.1/documentation/inspector/#extending_the_datainspector and a few relevant bits of the source code, I get the impression that this use case isn't possible without writing a horribly hacky override for `show_data(inspector::DataInspector, plot::Scatter, idx)` affecting all scatter plots and abusing global variables.

It would be great if `DataInspector` could accept an "custom show functions"-type parameter, something like a dictionary between plot types and show functions that this specific inspector should use. If this existed, I could simply box the data in a custom show function and use it this way.

Let me know if you'd consider adding something like this.

**Comment by ffreyer** [comment]
> Looking at https://makie.juliaplots.org/v0.15.1/documentation/inspector/#extending_the_datainspector and a few relevant bits of the source code, I get the impression that this use case isn't possible without writing a horribly hacky override for show_data(inspector::DataInspector, plot::Scatter, idx) affecting all scatter plots and abusing global variables.

Yea that's true. I originally thought people would mainly be looking to add special behavior for custom recipes. I've been meaning to rework this stuff for a while but I haven't found the time yet.

> It would be great if DataInspector could accept an "custom show functions"-type parameter, something like a dictionary between plot types and show functions that this specific inspector should use. If this existed, I could simply box the data in a custom show function and use it this way.

My idea was to look for some custom label providing function in `plot.attributes` and fall back on the current behavior if none exist.

**Comment by ffreyer** [comment]
I think it's better to keep the scope of the inspector relatively small but make the parts that go into it available. Putting something like `on_hover` and `on_click` in there would basically make it a second, more restrictive version of the event system we have.

Something like `plot.attributes[:on_click] = Observable((scene, plot, idx) -> ...)` would be more or less the same as
```julia
on(events(scene).mousebutton, 10) do event
    if event.button == Mouse.left && event.action = Mouse.press
        plot, idx = pick(scene, 10)
        if plot == relevant_plot
            ...
        end
        return Consume(true)
    end
    return Consume(false)
end
```
And that could just become a function `on_click(f, plot; settings)` too.

**Comment by tecosaur** [comment]
Ah! I think I need to look at the event system a bit more. Thanks for the example.

Scratch out everything I say after "something else has just occurred to me", but I think my comments on ideally wanting a label + per-inspector `show_data` still stand.
