### ISSUE TITLE
Allow passing a backend manually to `save`

### ISSUE THREAD

**Issue by ericphanson** [MakieOrg/Makie.jl#1960]
The backend is pulled from a global at `show` time:
```julia
function Base.show(io::IO, m::MIME, scene::Scene)
    ioc = IOContext(io,
        :full_fidelity => true
    )
    screen = backend_show(current_backend[], ioc, m, scene)
    push_screen!(scene, screen)
    return screen
end
```
It would be nice if instead `show` or `save` supported an optional keyword argument to set the backend without overriding the global.

(Same use case as https://github.com/JuliaPlots/Makie.jl/issues/1959)

**Comment by cossio** [comment]
Also, pulling from your comment on Slack, I think it would be nice to have a function like:

```
function with_backend(f, backend)
     # set backend temporarily to `backend`
     f() # calls the passed function
     # restore previous backend
end
```

which can be used like:

```
with_backend(backend) do
   # plots figures
   # save
   # etc
end
```

**Comment by jkrumbiegel** [comment]
I don't think the with backend is necessary as until `show` is called, the plot objects created are exactly the same, so you don't need to wrap anything but save, I which case I would find a direct argument more straightforward probably.

**Comment by SimonDanisch** [comment]
I proposed `Backend.save/show` some time ago for this.
Would that work as well?

**Comment by jkrumbiegel** [comment]
That could be confusing though right? That it wouldn't be Base.show and FileIO.save unlike everywhere else? Would be pretty convenient though

**Comment by asinghvi17** [comment]
I can definitely see the confusion there.  Perhaps we could pass the backend in the IOContext, like `save(filename, figurelike; backend = GLMakie)`?  That could be a selective dispatch on the Makie end, specifically as a kwarg in https://github.com/JuliaPlots/Makie.jl/blob/983f564cd7b220b8536e13a56bb83dc327efcf3f/src/display.jl#L216-L221

and then have the new kwarg be `backend = Makie.current_backend[]` as default, with the option to pass `CairoBackend()`, `GLBackend`, ...

**Comment by asinghvi17** [comment]
From discussion with @SimonDanisch, it seems a nice way to do this might be to define `save` for backend screens instead.  With a small refactor for uniformity, the user should be able to do:
```julia
save("filename.png", scene) # uses current backend
save("filename.png", display(scene)) # display returns a Screen of the current backend
save("filename.png", GLMakie.display(scene)) # GLMakie.display returns a GLMakie.Screen
# possibly
save("filename.png", CairoMakie.Screen(scene; px_per_unit = 4)) # save with Cairo upscaling

**Comment by SimonDanisch** [comment]
Ok, thinking some more about this, i'd propose the following API:
```julia
# Opens a window and returns a screen for the current active backend
screen = display(figlike; screen_params...)::Backend.Screen

# Opens a window and displays some figure on it independend of which backend is active
screen = Backend.Screen(; screen_params...)
display(screen, figlike)

# does the same as above, just shorter,
screen = Backend.Screen(figlike)

save("plot.png", screen) # can be saved
show(screen) # can be shown in plotpane, default display behaviour
```

This should also remove inline!(true) since that will then just be the default and opening a window will need an explicit display. This should also help cleaning up the API in #1771

**Comment by asinghvi17** [comment]
Makes sense, and it's definitely a nice clean API.  I would suggest we also offer a similar option to `record` (i.e., pass a screen or a figlike) - it would make things a lot easier to go from CairoMakie for regular plotting to GLMakie for high speed recording.

**Comment by jkrumbiegel** [comment]
Hm don't you find it confusing that users would have to open Screens for CairoMakie then? It doesn't have those (I mean technically there's an object named like that but it's not what normal people would expect when hearing Screen). I find it clearer if 

```julia
screen = Backend.Screen(figlike)
save("plot.png", screen) # can be saved
```

becomes

```julia
save("plot.png", figlike, backend = CairoMakie)
```

Yeah I would probably actually pass the module there, why not. It seems to me to be the easiest to understand, why do I want to figure out what backend objects there are, if I only need to construct one to choose CairoMakie for rendering. We can of course still use backend objects for dispatch in the background.

**Comment by asinghvi17** [comment]
CairoMakie may actually have different screen types (if we decide to integrate Gtk) so while passing the module is a good option for a user interface, it should still decompose to the first bit of code internally, and the first type of method should be present so that one can choose which display to show the plot in.

**Comment by bilderbuchi** [comment]
Do I understand correctly that this would mean that one could e.g. create a plot with GLMakie, interact with it (e.g. zoom into a region of interest), and then save the now displayed plot as a (vector-based) pdf using CairoMakie?
If yes, that could be quite useful for getting _both_ interactivity and crisp plot files! :-)

**Comment by jkrumbiegel** [comment]
> and then save the now displayed plot as a (vector-based) pdf using CairoMakie

You should already be able to do that, it's just that you'd need to `CairoMakie.activate!` before saving. Not sure what exactly happens with an open GLMakie figure at that point.

**Comment by SimonDanisch** [comment]
This actually got implemented, so no `activate!` needed anymore, just do:
```julia
save("test.pdf", fig; backend=CairoMakie)
```

**Comment by jkrumbiegel** [comment]
Ah you're completely right, I forgot about that change

**Comment by bilderbuchi** [comment]
Awesome! It did not take the currently shown viewport/limits into account though, but used the initial one, zooming etc don't have an effect on the saved figure. 
That might be another issue though (probably my understanding).

**Comment by SimonDanisch** [comment]
Oh you're right -.- seems we don't enough tests for this yet ....

**Comment by SimonDanisch** [comment]
I don't have much time to fix this, but it's very likely this part: https://github.com/MakieOrg/Makie.jl/blob/master/src/display.jl#L33
I think we need to losen that up to allow one screen _per_ backend! 
This should fix the issue. 
For the limits, try `save(...; update=false)`

**Comment by bilderbuchi** [comment]
Thanks, that worked! Filed #2675 for the dying figure issue.

**Comment by RomeoV** [comment]
Is there a way to do the same with `display`? Specifically, I would like to have `CairoMakie` setup as the plotting backend in a Pluto notebook, but then plot a single plot with `WGLMakie`. However, `display(fig; backend=WGLMakie)` errors as in https://github.com/MakieOrg/Makie.jl/issues/3535.
