### ISSUE TITLE
latex rendering of "/" is incorrect, which affects figure axis labels

### ISSUE THREAD

**Issue by AshtonSBradley** [MakieOrg/Makie.jl#1967]
Great to see https://github.com/JuliaPlots/Makie.jl/pull/1952 happen. Lower case Greek now renders italic! 

However, there is a new issue for axis labels related to the update (that I have so far noticed) and forwardslash: for example `2\pi/\xi`

gets rendered as

<img width="60" alt="Screen Shot 2022-05-23 at 7 15 08 PM" src="https://user-images.githubusercontent.com/24194258/169764187-adc87d70-de1b-4805-89c2-9fad8cc723d1.png">

instead of $2\pi/\xi$, or `0.0/\omega` becomes

<img width="73" alt="Screen Shot 2022-05-23 at 7 16 37 PM" src="https://user-images.githubusercontent.com/24194258/169764450-0d677402-3fb1-4398-baa3-0a4e7e46321a.png">

instead of 

$0.0/\omega$, with `CairoMakie v0.8.3`

A simple hack to fix this is to add some horizontal space after the "/" e.g. `x/a` --> `x/\;\;\;a`

```julia
versioninfo()
Julia Version 1.8.0-beta3
Commit 3e092a2521 (2022-03-29 15:42 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_PKG_DEVDIR = /Users/abradley/Dropbox/Julia/Dev
  JULIA_NUM_THREADS = 8
  JULIA_REVISE_WORKER_ONLY = 1
```

**Comment by ffreyer** [comment]
Has been fixed
