### ISSUE TITLE
RPRMakie produces only black plots

### ISSUE THREAD

**Issue by gdkrmr** [MakieOrg/Makie.jl#1974]
RPRMakie only produces black images for me. I am on Manjaro with an AMD Ryzen 7 PRO 4750U with Radeon Graphics and RPRMakie v0.3.3 and Julia 1.7.3.

**Comment by SimonDanisch** [comment]
I haven't tested it with AMD GPUs yet... Have you tried the different ray tracing backends?

**Comment by SimonDanisch** [comment]
What's the error

**Comment by gdkrmr** [comment]
With Tahoe:
```
julia> save("submarin_cables.png", scene)
ERROR: Error code returned: RPR_ERROR_UNSUPPORTED
```

Hybrid:
```
julia> save("submarin_cables.png", scene)
Error: Fatal error: Could not create Vulkan instance, VkResult=-9
ERROR: Error code returned: RPR_ERROR_UNSUPPORTED
```

HybridPro:
```
julia> save("submarin_cables.png", scene)
Error: Required instance extension VK_KHR_get_physical_device_properties2 is not supported.
ERROR: Error code returned: RPR_ERROR_UNSUPPORTED
```

**Comment by SimonDanisch** [comment]
Hm, maybe you have drivers missing? Otherwise, I'd suggest reporting at https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK

**Comment by SimonDanisch** [comment]
Sorry, I have no idea, i've never had an AMD GPU on linux.

**Comment by gdkrmr** [comment]
Don't worry, the GPU compute for consumers on AMD is practically abandoned by AMD so I kind of expected this to not work. 

#1975 is not related, I think.  The errors didn't change before and after the update.

**Comment by ffreyer** [comment]
Closing this since it doesn't seem like we can help here
