### ISSUE TITLE
The size of a layout element is wrong when inherited from another with a recursively updated computedbbox

### ISSUE THREAD

**Issue by ffreyer** [MakieOrg/Makie.jl#1976]
I noticed this in #1944 when resizing the window in GLMakie with this example:

```julia
fig = Figure()
lbl = Label(fig[1, 1], lorem_ipsum, word_wrap = true)
box = Box(fig[1, 1], color = (:red, 0.3))
fig
```

Resizing the window triggers updates of the bounding boxes that layout elements occupy. For label, this update can also trigger word wrapping. If that inserts (or removes) a new line, the new size is not communicated correctly to `Box`. Triggering another update (without adding or removing a new line) fixes this.

Note that

```julia
fig = Figure()
box = Box(fig[1, 1], color = (:red, 0.3))
lbl = Label(fig[1, 1], lorem_ipsum, word_wrap = true)
fig
```

does not have this issue.

#### Why I think it happens

From what I can tell the problem is that `Label` updates recursively. The chain of updates is:

1. `lbl.computedbbox` updates because of an outside change
2. This triggers a recalculation of the text position and word_wrap_width, which both trigger if they have changed
3. If word_wrap_width triggers (i.e. the width of the bbox changed) the text bounding box gets updated and `lbl.autosize` triggers with an automatic width and a height based on the text bounding box
4. Layouting updates `lbl.computedbbox` based on the changed `autosize`
5. This triggers another recalculation of text position and word_wrap_width. The latter should still be correct and therefore not trigger autosize again

From what I understand we have something like `map!(box.computedbbox, lbl.computedbbox)` in the first case. This means that the update of `box.computedbbox` triggers after the updates set in `Label` are done, which means (2) happens before it. Because (2) triggers another update of `lbl.computedbbox` in (4) there is another update of `box.computedbbox`. The update from (4) will happen first and update the `box.computedbbox` with the correct size, then the update from (2) happens with the incorrect size.

In the working case I think that the update to `box.computedbbox` is set up first and therefore executes before the internal `Label` updates do.

#### What to do about it

One way to fix this would be always have layout elements talk to each other immediately, i.e. guarantee case 2 through a high priority.

**Comment by jkrumbiegel** [comment]
I think the logic inside Label is incorrect now (at least in terms of how layouts are meant to work). An object is not allowed to change its own `reportedsize` based on the `suggestedbbox` it receives, because that can trigger an infinite update cycle. To me it makes sense that the Label knows its height if its width is fixed by the user and word wrapping picks up on that width, but not in an initially unconstrained situation.

**Comment by ffreyer** [comment]
This has been fixed
