### ISSUE TITLE
streamplot color option

### ISSUE THREAD

**Issue by lazarusA** [MakieOrg/Makie.jl#1987]
In the current implementation of streamplot the color intensity is calculated internally, however the default in some cases doesn't show certain properties, that with a different color values/scales will be more interesting. 

Having the option colour as in this example
https://matplotlib.org/3.5.0/gallery/images_contours_and_fields/plot_streamplot.html

will be a nice feature to have.

**Comment by asinghvi17** [comment]
The API would be a bit different since (AFAIK) our streamplots are continuous.  Still it could be done, if we pass color as a function for example.

**Comment by lazarusA** [comment]
yes, a function will do also. I think matplotlib has both options.

**Comment by lazarusA** [comment]
solve by https://github.com/MakieOrg/Makie.jl/pull/2002
