### ISSUE TITLE
Search required 3 chars to return results, but appear to load with 1 and 2

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#2004]
One and two character searches stay like this:
<img width="252" alt="image" src="https://user-images.githubusercontent.com/61620837/171182376-1c22b21b-9b56-4d03-b2b7-ef5d3baaa16d.png">

The moment i enter a third char, the result pops up.
It should not appear to load when it fact it is waiting for more input.

**Comment by ffreyer** [comment]
Closing this as the docs backend has changed and this has been fixed
