### ISSUE TITLE
Transform is applied even if `space != :data`

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#2065]
@ffreyer these two should be the same I think?

```julia
scatter(Point(100, 100), axis = (xscale = log10, yscale = log10), space = :pixel)
```

![grafik](https://user-images.githubusercontent.com/22495855/174276503-f0e59f5a-8316-462c-ae9e-c11d0365e9a6.png)

```julia
scatter(Point(100, 100), space = :pixel)
```

![grafik](https://user-images.githubusercontent.com/22495855/174276552-5a113b29-e35f-4dbb-aaa6-64f36e52e593.png)

**Comment by ffreyer** [comment]
Yea, probably. I viewed the transform functions as an independent step and didn't think much about it. But the things you (have to) do with it, like log scales or spherical coordinates, don't make sense in pixel, relative or clip space.

**Comment by jkrumbiegel** [comment]
Ok then we should make sure that the transform is only applied when `space == :data`.

**Comment by asinghvi17** [comment]
Is it possible to then add an extra step (`space = :transformed`) which skips applying `transform_func` but in all other ways acts like `space = :data`?  This would be pretty useful for debugging, plotting calculated bounding boxes and dealing with transforms without a defined inverse.

**Comment by ffreyer** [comment]
All the `transform_func` stuff happens at some point before things move into shaders. I think fixing this is pretty much just implementing `apply_transform(f, x, space) = space == :data ? apply_transform(f, x) : x` and hunting down and adjusting all calls to `apply_transform(f, x)` to it.

**Comment by dgleich** [comment]
This seems reasonably straightforward to fix. Do you know if anyone is working on it already? If not, I will send a plan.

**Comment by jkrumbiegel** [comment]
I don't think anyone has started, if you'd be interested, go ahead :)
