### ISSUE TITLE
Fix error in NextJournal example page

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#2128]
The following page describes Julia usage on NextJournal:
https://nextjournal.com/nextjournal/julia-environment?change-id=CozcTBwNndNtXtFSJxxokb&node-id=39e3f06d-60bf-4003-ae1a-62e835085aef

The page contains the following block, with the only output being the single line error shown:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/61620837/178423684-35a255b5-67df-4d33-95c3-656ff7a4d37d.png">

I am not sure where things go wrong, but a fix should be simple enough.

**Comment by SimonDanisch** [comment]
I guess this should be discussed with Nextjournal
