### ISSUE TITLE
[Feature Request] Add highclip, lowclip and nan_color to poly

### ISSUE THREAD

**Issue by cristobaltapia** [MakieOrg/Makie.jl#2156]
Hi,

thanks for this great package! Would you consider adding `highclip`, `lowclip` and `nan_color` to the `poly()` function? Reading the code [here](https://github.com/JuliaPlots/Makie.jl/blob/05413d3206565a1dcdd1697106e5dc39da08da48/src/basic_recipes/poly.jl#L49-L64) it seems that it should be straightforward, as these parameters only need to be passed to `mesh()`.

Cheers

**Comment by SimonDanisch** [comment]
Maybe this is the perfect chance for a PR, if you already know where and how to edit it? :)

**Comment by cristobaltapia** [comment]
Well, if that is the right place to make the changes, then I'll take a shot at it ;)

**Comment by SimonDanisch** [comment]
We have this now
