### ISSUE TITLE
Support both "Bool" and "Tuple{Bool, Bool}" for "xtrimspine" and "ytrimspine"

### ISSUE THREAD

**Issue by marcpabst** [MakieOrg/Makie.jl#2169]
I think the meaning would be self-explanatory. Sometimes you want to trim only one end of the spine and currently that's not possible. 

I would be happy to implement this if this is okay with the maintainers.

**Comment by jkrumbiegel** [comment]
Sounds good!

**Comment by SimonDanisch** [comment]
Merged in https://github.com/MakieOrg/Makie.jl/pull/2279
