### ISSUE TITLE
Order of decomposes coordinates is not counter/clockwise

### ISSUE THREAD

**Issue by yakir12** [MakieOrg/Makie.jl#2181]
The `Point2f`s that `decompose(Point2f, Rect(0, 0, 1, 1))` returns are not sorted in a clockwise order (nor counter clockwise). This is not ideal because plotting a decomposed rectangle doesn't work:
```julia
poly(decompose(Point2f, Rect(0, 0, 1, 1)))
```
![tmp](https://user-images.githubusercontent.com/3281957/180878478-de70e435-1820-4306-a980-eafd4b92af85.png)
nor does plotting polygons with a hole:
```julia
using GeometryBasics
p = Polygon(decompose(Point2f, Rect(0, 0, 1, 1)), [decompose(Point2f, Circle(Point2f(0.5), 0.25))])
poly(p)
```
![tmp](https://user-images.githubusercontent.com/3281957/180879079-d9df1a9b-27a1-4af8-8b74-a06fe3722c94.png)

Only specifying the coordinates manually:
```julia
p = Polygon(Point2f[(0,0), (1,0), (1,1), (0,1)], [decompose(Point2f, Circle(Point2f(0.5), 0.25))])
```
worked:
![tmp](https://user-images.githubusercontent.com/3281957/180879309-f85579c5-a1c0-4cff-bf3d-35dd78d7713d.png)

**Comment by ffreyer** [comment]
Should probably be considered in https://github.com/JuliaGeometry/GeometryBasics.jl/pull/173

**Comment by asinghvi17** [comment]
Yeah, I've run into this issue as well....

**Comment by ffreyer** [comment]
Right, this is probably going to be a part of that pr now. Question is which way? Does Cairo have a preference?

**Comment by ffreyer** [comment]
I guess with `reverse()` existing it doesn't matter that much as long as it is consistent?

**Comment by asinghvi17** [comment]
If you're talking about geospatial, I can find you a standard which fits any winding order you might want to do :D but for now, we could go with the standard counterclockwise order?  Cairo is fine with either CW or CCW.
