### ISSUE TITLE
Barplot doesn't use bar height for limits

### ISSUE THREAD

**Issue by Moelf** [MakieOrg/Makie.jl#2182]
```julia
using WGLMakie

begin
	N = 10
	δ = 0.05
	cs = repeat([1,2], N÷2)
	heights = rand(N) * 10
	meshscatter(Point3f.(rand(N), rand(N), 0.00001rand(N)); 
	  	color = cs, 
		markersize = Vec3f.(δ, δ, heights),
		colormap = :Spectral_7,
		marker = Rect3f(Vec3f(0), Vec3f(1)),
	    shading=false
	)
end
```
![image](https://user-images.githubusercontent.com/5306213/180924606-cf070eb6-97c9-49cc-8112-dc2617137c5f.png)

```julia
begin
	N = 10
	δ = 0.05
	cs = repeat([1,2], N÷2)
	heights = rand(N) * 10
	meshscatter(Point3f.(rand(N), rand(N), 0.00001rand(N)); 
	  	color = cs, 
		markersize = Vec3f.(δ, δ, heights),
		colormap = :Spectral_7,
		marker = Rect3f(Vec3f(0), Vec3f(1)),
	 	axis = (type = Axis3,
            xlabel = "x label", ylabel = "y label", zlabel = "z label",
		),
	    shading=false
	)
end
```
![image](https://user-images.githubusercontent.com/5306213/180924637-21a28382-1e1c-4170-84fb-98a9cdda3f3c.png)

**Comment by Moelf** [comment]
something funky with Z auto limiting, adding
```julia
		    limits = (nothing, nothing, nothing, nothing, 0, 10)
```
solved it:
![image](https://user-images.githubusercontent.com/5306213/180925853-b6def4d1-8444-481a-ad6b-f3db0e38cf54.png)

**Comment by ffreyer** [comment]
This has been a thing forever. `data_limits` only considers the positions passed, not the extent of the meshes. This is also true for scatter.

**Comment by SimonDanisch** [comment]
I think we should close this in favor of https://github.com/MakieOrg/Makie.jl/issues/2881
