### ISSUE TITLE
DataInspector show other values like color origin

### ISSUE THREAD

**Issue by rapus95** [MakieOrg/Makie.jl#2188]
It would be really cool if the DataInspector would also show the Threshold value (used as input to the color argument) at that specific point and if it would show the axis labels of the plot rather than x/y as labels.
![image](https://user-images.githubusercontent.com/5960902/182070510-b5731eee-d458-452d-b36d-5414d840d46b.png)

**Comment by ffreyer** [comment]
I think this is solved by providing a custom `plot(..., inspector_label = (self, idx, pos) -> some_label)`
