### ISSUE TITLE
Default method in Makie for set_window_config!

### ISSUE THREAD

**Issue by Azzaare** [MakieOrg/Makie.jl#2193]
Hi there!

I would like to have a default method for `set_window_config!` that does nothing in `Makie.jl`.

I am currently writing a visualization tool which is independent of the Makie backend. Still I would like to customize it depending of the backend.

**Comment by SimonDanisch** [comment]
You can set it as part of your theme:
```julia
Makie.set_theme!(GLMakie=(; float=true, title="MyApp"))
```
