### ISSUE TITLE
Rotating the title of the y-axis?

### ISSUE THREAD

**Issue by rben01** [MakieOrg/Makie.jl#2222]
Currently, in a 2D plot, the y-axis title, `ylabel`, is always written vertically, along the y-axis. For short titles it might make more sense to rotate the y-axis title so that it's horizontal, so that it's easier to read. However this doesn't seem possible currently. It would be great to add a `ylabelrotation` kwarg to `Axis`, and probably it wouldn't hurt to add it for the x-axis as well.

**Comment by Lightup1** [comment]
And for `Colorlaber`.
