### ISSUE TITLE
JSServe.record_states brittle with slider + multiple observables

### ISSUE THREAD

**Issue by AlexisRenchon** [MakieOrg/Makie.jl#2223]
I noticed that sometime Observable work for GLMakie, but have issues in WGLMakie. 
Below is an MWE, with multiple Observables that change size. 
In GLMakie, it works perfectly. (with the strategy update val without triggering listeners, then update them triggering listener). Try the code below 
```
using GLMakie 

i = Observable(Int64(round(rand()*100+1))) # array dimensions
x = Observable(rand(i.val).*10) # x values
y = Observable(rand(i.val).*10) # y values
c = Observable(rand(i.val).*10) # color
z = Observable(rand(i.val).*100) # markersize

fig = Figure()
ax = Axis(fig[1,1])

sl = Slider(fig[2, 1], range = 1:1:20, startvalue = 1)
slider = sl.value

scatter!(ax, x, y, color = c, markersize = z)

ylims!(ax, (0,10))
xlims!(ax, (0,10))

on(slider) do stuff
  i.val = Int64(round(rand()*100+1))
  x.val = rand(i.val).*10
  y.val = rand(i.val).*10
  c.val = rand(i.val).*10
  z.val = rand(i.val).*100

  i[] = i.val
  x[] = x.val
  y[] = y.val
  c[] = c.val
  z[] = z.val
end
```
(I know it's a weird code since the `on(slider)` `do` does not care about the value `stuff` of the slider, but it doesn't matter)
Now, the exact same code in WGLMakie, will be glitchy. Here is the code:
```
using WGLMakie, JSServe

app = App() do session::Session    
	slider = JSServe.Slider(1:20)

	i = Observable(Int64(round(rand()*100+1))) # array dimensions
	x = Observable(rand(i.val).*10) # x values
	y = Observable(rand(i.val).*10) # y values
	c = Observable(rand(i.val).*10) # color
	z = Observable(rand(i.val).*100) # markersize

	fig = Figure()
	ax = Axis(fig[1,1])

	scatter!(ax, x, y, color = c, markersize = z)

	ylims!(ax, (0,10))
	xlims!(ax, (0,10))

	on(slider) do stuff
	  i.val = Int64(round(rand()*100+1))
	  x.val = rand(i.val).*10
	  y.val = rand(i.val).*10
	  c.val = rand(i.val).*10
	  z.val = rand(i.val).*100

	  i[] = i.val
	  x[] = x.val
	  y[] = y.val
	  c[] = c.val
	  z[] = z.val
	end 

	sl = DOM.div("data: ", slider, slider.value)
	return JSServe.record_states(session, DOM.div(sl, fig))
end
```

It will sometime update some Observables (e.g., the locations of the dots, there color, their size), sometime update some, sometimes update nothing. 
If you run manually the lines, they do work, though. 
The more complex the code (e.g., 3D plots, meshscatter), the more bugged it gets. 

I think the strategy update `.val` without triggering listener, then update `[]` triggering listener, doesn't work great in WGLMakie.

I have tried to find a way to update everything (points values, multiple attributes) in one observable, but have been unsuccessful so far. 

EDIT: I guess this might be more a `JSServe` issue than a `WGLMakie` issue

**Comment by SimonDanisch** [comment]
Did you try without `JSServe.record_states`? `record_states` is very brittle with sliders + multiple ovservables...

**Comment by AlexisRenchon** [comment]
@SimonDanisch that's the issue I want to report. I renamed it. My goal is to generate standalone html, so record_states is necessary?
 If this issue should be in JSServe, we can close this one and move it there. 
 If it is already known, we can just close this.

**Comment by SimonDanisch** [comment]
I think this is more of a documentation issue.. I thought I made it pretty clear that record_states is brittle, but when I look at the meager docs, it isn't really documented...

**Comment by SimonDanisch** [comment]
Maybe also a testing issue, since we should start adding more tests for it and then document better what's expected to work and what not

**Comment by AlexisRenchon** [comment]
Do you think this is something that can be improved? 
Either by having a way to make multiple observable one, or just as JSServe evolve

**Comment by AlexisRenchon** [comment]
multiple value combinations is mostly a problem with multiple sliders, right? 
A slider with e.g., 20 values, only has 20 combinations, even if there is multiple observables

**Comment by ffreyer** [comment]
@SimonDanisch Is this still relevant with Bonito?

**Comment by SimonDanisch** [comment]
I think it should be a bonito issue in any case...
