### ISSUE TITLE
Colorbar with transparent colormap showing the wrong colors when exporting to PDF or SVG with CairoMakie

### ISSUE THREAD

**Issue by Klafyvel** [MakieOrg/Makie.jl#2238]
Hi,
I encountered this weird bug with CairoMakie today. I am aware of #841, but this might be a bit different. MWE I ran in a temporary environment:

```julia
using CairoMakie, ColorSchemes
xs = range(0, 10, length = 25)
ys = range(0, 15, length = 25)
zs = [cos(x) * sin(y) for x in xs, y in ys]
original_array = ColorSchemes.linear_wyor_100_45_c55_n256.colors
my_cmap = map(((x, α),) -> RGBAf(x.r, x.g, x.b, α), zip(original_array, range(0, 1, length=length(original_array))))
heatmap(xs, ys, zs, colormap=my_cmap)
Colorbar(fig[1,2], hm)
save("test.pdf", fig)
save("test.svg", fig)
save("test.png", fig)
```

This produces the three following figures :

[test.pdf](https://github.com/JuliaPlots/Makie.jl/files/9434342/test.pdf)
![test.svg](https://user-images.githubusercontent.com/6209071/186936568-6c744024-8897-4e18-b0a5-b16c22b075ac.svg)
![test.png](https://user-images.githubusercontent.com/6209071/186936586-b7f45935-a20d-477d-a150-24770e9f896a.png)

As you can see, the colorbar looks weird in the SVG and PDF outputs.

I would be happy to help fix that, but I might need a hint on where to begin (I am not sure if there is a page documenting the internals of Makie ?)

**Comment by lazarusA** [comment]
I have also the same issue using the latest versions. Specially for the pdf output, my colorbar goes wild once there are transparent colours in it.

**Comment by jkrumbiegel** [comment]
Maybe this is the same thing as this https://github.com/JuliaPlots/Makie.jl/pull/2080#issuecomment-1183603088

That's also a color artifact in images in pdfs (the continuous colorbar is implemented as an image to avoid inner edge artifacts)

**Comment by Klafyvel** [comment]
It does look suspiciously alike. Which I guess means this issue should be linked to #2162.
