### ISSUE TITLE
`vlines!` in custom plot recipes?

### ISSUE THREAD

**Issue by MichaelHatherly** [MakieOrg/Makie.jl#2245]
https://github.com/JuliaPlots/Makie.jl/pull/2023 added support for `[h/v]lines!` as recipes. There's a slight difference in behaviour between calling `vlines!` directly on an `Axis` and using it in a custom `@recipe`, see below, where a custom recipe results in excess vertical space taken up by the `vlines`, while the second one gives a more suitable use of space. Is this a bug? Or just something that can't be supported in `@recipe` usage?

```julia
@recipe(CustomPlot, x, y) do scene
    Attributes()
end

function Makie.plot!(cp::CustomPlot)
    scatter!(cp, cp[1], cp[2])
    vlines!(cp, cp[:vlines])
    return cp
end

customplot(rand(5), rand(5); vlines = [0.5])
```

![image](https://user-images.githubusercontent.com/6144086/187442984-14e26cc3-666b-4cb0-8c92-98cd85db8778.png)

```julia
f = Figure()
a = Axis(f[1,1])
scatter!(a, rand(5), rand(5))
vlines!(a, [0.5])
```

![image](https://user-images.githubusercontent.com/6144086/187442910-fceea0b5-4072-4e2b-9093-ff2a6393cad1.png)

This is on `Makie v0.17.13` and Julia 1.7.2.

**Comment by jkrumbiegel** [comment]
Ah I assume this is because `yautolimits = false` of the nested vlines is not picked up correctly. That means the line is measured at the current limits, they are expanded a bit, and the line grows further when they do.
