### ISSUE TITLE
Png output in HTML-capable environments

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#2264]
I'm wondering if it would make sense to output png with an `<img>` wrapper tag instead of as raw image data when the environment can display HTML. The problem is that if I set `px_per_unit = 2` to have a crisp output from CairoMakie, the image can become very large but still kind of blurry in something like Pluto or Quarto. I'm using a retina screen Macbook, so what happens is that one image pixel is displayed with four screen pixels by default. I guess in order to override this, one would have to pass half the image size as `<img width=...` etc, hence the idea to output HTML when png is activated. Not sure how the scale factor should be determined, though. Maybe one would just divide by `px_per_unit`.

**Comment by jkrumbiegel** [comment]
This seems to do it if called directly, question is if we should use this if `CairoMakie.activate!(type = "png")` was used. I think so, because then the image is the same size no matter the `px_per_unit` value.

```julia
function Base.show(io::IO, ::MIME"text/html", f::Figure)
    w, h = widths(f.scene.px_area[]) ./ 0.75
    iob = IOBuffer()
    Base.show(iob, MIME"image/png"(), f)
    b64 = Base64.base64encode(String(take!(iob)))
    print(io, "<img width=$w height=$h src=\"data:image/png;base64, $(b64)\"/>")
end
```

**Comment by ffreyer** [comment]
https://github.com/MakieOrg/Makie.jl/blob/904e7f6370101fed2fad2580d980b2686ec705f4/src/display.jl#L488-L496

Looks like this got added
