### ISSUE TITLE
Docs down

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#2265]
I am currently unable to access the docs:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/61620837/189671014-615e028d-8f4c-4a54-996b-dbb7b7976172.png">

I get the same error for stable and dev docs.

**Comment by SimonDanisch** [comment]
They should be online soon under docs.makie.org, and redirect should be in place soon as well...

**Comment by KronosTheLate** [comment]
Can confirm, thnx ^_^

**Comment by hbsmith** [comment]
Thank Jesus, everything on google points to broken pages
