### ISSUE TITLE
Pasting text into a textbox?

### ISSUE THREAD

**Issue by ConnectedSystems** [MakieOrg/Makie.jl#2266]
Pasting text (with `ctrl+v`) into the textbox does not seem to work - at least on Windows.

```julia
using GLMakie

f = Figure()

tb = Textbox(f[1, 1], placeholder = "Try copy/pasting text into me")

gl_screen = display(f)
wait(gl_screen)
```

Relevant dump from status:

```julia
pkg> status GLMakie
Status `C:\[project path]\Project.toml`
  [e9467ef8] GLMakie v0.6.13
```

**Comment by jkrumbiegel** [comment]
The Textbox is very barebones, currently you can't expect any fancier behavior from it than adding or deleting characters manually. Pasting should be relatively straightforward to implement though.
