### ISSUE TITLE
3D arrows with variable thickness 

### ISSUE THREAD

**Issue by BambOoxX** [MakieOrg/Makie.jl#2271]
Hello, it seems possible to get arrows with a variable `linewidth` for 2D `arrow` / `quiver` plots, given the discussion in #943. 
I do not think that this approach works in 3D, is it ?

**Comment by ffreyer** [comment]
The current implementation assumes scalar inputs for lengthscale, linewidth and arrow_size. The pr should fix that, though in the 3D case `linewidth`is one value per arrow.

**Comment by BambOoxX** [comment]
Thanks for the quick fix @ffreyer !
