### ISSUE TITLE
`scale!` ignores spine lines in Axis3

### ISSUE THREAD

**Issue by fatteneder** [MakieOrg/Makie.jl#2275]
## MWE

```julia
using GLMakie
GLMakie.activate!()

f = Figure()
ax = Axis3(f[1,1])
scale!(ax.parent.scene, 1.5, 1, 1)
f
```

![image](https://user-images.githubusercontent.com/26469701/190237157-b1fc0fe5-a4cd-425e-acc4-88ca06922d9f.png)

Happens with `GLMakie` and `CairoMakie`.

**Comment by jkrumbiegel** [comment]
Yeah you're manipulating the backend scene without Axis3 knowing about it, so some breakage is expected ;)

**Comment by fatteneder** [comment]
Ok.

Using `scale!(ax.scene, 1.5, 1, 1)` instead does not work either.
But the same thing for an `Axis` instead of an `Axis3` object works.

What is the right way to apply scaling to `Axis3` objects? Or is this something that should not be used/needed and instead we should only apply to 'raw' `Scene`s or plot elements (lines, scatter, etc)?

**Comment by jkrumbiegel** [comment]
Axis3 uses the viewmode and aspect keywords plus the limits to calculate its scaling, so those determine the projection matrices and if you apply some additional change to the matrices directly, things will break. Maybe changing the `aspect` will have the effect you want?

**Comment by jkrumbiegel** [comment]
https://docs.makie.org/stable/examples/blocks/axis3/index.html#aspect

**Comment by fatteneder** [comment]
Indeed, `aspect` is what I was looking for.

The reason I tried `scale!` in the first place was that it was mentioned in the docstring of the `transform_marker=true` option in `scatter`.

Thank you!
