### ISSUE TITLE
Latex \dot not working

### ISSUE THREAD

**Issue by ValentinKaisermayer** [MakieOrg/Makie.jl#2287]
```julia
with_theme(Theme(fontsize = 35)) do 
    f = Figure()
    Axis(f[1, 1],
        title = L"\frac{x + y}{\sin(k^2)}",
        xlabel = L"\sum_a^b{xy}",
        # ylabel = L"\sqrt{\frac{a}{b}}",
        ylabel = L"\dot{Q}",
    )      
    f
end
```

![plot_35](https://user-images.githubusercontent.com/50108075/191254957-fd5a54ad-6d59-4ee5-8690-9dbbf1604aba.png)

  [ee78f7c6] Makie v0.17.13
  [13f3f980] CairoMakie v0.8.13

**Comment by jkrumbiegel** [comment]
Did it stop working or never work?

**Comment by ValentinKaisermayer** [comment]
It stopped

**Comment by jkrumbiegel** [comment]
Probably broke with the changes in MathTeXEngine.jl, @Kolaru ?

**Comment by Moelf** [comment]
maybe https://github.com/Kolaru/MathTeXEngine.jl/pull/74 ?

**Comment by Kolaru** [comment]
For some reason with CairoMakie v0.8.13, MathTeXEngine is set to v0.4.3, which is weird since Makie requires v0.5.

By deving Makie and using MathTeXEngine v0.5.1, it is still broken, but differently (the dot is too low, seems to be common to all accents, I'll investigate).

**Comment by Kolaru** [comment]
> For some reason with CairoMakie v0.8.13, MathTeXEngine is set to v0.4.3, which is weird since Makie requires v0.5.

My bad it is not weird, compatibility with MathTeXEngine v0.5 is only available on Makie master yet.

**Comment by ValentinKaisermayer** [comment]
> For some reason with CairoMakie v0.8.13, MathTeXEngine is set to v0.4.3, which is weird since Makie requires v0.5.
> 
> By deving Makie and using MathTeXEngine v0.5.1, it is still broken, but differently (the dot is too low, seems to be common to all accents, I'll investigate).

Any progress?

**Comment by Kolaru** [comment]
Yes the versions are now compatible.

Which revealed that the accents are incorrectly placed, but that's a pure MathTeXEngine issue (https://github.com/Kolaru/MathTeXEngine.jl/issues/89).

**Comment by SimonDanisch** [comment]
This seems to be fixed
