### ISSUE TITLE
allow `nothing` for the `label` in `scatter` etc. to hide it in axis legend?

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/Makie.jl#2300]
perhaps would be nice to allow `nothing` in the `label=` for `lines`, `scatter`, etc. to enable automatic removal of a series from the `axislegend()`. or include a default `label` somewhere in the docs where we can hide it? thank you!

```julia
fig = Figure()
ax  = Axis(fig[1, 1])
scatter!(rand(3), rand(3), label=label_plot_one ? nothing : "scatter")
lines!(rand(3), rand(3), label="line")
axislegend()
fig
```

**Comment by fatteneder** [comment]
implemented in #2350. please close.
