### ISSUE TITLE
`direction=:y` for `band!`

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/Makie.jl#2301]
hi. I need to manually draw a density to match that of `density!` with `direction=:y`, but `band!` cannot accommodate `direction=:y`. would be nice to allow us to manually draw something like below. (I'm trying to plot an analytical distribution on top of the empirical distribution visualized below with `density!`.

<img width="537" alt="Screen Shot 2022-09-26 at 8 55 21 PM" src="https://user-images.githubusercontent.com/30643894/192428327-a9aa1d31-0777-49c7-b588-868a1b734ab9.png">

**Comment by jkrumbiegel** [comment]
You can use `poly`, or pass two vectors of Point2 to `band`.

**Comment by SimonEnsemble** [comment]
thx. for anyone else, here is my code to make my own `band!(..., direction=:y)`.

```julia
function band_direction_y!(ax, x, bot, top, color)
    band!(ax, [Point2(top[i], x[i]) for i = 1:length(x)],
              [Point2(bot[i], x[i]) for i = 1:length(x)], color=color)
end
```
