### ISSUE TITLE
LaTeX strings in annotations?

### ISSUE THREAD

**Issue by gjankowiak** [MakieOrg/Makie.jl#2310]
Is it possible to get LaTeX strings into annotations somehow? The [documentation](https://docs.makie.org/v0.17.13/api/index.html#annotations) has no specific mention, and the following fails:

```
using CairoMakie

f = Figure(resolution=(600,400))
ax = Axis(f[1,1])

t = range(-π, π, 100)
lines!(ax, t, sin.(t))

annotations!(ax, [L"\sin"], [Point(1, 0.5)])

save("annotation.pdf", f)
```

![Screenshot_2022-09-30_14-46-18](https://user-images.githubusercontent.com/6949106/193273323-bfec2e1a-7f4f-4a7d-b238-789503bef8c4.png)

Thank you!

**Comment by Moelf** [comment]
```julia
	annotations!(ax, L"\Psi", position=Point(1, 0.5))
```

works, there's something funky about a list of annotations

**Comment by Moelf** [comment]
@SimonDanisch looks like I lost access when we moved away from JuliaPlots org, possible for me to regain it? want to close this issue

**Comment by jkrumbiegel** [comment]
Ah yeah we just removed all mentions of it but left it in for compatibility. But would definitely be good to at least update the docstring, if not add a deprecation warning.
