### ISSUE TITLE
Allow `object.visible[] = false` for all objects (or something similar)

### ISSUE THREAD

**Issue by rafaqz** [MakieOrg/Makie.jl#2311]
I'm building some interfaces in GLMakie that have a few different plot windows, but largely keep the same widgets besides a few that need to change.

I can show and hide plots simply with `plot.visible[] = false`, but showing and hiding the few controls specific to each window appears to be difficult. 

My first attempt involved simply rebuilding the whole interface, but it took a few seconds, which makes the interface feel very sluggish. Just hiding plots is very snappy in comparison. The problem is buttons, sliders, toggles etc. Once they are in a `GridLayout()` it's not so easy to hide them/swap them for a different widget for a new context, keeping all of their observable connections intact.

What I propose is to extend the `visible` fields on plots to all objects - sliders, buttons and whole GridLayouts, so we can more easily control what is shown in the figure at any time. This does not need to affect the layout - they can still be accounted for in spacing, just not actually visualised. I'm not sure how easy this is to do internally.

**Comment by jkrumbiegel** [comment]
This would mostly be about making `scene.visible = false` work first, as then you could easily set that on a `Block`'s container `Scene`. `GridLayout`s on the other hand are not display objects, they just control positioning, so you can't "hide" them. But one can traverse a layout's children and hide those, which is what you mean anyway I guess.
