### ISSUE TITLE
Save with current axis settings

### ISSUE THREAD

**Issue by ValentinKaisermayer** [MakieOrg/Makie.jl#2315]
If I have a figure with `GLMakie` and want to save it the axis limits will be restored.

**Comment by jkrumbiegel** [comment]
limits!(ax, ax.finallimits[]) should fix the limits to whatever setting you have dialed in manually. This behavior was added to reduce the amount of times limits are calculated when adding plots.

**Comment by nathanrboyer** [comment]
Could you automatically recalculate the limits once as part of the `save` function? I would think this is the default behavior users want. `limits!(fig.figure.current_axis.x, fig.figure.current_axis.x.finallimits[]); save(path, fig)` is too long and has the weird `[]` to remember.

**Comment by SimonDanisch** [comment]
`save(path, fig; update=false)` should do the trick!
