### ISSUE TITLE
SSAO doesn't work for vectors of meshes

### ISSUE THREAD

**Issue by lhupe** [MakieOrg/Makie.jl#2324]
When using `mesh` to plot a vector `v` of meshes, SSAO does not seem to work, regardless of settings both in the plot and its parent scene.
Merging the same data into a single mesh and plotting it restores the expected behaviour. Ηowever, since colours now have to be specified per vertex instead of per mesh, this is inconvenient in some applications.

## MWE
```julia
using GLMakie, GeometryBasics
GLMakie.enable_SSAO[] = true


rects = [Rect3(Vec3f(x,y,0), Vec3f(0.09, 0.09, 0.2*rand())) for x ∈ -1:0.1:1 for y ∈ -1:0.1:1]
meshes = normal_mesh.(rects)
merged_mesh = merge(meshes)

fig = Figure(resolution = (1000, 500))

ls1 = LScene(fig[1,1], show_axis = false)
ls2 = LScene(fig[1,2], show_axis = false)

mesh!(ls1, meshes, color = :magenta, ssao = true)
mesh!(ls2, merged_mesh, color = :magenta, ssao = true)

display(fig)
```
produces
![ssao_mwe](https://user-images.githubusercontent.com/34064555/194920747-ce354256-83ae-40d4-a8ec-356a76986bf5.png)
(Makie v0.17.13)

**Comment by SimonDanisch** [comment]
Ah, I guess we forgot to forward the ssao attribute... you could try this hack to work around it until we merge a fix:
```julia
plot_object = mesh!(ls1, meshes, color = :magenta, ssao = true)
plot_object.plots[1].ssao = true
`
