### ISSUE TITLE
VSCode Plot Pane not working with CairoMakie v0.9.0

### ISSUE THREAD

**Issue by kfrb** [MakieOrg/Makie.jl#2331]
After updating to CairoMakie v0.9.0, plots in VSCode no longer open in the Plot Pane, but as a separate png file.

I tried this example
```julia
using CairoMakie
lines(1:10, rand(10))
```
in a project with only CairoMakie installed
```julia-repl
pkg> status
  [13f3f980] CairoMakie v0.9.0
```
and with the following versions:
```julia-repl
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 16 × Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 16 virtual cores
```
VSCode:
```
Version: 1.72.1 (Universal)
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:25:13.482Z (2 days ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
```
with VSCode Julia Extension `v1.37.2`

**Comment by SimonDanisch** [comment]
Are you sure you have the Plotpane enabled?

**Comment by SimonDanisch** [comment]
Or is this in the repl by any chance? I think this depends on your vscode repl settings...

**Comment by kfrb** [comment]
Hello Simon, thanks for your fast reply!
I checked the VSCode settings and everything should be fine.
The plots show in the Plot Pane again by downgrading with
```julia-repl
pkg> add CairoMakie@0.8.13
```
in the example project.
After that, updating with
```julia-repl
pkg> update
```
results in the plots opening as png files.

**Comment by SimonDanisch** [comment]
Really? That'd surprise me quite a bit...How did you eval the file? Have you set file eval to eval in REPL? VScode has quite a few options like that..

**Comment by kfrb** [comment]
I have tried all `Julia: Execute [...]` commands of the command palette. What else can I try? In what other way can code be evaluated? I'm not sure which REPL settings play a role there as well, but I use almost all default settings otherwise.

**Comment by jkrumbiegel** [comment]
This is not a fault on your end, something in the display stack just got broken and needs to be fixed.

**Comment by lyon-fnal** [comment]
Any thoughts here on how to proceed? I'm seeing the same problem with Jupyter notebooks in VSCode on Mac (plot appears in the Mac Preview window instead of inline). Furthermore, `CairoMakie.activate!(type = "svg")` seems to have no effect. I still get a PNG image in Mac Preview. Downgrading to `CairoMakie@0.8.13` restores the correct behavior.

**Comment by SimonDanisch** [comment]
We're still trying to figure out if we can actually fix this nicely, or if we need to revert the changes...

**Comment by lyon-fnal** [comment]
Thanks! If you want me to try anything, please don't hesitate to let me know.
