### ISSUE TITLE
Should we add InnerTopLeft(), InnerBottomLeft(), etc?

### ISSUE THREAD

**Issue by aramirezreyes** [MakieOrg/Makie.jl#2335]
This concerns the constructs TopLeft(), TopRight(), BottomLeft(), BottomRight(), Right(), Top(), Bottom(), and Left(). These are used to add elements on the potrusions of the axis, as the labels in the following example:
![image](https://user-images.githubusercontent.com/6992761/195718788-46f69e14-4541-424b-b4b7-c736c307c724.png)

Would it be worth it/possible to add equivalent constructs InnerTopLeft(), InnerTopRight(), InnerBottomLeft(), InnerBottomRight(), InnerRight(), InnerTop(), InnerBottom(), and InnerLeft() so that labels can be easily placed inside the axis? e.g.,
![image](https://user-images.githubusercontent.com/6992761/195719690-f80f5b73-2cc4-47f1-b89c-3219a9fd443a.png)

In this last example, the bottom row does not have a title and it is too close to the upper row. Adding a label on an upper potrusion would mess with this.

**Comment by jkrumbiegel** [comment]
You can reuse the axis cells for that and position with halign left and valign top, plus some padding. This only doesn't work so well if the Axis is smaller than its cell (aspect =) but that should not really be used for very complex plots anyway.

**Comment by aramirezreyes** [comment]
I am aware this can be achieved by hand-tweaking. (If I remember correctly
I did the second plot on Makie). This would be more a matter of convenience
which I think is worth it.

It could be as a keyword argument to the label instead of something like
TopRight().

**Comment by jkrumbiegel** [comment]
Ah yeah, I see that it's convenient but it doesn't make sense semantically within the existing framework. For the protrusions, it means something specific to specify TopLeft() etc, it's not just aligning stuff to the top left

**Comment by lazarusA** [comment]
Indeed, this one I do always by tweaking parameters, but it's something that is use in a lot of cases.

**Comment by jkrumbiegel** [comment]
You can also do this nowadays:

```julia
scatter(randn(100, 2))
text!(0, 1, text = "A", space = :relative, align = (:left, :top), offset = (10, -10), textsize = 30)
current_figure()
```

![image](https://user-images.githubusercontent.com/22495855/195904052-59f14fe4-2d4e-4352-ae8c-a31f36e5938a.png)

**Comment by lazarusA** [comment]
This is a good way. I will change things to this approach. Thanks 😊

**Comment by aramirezreyes** [comment]
Oh, that works, thanks!
