### ISSUE TITLE
Setting linecolor in a Theme does not change plot line color 

### ISSUE THREAD

**Issue by garrekstemo** [MakieOrg/Makie.jl#2341]
I've noticed that setting `linecolor` in `Theme()` does not change the plot line color. I'm not sure in what version this first appeared, but it affects the latest CairoMakie (0.9.0) and GLMakie (0.7.0) versions. For example, the `theme_black()` in the default themes sets `linecolor` to white, but it stays the default blue. I have made a MWE theme that also demonstrates this. Here, `backgroundcolor` will update the plot correctly but `linecolor` does not.

```
using CairoMakie

function theme_lines()
    Theme(
        backgroundcolor = :blue,
        linecolor = :red
    )
end

set_theme!(theme_lines())
f, ax, l = lines(0:0.1:10, sin)
f
end
```
![linecolors](https://user-images.githubusercontent.com/8449000/196640830-90bcb78b-0810-4894-b137-c56dba40afdb.png)

**Comment by jkrumbiegel** [comment]
It's because the default cycle on line color overrides the default linecolor theme entry. If you remove the cycle, you'll get the color back.

**Comment by garrekstemo** [comment]
Oh I see. Thanks. I'll write up an explainer on Discourse in case someone else runs into this.
