### ISSUE TITLE
WGLMakie plot pane cut on JuliaHub

### ISSUE THREAD

**Issue by SebastianM-C** [MakieOrg/Makie.jl#2358]
I've tried using WGLMakie on JuliaHub with:
```julia
using JSServe
JSServe.configure_server!(listen_url="0.0.0.0", listen_port=9284, forwarded_port=80, external_url=ENV["JH_APP_URL"] * "proxy/9284")

using WGLMakie
scatter(rand(10), rand(10), rand(10))
```
and I'm getting the figure cut in the plot pane. Do you know how I can investigate this issue?
![image](https://user-images.githubusercontent.com/31181429/197527946-cd294d1f-d440-46a5-a3f2-71b81c5040a4.png)

```
(v1.7) pkg> st -m WGLMakie JSServe
      Status `/mnt/data/.julia/environments/v1.7/Manifest.toml`
  [824d6782] JSServe v1.2.9
  [276b4fcb] WGLMakie v0.7.0
```

**Comment by SebastianM-C** [comment]
@ViralBShah ^

**Comment by pfitzseb** [comment]
Looks like adding a `height: 100vh` to the jsserve div may be enough to fix this:
![image](https://user-images.githubusercontent.com/6735977/197582300-52444e84-6652-4442-9cfa-eccf89fe9de0.png)

Not entirely sure why there's an WGLMakie needs to inject its own iframe though -- is that for isolation purposes?
