### ISSUE TITLE
Color difference between plot and legend markers

### ISSUE THREAD

**Issue by fatteneder** [MakieOrg/Makie.jl#2366]
### MWE

```julia
using GLMakie                                                                                       
GLMakie.activate!()                                                                                 
                                                                                                     
f = Figure()                                                                                        
ax = Axis(f[1,1])                                                                                   
lines!(ax, 1:5, 1:5, label="test")                                                                  
Legend(f[1,2], ax)                                                                                  
                                                                                                     
display(f) 
```

On all of my systems the above yields a legend where the marker's color is slightly brighter than the actual line in the plot:

![image](https://user-images.githubusercontent.com/26469701/197776170-8d94cc20-aa67-4cac-8dd3-bf2398d24e8d.png)

`versioninfo()` and `Pkg.status()` as in #2365.

**Comment by jkrumbiegel** [comment]
I don't really see a difference, I tried with a color picker but the central part looked very similar if not exactly the same. Could be an effect of antialiasing?

**Comment by fatteneder** [comment]
> I don't really see a difference, ...

You can't visually see it or you can't see it in the color picker result?
Because I can certainly tell a difference.

You are right, the central part is the same (I now also tested with `gpick`).

> Could be an effect of antialiasing?

Probably, because if I plot a horizontal line (as it is in the legend) with `lines!(ax, 1:5, ones(5), label="test")` then the visual difference is gone too.

Or maybe its just me going crazy ... :laughing:

**Comment by fatteneder** [comment]
Just for reference:
![image](https://user-images.githubusercontent.com/26469701/197788732-187492c8-1b67-46d6-ab55-d66ecdcd3144.png)
