### ISSUE TITLE
violin plot with textual ticks 

### ISSUE THREAD

**Issue by anandijain** [MakieOrg/Makie.jl#2368]
every example in https://docs.makie.org/v0.18.1/examples/plotting_functions/violin/index.html provides numeric positions along x axis.

how do you use strings? I get issues with convert_arguments. 

i tried xlabel! but that didn't work because of https://github.com/MakieOrg/Makie.jl/issues/1808

id be happy to add an example if I can get it to work

**Comment by anandijain** [comment]
same for boxplot

**Comment by lazarusA** [comment]
you mean like this: https://beautiful.makie.org/dev/examples/generated/2d/violins/airquality/ 

or something else?

**Comment by anandijain** [comment]
Thanks!
