### ISSUE TITLE
regression scatter marker Circle

### ISSUE THREAD

**Issue by lazarusA** [MakieOrg/Makie.jl#2373]
something like this no longer works with the latest release. 

```Julia
scatter(Point2f(0,0);
            marker = Circle(Point2f(0), 0.5f0),
            image = rand(RGB, 10,10)
```

It use to work here: https://beautiful.makie.org/dev/examples/generated/2d/scatters/makie_contributors/

**Comment by jkrumbiegel** [comment]
That's deprecated, you just use `Circle` now with `markersize`

**Comment by lazarusA** [comment]
apologies, but what is the correct full syntax?

**Comment by jkrumbiegel** [comment]
The news has:

> Deprecated concrete geometries as markers like Circle(Point2f(0), 1.5) in favor of using the type like Circle for dispatch to special backend methods

So now you do `marker = Circle, markersize = ...` instead of specifying a size via the marker itself.

**Comment by SimonDanisch** [comment]
We ignored the size of the concrete Geometry in most backends (I think only CairoMakie respected it), so we deprecated it...
