### ISSUE TITLE
confusing behavior in violin and boxplot. presenting misleading data 

### ISSUE THREAD

**Issue by anandijain** [MakieOrg/Makie.jl#2378]
I had a bug where for the first arg of `violin` I did as a part of my loop to generate plots comparing two datasets, `fill(i, length(n))` instead of the proper `fill(i, n)`. This created plots where one side was quite different from the other, despite the summary statistics lining up. 

My main question is: should the first argument length be required to equal that of the second?

```julia
julia> using GLMakie 

julia> x = randn(1000);

julia> violin([1], x)

julia> violin(ones(length(x)), x)

julia> boxplot([1], x)

julia> boxplot(ones(length(x)), x)


```

It's very odd that this plot doesn't center around zero, despite the vector having mean ~ 0.
![image](https://user-images.githubusercontent.com/33790004/198100887-3ad92aa1-cdcd-42bd-9962-1f90696def1a.png)

If we actually make the first argument equal length, then we're fine.
![image](https://user-images.githubusercontent.com/33790004/198100949-96886a35-4207-40d5-bb10-34dd2d62f8d5.png)

Same for boxplots
![image](https://user-images.githubusercontent.com/33790004/198101540-627ea6fc-b589-458a-99c7-7aa73d9cd87f.png)
![image](https://user-images.githubusercontent.com/33790004/198101622-5d7ec149-0931-4703-942a-a3dbcf65e219.png)

thanks

**Comment by ffreyer** [comment]
This has been fixed
