### ISSUE TITLE
Interactivity of GLMakie plots lost after `save`

### ISSUE THREAD

**Issue by fatteneder** [MakieOrg/Makie.jl#2380]
### MWE

```julia
using GLMakie
GLMakie.activate!()

f = Figure()
ax = Axis(f[1,1])
lines!(ax, 1:5, 1:5)
display(f)
```

Running the above gives an interactive plot (e.g. rectangle zoom, scroll zoom, drag pane, reset limits etc.)

If you then run `save("test.png", f)` in the same REPL a nice `png` is generated. However, if you switch back to the `GLMakie` window you notice that neither rectangle zoom nor dragging nor reset limits work anymore, only scroll zoom works.

Problem appears on `GLMakie@v0.7.0` and `julia@v1.8.2`.

**Comment by SimonDanisch** [comment]
Ah jeez...Seems like my "better clean up" was quite destructive after all -.-

**Comment by fatteneder** [comment]
This is fixed by #2367 or?

**Comment by fatteneder** [comment]
Just checked, its fixed on master.

**Comment by fatteneder** [comment]
Wait. What works is
- Run above `mwe.jl`
- Run `save("mwe.png", f)` -> Saves png but the window is not interactable.
- Run `display(f)` to gain interactivity again.

Not sure if that was also how it worked before `v0.18.0`? I will test quickly.

**Comment by fatteneder** [comment]
Ok. On `v0.17.13` you did not need the extra `display(f)` to regain interactivity.
