### ISSUE TITLE
Redundant import of CairoMakie in the Basic Tutorial

### ISSUE THREAD

**Issue by bluzukk** [MakieOrg/Makie.jl#2394]
I was working through the [Basic Tutorial](https://docs.makie.org/stable/tutorials/basic-tutorial/) and noticed that starting in the [#array_attributes](https://docs.makie.org/stable/tutorials/basic-tutorial/#array_attributes) section in the third plot/code example, 
'_using CairoMakie_'  is used in multiple code examples without being needed. Is this on purpose?

If it is not on purpose I propose to remove all imports (except in [#importing](https://docs.makie.org/stable/tutorials/basic-tutorial/#importing))  to keep the examples in the Basic Tutorial consistent.

In addition, I would like to ask if I could 'work' on this since it seems like a good first issue for me :)

**Comment by Moelf** [comment]
The documentation may be generated individually for each section.

also the docs probably is not geared towards someone reading from cover to cover, if they jump to that section they only need the code there to reproduce
