### ISSUE TITLE
Default font does not include all superscript numbers

### ISSUE THREAD

**Issue by jqfeld** [MakieOrg/Makie.jl#2401]
I just noticed, that the new default font (TeX Gyre Heros Makie, since #1897) does not include all superscript numbers (only 1-3 are included). This leads to odd looking log-scale plots, because for the numbers 0, 4-9 DejaVu Sans is used as fallback (#1296):
![test.pdf](https://github.com/MakieOrg/Makie.jl/files/9940363/test.pdf)

One way of solving this problem, would be to add the missing superscripts to the font. But this of course only fixes the given font (still, for the default font it might be reasonable). 
Therefore, one might think about a different fallback strategy if the superscripts are missing. The most naive approach, that comes to mind, would be some automatic generation through scaling and translating the normal number glyphs. (No idea how hard this would be to implement. :sweat_smile: )

**Comment by jkrumbiegel** [comment]
https://github.com/MakieOrg/Makie.jl/pull/2321 is doing that

**Comment by jqfeld** [comment]
Ah, awesome! Thanks!
