### ISSUE TITLE
[GLMakie]hold the windows existing after program which launched outside REPL closed.

### ISSUE THREAD

**Issue by Xlin0mu** [MakieOrg/Makie.jl#2410]
when I run the files in IDE or launch it with console, windows created by GLMakie all shut off automatically after  program closed unless jamming it manual.
Could we add an argument to `display()` controling whether to hold a window existing by create a new window thread?
This help optimizing experience for IDE users.

**Comment by lmshk** [comment]
I think what they meant was that windows `display`ed from a script will automatically close when the process exits. I was facing the same problem. Good to know that I can just `wait` on the `Screen`!

**Comment by Xlin0mu** [comment]
Glad to receive your reply.
I mean to create a new independent process of windows, so closing julia file program won't lead to Makie's windows close.
Seperate the windows program and the window-creator program.
Because IDE need to shut main program, but sometimes we need windows keep exist while using IDE.
Using `wait()` is a good idea, except that it makes IDE wait, too.
Or we can just launch another REPL to generate this window, it's also nice, only drawback is that not in IDE.
Honestly it's not an important feature, just for a better experience of IDE users.

**Comment by SimonDanisch** [comment]
>Because IDE need to shut main program, but sometimes we need windows keep exist while using IDE.

I think this is the main thing I don't understand. Why does the program need to be terminated, while you continue using the IDE? 

Do you maybe want multiple windows? you can use `display(GLMakie.Screen(), figure)` to create multiple windows, which you can just leave open...

**Comment by Xlin0mu** [comment]
Like VSCode: run file -> call `disply()` -> windows occur -> `display()` finished -> process close (also close windows)
It'll terminate program process after all function call finished automatically.
Using `wait()` make IDE always waiting that can't run another file.

**Comment by SimonDanisch** [comment]
Ok, I'm not sure what Makie could improve to help you, so I'm closing the issue. 
Maybe this is more something to be discussed on [discourse](https://discourse.julialang.org/)?
