### ISSUE TITLE
How to add Makie to a personal project only for plotting recipes?

### ISSUE THREAD

**Issue by danilo-bc** [MakieOrg/Makie.jl#2412]
I've been experimenting with Makie recently and I want to create a package which runs and plots a few mathematical functions from personal packages.

I heard that Plots has a RecipesBase package if one wants to create simple plotting recipes and leave the plotting application to the user.

What is the correct way to achieve this?

Example plotting code:
```julia
function plot_as_stem(ax, data_in)
    empty!(ax)
    stem!(ax, data_in, color = :indigo, stemcolor = :indigo, trunkcolor = :indigo)
    nothing
end
```

I want to keep the function packages separate by domain, so if I really need to do include Makie, I'm afraid it will make the size of the (pre)compiled packages too big, since each will have Makie as a dependency. I also wanted to refrain from adding Makie to prevent long precompilation times for packages that are purely mathematical.

Thank you in advance.

p.s.: of course the sample code won't precompile wihtout any reference to Makie since `empty!`, `stem!` and `:indigo` are not present in Julia Base.

**Comment by Moelf** [comment]
use Requires

**Comment by danilo-bc** [comment]
Thank you, it seems to be the solution I need. Is this route mentioned anywhere in the Makie docs? It solves a lot of generic Julia dependency problems, but I can see it being helpful to add a little hint about it somewhere in Makie's docs/tutorials.

**Comment by Moelf** [comment]
it's not really a Makie thing so it would be weird for make to document it. In fact, once MakieCore.jl is ready we probably won't need the Requires.jl hack

**Comment by danilo-bc** [comment]
Great news! I'm closing this and will follow the development closely.
