### ISSUE TITLE
Attribute `palette` for `LScene`

### ISSUE THREAD

**Issue by TCLiuu** [MakieOrg/Makie.jl#2417]
I'm trying to make the color of lines cycle automatically in `LScene` by the keyword `cycle` of `plot` function, but it does not work. After checking the source code of `LScene`, I found that there is no definition of the attribute `palette`. And the `plot!` function for `LScene` does not call `get_cycle_for_plottype` method and `add_cycle_attributes!` method, it cannot handle the keyword `cycle` correctly, which is different from `Axis3D`.

Is that how `LScene` is designed? Are there any future plans to make it support this feature? Thank you.

**Comment by ffreyer** [comment]
After #4131 Axis3 can hopefully replace LScene as the main 3D plotting option and LScene can become a lightweight option that explicitly doesn't support this.

**Comment by ffreyer** [comment]
Nvm this is fixed
