### ISSUE TITLE
Reached "This shouldn't happen..." warning with own recipe

### ISSUE THREAD

**Issue by fbanning** [MakieOrg/Makie.jl#2421]
I've somehow managed to reach

https://github.com/MakieOrg/Makie.jl/blob/9f767a36640369950d662377579dca5d0d0c52ba/GLMakie/src/picking.jl#L116

while working on extending the `abmplot` recipe over at InteractiveDynamics.jl ([link to PR](https://github.com/JuliaDynamics/InteractiveDynamics.jl/pull/114)). Using GLMakie.

I'd like to find out why this is happening but am at a bit of a loss regarding where to look for clues. Does anyone of you have an idea how to hunt down this bug?

<details>
<summary>Package versions in the test environment where this happens</summary>

```julia
  [46ada45e] Agents v5.6.1 `https://github.com/JuliaDynamics/Agents.jl.git#main`
⌃ [13f3f980] CairoMakie v0.8.13
  [a93c6f00] DataFrames v1.4.3
  [31c24e10] Distributions v0.25.77
  [634d3b9d] DrWatson v2.12.0
  [5789e2e9] FileIO v1.16.0
⌃ [e9467ef8] GLMakie v0.6.13
⌅ [1ecd5474] GraphMakie v0.3.6
  [ec714cd0] InteractiveDynamics v0.21.11 `~/.julia/dev/InteractiveDynamics`
⌅ [ee78f7c6] Makie v0.17.13
  [76b6901f] OSMMakie v0.0.5
  [2913bbd2] StatsBase v0.33.21
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [10745b16] Statistics
```

Updating Makie/GLMakie/CairoMakie is currently blocked due to compat entries. We're working on that but I don't think it's relevant for this issue. (Or is it?)
</details>

**Comment by ffreyer** [comment]
Since the loop skips the `cache2plot` check I suppose this would occur if a plot is deleted after opengl sends over the image for picking. It shouldn't be a problem to just `continue` there instead, or do
```julia
if (picks[i, j][1] > 0) && haskey(screen.cache2plot, picks[i, j][1])
    d = (x-i)^2 + (y-j)^2
    i = findfirst(isequal(picks[i, j]), selected)::Int
    if distances[i] > d
        distances[i] = d
    end
end
```

**Comment by fbanning** [comment]
I also didn't notice any issue with it but the REPL prints the warning like crazy after displaying the figure. So should we just replace the warning with a `continue` or what would be the smarter way?

**Comment by ffreyer** [comment]
If the code I posted does the trick I would prefer that. Should be a bit faster I think.

What are you running that triggers the warning?

**Comment by fbanning** [comment]
I've been running the above-mentioned branch with the example SIR model found [here](https://github.com/JuliaDynamics/InteractiveDynamics.jl/blob/graphspace-support/examples/agents/agents_SIR.jl). If you want to test it out yourself, you can run that file up until LOC 192. Once you run `fig` and the window is displayed, the REPL is flooded with the warning messages. Sometimes it doesn't happen on the first try though. If that's the case, close the window and run `fig` again.
