### ISSUE TITLE
Latex string like $\Delta$ should be regular but showing as italic in CairoMakie

### ISSUE THREAD

**Issue by Lightup1** [MakieOrg/Makie.jl#2423]
When use L"\Delta" as label, it should be $\Delta$ since `MathTexEngine.jl` render it as NewComputer Modern Math regular
But CairoMakie renders it as ![image](https://user-images.githubusercontent.com/32999017/202089095-67db97c4-943b-4e28-aa4b-b24a602f7e9e.png) which is italic and causes error when one tries to edit it with Illustrator or Inkscape.
In Illustrator,![image](https://user-images.githubusercontent.com/32999017/202089095-67db97c4-943b-4e28-aa4b-b24a602f7e9e.png) is converted into path.
And, in Inkscape, if you try to reserve the font information,  it becomes garbled.

**Comment by Lightup1** [comment]
Even if you write L"\mathrm{\Delta}",  CairoMakie renders it as ![image](https://user-images.githubusercontent.com/32999017/202089095-67db97c4-943b-4e28-aa4b-b24a602f7e9e.png)

**Comment by jkrumbiegel** [comment]
Makie just receives a font and glyph index pair from MathTeXEngine, it seems unlikely to me that the bug shouldn't be on MathTeXEngine's side. Have you checked what TeXChar MathTeXEngine returns when you parse the L string with the delta? Are you sure the font chosen is regular?

**Comment by Lightup1** [comment]
I'm sure.
```
julia> using MathTeXEngine

julia> generate_tex_elements(L"\Delta")
1-element Vector{Any}:
 (TeXChar 'Δ' [index 3329 in NewComputerModern Math - Regular], [0.0, 0.0], 1.0)
```
And NewComputerModern Math seems only having Regular font.

**Comment by jkrumbiegel** [comment]
Can you load that font file into a font inspection tool and check what's at that index? There are tools like that available as websites

**Comment by Lightup1** [comment]
![image](https://user-images.githubusercontent.com/32999017/202108847-78dd20ee-7d84-4682-ac61-07e131c14f61.png)
Oh, it's italic in that font file.

**Comment by Lightup1** [comment]
But in latex it will give you a regular one:
like:
![image](https://user-images.githubusercontent.com/32999017/202109621-483efa1b-88ac-481e-a4b2-da6400a634de.png)
Is it a bug that `MathTexEngine.jl` renders to an italic glyph?

**Comment by jkrumbiegel** [comment]
Yes I'd say so, you can open an issue there, requesting that the glyph be changed

**Comment by jkrumbiegel** [comment]
I'll close here because there's nothing actionable for Makie
