### ISSUE TITLE
Integrate `MakieTex.jl` into `Makie.jl`

### ISSUE THREAD

**Issue by Lightup1** [MakieOrg/Makie.jl#2426]
Is it better to integratee `MakieTex.jl` into `Makie.jl`?
`MakieTex.jl` now is just not working under the latest version of `Makie.jl`.
In `Matplotlib`, rendering latexstring by latex engines is well supported.
It would be great if `Makie.jl` could support this feature too.

**Comment by ffreyer** [comment]
I think with MathTexEngine existing and being integrated this is not going to happen.
