### ISSUE TITLE
Text with relative space does not show in log-scale figures.

### ISSUE THREAD

**Issue by himcraft** [MakieOrg/Makie.jl#2429]
I want to add some text on my figure, which has a logarithmic scale x-axis. I followed the answer on [julia discourse](https://discourse.julialang.org/t/makie-text-coordinates-relative-to-the-edges-of-the-axis/81102/4) using `space=:relative`. But no text shows up. The MRE is as follows:

```julia
f=Figure()
ax=Axis(
    f[1,1],
    xscale=log10,
)
lines!(ax,100..110,sin)
text!("hello",space = :relative, position = Point2f(0.1, 0.9))
text!("bye", space = :relative, position = Point2f(0.5, 0.5))
current_figure()
```

The figure is:
![plot_10](https://user-images.githubusercontent.com/31373414/202885547-cc28ef1f-c172-499b-aab4-c5152a647da3.png)

Should text with `:relative` space not show in log-scale plots?

**Comment by jkrumbiegel** [comment]
It should, this is currently buggy because the transformation is still applied even though it does not matter for relative space.

**Comment by himcraft** [comment]
After v0.18.4 it can correctly display the texts in `:relative` space with logarithmic scales. Thanks!
