### ISSUE TITLE
Saving to pdf or svg is now errored with larger withite space

### ISSUE THREAD

**Issue by Lightup1** [MakieOrg/Makie.jl#2433]
In v18.3, the saved figure is not cropped to the real size but with a large white area outside the figure not cropped.
![image](https://user-images.githubusercontent.com/32999017/202951103-fc8006c2-71ca-4fae-a77e-4004da66f156.png)

**Comment by fatteneder** [comment]
Could you please provide a self-contained minimal (not-)working example?

**Comment by Lightup1** [comment]
```
size_inches = (6.8, 11)
size_pt = 72 .* size_inches
fig=Figure(figure_padding = 5,resolution=size_pt)
ax=Axis(fig[1, 1])
save("fig.pdf",fig,pt_per_unit=0.5);
```
This should reproduce the problem.

**Comment by fatteneder** [comment]
I cannot reproduce the problem under
```julia
(debug_Makie) pkg> status
Status `~/wd/scratch/debug_Makie/Project.toml`
  [13f3f980] CairoMakie v0.9.3
  [e9467ef8] GLMakie v0.7.3
  [ee78f7c6] Makie v0.18.3
  [276b4fcb] WGLMakie v0.7.3
```

**Comment by Lightup1** [comment]
Sorry for that.
This one will reproduce the error. 
```
using CairoMakie
function debug()
    size_inches = (6.8, 11)
    size_pt = 72 .* size_inches
    fig=Figure(figure_padding = 5,resolution=size_pt)
    ax=Axis(fig[1, 1])
    fig
end
fig=debug()
save("fig.pdf",fig,pt_per_unit=0.5);
```
I just find that wrapping things into a function cause this error

**Comment by Lightup1** [comment]
If you run it in REPL, the error will occur.
But if you run it in a new process, there is no error.
The error also occurs in a pluto.jl notebook.

**Comment by Lightup1** [comment]
To reproduce that, maybe you should run 
```
fig=debug()
save("fig.pdf",fig,pt_per_unit=0.5);
``` 
multiple times in REPL.
My versioninfo:
```
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf26 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 6 on 12 virtual cores
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_PKG_SERVER = https://mirrors.tuna.tsinghua.edu.cn/julia
  JULIA_EDITOR = code
(makie_debug) pkg> st
Status `F:\makie_debug\Project.toml`
  [13f3f980] CairoMakie v0.9.3
```

**Comment by Lightup1** [comment]
Despite the errored cropping, if you just run 
```
save("fig.pdf",fig,pt_per_unit=0.5);
```
multiple times in REPL, you will get errored PDF file with file size to be 0kB

**Comment by Lightup1** [comment]
> The error also occurs in a pluto.jl notebook.

I originally found this error in a pluto notebook.

**Comment by fatteneder** [comment]
Thanks, now I can reproduce it consistently with
```julia
using CairoMakie
size_inches = (6.8, 11)
size_pt = 72 .* size_inches
fig=Figure(figure_padding = 5,resolution=size_pt)
ax=Axis(fig[1, 1])
save("fig.pdf",fig,pt_per_unit=0.5);
save("fig.pdf",fig,pt_per_unit=0.5);
```

After first `save` the file is 4K big, after second it is only 0K.

**Comment by fatteneder** [comment]
> ... after second it is empty with 0K (cat fig.pdf gives no output).

This issue is now different from what you reported initially or?

**Comment by Lightup1** [comment]
Yes, that's two issues, but all occurred when you run some codes several times.

**Comment by de-souza** [comment]
This issue is still ocurring for me after commit 124a450.

Minimum working example:
```julia
using Pkg
Pkg.activate(".")
Pkg.add([PackageSpec(url="https://github.com/MakieOrg/Makie.jl/", rev="124a450"),
         PackageSpec(url="https://github.com/MakieOrg/Makie.jl/", subdir="CairoMakie",
                     rev="124a450")])
using CairoMakie
size_inches = (6.8, 11)
size_pt = 72 .* size_inches
fig=Figure(figure_padding = 5,resolution=size_pt)
ax=Axis(fig[1, 1])
save("fig.png",fig,px_per_unit=0.5);
save("fig.pdf",fig,pt_per_unit=0.5);
```
Result: fig.pdf has larger white space.

**Comment by SimonDanisch** [comment]
Hm, I get:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/1010467/205080922-96d749a4-53bd-45d5-ac10-10bc537d8b80.png">
Looks almost too small :D

**Comment by SimonDanisch** [comment]
Ok, weird... The env I'm currently using should be identical with master for CairoMakie at least, and in that ENV it works without whitespace.
In your env, and also if I do `]activate --temp; add MakieCore#master Makie#master CairoMakie#master`, it doesn't actually work -.-
