### ISSUE TITLE
bug in Pluto for displaying the figure

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/Makie.jl#2438]
figure gets cut off oddly when displaying. only happens if I `save`...

<img width="734" alt="Screen Shot 2022-11-22 at 11 46 25 PM" src="https://user-images.githubusercontent.com/30643894/203494716-811e4d71-5d1f-4fc9-bc59-ae04c8c1fb90.png">
<img width="734" alt="Screen Shot 2022-11-22 at 11 46 37 PM" src="https://user-images.githubusercontent.com/30643894/203494722-fcf973cc-d662-4eb5-b296-ba94d0bded77.png">

(this must be from a recent change, as it did not happen before.)

**Comment by jkrumbiegel** [comment]
maybe related to https://github.com/MakieOrg/Makie.jl/issues/2433?
