### ISSUE TITLE
Improve search result ordering, make results more concise.

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#2448]
The Makie documentation search is lightning fast, which is lovely. But there are two problems that make it a whole lot less useful that it can be.

## Issue number 1: Search result ordering is far from optimal
Currently, more or less whatever I search generally returns results from the API section first:
<img src="https://user-images.githubusercontent.com/61620837/204091483-76a189ec-c6e5-47e1-b9ba-3399272abf1b.png" width="300">
<img src="https://user-images.githubusercontent.com/61620837/204091490-3fc28d70-ce1c-4955-ba9c-9f4229f27f8f.png" width="300">
<img src="https://user-images.githubusercontent.com/61620837/204091495-6cc4681c-7007-471c-a3b7-1b7f77a4eada.png" width="300">

Returning the API is especially useless because it is the same help that you get from the docstrings (right?), so that it is (at least for me) _**never**_ what I go to the full documentation to find.

Other times, the first result is hardly the most relevant:
<img src="https://user-images.githubusercontent.com/61620837/204091509-15db2ec8-f126-4050-8953-ac7960053bde.png" width="300">

This issue is made more painful from the second issue (verbose results), so that one often needs to scroll significantly to get to the relevant results.

Can the ordering of the results have some bias? Perhaps each file could get a particular "general relevance rating" for the search results? Or biased by the most frequently visited pages of the documentation (with some "forgetting factor" to remove initial bias from appearing first)?

## Issue number 2: Results are too verbose
This is all _a single_ result:
<img src="https://user-images.githubusercontent.com/61620837/204091827-c07093ba-2f30-4faa-85b1-42bb47fdb589.png" width="300">
<img src="https://user-images.githubusercontent.com/61620837/204091840-f4cbd825-526f-44a5-a03f-bac06967d3d5.png" width="300">

It is generally not that useful to see all sentences containing the word, as it is pretty much all code, and it can be hard to quickly parse the differences (particularly for newer users). I would **much** prefer seing something like "`**Filename**` (next line) `17 hits found`". This would make it possible to get an overview of the results, rather than the currently verbose and frankly unhelpful display of the hits. 

Alternativly, simply not showing _code_ in the results could make the display of hits go from annoying to useful.

Fixing this would greatly alleviate the pain from issue number 1, but fixing both would clearly be worth some effort IMO.

<img src="" width="300">

**Comment by jkrumbiegel** [comment]
I agree with the API being mostly not very useful as a result, although I find the search result context very useful and would not like reducing that to "x hits" only. Maybe the amount of text shown can be tweaked? Another idea was to replicate a "static search page" where you'd simply have more space to view the results. Stork's default and only inbuilt mode is the search box being populated, and many people have expressed the wish to be redirected to a search page when hitting enter.

**Comment by KronosTheLate** [comment]
A search page would be neat. But perhaps that is out the the realm of actionable if it relies on Stork devs?

So you personally prefer all the text displayed in "issue 2" to "x hits"? Fair enough, as it is a matter of preference. I can however not resist attempting to change your mind: The amount of text drowns out all the other results, in a "more is less" kind of fashion. _Particularily_ with the small amount of pixel-real-estate available.

But if we still disagree on that point, then we still agree on the ordering issue. Is there a good way to make changes to the order?

**Comment by jkrumbiegel** [comment]
The search page would be the same thing as the box, just a full page so there's more space to see things. And maybe the settings could be tweaked for each case to maximize usefulness.

**Comment by KronosTheLate** [comment]
So for the small drop down, you would be open to trying to make the results less verbose to allow viewing multiple results at the same time?

And for ordering - do you know how to change the order of search results?

In asking you to essentially do things, I am hoping to keep the thread active and productive. I want to make clear that I do not expect anything, and that I am very grateful for your work on Makie ^_^

**Comment by bluzukk** [comment]
Hi! Can I work on this issue?

Regarding

**... Issue 1: Search result ordering is far from optimal** 

- I suggest to change the ordering such that more relevant results appear at the top. 
For example if searching for _scatter_, I guess it is best if https://docs.makie.org/v0.19.0/examples/plotting_functions/scatter/index.html appears as the first search result, since it seems most relevant to me.


**... Issue 2: Results are too verbose** 
- I suggest to add a search page with more space for showing the results in addition to the search box.
Then tweak the settings for both cases i.e. make the output of the search box less verbose while showing a more verbose search result on the search page.


In addition I found another Issue with the search:
For example if searching for _Axis_ and clicking the API search result it links to:
https://docs.makie.org/v0.19.0/api/
Instead, I suggest to link to:
https://docs.makie.org/v0.19.0/api/index.html#Axis
I think this linking can be changed by tweaking the Stork config.


Feel free to add opinions to my suggestions.

**Comment by KronosTheLate** [comment]
Your though sound great by me (Y)
Also, your work on improving the Makie docs search would definitivly be much appriciated!
