### ISSUE TITLE
`CairoMakie`'s png output empty for large enough surface plot

### ISSUE THREAD

**Issue by fatteneder** [MakieOrg/Makie.jl#2454]
# MWE

```julia
# using GLMakie
# GLMakie.activate!()
using CairoMakie
CairoMakie.activate!()

Nx, Ny = 512, 8001
x, y = collect(LinRange(-20,40,Nx)), collect(LinRange(-20,20,Ny))
xx, yy = repeat(x, 1, Ny), repeat(y', Nx, 1)
zz = @. sin(xx) * cos(yy)

f = Figure()
ax = Axis3(f[1,1])
surface!(ax, xx, yy, zz)

save("mwe.png", f)
```

- `GLMakie`:
![image](https://user-images.githubusercontent.com/26469701/204265007-8af9efd8-3d9e-438d-8f77-a9d230d7d44c.png)

- `CairoMakie.jl`:
![image](https://user-images.githubusercontent.com/26469701/204264921-6d639cbf-5976-43d7-a3a3-d233065af527.png)

`CairoMakie` seems to do something, because it takes a while for the script to complete.

**Comment by jkrumbiegel** [comment]
have you tried `rasterize = 1` on `surface`?

**Comment by fatteneder** [comment]
Another test says its the overall size of the surface, e.g. if `Nx*Ny >= 2560000 (= 512 * 5000)` then it refuses to plot.

**Comment by SimonDanisch** [comment]
There's another weird limit like that: https://github.com/MakieOrg/Makie.jl/blob/master/CairoMakie/src/primitives.jl#L604
Above that threshold, cairo also just stops rendering without any error....

**Comment by jkrumbiegel** [comment]
Ok but the limit for a single texture makes more sense to me than a count limit for drawing meshes on a bitmap. Unless before the drawing is over, there is some state being accumulated where the count matters. Maybe one can flush that state before the drawing is over?

**Comment by fatteneder** [comment]
With this patch here to read `cairo_pattern_status` and the above MWE I get
```julia
julia> include("mwe.jl")
cairo_pattern_status = no error has occurred
cairo_pattern_status = no error has occurred
cairo_pattern_status = no error has occurred
cairo_pattern_status = out of memory
CairoMakie.Screen{IMAGE}
```

**Comment by fatteneder** [comment]
Not sure why there are 4 calls to `mesh2d`, but I guess it doesn't matter.

I also found two threads discussion some 32k pixel limits:
- https://cairo.cairographics.narkive.com/H3TgPxCc/invalid-value-typically-too-big-for-the-size-of-the-input-surface-pattern-etc
- https://cairo.cairographics.narkive.com/Mkjwvkep/32k-limit-with-image-surface

One threads mentions as a work around to manually tile a surface to avoid these limits.

**Comment by fatteneder** [comment]
Not sure if we should just add a status check like above, because inside `Cairo.jl` there is the following comment:
```julia
# Ideally we'd check the status, but at least for certain releases of the library
# the return value seems not to be set properly (random values are returned)
```

**Comment by jkrumbiegel** [comment]
> Not sure why there are 4 calls to mesh2d

The first three are the Axis3 side panels.
Maybe there's something wrong with the way we call the mesh drawing functions, as the limits you talk about should apply to the overall surface size required for one mesh, but not accumulated over time (as far as I can tell).
