### ISSUE TITLE
`CairoMakie` image with fast_path not working, image with space=:pixel and transformation not working 

### ISSUE THREAD

**Issue by dgleich** [MakieOrg/Makie.jl#2457]
As part of the discussion involving https://github.com/MakieOrg/Makie.jl/pull/2436 the following `CairoMakie.jl` codes do not work. 

```
using CairoMakie
fig = Figure()
image(fig[1,1], Makie.logo()', 
    axis=(yreversed=true,),
    fast_path=false)
fig
```

```
using CairoMakie
fig = Figure()
image(fig[1,1], Makie.logo()', 
    axis=(yreversed=true, yscale=sqrt, xscale=log10),
    space=:pixel)
fig
```

**Comment by jkrumbiegel** [comment]
The code should just ignore transformation functions if the space isn't `:data` and not error in that case I guess.

**Comment by dgleich** [comment]
That's what I'm planning to do in a future edit!

I just would want to make sure that the behavior is consistent with and without the fast path in terms of transformations. But the code without fast_path is currently broken.

**Comment by dgleich** [comment]
Okay, there's a slightly interesting issue here. At the moment, the CairoMakie.jl code combines HeatMaps and Images into one path. But Heatmaps have xy coords defined on edges as they are a DiscreteSurface. Whereas Images have xy coords defined for each pixel location because they are a ContinuousSurface. So the code non fast-path code in CairoMakie works for Heatmaps (that have N+1 points in the xy arrays) but breaks for Images (that only have N points in the xy arrays). 

Looking around in the codes also turned up this odd case. 

In `GLMakie` 
`julia> image([0,1,2,4,8],[0,1,2,4,8], randn(4,4), interpolate=false)`
![test](https://user-images.githubusercontent.com/33995/205537190-ead81413-96f3-4d13-877a-bd14f22fbfd3.png)

In `CairoMakie`
`julia> image([0,1,2,4,8],[0,1,2,4,8], randn(4,4), interpolate=false)`
![test](https://user-images.githubusercontent.com/33995/205537369-547f3de0-f7d4-4774-9b7c-75d4d0a1498a.png)

So GLMakie assumes uniformly spaced images. This was recently noted in #2450 

It seems to me the simple path forward would be to assume that images are uniformly spaced (seems to be the consensus from #2450) ... In which case the transformation issues are fairly easy to handle.

**Comment by ffreyer** [comment]
You can't (directly) set `fast_path` anymore. Both the initial and later cases work fine now
