### ISSUE TITLE
`Legend` markers with different `linestyle`s become indistinguishable for large enough `linewidth`

### ISSUE THREAD

**Issue by fatteneder** [MakieOrg/Makie.jl#2468]
### MWE

```julia
using GLMakie

fig = Figure()
ax = Axis(fig[1,1])

x = 1:10
ys = [ x, x.^2, x.^3 ]
linestyles = [ :solid, :dash, :dot ]

for (y, ls) in zip(ys, linestyles)
    lines!(x, y; linestyle=ls, color=:blue, label="linestyle = $ls", linewidth=5)
end

Legend(fig[1,2], ax)

display(fig)
```

![image](https://user-images.githubusercontent.com/26469701/205605442-e5f0b85c-6d1e-4611-a808-bbe83892719d.png)

Not sure what to do here:
1. We could ignore `linewidth` for the `Legend` markers. But then there is not distinction between thick and thin lines.
2. We can make the marker longer based on the `linewidth` till one period of the pattern fits in. But I guess that might give overly wide `Legends` if `linewidth` becomes large enough.
3. Reduce the length of a period of a pattern so that it fits into the marker's scenes.
4. Other suggestions?

All of the above ideas will cause the actual marker to deviate from what is in the plot.
I think we should check what other plotting libraries do in such cases.

PS: The uneven dash distribution is due to: https://github.com/MakieOrg/Makie.jl/issues/1614

**Comment by jkrumbiegel** [comment]
You would make `legend.patchsize` wider which would also make the lines longer. I don't think wide marker patches are a good default, so I think it's ok to leave that as a thing users should set when they encounter the issue.

**Comment by himcraft** [comment]
Yes. `Legend(fig[1,2], ax,patchsize=(50,20))` is fine.
