### ISSUE TITLE
`fonts` not available for Label

### ISSUE THREAD

**Issue by lazarusA** [MakieOrg/Makie.jl#2476]
The new keyword `fonts` is not available for `Label`, hence doing something like 

```Label(..., fonts = (; regular = "sans")) ```

does not work.

**Comment by jkrumbiegel** [comment]
In that example, where would you want to use it? Usually you should be able to pass all fonts you need to the figure

**Comment by lazarusA** [comment]
[here](https://github.com/MakieOrg/BeautifulMakie/blob/e39601330cb2776b16d4d8e95552e3723dbe365f/examples/datavis/multipleTitles.jl#L33) where `font` is used... it should be `fonts` in order to be consistent?

**Comment by jkrumbiegel** [comment]
Ah no you would just do `font = :bold` there now and it picks up what `:bold` means from the figure by default.

**Comment by jkrumbiegel** [comment]
You can set any fonts, the labels are arbitrary. Compare with this example: https://docs.makie.org/stable/documentation/fonts/#symbol

**Comment by lazarusA** [comment]
thanks for the explanation. My understanding was different. This solves my issue.
