### ISSUE TITLE
Broken fonts and markers when using GLMakie with a custom system image

### ISSUE THREAD

**Issue by lassepe** [MakieOrg/Makie.jl#2480]
To reduce load time, I have GLMakie baked into my custom dev system image. I generate this image from the following precompile work load:

```julia
using GLMakie: GLMakie
GLMakie.scatter([0])
````

This has worked great for a long time but recently this causes issues with fonts and markers. For example, a simple scatter plot now looks like this

![image](https://user-images.githubusercontent.com/10076790/206446587-866f6597-c5e3-4ef5-a7ad-647c655b06d4.png)

Note that the marker is a square instead of a circle and there are various artifacts in the tick labels as well.

This seems to be tied to the system image generation process. Since https://github.com/JuliaLang/julia/pull/47184#pullrequestreview-1163539519 introduces package images, this will probably show up even in a non-custom environment soon. In fact, if I simply run the above workload with julia compiled from that branch, I observe the exact same issue (without a custom system image, just the package image).

**Comment by SimonDanisch** [comment]
Yeah I noticed this too! First thought, it was maybe linux on wsl2 (since I'm never using that, but used it for once to build https://github.com/JuliaLang/julia/pull/47184#pullrequestreview-1163539519)... 
I maybe have some explanation but still need to investigate!

**Comment by shaul-pollak** [comment]
I was able to solve this by redefining the following function in my startup.jl

function Makie.sdistancefield(img, downsample, pad)
    # we pad before downsampling, so we need to have `downsample` as much padding
    pad = downsample * pad
    # padd the image
    padded_size = size(img) .+ 2pad

    # for the downsampling, we need to make sure that
    # we can divide the image size by `downsample` without reminder
    dividable_size = ceil.(Int, padded_size ./ downsample) .* downsample

    in_or_out = fill(false, dividable_size)
    # the size we fill the image up to
    wend, hend = size(img) .+ pad
    in_or_out[pad+1:wend, pad+1:hend] .= img .> (0.5 * 255)

    yres, xres = dividable_size .÷ downsample
    # divide by downsample to normalize distances!
    return Float16.(Makie.sdf(in_or_out, xres, yres) ./ downsample)
end

**Comment by lassepe** [comment]
As of Julia 1.8.4, this problem also appears in GLMakie 0.6.x

**Comment by SimonDanisch** [comment]
This should be fixed on master
