### ISSUE TITLE
More flexible construction of colorbars

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#2482]
Is it possible to generalize the construction of colorbars to accept ColorSchemes.jl objects as input or at least a vector of colors? As I understand it, the colorbar is simply a visual display of a ColorScheme plus ticks and labels.

Currently, custom recipes, which do not have the `colormap` attribute, do not produce plot objects that can be passed to the `Colorbar` constructor.

**Comment by jkrumbiegel** [comment]
You can do `Colorbar(..., colormap = some_map)`, doesn't that work with color schemes?
