### ISSUE TITLE
Colorbar not sync'ed with Menu selection

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#2484]
I have a basic `viewer` function that adds interactive elements to an existing `viz` recipe:

https://github.com/JuliaGeometry/MeshViz.jl/blob/61f232e233be09271476f7f94d1d7b2626a1fca1/src/data.jl#L36-L54

Everything is working perfectly, except that the colorschemes (and colorbars) are not updating with menu selection.

MWE:

```julia
using GeoStats
using MeshViz # master

# random geospatial data
d = georef((a=rand(10,10), b=rand(1:5, 10,10))) |> Coerce(:b => Multiclass)
10×10 CartesianGrid{2,Float64}
  variables (rank 2)
    └─a (Float64)
    └─b (CategoricalArrays.CategoricalValue{Int64, UInt32})

# works perfectly in non-interactive mode
viz(domain(d), color = d.a) # automatically selects continuous colormap
viz(domain(d), color = d.b) # automatically selects categorical colormap

# same as above but adds interactive elements to scene
viewer(d)
```

In the viewer, if we select any variable from the menu, the values get updated correctly, but the colors are still shown in the continuous colormap. I tried finding bugs in the treatment of observables inside the recipe, but couldn't find any. The recipe ultimately calls `Makie.heatmap!(plot, xs, ys, C)` where `C` is already a matrix of color objects, see:

https://github.com/JuliaGeometry/MeshViz.jl/blob/61f232e233be09271476f7f94d1d7b2626a1fca1/src/cartesiangrid.jl#L47

Is it possible that `Makie.heatmap` is not fully integrated with observable colors and colorschemes yet? Any help is appreciated finding the root of the issue.

**Comment by SimonDanisch** [comment]
It really helps to create an MWE, to have an issue get addressed.
Not only because its quicker to try out (because I dont need to install dependencies and wait for them to precompile), but also because it makes sure that I don't spend 90% of my time debugging code I'm not familiar with.
Also, it makes sure that the error really is with Makie.

**Comment by juliohm** [comment]
I will close the issue and provide a MWE with pure Makie later.
