### ISSUE TITLE
Search page redirect doesn't respect prefix

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#2486]
When you search something on `docs.makie.org/dev` and press enter, you get to `https://docs.makie.org/search?q=` so the `/dev` prefix is missing. This leads to a 404. @bluzukk

**Comment by bluzukk** [comment]
Oh that's unfortunate... I will look into fixing this

**Comment by jkrumbiegel** [comment]
Thank you!
