### ISSUE TITLE
Outdated documentation for observables

### ISSUE THREAD

**Issue by vladdez** [MakieOrg/Makie.jl#2487]
Trying to run a code from these page here https://docs.juliahub.com/AbstractPlotting/6fydZ/0.13.9/animation.html# and here https://docs.juliahub.com/AbstractPlotting/6fydZ/0.13.9/interaction.html#Observables-and-Interaction
I realised that the code is clearly outdated. For instance, Node function doesn't exists anymore, it is Observable instead of it now.
Also trying to install AbstractPlotting I always have message what this library is incompatible with Makie. 

I think you need recheck these documentation pages.

**Comment by SimonDanisch** [comment]
We really need to wipe the old docs somehow...
Please use [docs.makie.org](https://docs.makie.org/stable/)
