### ISSUE TITLE
fontsize in Label doesn't work

### ISSUE THREAD

**Issue by vladdez** [MakieOrg/Makie.jl#2492]
I was trying to use the first code snippet from documentation https://docs.makie.org/v0.19.0/examples/blocks/label/index.html and got error:
MethodError: no method matching initialize_block!(::Label; fontsize=30)

So how should I change fontisize in Label() or in text()?

**Comment by jkrumbiegel** [comment]
Are you on version 0.19?

**Comment by vladdez** [comment]
Makie v0.18.1

**Comment by jkrumbiegel** [comment]
Before 0.19 it was textsize, that was one of the breaking changes of that version.
