### ISSUE TITLE
Legend for labeled data in scatter plot

### ISSUE THREAD

**Issue by shayandavoodii** [MakieOrg/Makie.jl#2508]
Suppose I have the following data:
```
using DataFrames, CairoMakie, RDatasets

iris_df = dataset("datasets", "iris")[:, 1:4];

preds = rand((0, 1), 150)
```

Now I want to draw a scatter plot with a legend and arbitrary labels:
```
p = scatter(
  iris_df[:, 2], iris_df[:, 3],
  color=preds,
  dpi=300,
)
```
[![enter image description here][1]][1]

Now I want to add a legend for it, But I'm unsuccessful.  
What I've tried:
```
julia> Legend(p, ["label2", "label1"])

ERROR: MethodError: no method matching _block(::Type{Legend}, ::Makie.FigureAxisPlot, ::Vector{String})
Closest candidates are:
  _block(::Type{<:Makie.Block}, ::Union{GridPosition, GridSubposition}, ::Any...; kwargs...) at C:\Users\Shayan\.julia\packages\Makie\Ggejq\src\makielayout\blocks.jl:287
  _block(::Type{<:Makie.Block}, ::Union{Figure, Scene}, ::Any...; bbox, kwargs...) at C:\Users\Shayan\.julia\packages\Makie\Ggejq\src\makielayout\blocks.jl:298
```
Or:
```
f = Figure()
Axis(f[1, 1])

p = scatter!(
  iris_df[:, 2], iris_df[:, 3],
  color=preds,
  dpi=300,
)

Legend(p, ["label2", "label1"])


ERROR: MethodError: no method matching _block(::Type{Legend}, ::Scatter{Tuple{Vector{Point{2, Float32}}}}, ::Vector{String})
Closest candidates are:
  _block(::Type{<:Makie.Block}, ::Union{GridPosition, GridSubposition}, ::Any...; kwargs...) at C:\Users\Shayan\.julia\packages\Makie\Ggejq\src\makielayout\blocks.jl:287
  _block(::Type{<:Makie.Block}, ::Union{Figure, Scene}, ::Any...; bbox, kwargs...) at C:\Users\Shayan\.julia\packages\Makie\Ggejq\src\makielayout\blocks.jl:298
```

  [1]: https://i.stack.imgur.com/sMV4O.png

**Comment by t-bltg** [comment]
Adding legends is [documented here](https://docs.makie.org/v0.19.0/examples/blocks/legend/index.html).

Note that non-mutating `Makie` plot commands return a [`FigureAxisPlot`](https://docs.makie.org/v0.19.0/documentation/plot_method_signatures/index.html#non-mutating) object which can be unpacked into individual elements `fig, ax, p = fap`.

Here are your options:
```julia
using DataFrames, CairoMakie, RDatasets

iris_df = dataset("datasets", "iris")[:, 1:4]

preds = rand((0, 1), 150)

# option 1 - legend inside plot area
fig, ax, p = scatter(
  iris_df[:, 2], iris_df[:, 3],
  color=preds, dpi=300, label = "label 1"
)

axislegend(ax, position = :lb)

# option 2 - legend outside plot area
fig, ax, p = scatter(
  iris_df[:, 2], iris_df[:, 3],
  color=preds, dpi=300,
)

Legend(fig[1, 2], [p], ["label 2"])
```

**Comment by shayandavoodii** [comment]
@t-bltg, Thanks, But it doesn't give me the desired result. I need two labels; one for black dots and one for yellow. The code you wrote notes the label of black dots.

**Comment by jkrumbiegel** [comment]
Currently, you cannot adjust how a plot's marker is created, so you cannot influence just the color, for example. The reason the dot is black is that this is the default color which is chosen if the plot color is an array. An array of colors can't be shown in one marker, so it is assumed that for the legend the color is not important.

I've been thinking about mechanisms to make all this more adjustable, because I know that people like to create prototypical legend elements corresponding to only some specific values in array-like attributes. But this is a complicated problem and I haven't yet made a lot of progress.

**Comment by jkrumbiegel** [comment]
You can, however, always construct legend elements completely manually. This takes more work but is at least 100% flexible:
https://docs.makie.org/stable/examples/blocks/legend/index.html#creating_legend_entries_manually

**Comment by t-bltg** [comment]
@shayandavoodii in addition to the previous answer, your example is easy to split into 2 plots commands, because `preds` has only `0` or `1`s (maybe use `findall` ?).
You can then label these 2 series individually.

**Comment by shayandavoodii** [comment]
> You can, however, always construct legend elements completely manually. This takes more work but is at least 100% flexible: https://docs.makie.org/stable/examples/blocks/legend/index.html#creating_legend_entries_manually.

Then I tried to make a legend manually based on @t-bltg suggestion:

```julia
using DataFrames, CairoMakie, RDatasets

iris_df = dataset("datasets", "iris")[:, 1:4];
preds = rand((0, 1), 150);

fig, ax, p = scatter(
  iris_df[:, 2], iris_df[:, 3],
  color=preds, dpi=300,
)

elem_1, elem_2 = (
  [
    MarkerElement(
    color = :black,
    marker = :square,
    markersize = 15
    )
  ],
  [
    MarkerElement(
    color = :yellow,
    marker = :square,
    markersize = 15
    )
  ]
)

Legend(
  fig[1, 2],
  [elem_1, elem_2],
  ["label 1", "label 2"],
  "Legend"
)
display(fig)
```
![cairo](https://user-images.githubusercontent.com/52105833/208918420-a9f649e1-6c6d-4209-b0a2-fee14fd19a9e.png)

Thank you so much.

**Comment by shayandavoodii** [comment]
> @shayandavoodii in addition to the previous answer, your example is easy to split into 2 plots commands, because `preds` has only `0` or `1`s (maybe use `findall` ?). You can then label these 2 series individually.

I think it's possible. But don't you think it needs extra code on the data itself to `findall` zeros and ones (considering I might have much more than two labels)?

**Comment by t-bltg** [comment]
> But don't you think it needs extra code

Yeah, your solution is more efficient.

**Comment by jkrumbiegel** [comment]
just note that yellow and black are note really the outermost colors of your colormap. You can do `cm = Makie.to_colormap(:viridis); startcolor = first(cm); endcolor = last(cm)`

**Comment by shayandavoodii** [comment]
> just note that yellow and black are note really the outermost colors of your colormap. You can do `cm = Makie.to_colormap(:viridis); startcolor = first(cm); endcolor = last(cm)`

Are you suggesting putting those kwargs in the `MarkerElement`?

**Comment by jkrumbiegel** [comment]
Instead of `color = :black` you'd do `color = startcolor` or `color = Makie.to_colormap(:viridis)[end]` or anything to that effect.

**Comment by shayandavoodii** [comment]
> Instead of `color = :black` you'd do `color = startcolor` or `color = Makie.to_colormap(:viridis)[1]` or anything to that effect.

I got your point:
```julia
fig, ax, p = scatter(
  iris_df[:, 2], iris_df[:, 3],
  color=preds, dpi=300,
  size=(50, 50),
  colormap = :viridis,
)

cm = Makie.to_colormap(:viridis); startcolor = first(cm); endcolor = last(cm);

elem_1, elem_2 = (
  [
    MarkerElement(
    color = startcolor,
    marker = :square,
    markersize = 15
    )
  ],
  [
    MarkerElement(
    color = endcolor,
    marker = :square,
    markersize = 15
    )
  ]
)

Legend(
  fig[1, 2],
  [elem_1, elem_2],
  ["label 1", "label 2"],
  "Legend"
)
display(fig)
```
Thanks!
