### ISSUE TITLE
CairoMakie outputs rasterized svg if legend is added with RGBA-polygon

### ISSUE THREAD

**Issue by jaakkor2** [MakieOrg/Makie.jl#2510]
Similar in spirit to https://github.com/MakieOrg/Makie.jl/issues/2396, but now with a polygon having alpha color, first output saved to `debug1.svg` is vectorized, but when the legend is added, `debug2.svg` is rasterized.
```
using CairoMakie
CairoMakie.activate!(type="svg")
using Makie.GeometryBasics

item1 = Point2.([[0,0],[1,0],[0,1],[0,0]])
fig = Figure()
ax = Makie.Axis(fig[1,1])
Makie.poly!(ax, Polygon(item1), color = ("#FF0000", 0.7), label = "foo")
save("debug1.svg", fig) # vector (ok)
fig[1, 2] = Legend(fig, ax, "Bar")
save("debug2.svg", fig) # png raster inside .svg
```

 Makie v0.19.0, CairoMakie v0.10.0

**Comment by jaakkor2** [comment]
The type of the polygon color `("#FF0000", 0.7)` is `Tuple{String, Float64}`. Since that type is none of `Union{Symbol, Colorant, Makie.AbstractPattern}`, this path is not hit https://github.com/MakieOrg/Makie.jl/blob/v0.19.0/CairoMakie/src/overrides.jl#L39-L40

Modifying the color definition to `RGBAf(1,0,0,0.7)` saves the svg into vector format.

**Comment by jaakkor2** [comment]
Another problematic color definition `(:red, 0.7)` has type `Tuple{Symbol, Float64}`.

**Comment by SimonDanisch** [comment]
Oh, the color should really get converted before calling such a function!
