### ISSUE TITLE
Add `@test_figure` macro to support figure testing

### ISSUE THREAD

**Issue by hannahilea** [MakieOrg/Makie.jl#2515]
From Beacon-internal code by @SimonDanisch, we use the following macro all over our codebases: 

```julia
IMAGE_DIR = joinpath(pkgdir(Foo), "test", "test_images")
mkpath(IMAGE_DIR)

"""
    test_figure(name, figlike)

Does reference testing with Percy of the figure.
Name needs to be unique across tests for now.
"""
macro test_figure(name, figlike)
    # In julia we can only test if saving the image actually works
    # In percy, we then compare it to the reference images
    return quote
        result = FileIO.save(joinpath(IMAGE_DIR, string($(esc(name)), ".png")),
                             $(esc(figlike)))
        @test $(esc(figlike)) isa Makie.Figure ||
              $(esc(figlike)) isa Makie.FigureAxisPlot || isfile(p)
    end
end
```

It would be great to have this as an official macro, e.g.

```
@test_figure <IMGAGE_DIR> <IMAGE_NAME> fig
```
where IMAGE_DIR could be `missing` or something for cases where users do not want the image saved at all, just want it tested _as_ an image.

(While we happen to upload our IMAGE_DIR to percy as part of CI, users may want to do something else with it and/or skip the save step altogether)

**Comment by jkrumbiegel** [comment]
Not sure I get what this is supposed to do. It saves the figure to a png and then tests if we're dealing with a `Figure` or a `FigureAxisPlot` or whether some variable `p` which I don't see is a file. Where is it doing any kind of reference testing?

**Comment by ffreyer** [comment]
Same, can this be closed? If this is about testing infrastructure I don't think it'll be useful for us.
