### ISSUE TITLE
Surface of unstructured grid

### ISSUE THREAD

**Issue by b-fg** [MakieOrg/Makie.jl#2516]
I have an unstructured grid consisting of high-order elements (multiple points per element). Is there a way I can use the `surface` plot given that I transform my grid data into a vector of `x` and `y` positions (points cloud), and another vector of `z` values?
Ideally it would be something like the `tricontourf` but for surfaces.
Thanks!

**Comment by jkrumbiegel** [comment]
You mean you need something that triangulates an unstructured three-dimensional point cloud into a mesh that can the be plotted with `mesh`?

**Comment by b-fg** [comment]
Well I would like 3D axes that take `x` and `y` values for 2D position and `z` values for height. This would be then plotted as a surface (after some triangulation). For example: https://beautiful.makie.org/dev/examples/generated/2d/surfaces/surface/
Ideally the input to `surface` would be 3 `Vector`s.

**Comment by jkrumbiegel** [comment]
right but `surface` relies on matrix structure to determine the connectivity, so if you pass vectors you have to decide the triangulation some other way. And that is essentially what `mesh` does.

**Comment by b-fg** [comment]
Sure, but can I still get the 3D surface view using `mesh`? Also documentation from `surface` mentions the possibility of using `Matrix` types for coordinates of irregular grids, so this might be an option but I am unsure on how would this be implemented. Is there an example out there? Thanks.

**Comment by juliohm** [comment]
@b-fg are you aware of the Meshes.jl + MeshViz.jl combo? If you are working with a lot of non-trivial mesh topologies, we provide Makie recipes to visualize them with ease.

**Comment by b-fg** [comment]
I have not seen this yet, could you please point me to an example?

**Comment by juliohm** [comment]
Please read the documentation, it contains various examples: https://juliageometry.github.io/Meshes.jl/stable

If you create a `mesh` object from Meshes.jl, the visualization is as trivial as `viz(mesh)`.

Take a look at the README of MeshViz.jl and the test suite for more examples: https://github.com/JuliaGeometry/MeshViz.jl

**Comment by jkrumbiegel** [comment]
Isn't the difficulty here to create the mesh in the first place? Once you have a connectivity structure, plotting it is easy. The question is what structure you want to have given your data. You still haven't really given an example that would clarify this so we can only guess.

**Comment by b-fg** [comment]
I do have the connectivity, so I could create a mesh indeed. The question was more related on having an analogous function as the `tricontourf` but for `surface`. I see that the tessellation is required beforehand in this case, so I will just try to use `MeshViz.jl` for the moment. Closing this now and I will reopen in case anything comes up. Thanks both!
