### ISSUE TITLE
Hardcode Makie's default fonts to avoid findfont latency

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#2528]
It seems that font search can account for long loading latency if a user has a lot of font files https://github.com/JuliaLang/julia/pull/47184#issuecomment-1364028015

There were ideas to solve this on the FreeTypeAbstraction level by caching the list of fonts found on the system, for example in this issue: https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/issues/67

I think it might make sense to just add the names of Makie's default fonts as they are specified in the theme to `Makie.to_font`, so that `findfont` is not even run for those names. Sort of like:

```julia
if fontname == "TeX Gyre Heros Makie Regular"
   # access font file shipped with Makie
elseif fontname == "TeX Gyre Heros Makie Italic"
    ....
else
    findfont(...
```

I think this would be the easiest to do because it doesn't need a caching mechanism to alleviate the latency issue (we can still add better caching to FreeTypeAbstraction later if desired).

**Comment by timholy** [comment]
This seems like the right solution. We're starting to write up TTFX blog posts etc. that will include many benchmarks, and it would be nice to be able to include Makie. Fixing this issue appears to be Makie's ticket-to-entry (I will exclude it from discussion otherwise).

Plots has a similar (though much less serious) issue, xref https://github.com/jheinen/GR.jl/issues/505.

**Comment by jkrumbiegel** [comment]
@timholy do you want to check if the problem is gone with #2531?

**Comment by timholy** [comment]
Previously I had a latency for `@time @eval display(plot(sin.(rand(100))))` of ~19s. Now it's 2s! Thanks so much!

**Comment by sefffal** [comment]
On my computer and Julia master, this brought down the `using` time of GLMakie from about 40s to 17.5s

**Comment by jkrumbiegel** [comment]
It's crazy that this was going on for so long, goes to show again that the systems that the devs run matter a lot.
