### ISSUE TITLE
`axislegend` cannot accept an axis and title at the same time

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/Makie.jl#2530]
I'd like to draw an `axislegend` on a particular axis `ax` _with_ a `title`. the first two calls to `axislegend` work as expected bu the latter fails. of course, this is a toy example; I wish to do this on a plot with many axes. thanks.

```
fig = Figure()
ax = Axis(fig[1,1])
scatter!(rand(2), rand(2), label="a")
axislegend(ax)   # works
axislegend("hi") # works
# axislegend(ax, title="dude") # broken
fig
```

**Comment by jkrumbiegel** [comment]
There seems to be a method missing there, in principle all `axislegend` versions should forward to `Legend` with all variants supported.

**Comment by SimonEnsemble** [comment]
agreed. `axislegend(ax, "title")` nor `axislegend("title", ax)` works either.

another `axislegend` issue is that it should work as usual when no label is provided
```
fig = Figure()
ax = Axis(fig[1,1])
scatter!(rand(2), rand(2))
axislegend("my title", position=:rt) # ERROR
fig
```
oddly, it runs if I pass `label=nothing` but then something really weird happens.
```
fig = Figure()
ax = Axis(fig[1,1])
scatter!(rand(2), rand(2), label=nothing)
axislegend("my title", position=:rt) # ERROR
fig
```
![image](https://user-images.githubusercontent.com/30643894/209850070-e833e55b-cf64-4512-bf5d-4488c0fe4368.png)

**Comment by jkrumbiegel** [comment]
That would happen with an empty legend I guess, because the GridLayout in which the labels are placed is emtpy and therefore cannot contract.
