### ISSUE TITLE
ReferenceTests README link is broken in README

### ISSUE THREAD

**Issue by DanielVandH** [MakieOrg/Makie.jl#2532]
The README links to https://github.com/MakieOrg/Makie.jl/blob/master/ReferenceTests/README.md for more information about ReferenceTests in the "Developing Makie" section. This link is broken. There doesn't seem to be README.md anywhere in https://github.com/MakieOrg/Makie.jl/tree/master/ReferenceTests, so I'm not sure if a correct link does exist.

**Comment by thomvet** [comment]
I think the intent is to link the README of The package ReferenceTests.jl (https://github.com/JuliaTesting/ReferenceTests.jl). 

Will Make a PR when back at a computer.

**Comment by hyrodium** [comment]
>I think the intent is to link the README of The package ReferenceTests.jl

The UUIDs of these package are different:

* `d37af2e0-5618-4e00-9939-d430db56ee94` [Makie.jl/ReferenceTests/Project.toml](https://github.com/MakieOrg/Makie.jl/blob/16311279aeca43c57a9b8e862a842275befd82cc/ReferenceTests/Project.toml#L2)
* `324d217c-45ce-50fc-942e-d289b448e8cf` [ReferenceTests.jl/Project.toml](https://github.com/JuliaTesting/ReferenceTests.jl/blob/550b61c6aaac67c767615783c6475b9050595d3d/Project.toml#L2)

I think renaming Makie.jl/ReferenceTests package would be better to avoid the confusion.

**Comment by SimonDanisch** [comment]
@jkrumbiegel I think this readme is what was supposed to link to?
https://github.com/MakieOrg/Makie.jl/blob/v0.20.0/ReferenceUpdater/README.md
And I guess it got lost when factoring out ReferenceUpdater?

**Comment by SimonDanisch** [comment]
I updated the link
