### ISSUE TITLE
Missing method for ispressed and Exclusively

### ISSUE THREAD

**Issue by mkoculak** [MakieOrg/Makie.jl#2538]
Hi,
I am working on some plot interactions with hotkeys and was following the documentation on this matter.

However, when combining `ispressed()` and `Exclusively`
```julia
rawHotkeys = Dict(
    "stepBack" => Exclusively(Keyboard.left),
    "stepForw" => Exclusively(Keyboard.right),
    "stepBackFull" => Exclusively((Keyboard.left_shift & Keyboard.left)),
    "stepForwFull" => Exclusively((Keyboard.left_shift & Keyboard.right)),
)

on(events(fig).keyboardbutton) do event
        ispressed(fig, rawHotkeys["stepBack"]) && step_back()
        ispressed(fig, rawHotkeys["stepForw"]) && step_forw()
        ispressed(fig, rawHotkeys["stepBackFull"]) && step_back()
        ispressed(fig, rawHotkeys["stepForwFull"]) && step_forw()
end
```

I got an MethodError:
```julia
MethodError: no method matching ispressed(::Figure, ::Exclusively)
```

This is for:
```
[ee78f7c6] Makie v0.19.0
[e9467ef8] GLMakie v0.8.0
```

Looking at source code, in the [crucial line](https://github.com/MakieOrg/Makie.jl/blob/9c9cc6acd56fa01e640665721e7bfec643db4162/src/interaction/events.jl#L266) its the only method variant that has type declaration on the first argument.
Extending `ispressed` with exactly the same code without type declaration solves the issue and interaction works as intended.

Is this an omission or is it left there deliberately?

**Comment by ffreyer** [comment]
It should be fine to remove the `::Scene` type there. They were probably all typed at the start and this one got overlooked.

**Comment by mkoculak** [comment]
That was my thought. I'll make a pull request for removing the type.
