### ISSUE TITLE
WGLMakie: Synchronization of Makie and JS Camera

### ISSUE THREAD

**Issue by hexaeder** [MakieOrg/Makie.jl#2543]
In `GraphMakie`, I use `project(ax.scene, p)` to project node positions in pixel space to calculate angles to align labels with edges. In WGLMakie this projection accumulates some error unter rotation.

MWE:
```julia
using Pkg
pkg"activate --temp"
pkg"add GraphMakie, WGLMakie, Graphs, NetworkLayout, JSServe"
pkg"precompile"
using GraphMakie, WGLMakie, Graphs, NetworkLayout, JSServe

JSServe.browser_display()
WGLMakie.activate!()

g = complete_graph(3)
fig, ax, p = graphplot(g;
                       layout=Spring(dim=3),
                       nlabels=repr.(1:nv(g)),
                       elabels="edge ".*repr.(1:ne(g)))
```

https://user-images.githubusercontent.com/35867212/210257277-763419dd-4fc0-4582-97c5-7468a1d25f1b.mp4

Things i've noticed while trying to find out whats happening (not sure if they are actually usefull for you):

1. problem seems to be especially bad if the cursor leaves the plot area. Maybe the mouse positions outside the plot are still counted for the Makie rotation?

2. The following code explicitly creates such discrepancy: using `rotate_cam!` changes the projection but not the plot itself.
```julia
WGLMakie.activate!()

fig, ax, p = lines([(0,0,0), (1,1,1)])

Makie.project(ax.scene, Point3f(1,1,1))
# 2-element Vec{2, Float32} with indices SOneTo(2):
#  384.49997
#  310.39197

rotate_cam!(ax.scene, (0, 0.1, 0)) # plot does not change
Makie.project(ax.scene, Point3f(1,1,1))
# 2-element Vec{2, Float32} with indices SOneTo(2):
#  365.5982
#  310.90863
```

**Comment by ffreyer** [comment]
This has been fixed
