### ISSUE TITLE
How to set the marker space in scatter lines

### ISSUE THREAD

**Issue by crazyfireji** [MakieOrg/Makie.jl#2562]
if my data Distribute in a increase or exp, how to adapt the space of every scatter, i want get a line with data, but not a scatter
![mmexport1672994656013](https://user-images.githubusercontent.com/112403698/210964806-f11e22bb-6c0e-4854-82fb-7e98a7e60958.png)

**Comment by jkrumbiegel** [comment]
I don't understand what you're asking. The dots of the scatter are placed at every data point you pass in. So the spacing depends on your data.

**Comment by SimonDanisch** [comment]
It's not clear what you mean here, please use [discord](https://discord.gg/dwxUVEH6Tz) for help questions, instead of filing bug reports.

**Comment by crazyfireji** [comment]
> I don't understand what you're asking. The dots of the scatter are placed at every data point you pass in. So the spacing depends on your data.

You can set any line style interval via an array of numbers.
I want plot a line with marker, but not with scatter, the marker in line with marker distribution equally, but it will depend on data in scatter. I'm poor in English, I don't know whether it's clear. like lines(1:1000,1:1000), i want the marker is star or others, but if xscale=log10，if I use scatterline, the marker will distribute with unequal space, I want equal distribute marker

like this picture, I need more linestyle to distinguish the result, but I only know dot, dashdot, I need more, so I used scatter, but the scatter space unequally because the x is log
![mmexport1673005632446](https://user-images.githubusercontent.com/112403698/211006560-ae5b7901-1b83-4501-86cb-85686ab60461.png)
A better result like this
![mmexport1673005763175](https://user-images.githubusercontent.com/112403698/211006842-ee69b877-26eb-431b-9f5e-328263793216.png)

**Comment by jkrumbiegel** [comment]
Are you sure that the example in python is done via line style? At least I've never seen that before with markers.

If you were plotting in linear space you could just pick a subset of equally spaced points from your data and do a separate scatter with those. As you're plotting in log space, the points must be equally spaced in log space.

Let's say you have n equally spaced values. Then you can pick a subset for your log axis by computing indices like this (untested):

```julia
indices = round.(Int, exp.(range(log(1), log(n), length = 20)))

scatter!(xvals[indices], yvals[indices])
```

**Comment by crazyfireji** [comment]
> Are you sure that the example in python is done via line style? At least I've never seen that before with markers.
> 
> If you were plotting in linear space you could just pick a subset of equally spaced points from your data and do a separate scatter with those. As you're plotting in log space, the points must be equally spaced in log space.
> 
> Let's say you have n equally spaced values. Then you can pick a subset for your log axis by computing indices like this (untested):
> 
> ```julia
> indices = round.(Int, exp.(range(log(1), log(n), length = 20)))
> 
> scatter!(xvals[indices], yvals[indices])
> ```

second picture plotted by python
`    ax.plot(yd, D_term, 'o', ls='--', markevery=0.1, label='D')
     ax.plot(yd, V_term, 'v', ls='--', markevery=0.1, label='V')` 
this code plot the second fig.

**Comment by crazyfireji** [comment]
> 

PyPlot Can work well too, but Plots.pyplot() can't
