### ISSUE TITLE
Add marker on lines

### ISSUE THREAD

**Issue by crazyfireji** [MakieOrg/Makie.jl#2568]
I want add some markers on lines, but it can't work. I don't want plot scatterlines, because the scatter space in scatterlines depends on data. I want run like this:
`lines(x, y, linestyle=:dot, marker=:cross)`
It can run, but no marker on lines.
![mmexport1673060788778](https://user-images.githubusercontent.com/112403698/211128666-49d2222e-3643-4c00-beef-d57f386d6a55.png)

**Comment by ffreyer** [comment]
This is the same thing you've asked for in #2563, right?

**Comment by SimonDanisch** [comment]
I'd say close this one and continue in #2563, since there has been some discussion of this feature already...You can also edit your first comment + title, if you want to make things clearer.
