### ISSUE TITLE
WGLMakie: Axis3(Figure()) error Timed out  

### ISSUE THREAD

**Issue by AlexisRenchon** [MakieOrg/Makie.jl#2575]
WGLMakie Axis, Menu, and many other are created without issue, but Axis3 still creates a Timed out error

MWE: 

using WGLMakie
fig = Figure()
ax3D = Axis3(fig[1,1])

**Comment by SimonDanisch** [comment]
Fixed by: 
https://github.com/MakieOrg/Makie.jl/pull/2856
