### ISSUE TITLE
Add Roman Number to Figure

### ISSUE THREAD

**Issue by crazyfireji** [MakieOrg/Makie.jl#2581]
how to display a Roman number on the figure 
![mmexport1673345941580](https://user-images.githubusercontent.com/112403698/211525034-86f19c3c-f5b2-41d0-a0dc-9ab6c5f84678.png)

**Comment by jkrumbiegel** [comment]
Please check out the discord channel or the discourse forum linked to from the docs for usage questions, the issues are for bugs and feature requests.
