### ISSUE TITLE
Rasterize functionality broken in CairoMakie

### ISSUE THREAD

**Issue by awage** [MakieOrg/Makie.jl#2608]
Hi! The rasterizing function doesn't work anymore. Is there a workaround?
MWE: 

```
using CairoMakie
using Random
fig = Figure(resolution = (1024, 768))
ax = Axis(fig[1,1])
scatter!(ax, rand(200000) , rand(200000), markersize = 0.7, color = :black, rasterize = 4)
save("raster_test.png",fig)
save("raster_test.svg",fig)

```

Status: 
[13f3f980] CairoMakie v0.6.3
[ee78f7c6] Makie v0.15.0

**Comment by asinghvi17** [comment]
Not sure why - could be that a code path has changed.  I'll have to look into it.

**Comment by awage** [comment]
I have tried on fresh julia install v1.8: 

```
  [13f3f980] CairoMakie v0.10.1
  [ee78f7c6] Makie v0.19.1

```

The svg file has no image: 

```
 @show !occursin("<image id=", read("raster_test.svg", String))
!(occursin("<image id=", read("raster_test.svg", String))) = false
false
```

![Captura de pantalla_2023-01-18_10-29-54](https://user-images.githubusercontent.com/3494384/213134558-839b8ab0-79ee-4001-801b-03a81cf82e63.png)

**Comment by awage** [comment]
I will check out Makie in dev and try to debug a little bit further. I will come to you if I don't find the bug.

**Comment by awage** [comment]
@asinghvi17 it is not a bug. I've checked out the package and cleaned the cache and now everything is working. I have no idea why it wasn't working. Sorry for the noise.

**Comment by SimonDanisch** [comment]
Maybe we should add some test like your MWE?
```julia
using CairoMakie
using Random
fig = Figure(resolution = (1024, 768))
ax = Axis(fig[1,1])
scatter!(ax, rand(200000) , rand(200000), markersize = 0.7, color = :black, rasterize = 4)
save("raster_test.png",fig)
save("raster_test.svg",fig)
@testoccursin("<image id=", read("raster_test.svg", String))
```
Not sure how extensive our current testsuite tests rastererization...

**Comment by asinghvi17** [comment]
We already do that, more or less (see https://github.com/MakieOrg/Makie.jl/blob/master/CairoMakie/test/rasterization_tests.jl)
