### ISSUE TITLE
Extra workflow runs

### ISSUE THREAD

**Issue by jariji** [MakieOrg/Makie.jl#2619]
I filed an issue a few minutes ago https://github.com/MakieOrg/Makie.jl/issues/2618 and then I got a notification email about a failed build. https://github.com/MakieOrg/Makie.jl/actions/runs/3965138006

I don't think this is intended, I shouldn't be getting build notifications after opening an issue.

**Comment by jkrumbiegel** [comment]
Thanks, there must be a spurious trigger, will investigate.

**Comment by SimonDanisch** [comment]
We do have `on issues` in CompatHelper:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/1010467/223083147-f502b389-d3f0-40c3-98aa-c8c969880e1e.png">

Which doesn't seem to be in the official compathelper script:
https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml

**Comment by SimonDanisch** [comment]
This should fix it: https://github.com/MakieOrg/Makie.jl/commit/04c43f8ef89a0421787e9b999bb3a12539a951b7
