### ISSUE TITLE
Color gradient test changed

### ISSUE THREAD

**Issue by SimonDanisch** [MakieOrg/Makie.jl#2635]
This:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/1010467/215133279-63fd4d55-818b-4b69-9ff1-9a8b34d83222.png">

became this on all backends:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/1010467/215133211-10ea40dc-572e-401b-9a27-8d3a03f58934.png">

On recent PRs.. 
Since the last merged PR doesn't show this behaviour, and it suddenly showed up in all newly opened PRs, I'm suspecting the new PlotUtil release:
https://github.com/JuliaPlots/PlotUtils.jl/releases/tag/v1.3.3
@t-bltg, could such a change be introduced by that release? The timing fits perfectly and it does seem to touch color gradient code...

**Comment by t-bltg** [comment]
Hum, could be. On which backend is it ?

I ran some Makie checks in https://github.com/JuliaPlots/PlotUtils.jl/pull/145, and didn't observe any regression.

**Comment by SimonDanisch** [comment]
> On which backend is it 

As I said, all backends ;) Did you test something like in the test that fails?

```julia
    cmap = cgrad([:black,:white,:orange],[0,0.2,1])
    fig = Figure(resolution=(400,200))
    ax = Axis(fig[1,1])
    x = range(0,1,length=50)
    scatter!(fig[1,1],Point2.(x,fill(0.,50)),color=x,colormap=cmap)
    hidedecorations!(ax)
    Colorbar(fig[2,1],vertical=false,colormap=cmap)
    fig
```

**Comment by t-bltg** [comment]
> Did you test something like in the test that fails?

All tests were clear for `Makie` and `CairoMakie`.

I will investigate with the reproducer at https://github.com/MakieOrg/Makie.jl/issues/2635#issuecomment-1406715732.

**Comment by t-bltg** [comment]
Wait, how come recent PRs such as https://github.com/MakieOrg/Makie.jl/commit/07c5f618c04910c5122045344b50b6dd77109ef4 (2 hours ago) have a green CI (they ran against PlotUtils `1.3.3` which was released yesterday) ?

**Comment by SimonDanisch** [comment]
Sadly, the visual difference is too small to fail CI 😢 Long standing problem with our reference tests -.-

**Comment by t-bltg** [comment]
Hum, that explains.
A test with a massive colorbar (or similar, taking the whole figure size) should maybe be added ...

Typical regression to be caught by a test suite I'd say.

That being said let's fix this.

**Comment by SimonDanisch** [comment]
If it helps, I just tested the two PlotUtils version against GLMakie@latest and the culprit is indeed `PlotUtils@1.3.3`

**Comment by t-bltg** [comment]
Yep, working on a fix, and most important a test.

**Comment by t-bltg** [comment]
I'm going to merge and release a fix once ci is green https://github.com/JuliaPlots/PlotUtils.jl/pull/149.

**Comment by t-bltg** [comment]
https://github.com/JuliaRegistries/General/pull/76516, should be available in ~20m.

**Comment by t-bltg** [comment]
Merged in `General`.

This issue is now covered by added tests.

Still, the coverage is quite low in `PlotUtils`; I'm marking that on my TODO list: the only remedy to these regressions is more and more coverage (a significant effort has been made for `Plots` reaching about `~90%` cov, but more needs to be done in `PlotUtils` ...).

Sorry for the trouble !

**Comment by SimonDanisch** [comment]
Thanks for the quick fix!
