### ISSUE TITLE
[Feature request] Add a markerevery option to scatter/scatterlines

### ISSUE THREAD

**Issue by RayleighLord** [MakieOrg/Makie.jl#2639]
It would be nice to have an option to select the number of markers when using scatter or scatterlines. It is frequently the case where you have more data points than you want to show with markers and picking a subset of that vector is a minor inconvenience.

**Comment by ffreyer** [comment]
Ah I forgot to mention that there is already an issue about it. See #2563

**Comment by crazyfireji** [comment]
does it solved?

**Comment by RayleighLord** [comment]
No, but since it was duplicated I thought it was better to close this one. I am somewhat new to GitHub, should have I procceeded otherwise?

**Comment by jkrumbiegel** [comment]
No you're good :)
