### ISSUE TITLE
How to make subplot more compact and move ticks of colorbar

### ISSUE THREAD

**Issue by crazyfireji** [MakieOrg/Makie.jl#2651]
As mentioned in title, I can't move the ticks locations and make the subplot more compact as fig 1
![mmexport1675567656077](https://user-images.githubusercontent.com/112403698/216800120-a67fd1b5-13f1-4d41-b60b-adad924f8746.png)
![mmexport1675568101569](https://user-images.githubusercontent.com/112403698/216800121-fdc09a61-5b3c-47a8-be20-e96760440491.png)

**Comment by asinghvi17** [comment]
For the colorbar, you can set `cb.flipaxis[] = false` for `cb = Colorbar(...)`.

To get the axes closer together, you can set the rowgaps of your layout to negative values, such as:
```julia
# assuming that the two axes are in rows 2 and 3 of `fig`
rowgap!(fig.layout, 2, -40) # set the gap between rows 2 and 3 to -40
```

**Comment by crazyfireji** [comment]
> For the colorbar, you can set `cb.flipaxis[] = false` for `cb = Colorbar(...)`.
> 
> To get the axes closer together, you can set the rowgaps of your layout to negative values, such as:
> 
> ```julia
> # assuming that the two axes are in rows 2 and 3 of `fig`
> rowgap!(fig.layout, 2, -40) # set the gap between rows 2 and 3 to -40
> ```

thank you so much, it works
