### ISSUE TITLE
How to set the position of the label?

### ISSUE THREAD

**Issue by crazyfireji** [MakieOrg/Makie.jl#2670]
I want to set the yticks as 10^n，so I set the label on the TopLeft(), and I want to move the label to left, or set it on the ylabel, but the fontsize is too large, how can I adjust it.
![mmexport1676085719038](https://user-images.githubusercontent.com/112403698/218237380-40d76468-e511-4d41-a78f-4132adff7c4e.png)

**Comment by crazyfireji** [comment]
![mmexport1676087396683](https://user-images.githubusercontent.com/112403698/218237460-16733648-ff7f-4573-8f46-d9a6234f60aa.png)

**Comment by asinghvi17** [comment]
You can change `mylabel.fontsize`, or set `fontsize` to a vector of the same length as your string.
