### ISSUE TITLE
Minor ticks in one plot is interfering with another one in the same figure

### ISSUE THREAD

**Issue by ronisbr** [MakieOrg/Makie.jl#2689]
Hi!

If I create two plots in the same figure using Y minor ticks in the second one, some unexpected ticks appears in the first one:

```julia
using CairoMakie

t  = 0:1:100
d1 = randn(length(t))
d2 = rand(0:1, length(t))

fig = Figure(resolution = (1600, 1200))

ax = Axis(fig[1, 1],)

scatter!(ax, t, d1)

ax = Axis(
    fig[2, 1],
    spinewidth         = 4,
    yminorticksvisible = true,
    yminorgridvisible  = true,
)

lines!(ax, t, d2)

ax.yticks = (0:1, ["A", "B"])

save("bug.png", fig)
```

The result is:

![bug](https://user-images.githubusercontent.com/1068295/219490608-d9152d35-e50f-4c86-a251-c650b23054d0.png)

Notice the additional ticks after -1 and 1 in the first figure.

**Comment by aramirezreyes** [comment]
I can reproduce on Julia Version 1.9.0-beta4 with CairoMakie v0.10.1 but not with GLMakie.

It stays the same if we change the name of the second axis to something different than ax.

**Comment by asinghvi17** [comment]
I can also reproduce this on Julia 1.8.5 with Makie master.  However, for me this issue happens with WGLMakie as well as CairoMakie.  Haven't tested on GLMakie yet.

**Comment by ffreyer** [comment]
Has been fixed
