### ISSUE TITLE
Scene tutorial not working

### ISSUE THREAD

**Issue by giannishatzo** [MakieOrg/Makie.jl#2697]
When I try the first part of the scene tutorial:
`using GLMakie, Makie`
`GLMakie.activate!()`
`scene = Scene(backgroundcolor=:gray)`
`subwindow = Scene(scene, px_area=Rect(100, 100, 200, 200), clear=true, backgroundcolor=:white)`
`scene`

I get the following error;
Error showing value of type Scene:
ERROR: AssertionError: internal error. Scene already displayed by screen but not as root scene

The result of `pkg> status`  gives me the following package versions:
[e9467ef8] GLMakie v0.8.2
[ee78f7c6] Makie v0.19.2

I also tried on a different computer where I've never used Makie before and I got the exact same error.
Digging a bit further I could see that the Scene() constructor called was commented as `#legacy constructor` in the source code. I'm not sure if this should be the one called. 
Has anyone seen this before?

**Comment by giannishatzo** [comment]
I stand corrected on the `# legacy constructor` the actual methods called are **scenes.jl:146** on the first call of Scene and **scenes.jl:233** on the second.

**Comment by asinghvi17** [comment]
For the moment, if you don't display `subwindow`, i.e., replace that line with `subwindow = Scene(scene, px_area=Rect(100, 100, 200, 200), clear=true, backgroundcolor=:white);` so it doesn't display, that should fix your issue.

Basically, the cause of this error is that we don't allow a Scene whose parent scene is already displayed to be displayed again, and I guess the tutorial wasn't updated to reflect this.

**Comment by giannishatzo** [comment]
Hi Anshul

Thanks for the reply, it solves the problem.
Actually you need to not display at the first constructor as well to be able to see the subwindow later.
For future reference this works perfect;
`using GLMakie, Makie`
` GLMakie.activate!()`
`scene = Scene(backgroundcolor=:gray);`
`subwindow = Scene(scene, px_area=Rect(100, 100, 200, 200), clear=true, backgroundcolor=:white);`
`scene`

Thanks for your help!
