### ISSUE TITLE
error with rich text

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/Makie.jl#2698]
I rely on `rich` text for subscripts since the LaTeX font is not configurable (and default is unpalatable).

when I use the "ℋ" unicode character, oddly it disappears after I add a subscript after it / put it in the `rich` text environment. is this a bug? it displays correctly outside of the `rich` text environment. 
<img width="873" alt="Screenshot 2023-02-20 at 2 57 18 PM" src="https://user-images.githubusercontent.com/30643894/220210076-13731d39-bc52-42e8-b341-c4ff0dc63dd5.png">

```julia
using CairoMakie
import AlgebraOfGraphics as aog
aog.set_aog_theme!(fonts=[aog.firasans("Light"), aog.firasans("Light")])
update_theme!(fontsize=20, linewidth=3, resolution=(500, 400))


fig = Figure()
ax  = Axis(fig[1, 1],
  ylabel=rich("probability s ∈ ℋ", subscript("0.5")) # does not work
  # ylabel="probability s ∈ ℋ" # works
)
fig
```

**Comment by asinghvi17** [comment]
Just looked into it - rich text does not choose an alternate font, if the symbol is not found in the provided font.  This seems to be two issues:

1. Rich text doesn't find a font which contains the character automatically if the current font does not
2. `TeX Gyre Heros Makie` doesn't have a lot of the unicode characters that it should

I guess we could try to update it by using e.g. the lookup tables in the `unicode-math` latex package?  CC @jkrumbiegel
