### ISSUE TITLE
Minor ticks update after drag

### ISSUE THREAD

**Issue by jaakkor2** [MakieOrg/Makie.jl#2701]
```
fig = Figure()
ax = Axis(fig[1,1], xminorticksvisible = true, xminorticks = IntervalsBetween(5))
plot!(ax, rand(10))
```
when I drag x-axis a bit with right mouse button, I get this
![image](https://user-images.githubusercontent.com/7318249/220282671-6e7ea5bb-7401-4c5a-a232-fa90b4dc7f02.png)

Edit:  GLMakie v0.8.2

**Comment by ffreyer** [comment]
Partially fixed - I don't see the missplaced tick on the left but the gap still exists on the right (when you first reveal new values on that side)

**Comment by ffreyer** [comment]
Closing this in favor of #3690 since that issue is specifically for the missing minor ticks.
