### ISSUE TITLE
Simple lines() plot is truncated

### ISSUE THREAD

**Issue by robsmith11** [MakieOrg/Makie.jl#2702]
I've installed GLMakie with a fresh install of the latest nightly, but I'm getting weird problems with even the most simple lines() plots.  Please lmk if any additional info would be useful.

```
julia> using GLMakie

julia> lines(1:4, 1:4)

(plot2) pkg> st
Status `/tmp/plot2/Project.toml`
  [e9467ef8] GLMakie v0.8.2

julia> versioninfo()
Julia Version 1.10.0-DEV.643
Commit 56667bb47af (2023-02-21 12:52 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 7 4700U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver2)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
```
![s](https://user-images.githubusercontent.com/22622548/220387145-b3a7f8ff-eeb1-45a3-941f-807a1ab9e565.png)

**Comment by robsmith11** [comment]
I've noticed that the first call to `lines()` after restarting the Julia session looks correct, but any subsequent calls (even after closing the plot window) result in the truncated plot.

**Comment by asinghvi17** [comment]
Looks like https://github.com/MakieOrg/Makie.jl/issues/1460.  Have you tried CairoMakie/WGLMakie on this system?  They should perform better.

**Comment by robsmith11** [comment]
Ah you're right, thanks.
