### ISSUE TITLE
Interactively toggle visibility of plots by clicking on legend

### ISSUE THREAD

**Issue by robsmith11** [MakieOrg/Makie.jl#2717]
Not sure if this is within the scope and goals of Makie, so feel free to close, but Plotly has a very useful feature that helps when many traces/plots are combined.

Try clicking on the legend labels in some the examples here to try it:
https://plotly.com/javascript/line-charts/

The main features are:
1. Disable the visibility of the trace/plot that is clicked.
2. Resize the axes so that the remaining traces/plots fill the range.

The transition animations that Plotly has aren't needed IMO.

**Comment by SimonDanisch** [comment]
Gotta merge: https://github.com/MakieOrg/Makie.jl/pull/2276

**Comment by robsmith11** [comment]
Oh nice.  Somehow my searching missed that.  I'll close this issue then.
