### ISSUE TITLE
Fixed-axis camera rotation Y and Z axes swapped

### ISSUE THREAD

**Issue by pbouffard** [MakieOrg/Makie.jl#2721]
I noticed that holding down the y or z keys while dragging to rotate the 3D scene appears to rotate about the wrong world axis (about y when z is pressed and vice versa).

I think the culprit is this line: https://github.com/MakieOrg/Makie.jl/blob/master/src/camera/camera3d.jl#L487:

```
rotation *= qrotation(
                Vec3f(fix_x, fix_z, fix_y) .* Vec3f(sign(right[1]), viewdir[2], sign(up[3])),
                dot(Vec3f(fix_x, fix_y, fix_z), angles)
            )
```

Just swapping the 2nd and 3rd arguments to the first `Vec3f` appears to fix the issue.

**Comment by mohammadgruel** [comment]
https://duality-concluding.github.io/yx5lkx6WlAiyDFaFRcOsHeRhEjAccbWoOLN0QQGS4/
