### ISSUE TITLE
Name clash in `plot!` for arrow plots

### ISSUE THREAD

**Issue by steffenhaug** [MakieOrg/Makie.jl#2738]
When trying to normalize an arrow plot in Makie version `v0.19.2`, I get the error
```
ERROR: MethodError: objects of type Observable{Any} are not callable
```

Minimal steps to reproduce:
```julia
arrows!(ax12, xs´, ys´, u, v;
    normalize=true,
)
```

Looking at the history, I can see that at some point `StaticArrays.normalize` was changed to just `normalize` here:

https://github.com/MakieOrg/Makie.jl/blob/0cbae0437a60e5c1a41c1114aabf8a1440e324a9/src/basic_recipes/arrows.jl#L128

Which now makes the name clash with the name of the parameter.

This looks simple enough to fix, so I could try doing it myself. I'd be happy to contribute but I just started learning Julia two days ago so I might need some help.

**Comment by asinghvi17** [comment]
Hey!  Yeah, you could definitely make a PR changing `normalize` to `StaticArrays.normalize`.
