### ISSUE TITLE
"News" link on docs page broken

### ISSUE THREAD

**Issue by pbouffard** [MakieOrg/Makie.jl#2747]
Clicking the "News" button leads to https://docs.makie.org/stable/news/, which yields this:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/231346/224579289-6cb72594-6892-43c6-8167-444e508a9b2c.png">

The dev link (https://docs.makie.org/dev/news/) does work, however.

**Comment by jkrumbiegel** [comment]
Yeah I fixed it already, there was just no new version since then
