### ISSUE TITLE
Add Echarts as the backend? 

### ISSUE THREAD

**Issue by Geliv** [MakieOrg/Makie.jl#275]
I wonder if the [Echarts](https://github.com/apache/incubator-echarts) library can be used as the backend for Makie? Echarts is more lightweight, and browser friendly. Therefore, it should be easier to be used in Jupyter notebook and Jupyter lab. 

![image](https://user-images.githubusercontent.com/20089973/51010739-91f90200-1590-11e9-8266-d4c69139fbfa.png)

Here's some examples from the gallery. 
![image](https://user-images.githubusercontent.com/20089973/51010900-409d4280-1591-11e9-8942-467c3ef8362f.png)

![image](https://user-images.githubusercontent.com/20089973/51011028-c02b1180-1591-11e9-8334-87c8062cab54.png)

**Comment by mkborregaard** [comment]
There's https://randyzwitch.com/ECharts.jl/

**Comment by Geliv** [comment]
Many thanks. But it seems that this package does not support any 3d plotting functions?

**Comment by SimonDanisch** [comment]
Looks like a pretty awesome backend... ClayGL, there WebGL library also looks like a great candidate for the low-level webgl backend

**Comment by ffreyer** [comment]
Closing this since we have WGLMakie now, relying on Three.js
