### ISSUE TITLE
`markerspace = :data` seems not working with `scatter` plot

### ISSUE THREAD

**Issue by SteffenPL** [MakieOrg/Makie.jl#2758]
Maybe I missed some update news, somehow the behaviour of `markersize = :data` changed, 
the following used to give two circles with radius 1, but now it is something else (which is also not the volume)
```julia
using GLMakie
scatter( [0.0,0], [1.0,0], markersize = 1, markerspace = :data, axis = (;aspect = DataAspect()))
```
![test](https://user-images.githubusercontent.com/4634605/224919654-ed495750-6871-4869-b5c9-04dd5f60bf7b.png)

(The result is the same for `CairoMakie`.)

I updated to Julia 1.9rc and the environment was 
```julia
  [6e4b80f9] BenchmarkTools v1.3.2
  [13f3f980] CairoMakie v0.10.2
  [69e1c6dd] CellListMap v0.8.14
  [b0b7db55] ComponentArrays v0.13.8
  [31c24e10] Distributions v0.25.86
  [f6369f11] ForwardDiff v0.10.35
  [e9467ef8] GLMakie v0.8.2
  [1914dd2f] MacroTools v0.5.10
⌃ [a734d2a7] NestedTuples v0.3.6
  [92933f4c] ProgressMeter v1.7.2
  [90137ffa] StaticArrays v1.5.16
  [09ab397b] StructArrays v0.6.14
  [0c5d862f] Symbolics v5.1.0
  [1986cc42] Unitful v1.12.4
```

(Independent of that, thanks for the amazing package!)

**Comment by asinghvi17** [comment]
`markerspace=:data`, then markersize in data units should work

**Comment by SimonDanisch** [comment]
Yeah the default marker isn't unit scaled :( You can use `marker=Circle` for a unit scaled marker or create your own as specified in the docs....

**Comment by asinghvi17** [comment]
Looks like they should be easy enough to change to unit scale.  Is there any reason we shouldn't do that?

**Comment by SteffenPL** [comment]
Thanks for the replies! (And @asinghvi17 thanks for correcting the title!)
For me, `marker=Circle` is a good solution.

If wanted, I could try to add a sentence to the documentation, maybe here: https://docs.makie.org/stable/examples/plotting_functions/scatter/index.html#marker_space ?

**Comment by ffreyer** [comment]
It's already explained under https://docs.makie.org/stable/examples/plotting_functions/scatter/index.html#markersize
