### ISSUE TITLE
Meshes with specified materials lack color on MacOS

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#2769]
There's something wrong with materials in meshes on MacOS when using RPRMakie.
![iTerm2 KrTps3](https://user-images.githubusercontent.com/32143268/225274646-31c61027-d29f-448e-8b65-f8c78b63d8fe.png)
![iTerm2 Tfp6lf](https://user-images.githubusercontent.com/32143268/225274872-cbd8c8ed-6947-40e9-b495-3802620675f8.png)

Specifically, an error pops up when trying to construct an `RPR.Image`.  Run the earth and sun example, then try:
```julia
notify(mplot.color)
```
I get the error:
```julia
ERROR: Error code returned: RPR_ERROR_INVALID_PARAMETER
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] check_error
    @ ~/.julia/packages/RadeonProRender/R23Ls/src/LibRPR.jl:10 [inlined]
  [3] rprContextCreateImage(context::RadeonProRender.Context, format::RadeonProRender.RPR.rpr_image_format, image_desc::Base.RefValue{RadeonProRender.RPR.rpr_image_desc}, data::Matrix{RGB{Float32}})
    @ RadeonProRender.RPR ~/.julia/packages/RadeonProRender/R23Ls/src/LibRPR.jl:1872
  [4] Image
    @ ~/.julia/packages/RadeonProRender/R23Ls/src/highlevel-api.jl:374 [inlined]
  [5] (::RPRMakie.var"#32#35"{RadeonProRender.Context})(color::Matrix{RGB{N0f8}})
    @ RPRMakie ~/.julia/packages/RPRMakie/PMgeN/src/meshes.jl:28
  [6] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./essentials.jl:816
  [7] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base ./essentials.jl:813
  [8] (::Observables.MapCallback)(value::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:431
  [9] #invokelatest#2
    @ ./essentials.jl:816 [inlined]
 [10] invokelatest
    @ ./essentials.jl:813 [inlined]
 [11] notify(observable::Observables.AbstractObservable)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:169
 [12] top-level scope
    @ REPL[80]:1
```

**Comment by SimonDanisch** [comment]
Which render plugin?

**Comment by asinghvi17** [comment]
This was with Northstar.  Specifically, the config was:
```julia
RPRMakie.activate!(resource=RPR.RPR_CREATION_FLAGS_ENABLE_CPU,
               plugin=RPR.Northstar, iterations=50)
```
which was quite slow, but GPU causes a reliable segfault on MacOS.

**Comment by SimonDanisch** [comment]
What does Tahoe produce?

**Comment by SimonDanisch** [comment]
Can you post an mwe for the Image parameter error?

**Comment by asinghvi17** [comment]
huh, I'm trying to narrow it down but it's now magically working if I add lights.  Will post an MWE when I have one :D

**Comment by asinghvi17** [comment]
Tahoe tries to set the thread affinity, then crashes (illegal instruction, which makes sense - thread affinity might have been supported on Intel Macs, but it's not supported in the same way on M1)

**Comment by asinghvi17** [comment]
Ok, the image parameter has not errored once I restarted Julia.  It might be that RPR somehow got a corrupted state.

The earth example seems to work with some lights added:
```julia

# define some lighting
radiance = 500
lights = Makie.AbstractLight[
    # EnvironmentLight(0.5, Makie.FileIO.load(RPR.assetpath("studio026.exr"))),
    PointLight(Vec3f(0, 0, 20), RGBf(radiance, radiance, radiance))
]

f, ax, mplot = Makie.mesh(m; color=rand(RGBAf, 10, 10), axis = (; scenekw = (; lights = lights), show_axis = false));
RPRMakie.Screen(ax.scene)
```
![iTerm2 gQaeUo](https://user-images.githubusercontent.com/32143268/225291174-4bf96ac3-d89a-4ebe-bb25-2eb10777f193.png)

but the material example is still colorless with Northstar, and Tahoe consistently fails by trying to set thread affinity.
![iTerm2 Y9MPHc](https://user-images.githubusercontent.com/32143268/225291417-06dcb2da-24af-454c-ae7d-81f1ddc26468.png)

**Comment by asinghvi17** [comment]
Ok, this seems to work pretty well with RPR v3, so it's probably not an issue anymore!
