### ISSUE TITLE
GLMakie crash Julia on M2

### ISSUE THREAD

**Issue by YingboMa** [MakieOrg/Makie.jl#2771]
GLMakie crashes Julia with follow message when I full screen the plot.
```
julia> 2023-03-15 01:15:05.217 julia[91904:18181027] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSArray subarrayWithRange:]: range {1, 18446744073709551615} extends beyond bounds for empty array'
*** First throw call stack:
(
)
libc++abi: terminating with uncaught exception of type NSException

signal (6): Abort trap: 6
in expression starting at none:0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 93339713 (Pool: 93311047; Big: 28666); GC: 35
```
```julia
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65e* (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.3.0)
  CPU: 12 × Apple M2 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 4 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_PKG_DEVDIR = /Users/scheme/src/julia
  JULIA_PKG_SERVER = https://internal.juliahub.com
```

**Comment by SimonDanisch** [comment]
Seems like a Julia issue, I dont think we can do anything about that in Makie!

**Comment by YingboMa** [comment]
> julia> 2023-03-15 01:15:05.217 julia[91904:18181027] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSArray subarrayWithRange:]: range {1, 18446744073709551615} extends beyond bounds for empty array'

Is it a Julia issue? Why would Julia go out of bounds when I fullscreen Makie's plot?

**Comment by SimonDanisch** [comment]
Ah sorry im a bit quick to close obscure m1/2 issues for things that otherwise work perfectly well...
This seems to be a duplicate of:https://github.com/MakieOrg/Makie.jl/issues/2629
