### ISSUE TITLE
tricontourf and mesh use inconsistent triangulations

### ISSUE THREAD

**Issue by simonbyrne** [MakieOrg/Makie.jl#2796]
The `triangulation` argument to `tricontourf` [expects a `Matrix{<:Int}`](https://github.com/MakieOrg/Makie.jl/blob/2116627b5caed21ddf0e3bbd2103f55d5679d881/src/basic_recipes/tricontourf.jl#L183-L188), whereas `mesh` expects the triangulation as a vector of `GLTriangleFace`s

**Comment by asinghvi17** [comment]
We should probably use `convert_arguments(Mesh, input_triangulation...)` to pick up any nonstandard triangulation, and then convert to TriplotBase's preferred `TriplotBase.TriMesh` form.

**Comment by ffreyer** [comment]
Mesh accepts a matrix now. (Didn't it always?)

**Comment by asinghvi17** [comment]
Looks like it, the new triangulation interface should also accept a vector of GLTriangleFace for triplot.
