### ISSUE TITLE
Allow custom link text in `\mylinkref` in docs

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#2802]
This would be pretty nice, noticed in #2787.  

Some background: Makie's docs use Franklin.jl, which allows you to create custom commands which it picks up on and executes.  These commands are defined in `docs/utils.jl`, so you would just have to change the implementation of the `lx_mylinkref` function there to accept a keyword argument `text` which would determine the text of the link.

**Comment by ffreyer** [comment]
Assuming this is outdated now
