### ISSUE TITLE
Inline plots stopped appearing

### ISSUE THREAD

**Issue by kbarros** [MakieOrg/Makie.jl#2805]
Hi,

It looks like https://github.com/MakieOrg/Makie.jl/pull/2731 changed the behavior of `showable` (via `_backend_showable`) with this new line: https://github.com/MakieOrg/Makie.jl/blob/2116627b5caed21ddf0e3bbd2103f55d5679d881/src/display.jl#L149 

This caused surprising behavior for a [Literate.jl](https://github.com/fredrikekre/Literate.jl) workflow that would execute a source file and generate Markdown. Prior to this change, Literate would generate a png file for each inline image. After this change, Literate will just generate the text `Figure()`, thinking that the Figure is not showable as `image/png`.

~~I observed this surprising behavior on Github actions, but could not repeat it locally on my Mac. I'm not sure why yet.~~ Reproduces on Github actions and locally on Mac. I can work on creating a minimum example if it would be helpful.

The problem can be fully resolved by including `Makie.inline!(true)`, but it seems better to restore the old behavior (automatically detect that the figure is in fact "showable").

**Comment by kbarros** [comment]
To reproduce, please create a Julia file 'makie_test.jl' containing some simple GLMakie commands:

```julia
# Execute this file using the command:
#   import Literate; Literate.markdown("makie_test.jl", execute=true)

using GLMakie

# After executing within Literate, this example either:
#  (a) outputs an inline SVG into the output Markdown
#  (b) outputs the text "Figure()" into the output Markdown

f = Figure()
ax = Axis(f[1, 1])
x = range(0, 10, length=100)
y = sin.(x)
lines!(ax, x, y)
f
```

Then from the Julia REPL, execute `import Literate; Literate.markdown("makie_test.jl", execute=true)`. 

When I first tried this, I got SVG output inlined into the output Markdown. Then I played around with some GLMakie commands, and somehow the result changed so that only the text `Figure()` was inlined into the output Markdown. So, unfortunately, it seems the precise behavior I'm observing may be hard to reproduce.

If `Makie.inline!(true)` is included at the top of the script above, then the `Literate.markdown` command will output a .png which gets linked to the output Markdown.

**Comment by SimonDanisch** [comment]
Ah sorry.. I tried to finally make it work, that vscode doesn't display anything in the plot pane if inline! Is false... And didn't realize that it destroys the default for documenter / literate and friends

**Comment by asinghvi17** [comment]
I was under the impression that that usually works anyway, even before that PR landed?  At least, my experience with GLMakie was that it always popped open a separate window unless I called `Makie.inline!(true)`...CairoMakie always displayed in the plot pane, but then it probably should have anyway, as did WGLMakie.

**Comment by kbarros** [comment]
To me, the new default VSCode behavior seems kind of reasonable, at least for GLMakie. Let me explain. A new interactive GLMakie window always appears, and it seems impossible to suppress that (is this correct?). Given that the window appears, it seems redundant to plot things a second time in the inline VSCode panel.

**Comment by kbarros** [comment]
Related question -- the pop-up GLMakie window appears _behind_ existing windows. Usually that means it will be hidden behind the VSCode window, and it's easy to miss. This is very confusing for new users. Is there some way to make it appear in the foreground?

**Comment by SimonDanisch** [comment]
GLMakie.activate!(float=true)

**Comment by kbarros** [comment]
The option for that is `GLMakie.activate!(focus_on_show=true)`
I opened a separate discussion here:
https://github.com/MakieOrg/Makie.jl/discussions/2806
