### ISSUE TITLE
set different colors for xticklabel?

### ISSUE THREAD

**Issue by jaehongpark-neuro** [MakieOrg/Makie.jl#2807]
Hi,

I am trying to custom xticklabels like
ax2.xticks =([1.0,2.0],["A","B"])
I want to "A" and "B" with different colors, but it looks like I can change the only one color for a whole label
ax2.xticklabelcolor = :red

Is there any way to achieve my goal?

Thanks,

**Comment by asinghvi17** [comment]
```julia
ax.xaxis.attributes.ticklabelcolor[] = Makie.to_color.([:red, :blue])
```
should work!

**Comment by jaehongpark-neuro** [comment]
oh, it works!

Thanks so much.
