### ISSUE TITLE
Textbox contents appear in the wrong place

### ISSUE THREAD

**Issue by lhupe** [MakieOrg/Makie.jl#2814]
When running the text box example as used in the [docs](https://docs.makie.org/stable/examples/blocks/textbox/#textbox)
```julia
using GLMakie

f = Figure()
Textbox(f[1, 1], placeholder = "Enter a string...")
Textbox(f[2, 1], width = 300)

f
```
the content of the text boxes is displayed in the lower left-hand corner of the figure, not in the boxes. 
![image](https://user-images.githubusercontent.com/34064555/228263405-e0706171-9aba-48aa-93ad-6e6038908edb.png)

This problem seems to be reproducable in the documentation build environment as the same symptoms can be seen in the example image.

I'm on GLMakie v0.8.3 and have experienced this problem on Julia 1.8.5 and 1.9.0-rc1

**Comment by jkrumbiegel** [comment]
Ah I have an idea where this could have come from, something about child scene offsets. Maybe the offset of the parent needs to be included again because it was lost due to changes in the scene px_area observable setup

**Comment by jkrumbiegel** [comment]
Ah I see this was already created in response https://github.com/MakieOrg/Makie.jl/pull/2815
