### ISSUE TITLE
Another interaction example in Makie?

### ISSUE THREAD

**Issue by sairus7** [MakieOrg/Makie.jl#282]
I've found it pretty easy to plot some interactive examples in VegaLite:
https://discourse.julialang.org/t/interactive-plot-acting-as-a-range-slider-tool-for-another-plot/20392/6?u=sairus7
But it seems that it has limited functionality and performance. 
Can you give me some hints about how to make similar interaction example in Makie (and maybe add it to interaction gallery)?

**Comment by SimonDanisch** [comment]
Good point!
Would you want only x slices, or a whole rectangle to select a sub area?

**Comment by sairus7** [comment]
Rectangle here is actually a scrollbar, with another plot in background. User can drag it and change scale (rectangle width). In this example rectangle height cannot be changed.
In original Bokeh implementation it is possible to change rectangle width by dragging its edges. In VegaLite it is possible only to select a new rectangle area.

**Comment by SimonDanisch** [comment]
Yeah, so the question was, which one would you prefer?

**Comment by sairus7** [comment]
I think it is more convenient to change rectangle width by dragging its edges.

**Comment by ffreyer** [comment]
Closing this as stale/outdated
