### ISSUE TITLE
Empty vectors of 2d Polygon plot 3d

### ISSUE THREAD

**Issue by rafaqz** [MakieOrg/Makie.jl#2820]
```julia
poly = Polygon([Point2(1, 2), Point2(3, 4), Point2(4, 5), Point2(1, 2)])
# 2d
Makie.poly([poly])
# 3d
Makie.poly(typeof(poly)[])
```

**Comment by jkrumbiegel** [comment]
I thought we wanted to decide 2d / 3d based on plot type, maybe that hasn't actually been merged, yet. But at least that was the plan, to avoid runtime differences like this.

**Comment by SimonDanisch** [comment]
yeah, it's in the breaking branch!

**Comment by ffreyer** [comment]
Fixed
