### ISSUE TITLE
Broken trace in lines plot when figure stretched

### ISSUE THREAD

**Issue by bilderbuchi** [MakieOrg/Makie.jl#2826]
I have observed that, when plotting a large-ish number of points in a line plot, and the window gets slim aspect ratios, the line plot gets many small interruptions.
MWE:
```julia
using Random
using GLMakie

rng = MersenneTwister(1234);
TMAX = 1 #seconds
NSAMPLES = 1_000

t = range(0, TMAX, length=NSAMPLES)
y = Array{Float64}(undef, NSAMPLES)
y = randn(rng, Float64, NSAMPLES)
y[1] = 5
cumsum!(y, y)

lines(t, y)
```
Grab the resulting window and stretch it to a wide and low aspect ratio while observing the shown plot. You will notice that holes start to appear in the drawn line, e.g. like this:
![image](https://user-images.githubusercontent.com/327442/228830091-fcbd1a34-418e-4ea2-ae96-80aed0440ec8.png)
Detail crop: 
![image](https://user-images.githubusercontent.com/327442/228830584-d063c587-cd24-4cd4-875f-2f7c14032f61.png)

Could #2666 be related? 
I _think_ this started appearing (in another larger project) with GLMakie 0.8.3/Makie 0.19.3, but I haven't confirmed that with the MWE.

This is on Julia 1.8.5, GLMakie v0.8.3

**Comment by bilderbuchi** [comment]
Thanks for the quick fix! :-o

**Comment by bilderbuchi** [comment]
@ffreyer @SimonDanisch I have confirmed that GLMakie 0.8.4 improves the situation considerably -- thanks for the quick Unfortunately, I can still see issues in my application -- see this slightly modified MWE:
```julia
# Determine if line plots with a larger number of noisy points are plotted with breaks
using Random
using GLMakie

rng = MersenneTwister(1234);
TMAX = 1 #seconds
NSAMPLES = 5_000

t = range(0, TMAX, length=NSAMPLES)
y = Array{Float64}(undef, NSAMPLES)
y = randn(rng, Float64, NSAMPLES) + 5000 * sinc.(t * π) .^ 2

lines(t, y)
# Now grab the resulting window and stretch it to a wide and low aspect ratio while observing the shown plot. 
# You will notice that holes/interruptions start to appear in the drawn lines
```
![image](https://user-images.githubusercontent.com/327442/229727511-299c0773-ffdb-4d45-a4c2-87a7c4dc128a.png)
Detail crop:
![image](https://user-images.githubusercontent.com/327442/229727699-7b338269-a74b-4e90-b65b-50634f0a654b.png)

**Comment by bilderbuchi** [comment]
(very naive idea, surely) can you put a blend mode on the pieces (or some other way to achieve `opacity=max(a,b)` when two pieces of the same line paint the same pixel? That way the opacity reduction would be ineffective if it would act on a piece of the same line, and the line center should be intransparent throughout (but still antialiased on the border).

**Comment by ffreyer** [comment]
> (very naive idea, surely) can you put a blend mode on the pieces (or some other way to achieve `opacity=max(a,b)` when two pieces of the same line paint the same pixel? That way the opacity reduction would be ineffective if it would act on a piece of the same line, and the line center should be intransparent throughout (but still antialiased on the border).

Sort of, but lines would also use this blending mode to blend with other things. So if you had a transparent plane on the canvas, a line would replace the plane if it had larger alpha values and not draw with lower ones. We would have to special case lines to draw on a separate canvas, which then blends normally with the main canvas.
