### ISSUE TITLE
Named colors don't work in WGLMakie

### ISSUE THREAD

**Issue by HTofi** [MakieOrg/Makie.jl#2836]
The following code reproduces the correct color in GLMakie, but not in WGLMakie:
```julia
fig = Figure()
ax = Axis3(fig[1,1])
x = -1:0.01:1
y = -1:0.01:1
f(x,y) = (r = x^2 + y^2; exp(-r^2/2))
surface!(x, y, f, color=fill((:red, 1.0), 100, 100))
fig
```
However, when replacing `(:red, 1.0)` by `RGBA(1., 0., 0., 1.0)`, the code works fine.

**Comment by SimonDanisch** [comment]
This works now!
