### ISSUE TITLE
meshscatter does not show geometries with WGLMakie.jl

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#2844]
This first example of the Meshes.jl documentation is displayed correctly with GLMakie.jl but fails with WGLMakie.jl:

https://juliageometry.github.io/Meshes.jl/stable/algorithms/sampling.html#UniformSampling

Copying the code here for future reference:

```julia
using Meshes, MeshViz
import GLMakie as Mke # works
#import WGLMakie as Mke # fails

grid = CartesianGrid(20, 20)

sampler = UniformSampling(100, replace=false)
blocks  = sample(grid, sampler)

viz(blocks)
```

**Comment by SimonDanisch** [comment]
Whats the error?

**Comment by juliohm** [comment]
Nothing is displayed in the docs. The canvas is empty.

Em qua., 5 de abr. de 2023 17:19, Simon ***@***.***> escreveu:

**Comment by SimonDanisch** [comment]
Could you reduce it to a minimal working example? That would make fixing it much easier :)

**Comment by juliohm** [comment]
MWE:

```julia
using Meshes: Vec2 # custom StaticVector

import WGLMakie as Mke # leads to empty canvas

positions = rand(Vec2, 100)

Mke.meshscatter(positions,
  marker = Mke.Rect{2}((-1.,-1.), (1.,1.)),
  shading = false
)
```

**Comment by juliohm** [comment]
Any chance that this bug could be fixed? We are rewriting most of our docs with Makie.jl and the plots are empty sometimes.

**Comment by juliohm** [comment]
Issue fixed, thanks!
