### ISSUE TITLE
`NaN`s in `band` cause the band polygon to move to upper-left corner of the plot

### ISSUE THREAD

**Issue by kimlaberinto** [MakieOrg/Makie.jl#2845]
test_band.png
![test_band](https://user-images.githubusercontent.com/7938723/230212954-94faeffc-2389-4863-a967-de8c74e45f4c.png)

```
using CairoMakie

fig = Figure()
ax = Axis(fig[1, 1])
xs = [1, 2, 3, 4, 5, 6, 7]
upper = [10, 20, NaN, 40, 50, 60, 70]
lower = [5, 15, 25, 35, 45, 55, 65]
band!(ax, xs, lower, upper)
save("test_band.png", fig)


fig = Figure()
ax = Axis(fig[1, 1])
lines!(ax, xs, upper)
save("test_lines.png", fig)

```

vs. the behavior with `lines!`
![test_lines](https://user-images.githubusercontent.com/7938723/230212958-b448343b-1604-474a-af37-f9c9cea0c0e9.png)

Note that it seems like it doesn't use the `nan_color` defined in the docstring for `band`: https://docs.makie.org/stable/examples/plotting_functions/band/index.html#band

**Comment by jkrumbiegel** [comment]
Hm at least for Cairo it's impossible to draw the polygon if one of the points is NaN, maybe it should just error in that case, not sure. In GLMakie, because it falls down to a mesh, only two triangles would be missing I think, but that's also not "correct" in that sense. I would argue that it's undefined behavior if you have a NaN in a band, because it does not make sense for that plot type to have one. Unlike lines (gaps) or scatters (missing markers).

**Comment by SimonDanisch** [comment]
I guess, if we treat band more as a thick line, we could argue, that it should just skip nan segments like with lines...

**Comment by jkrumbiegel** [comment]
I think it should just error probably

**Comment by asinghvi17** [comment]
IMO skipping nan segments is more versatile, since people might want to use it that way and we shouldn't break the behaviour which is already in GLMakie.  Plus, we generally treat NaNs this way in all the basic recipes - lines, scatter, surfacelike, etc.

**Comment by jkrumbiegel** [comment]
If other plotting packages support bands with NaN gaps, I'd be willing to do this too. But I don't think it's a great idea

**Comment by SimonDanisch** [comment]
Matplotlib does it:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/1010467/234267739-2d0e9e8b-9649-4134-a3f8-4c9ee20372e3.png">
