### ISSUE TITLE
Can't turn of the grid of two axis simultaneously

### ISSUE THREAD

**Issue by pabloemontes** [MakieOrg/Makie.jl#2846]
The following code does not give the desired output
```
using CairoMakie

Fig = Figure()

ax1 = Axis(Fig[1, 1], title = "Axis 1")
ax2 = Axis(Fig[1, 2], title = "Axis 2")

hidedecorations!(ax1, grid = false)
hidexdecorations!(ax2, grid = false)

Fig
```
I expect this to give me two axis side by side with no grids, but both grids appear. If by the contrary one of the grids is set to true, then only one grid appears and the other one is hidden.

**Comment by asinghvi17** [comment]
In this context, `false` means not to hide it.  You might have to set every other kwarg to `false` if you only want to hide the grid.

That isn't reflected in the function docs, though, so we should add that.

**Comment by pabloemontes** [comment]
Oh now I get it, thank you for your reply
