### ISSUE TITLE
Consider using Float64 coordinates as standard in GL/WGLMakie

### ISSUE THREAD

**Issue by rafaqz** [MakieOrg/Makie.jl#2848]
So OpenGL needs to use Float32. But it may be best to delay conversion from Float64 to the last possible step.

Current Float32 errors dont seem to accumulate evenly for e.g. image pixels, points, and polygons - meaning they start to disasociate a high zoom levels, the fp error at each zoom level can move points and images to different locations independent of each other.

Its a little disconcerting defining geometries with MakieDraw.jl over Tyler.jl maps and seeing them jump out of place at a different zoom level.

I doubt using Float64 will solve this completely, but it seems like it could at least keep the errors in sync.

**Comment by ffreyer** [comment]
#2573 does that, though I haven't found time to work on it much in the past couple weeks. The pr needs to be reworked to not convert to Float64 by default, but keep input types when possible (I have some changes for this locally, need to finish them) and then a good amount of testing to make sure that all the conversions go as planned. 

The pr should fix float precision problems in CairoMakie as is. For GLMakie and WGLMakie we need to do some per-point transformation based on the current view before converting to Float32 and pushing to the GPU. I'm probably going to attempt that in a different pr though.
