### ISSUE TITLE
`ylabeloffset` for 2D plots?

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/Makie.jl#2857]
we are using the `bracket` function to label columns of a heatmap (nice!).
but then the `ylabel` is not centered with the heatmap, since we had to extend the `ylims` to accommodate the brackets.
how can we shift the `ylabel` down to make it centered with the heatmap? thx.
[same prob with x-label since we have brackets on the right] 

<img width="541" alt="Screen Shot 2023-04-13 at 8 40 00 PM" src="https://user-images.githubusercontent.com/30643894/231935803-c76747a6-d0de-4ec5-a34c-4030cf7ebc16.png">

**Comment by SimonEnsemble** [comment]
the colorbar on the right is too tall too, almost like I should use a separate axis for the brackets, but refer to the coordinates of the heatmap.

**Comment by asinghvi17** [comment]
Instead of using a separate axis - you could put the axes for the brackets in protrusions, and link the x and y axes depending on dimension.  This should solve most of your issues.

e.g.:
```julia
main_ax = Axis(fig[i, j], tellheight = true, ...)
top_ax = Axis(fig[i, j, Top()]; alignmode = Inner())
hidedecorations!(top_ax); hidespines!(top_ax)
right_ax = Axis(fig[i, j, Right()]; alignmode = Inner())
hidedecorations!(right_ax); hidespines!(right_ax)
cb = Colorbar(fig[i, j+1]; ...)
fig
```

**Comment by jkrumbiegel** [comment]
That idea goes in the right direction, here's an example:

```julia
fig = Figure()
main_ax = Axis(fig[1, 1])
top_ax = Axis(fig[1, 1, Top()], height = 35, xautolimitmargin = (0, 0))
hidedecorations!(top_ax); hidespines!(top_ax)
right_ax = Axis(fig[1, 1, Right()], width = 35, yautolimitmargin = (0, 0))
hidedecorations!(right_ax)
hidespines!(right_ax)
cb = Colorbar(fig[1, 2])

heatmap!(main_ax, randn(30, 10))

linkxaxes!(main_ax, top_ax)
linkyaxes!(main_ax, right_ax)

bracket!(top_ax, 1, 0, 10, 0, text = "First")
bracket!(top_ax, 10, 0, 30, 0, text = "Second")
ylims!(top_ax, low = 0)
bracket!(right_ax, 0, 1, 0, 5, text = "First", orientation = :down)
bracket!(right_ax, 0, 5, 0, 10, text = "Second", orientation = :down)
xlims!(right_ax, low = 0)

fig
```

<img width="603" alt="image" src="https://user-images.githubusercontent.com/22495855/232024302-798702ad-2d4a-4888-8c55-56f05e3ab68c.png">

**Comment by SimonEnsemble** [comment]
cool trick. perfectly suits our needs. now our plot is perfect!
thanks, you rock!
will show the final product after publication. brackets = great addition for heatmaps. 😄

**Comment by SimonEnsemble** [comment]
we pass `aspect=DataAspect()` to `main_ax = Axis(...)` to make the squares in the heatmap perfect squares. then this all breaks! we're unable to get the axes containing the brackets to share the axis with the main axis. 👀 

what happens in this toy example is not quite as dramatic as what's happening in our real example, but the underlying problem is that `linkxaxes!` is not being obeyed when `aspect=DataAspect()`.

<img width="597" alt="Screenshot 2023-05-06 at 10 41 18 AM" src="https://user-images.githubusercontent.com/30643894/236639033-886b3a0c-d6d8-4019-a976-e44cf0565b3b.png">

**Comment by SimonEnsemble** [comment]
_and_!

when I add a legend to the top in this toy example with
```julia
	 legend_patches = [
        PolyElement(color="red", strokecolor="gray"),
        PolyElement(color="green", strokecolor="gray")
    ]
    legend_labels = ["immiscible", "miscible"]
	Legend(fig[0, 1], legend_patches, legend_labels, orientation=:horizontal)
```

we find that even without `aspect=DataAspect()` the shared axes are not obeyed.

<img width="597" alt="Screenshot 2023-05-06 at 11 18 51 AM" src="https://user-images.githubusercontent.com/30643894/236640536-c8661f17-d991-433b-a30e-621de99d74bf.png">

**Comment by asinghvi17** [comment]
I think the best thing might be to follow e.g. [this tutorial](https://docs.makie.org/stable/tutorials/aspect-tutorial/#:~:text=Let%27s%20try%20the%20example%20from%20above%20again%2C%20but%20this%20time%20we%20force%20the%20column%20of%20the%20Axis%20to%20have%20an%20aspect%20ratio%20of%201.0%20relative%20to%20the%20row%20of%20the%20Axis%2C%20which%20is%20row%201.) and "manually" set the row and column size such that your axis is forced to the correct aspect ratio. (perhaps by using `ax.finallimits`).  Then, all of the spacing issues should theoretically fall into place.

**Comment by SimonEnsemble** [comment]
```julia
begin
	fig = Figure()
	main_ax = Axis(fig[1, 1])
	top_ax = Axis(fig[1, 1, Top()], height = 35, xautolimitmargin = (0, 0))
	hidedecorations!(top_ax); hidespines!(top_ax)
	right_ax = Axis(fig[1, 1, Right()], width = 35, yautolimitmargin = (0, 0))
	hidedecorations!(right_ax)
	hidespines!(right_ax)
	cb = Colorbar(fig[1, 2])
	
	heatmap!(main_ax, randn(30, 10))
	colsize!(fig.layout, 1, Aspect(1, 3.0))
	
	linkxaxes!(main_ax, top_ax)
	linkyaxes!(main_ax, right_ax)
	
	bracket!(top_ax, 1, 0, 10, 0, text = "First")
	bracket!(top_ax, 10, 0, 30, 0, text = "Second")
	ylims!(top_ax, low=0)
	bracket!(right_ax, 0, 1, 0, 5, text = "First", orientation = :down)
	bracket!(right_ax, 0, 5, 0, 10, text = "Second", orientation = :down)
	xlims!(right_ax, low = 0)
	legend_patches = [
            PolyElement(color="red", strokecolor="gray"),
            PolyElement(color="green", strokecolor="gray")
        ]
	legend_labels = ["immiscible", "miscible"]
	# Legend(fig[0, 1], legend_patches, legend_labels, 
	# 	orientation=:horizontal)
	resize_to_layout!(fig)
	fig
```

manually setting `colsize!` works! 

* but uncommenting the `Legend` _really_ messes up the scaling for some reason
* `ylims!(top_ax, 0, 89)` is not respected and the text is cutoff. 👀 

<img width="827" alt="Screenshot 2023-05-07 at 5 18 49 PM" src="https://user-images.githubusercontent.com/30643894/236709985-3afd1fa9-ca43-4c1b-9dd9-d6f48a5b9a2b.png">

**Comment by SimonEnsemble** [comment]
feeling confident this is a bug. when I don't hide the axes, clearly the brackets are not respecting the coordinates we drew them at. this is all b/c of the `Legend`.
<img width="825" alt="Screenshot 2023-05-07 at 5 42 52 PM" src="https://user-images.githubusercontent.com/30643894/236711274-ce239561-78ea-44ea-9cfa-1ce840fb5b1c.png">


```julia
	fig = Figure()
	main_ax = Axis(fig[1, 1])
	top_ax = Axis(fig[1, 1, Top()], height = 35, xautolimitmargin = (0, 0))
	# hidedecorations!(top_ax); hidespines!(top_ax)
	right_ax = Axis(fig[1, 1, Right()], width = 35, yautolimitmargin = (0, 0))
	# hidedecorations!(right_ax)
	# hidespines!(right_ax)
	
	heatmap!(main_ax, randn(30, 10))
	colsize!(fig.layout, 1, Aspect(1, 3.0))
	
	linkxaxes!(main_ax, top_ax)
	linkyaxes!(main_ax, right_ax)
	
	bracket!(top_ax, 1, 0, 10, 0, text = "First")
	bracket!(top_ax, 10, 0, 30, 0, text = "Second")
	
	bracket!(right_ax, 0, 1, 0, 5, text = "First", orientation = :down)
	bracket!(right_ax, 0, 5, 0, 10, text = "Second", orientation = :down)
	ylims!(top_ax, 0, 89)
	xlims!(right_ax, low = 0)
	legend_patches = [
      PolyElement(color="red", strokecolor="gray"),
      PolyElement(color="green", strokecolor="gray")
  ]
	legend_labels = ["immiscible", "miscible"]

	Legend(fig[0, 1], legend_patches, legend_labels, 
		orientation=:vertical, tellheight=true, tellwidth=true, alignmode=Inside())
	resize_to_layout!(fig)
	fig
```

**Comment by jkrumbiegel** [comment]
Hm yeah some kind of update bug because adding this at the end fixes the limits:

```julia
notify(top_ax.finallimits)
notify(right_ax.finallimits)
```

**Comment by jkrumbiegel** [comment]
Looks like the behavior is correct in the latest version.
