### ISSUE TITLE
Allow empty strings for tick labels (and other labels)

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#286]
I am doing:
```
    scplot[Axis][:ticks][:ranges] = ([0, 0.5, 1], [0, 0.5, 1])
    scplot[Axis][:ticks][:labels] = (["pmin", "", "pmax"], ["umin", "", "umax"])
```

But this doesn't work. One has to replace all `""` with `" "` (i.e. having a space). Otherwise it throws an error "collection must be non empty".

---

This is very low priority of course.

**Comment by mschauer** [comment]
How does this not work specifically? Does it error?

**Comment by Benoit9** [comment]
Yes, it errors

>  [42] (::getfield(REPL, Symbol("##26#27")){REPL.REPLBackend})() at ./task.jl:259ERROR: BoundsError: attempt to access 0-element UnitRange{Int64} at index [1]
Stacktrace:

**Comment by asinghvi17** [comment]
It's possible that the text extent computation fails?

**Comment by ffreyer** [comment]
Closing as outdated since the old 2D Axis doesn't exist anymore
