### ISSUE TITLE
Interactive record closes figure window

### ISSUE THREAD

**Issue by alex-s-gardner** [MakieOrg/Makie.jl#2879]
The recommended way to record an interactive session is:
https://docs.juliahub.com/MakieGallery/Ql23q/0.2.17/interaction.html#Recording-your-interactions

```julia
fig, ax, p = lines(rand(10))
fps = 10
record(fig, "test.mp4"; framerate = fps) do io
    for i = 1:100
        sleep(1/fps)
        recordframe!(io)
    end
end
```

but `record` causes the figure window to close so no interactions can be recorded

using:
GLMakie v0.8.4
Julia v"1.8.2"
macos 13.3.1 (22E261)

**Comment by SimonDanisch** [comment]
You can try `record(...; visible=true)` ... But ideally the default for the "interactive" version should be `visible=true`...
I think one can change the default here: https://github.com/MakieOrg/Makie.jl/blob/master/src/recording.jl#L140

**Comment by alex-s-gardner** [comment]
Thanks @SimonDanisch that did the trick. Should I open a PR?

**Comment by SimonDanisch** [comment]
Yes, I think that'd be a good idea!

**Comment by alex-s-gardner** [comment]
@SimonDanisch since the right most kw_arg will take precedence:
http://web.mit.edu/julia_v0.6.2/julia/share/doc/julia/html/en/manual/functions.html#Keyword-Arguments-1

the proposed implementation still allows the user to set `visible=false` in the kw_arg. I have tested this. Is there an alternative way that you would like to see this implemented?
