### ISSUE TITLE
Restructuring the docs

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#2887]
At MakieCon, there was a lot of talk about how the docs could have a better structure. Currently, it's kind of hard to find certain things and the examples are not useful enough to get one's work done quickly. Many people like the 4-section system from https://documentation.divio.com/ so I want to discuss how the docs could be restructured towards that.

The sections are _Tutorials_, _How-Tos_, _Reference_ and _Explanation_.

The current partitioning is:

<img width="476" alt="grafik" src="https://user-images.githubusercontent.com/22495855/233780387-7627cc60-3ec0-4903-9f81-963da79a4455.png">

- **Examples**
  - split into plot function and Block examples, both have an overview gallery
  - Block "examples" are a bit of a misnomer as it sounds like _How-To_ but there's also a lot of _Explanation_ put there, mixed with _Reference_.
- **Tutorials**
  - Basic tutorial could be made much more basic, in the divio system one should not mix it with _Explanation_ but that's what I definitely did there
  - other tutorials are also probably not _Tutorial_ enough
- **Documentation**
  - This was just a catch-all section for all the docs entries that didn't fit into the other categories. Needs to be cleaned up and bits shifted into separate categories
  - A lot of this will probably turn out to be _Explanation_
- **API**
  - This is _Reference_ although it contains no specifically written content, just the docstrings
- **News**
  - Just a copy of the NEWS.md file to make it more visible

I think the biggest question is how to redesign the _Reference_ section given that a plotting library cannot just present docstrings there. We should probably just clearly visualize all the attributes that a given plot or Block can have, so it's like a visually spruced-up reference. Additionally, I think the docstrings are too hard to navigate in the REPL anyway if they are super long, such as they are for `Axis`, for example. So we don't want to add even more stuff to Block docstrings, but we also don't want to have similar content in multiple places, that will be a nightmare to keep synchronized. Also, we want our explanations to be tested ideally (like doctest but with images).

So my current idea is that we basically remove the docstrings as they are from `Axis` etc. and make a function with a visual example for each attribute. Then those functions could be called from the REPL via some interface like `example(Axis, :xticklabels)` which would print out the text and show the example plot. But they also populate the _Reference_ section in the docs, so that we don't have a text-only API section but one with nice visual examples for each option. This way, one could also automatically check that no attribute is undocumented, which we currently cannot. I'm not sure if in practice one visual per attribute is too much. Maybe some attributes also need multiple images. But it might be a good start.

**Comment by felixcremer** [comment]
Is Makie making use of the extended docstrings? In the Repl I sometimes would not need the reference images, but just a reminder of what values certain attributes accept.

**Comment by jkrumbiegel** [comment]
In this PR https://github.com/MakieOrg/Makie.jl/pull/2894 I'm overloading some methods so you can write `?Axis.xticks` and it prints out the docstring only for this attribute which is going to be more extensive in the future.

**Comment by ffreyer** [comment]
Closing as the docs now use this structure
