### ISSUE TITLE
CairoMakie plots heatmaps incorrectly in 3D

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#2889]
We need to figure out how to scale the element in 2d to achieve the 3d effect.

```julia
f, a, p = heatmap(-2..2, -1..1, rand(100, 100); axis = (; type = LScene))
```
![download-3](https://user-images.githubusercontent.com/32143268/233804288-4a574385-5169-49f3-b831-3d212da25a21.png)

**Comment by jkrumbiegel** [comment]
That is not exact because you can't do "perspective projections" with the six-element matrix that cairo uses, but it was the closest thing I could think of at the time.
