### ISSUE TITLE
Improve docs for displaying figures in CairoMakie

### ISSUE THREAD

**Issue by bkamins** [MakieOrg/Makie.jl#2897]
On https://docs.makie.org/stable/tutorials/basic-tutorial/ you currently write:
> Note that CairoMakie can create images but it cannot display them.
> To see the output of plotting commands when using CairoMakie, we recommend you either use an IDE which supports png or svg output, such as VSCode, Atom/Juno, Jupyter, Pluto, etc., or try using a viewer package such as [ElectronDisplay.jl](https://github.com/queryverse/ElectronDisplay.jl), or alternatively save your plots to files directly. The Julia REPL by itself does not have the ability to show the plots.

Which does not it make easy to know what to do if you use terminal and want to display plots in a separate window.

**Comment by t-bltg** [comment]
It would be great to mention Sixels: if one's terminal supports them, I find it a pretty decent way to visualize CairoMakie plots.

**Comment by jakubkaczor** [comment]
When I use `Makie.inline!(true)` and I'm in a terminal session, the figure is displayed in my system image viewer, and this is exactly what I would want for every backend. But as far as I'm concerned, `Makie.inline!` is planned to be removed (https://github.com/MakieOrg/Makie.jl/pull/2353). Is there any standard, public API way of achieving the same effect? That is, displaying figures in a system viewer by default? If so, this is precisely what I would like to see in the documentation on this subject.

**Comment by jkrumbiegel** [comment]
It has proven hard to remove. I'm not sure what Simon's current opinion is on the topic, but if the function stays it's going to be much better documented in the future, for sure.

**Comment by jakubkaczor** [comment]
I see it is also discussed [here](https://github.com/MakieOrg/Makie.jl/issues/2805#issuecomment-1483852545), so I suppose that it should work the way I described by default, that is, to display a figure in a separate window, but it doesn't due to this VS Code workaround, correct? If so, I don't think documenting this extensively is needed, and I would only expect a note that, currently, it doesn't work, because of the other problem mentioned.

**Comment by randomizedthinking** [comment]
A display function has been added in `CairoMakie/Ry75I/src/display.jl`. On Linux, it will call `xdg-open` to open the image file generated by CairoMakie.

There is one issue with this display function that this call blocks. In my use case, `;` is used to suppress the display of some intermediate figure, and only display at the final stage.

**Comment by jkrumbiegel** [comment]
> this call blocks

Maybe that should be classified as a bug, given that other display behavior doesn't block. It should be possible to call `xdg-open` in a non-blocking way, I'm not sure what that means for the return value which we use to determine if opening worked.

**Comment by randomizedthinking** [comment]
> > this call blocks
> 
> Maybe that should be classified as a bug, given that other display behavior doesn't block. It should be possible to call `xdg-open` in a non-blocking way, I'm not sure what that means for the return value which we use to determine if opening worked.

Dugged into this... I think the cause of the call block is identified. It is related to the X-environment configuration: xdg-open will block under generic X installations: the image viewer program is called directly, and it blocks. It won't block under Gnome or KDE: the respective program launcher is used to launch the viewer program. It returns immediately.

**Comment by asinghvi17** [comment]
I suppose we could spin it off to a separate process?

**Comment by ffreyer** [comment]
I think CairoMakie now consistently opens an image viewer from the terminal. Can this be closed?

**Comment by asinghvi17** [comment]
Linux blocking behavior is worth an issue but I have no way to test.

**Comment by asinghvi17** [comment]
Linux blocking behavior is worth an issue but I have no way to test.

**Comment by duzaichuan** [comment]
> I think CairoMakie now consistently opens an image viewer from the terminal. Can this be closed?

Wondering this too.
