### ISSUE TITLE
Scene / subwindow tutorial not working

### ISSUE THREAD

**Issue by dafred94** [MakieOrg/Makie.jl#2904]
Following [this tutorial](https://docs.makie.org/stable/tutorials/scenes/#scenes_and_subwindows), only the first Scene but not the subwindow is displayed. It is already wrong in the images rendered on that tutorial page.

Tried the following code from [here](https://github.com/MakieOrg/Makie.jl/issues/2697):
```
using GLMakie, Makie
 GLMakie.activate!()
scene = Scene(backgroundcolor=:gray);
subwindow = Scene(scene, px_area=Rect(100, 100, 200, 200), clear=true, backgroundcolor=:white);
scene
```

But still no luck, unfortunately.

My `Project.toml` reports the following:

> [e9467ef8] GLMakie v0.8.4
> [ee78f7c6] Makie v0.19.4

**Comment by ffreyer** [comment]
```julia
julia> scene.children[1].px_area
Observable(GeometryBasics.HyperRectangle{2, Int64}([0, 0], [0, 0]))
```

With `px_area = Observable(Rect2i(...))` it works

**Comment by SimonDanisch** [comment]
Should be fixed!
