### ISSUE TITLE
Add an easily accessible way to cite makie in the main documentation

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#2906]
please :)

E.g., here:

![image](https://user-images.githubusercontent.com/19669089/235174216-e0dadb6c-60ae-42b9-8433-7f03fa17d511.png)

**Comment by asinghvi17** [comment]
FWIW it is in the README

**Comment by Datseris** [comment]
Aaaaah yes it is here: https://docs.makie.org/stable/#citing_makie No I think that's okay, I just didn't think of searching the side bar instead of the top bar!!!
