### ISSUE TITLE
Unable to close GLMakie window

### ISSUE THREAD

**Issue by mchitre** [MakieOrg/Makie.jl#2909]
To reproduce:
```julia
julia> using GLMakie
julia> GLMakie.update_theme!(resolution=(1500,1000), fontsize=28)
julia> x = [randn() for _ ∈ 1:1_000_000];
julia> lines(x)
# now close the window - closes OK
julia> lines(x)
# try closing window again - window hangs!
```

If the call to `GLMakie.update_theme!()` is removed, the closing more often works. However, if I zoom/pan a bit and try it, closing fails again and the window hangs (beachballs).

### System information
```
(jl_Ydxn0t) pkg> st
Status `/private/var/folders/hx/kbmkkbqd0rxbwlgymb6hfkmh0000gn/T/jl_Ydxn0t/Project.toml`
  [e9467ef8] GLMakie v0.8.4

julia> versioninfo()
Julia Version 1.9.0-rc2
Commit 72aec423c2a (2023-04-01 10:41 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
```

**Comment by ffreyer** [comment]
I can't reproduce this on linux or windows. Does your cpu or gpu usage saturate when this happens?

**Comment by mchitre** [comment]
No, neither CPU nor GPU usage is high. The Julia REPL remains responsive too. And if I quit the Julia REPL, the window closes normally.

**Comment by jkrumbiegel** [comment]
All the "window hangs at close" bugs before were only on Mac, so this seems a variant of those we squashed already. Interesting that it seems connected to the theme edit, we do have display variables in there these days so that could be a lead.

**Comment by ffreyer** [comment]
Does this also happen if you close the first window with `GLMakie.closeall()` or call that before opening the second window? That should fully close the window rather than just hiding it.

**Comment by kbarros** [comment]
The latest version of Makie does not expect a `resolution` argument. Here is an updated test:

```julia
using GLMakie
GLMakie.update_theme!(size=(800,600), fontsize=16)
x = [randn() for _ ∈ 1:1_000_000];
lines(x)

# now close the window

lines(x)

# no problem closing the window again
```

This issue might is now resolved? Tested on Mac.

**Comment by asinghvi17** [comment]
I can't replicate this on Mac (M1 as well) either.
