### ISSUE TITLE
Simple line plot example where axes are fixed relative to view and not the data

### ISSUE THREAD

**Issue by kcajf** [MakieOrg/Makie.jl#292]
Hi,

I was looking for an example of how to plot e.g. a line in Makie where the axes are re-draw as the scene is panned and zoomed. This is default behaviour in many plotting libraries, e.g. matplotlib below:
[https://imgur.com/a/13ZAqvN](https://imgur.com/a/13ZAqvN)

I've dug through all the examples, but can't find an obvious implementation of this behaviour. If someone has already implemented this somewhere, it would great if you could please point me to it! If not, it would be great if you could pleas point me in the right direction towards implementing this.

Thanks

**Comment by asinghvi17** [comment]
Unfortunately, this hasn't been implemented yet - the axis still "lives" in dataspace.  We are working towards it, though, and by the time layouting comes it will definitely exist.

**Comment by ffreyer** [comment]
Implemented via `Axis`
