### ISSUE TITLE
Document usage of colorbuffer to plot GLMakie 3D figure into a CairoMakie Figure

### ISSUE THREAD

**Issue by felixcremer** [MakieOrg/Makie.jl#2920]
As discussed on slack, it is possible to plot into a colorbuffer with the GLMakie backend and then use this colorbuffer to plot with CairoMakie. 

This capability should be documented somewhere and I didn't find it on the Makie webpage. 

@tknopp  Could you please add your example code here?

**Comment by tknopp** [comment]
Here is the MWE I posted on Slack. I used it within Pluto.

```julia
begin
	using CairoMakie
	import GLMakie
	using Makie
	
	CairoMakie.activate!()

	r = LinRange(-1, 1, 100)
	cube = [(x.^2 + y.^2 + z.^2) for x = r, y = r, z = r]
	
	cube_with_holes = cube .* (cube .> 1.6)
	fgl, a, p = GLMakie.volume(cube_with_holes, algorithm = :iso, isorange = 0.05, isovalue = 1.7)
	
	cb = Makie.colorbuffer(fgl.scene, backend=GLMakie)
	
	fcairo = Figure()
	ax, p = image(fcairo[1,1], cb', axis=(yreversed=true,))
	
	fcairo
end
```
Before putting it into the documentation it should be polished more. 
I am not sure where this could fit into the documentation. Probably into the examples?

**Comment by asinghvi17** [comment]
We could put it on the backends page, to show backend interop?

**Comment by SimonDanisch** [comment]
I would concentrate on merging @asinghvi17 pr before we advertise this as the solution for backend interop... Meanwhile we should add colorbuffer docs, which could actually include this as an example

**Comment by tknopp** [comment]
Here is an improved code that probably would fit somewhere in the docu:
```julia
using CairoMakie, GLMakie, Makie

CairoMakie.activate!()

r = LinRange(-1, 1, 100)
cube = [(x.^2 + y.^2 + z.^2) for x = r, y = r, z = r]
cube_with_holes = cube .* (cube .> 1.6)

fgl = Figure(resolution=(500,350))
axgl, pgl = GLMakie.volume(fgl[1,1], cube_with_holes, algorithm = :iso, 
		                     isorange = 0.05, isovalue = 1.7,
	                             axis=(type=Axis3, protrusions=10))
xlims!(axgl,1,100)
ylims!(axgl,1,100)
zlims!(axgl,1,100)

cb = Makie.colorbuffer(fgl.scene, backend=GLMakie)

fcairo = Figure(resolution=(800,400))
axleft, pleft = image(fcairo[1,1], cb', axis=(yreversed=true,aspect=1))
hidedecorations!(axleft)
hidespines!(axleft)

axright, pright = heatmap(fcairo[1,2], cube_with_holes[:,:,1],
		                            axis=(xlabel="x", ylabel="y", aspect=1) )

fcairo
```

![MakieColorbufferExample](https://user-images.githubusercontent.com/3109172/236698233-704da08d-9b87-4fd8-ab9c-96b80aedd873.png)

**Comment by SimonDanisch** [comment]
Ah, colorbuffer may actually not trigger the automatic limits!

**Comment by asinghvi17** [comment]
Yeah, you may want to call `Makie.update_state_before_display!(fgl)` manually before proceeding.

@SimonDanisch - that might make colorbuffer a bit slower, since `data_limits` is called twice in `reset_limits!`, which is called in `update_state_before_display!` for axes.  Especially for plots with a lot of data.  Maybe it would make sense to have a flag in `Axis` which `update_state_before_display!` sets, so that we know if the state has been calculated once or not?  That would also probably fix some of the issues people have had where saving axes with `update=true` resets the limits, which they might not want.

**Comment by SimonDanisch** [comment]
We still don't have sufficient docs for colorbuffer! I'd also would want to start exporting it by default.

**Comment by tknopp** [comment]
I confirm that `Makie.update_state_before_display!(fgl)` does fix the issue with the limits, i.e. I replaced
```julia
xlims!(axgl,1,100)
ylims!(axgl,1,100)
zlims!(axgl,1,100)
```
by
```julia
Makie.update_state_before_display!(fgl)
```

**Comment by ffreyer** [comment]
Related: #3652
