### ISSUE TITLE
`@inherit` calls include path in docstrings

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#2926]
From `julia> Base.Docs.getdoc(subtypes(Makie.Block)[1])` in a REPL, i.e. docstring for `Axis` on my system:
```
    •  yticklabelsize: The font size of the yticklabels. Default: #=
       /home/dennishb/.julia/packages/Makie/Iqcri/src/makielayout/types.jl:273
       =# @inherit :fontsize 16.0f0
```

This is not good for offline documentation though docstrings. Why does this happen?

**Comment by jkrumbiegel** [comment]
Ah yes that has annoyed me as well, it's just the default printing of macro expressions which prints out LineNumberNodes
