### ISSUE TITLE
Labled contour example not showing lables

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#2943]
In the [docs](https://docs.makie.org/stable/examples/plotting_functions/contour/index.html#contour), there is code to make a labeled contour plot:
![image](https://github.com/MakieOrg/Makie.jl/assets/61620837/4b9bb13d-78a5-4d65-9b43-88cd32444be6)

When I try to recreate it, I got the following:
![image](https://github.com/MakieOrg/Makie.jl/assets/61620837/440737c2-666f-4521-ad42-1360a1d9f8a2)

The code (from the example) is
```
using CairoMakie


himmelblau(x, y) = (x^2 + y - 11)^2 + (x + y^2 - 7)^2
x = y = range(-6, 6; length=100)
z = himmelblau.(x, y')

levels = 10.0.^range(0.3, 3.5; length=10)
colormap = Makie.sampler(:hsv, 100; scaling=Makie.Scaling(x -> x^(1 / 10), nothing))
f, ax, ct = contour(x, y, z; labels=true, levels, colormap)
f
```

Version info:
<details>

```
julia> versioninfo()
Julia Version 1.9.0-rc3
Commit 1853b903282 (2023-04-26 15:51 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_PKG_PRESERVE_TIERED_INSTALLED = true
  JULIA_CONDAPKG_BACKEND = Null

(@GeneralEnv) pkg> st GLMakie
Status `~/.julia/environments/GeneralEnv/Project.toml`
  [e9467ef8] GLMakie v0.8.4

```
</details>

**Comment by SimonDanisch** [comment]
What's the CairoMakie version? In your versioninfo, I only see GLMakie...

**Comment by KronosTheLate** [comment]
I am sorry, I was unclear.

I only have GLMakie installed, so instad of installing CairoMakie also, I just changed the backend. So the code is from the example, but the code I ran modified the backend.

**Comment by KronosTheLate** [comment]
That is stange indeed... I recreated this because a classmate had the same problem, and we got consisten results. Does this help the investigation?
```
julia> [(pkg.name, pkg.version) for pkg in values(Pkg.dependencies()) if pkg.name=="Makie"]
1-element Vector{Tuple{String, VersionNumber}}:
 ("Makie", v"0.19.4")
```

**Comment by SimonDanisch** [comment]
Ooh, my "fresh" environment is the one at fault.... 
I somehow ended up with GLMakie@0.8.4 and Makie#master...
So, the contourlabel PR isn't actually tagged yet, I'm honestly not sure how they made it into the stable docs. @jkrumbiegel any idea how that could happen?

**Comment by jkrumbiegel** [comment]
If it's in the docs it must be tagged no?

**Comment by KronosTheLate** [comment]
Oh, so this is a feature only available on the master branch? Then I suppose the next tagged release will close this issue all by itself. Perhaps a note is needed in the docs about the minimal version for this to work, as Julia Base commonly does?

**Comment by jkrumbiegel** [comment]
There must be something quite wrong with the docs build if this could happen, the dev version should never overwrite the stable build (which I assume must have happened?). Maybe this has been going on for a while and we haven't noticed?

**Comment by jkrumbiegel** [comment]
Ok found the issue with the docs, I assume the reference image push for the beta branch triggered a tag and a tag build of the docs, so since then `stable` had been essentially master from a couple weeks ago. I hope I've fixed it directly on gh-pages now, but even if not this issue can be closed.

**Comment by KronosTheLate** [comment]
Thanks for your efforts, I appriciate Makie a lot <3 Also the fact that issues are taken seriously, without having to wait for weeks.

**Comment by jkrumbiegel** [comment]
thanks! we certainly try, although we don't always have the time
