### ISSUE TITLE
GLMakie no longer displays to separate window in VS Code

### ISSUE THREAD

**Issue by garrekstemo** [MakieOrg/Makie.jl#2956]
In the most recent update (GLMakie 0.8.5 on Julia version 0.9.0) GLMakie no longer opens a separate window when executing from a file in Visual Studio Code (Julia extension also on the latest version). Instead, plots open in a new tab in VS Code, like CairoMakie. I tested with a new environment with only GLMakie installed and generating a blank `Figure()`. I'm not sure if it's a Makie or VSC problem.

**Comment by garrekstemo** [comment]
Ah ok. Is there a post or discussion somewhere that I can read? Has there been a change in the roadmap for GLMakie?

My thinking is that having it open in a separate window encourages the user to make use of the more interactive elements of GLMakie. This change suggests to me that perhaps there has been a change in thinking about how people should use it. I would like to make sure that when I'm teaching others that I'm going along with how Makie will be in the future.

**Comment by garrekstemo** [comment]
Ok, makes sense! Thanks for explaining.

**Comment by garrekstemo** [comment]
Ok. I'm actually getting ready to do a tutorial in my laboratory for new students over the next few weeks and I teach with Makie exclusively. Last year I got good feedback on Julia and Makie, so I'll share any ideas that I have this time.

**Comment by ffreyer** [comment]
I think the main selling points of GLMakie over CairoMakie are interactivity and 3D. Having one of these removed by default sounds bad to me. 

I think my preference for vscode would be interactive window > pane > both, since use it for tinkering with things. For jupyter notebooks it would be both > interactive window > static inline plot because I use them to show of and sort of archieve results as well as tinkering. If you could have an inline image that updates after manipulation of the open window that would be even better. Maybe that would be possible in Pluto?

**Comment by jkrumbiegel** [comment]
You could do something like 

```julia
fig = Figure()
wait(display(fig))
fig
```

in Jupyter, then the final result of your tinkering should be shown after closing the window, no?

**Comment by ffreyer** [comment]
Yea, I've done that. It ended up being about as annoying as useful because I wanted to do some napkin math or check something else in another cell. And you can't do that while waiting for the window to close.

**Comment by Reese-Martin** [comment]
Just want to throw in a comment here that this behavior changes has really messed up my workflow. I was only using GLMakie because of the generation of windows that I could interact with, and this has disabled that feature for (from my perspective) no reason and with no warning.

**Comment by ffreyer** [comment]
The change has been reverted in #3057 which is part of the 0.19.7 release. So with the latest version you should get interactive windows by default again (in vscode?)
