### ISSUE TITLE
Error: bracket! not defined

### ISSUE THREAD

**Issue by roccminton** [MakieOrg/Makie.jl#2960]
I'm trying to get the basic example from the Makie Documentation on the function `bracket` going, but get the 

> LoadError: UndefVarError: bracket! not defined

I am using the Makie v0.19.5 and CairoMakie backend on v0.10.5 and Julia v"1.6.3". Am I missing something obvious?

**Comment by roccminton** [comment]
No, sorry for the misunderstanding. The typo "brackets" instead of "bracket" exitsted only in the above message. That does not solve the issue. I copied the example from the documentation and got the above LoadError. So no room for typos there. I thougth it might have to do with some version issues, but as far as I know the versions that I use should be sufficent to know the funktion `bracket!`

**Comment by jkrumbiegel** [comment]
Sometimes you might have a variable clashing from another package. If you can get `Makie.bracket!` then that's probably the case.
