### ISSUE TITLE
[Bug] Invalid log limits error with valid limits

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#2971]
Even when I explicitly set limits that are valid for a log scale, I get an error upon setting the scale to log.
In trying to make a MWE before, I have been able to change the y-limits and gotten no error when setting the scale to log. But often "in the wild" it does error. Below is an example that reproduces the error for me.

<details><summary>Code showing the problem</summary>

```
julia> using GLMakie

julia> let
           fig = Figure()
           xs = -1:10
           ax, plt = scatter(fig[1, 1], xs, xs .^ 2 .- 3 .* xs)
           ax.limits = (nothing, nothing, 1, nothing)
           @show ax.limits
           ax.yscale = log10
           display(fig)
       end
ax.limits = Observable{Any}((nothing, nothing, 1, nothing))
ERROR: Found invalid x-limits (-2.0f0, 70.0f0) for scale log10 which is defined on the interval 0.0..Inf (open)
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] autolimits(ax::Axis, dim::Int64)
    @ Makie ~/.julia/packages/Makie/Iqcri/src/makielayout/blocks/axis.jl:970
  [3] yautolimits
    @ ~/.julia/packages/Makie/Iqcri/src/makielayout/blocks/axis.jl:983 [inlined]
  [4] reset_limits!(ax::Axis; xauto::Bool, yauto::Bool, zauto::Bool)
    @ Makie ~/.julia/packages/Makie/Iqcri/src/makielayout/blocks/axis.jl:598
  [5] reset_limits!
    @ ~/.julia/packages/Makie/Iqcri/src/makielayout/blocks/axis.jl:569 [inlined]
  [6] (::Makie.var"#1299#1329"{Axis})(#unused#::Function, #unused#::Function)
    @ Makie ~/.julia/packages/Makie/Iqcri/src/makielayout/blocks/axis.jl:190
  [7] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./essentials.jl:816
  [8] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base ./essentials.jl:813
  [9] (::Observables.OnAny)(value::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:415
 [10] #invokelatest#2
    @ ./essentials.jl:816 [inlined]
 [11] invokelatest
    @ ./essentials.jl:813 [inlined]
 [12] notify
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:169 [inlined]
 [13] setindex!(observable::Observable, val::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:86
 [14] setproperty!(x::Axis, key::Symbol, value::Function)
    @ Makie ~/.julia/packages/Makie/Iqcri/src/makielayout/blocks.jl:468
 [15] top-level scope
    @ REPL[2]:7
```
</details>

Note that it prints that the x-limits are wrong, but that the values match the y limits. I also believe that I fixed the printing in https://github.com/MakieOrg/Makie.jl/pull/2860.

<details><summary>Version information</summary>

```
julia> versioninfo()
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_PKG_PRESERVE_TIERED_INSTALLED = true
  JULIA_CONDAPKG_BACKEND = Null

julia> [p.name => p.version for p in values(Pkg.dependencies()) if occursin("Makie", p.name)]
3-element Vector{Pair{String, VersionNumber}}:
   "GLMakie" => v"0.8.4"
 "MakieCore" => v"0.6.3"
     "Makie" => v"0.19.4"
```
</details>

**Comment by jkrumbiegel** [comment]
The extrema of your y-values are `(-2, 70)` so the error is accurate (except for the printing bug). What I agree can be improved is saying that the limits of the data are invalid for the scale, not the limits of the axis. As all data has to be transformed before rendering, the view limits are not the decisive factor.

**Comment by jkrumbiegel** [comment]
You can also try pseudolog scales if you have data at/below 0 https://docs.makie.org/stable/examples/blocks/axis/#example_pseudo-log_scales

The problem with filtering out data is that for many plot types, it's possible that a point slightly outside of the limits would still need to be rendered partially. To exclude only points that are outside would mean checking the visual boundingboxes of everything, which is complex.

**Comment by KronosTheLate** [comment]
pseudolog and Symlog scales seem to be exactly what I have been looking for, thanks <3
I feel like it would be really nice to reccomend these scales in the invalid limits error, as well as make it very clear that we are not talking about axis limits. Do you agree with these suggestions? If yes, I will put it in a PR.
