### ISSUE TITLE
Vertical band plot

### ISSUE THREAD

**Issue by jebej** [MakieOrg/Makie.jl#2978]
Is it possible to plot a vertical band, with arguments `xlower`, `xupper`, and `y`? I attempted to pass `Point2f` and `Point3f` coordinates (with `z=0`) using the `band(lower, upper)` method but could not get it to work.

**Comment by jkrumbiegel** [comment]
xlower, xupper, y hasn't been implemented (it would need a keyword arg to flip I'd think) but for the upper/lower signature you should be able to do `Point2f.(xlower, y), Point2f(xupper, y)`

**Comment by jebej** [comment]
Yes, I had a mistake, got that syntax to work, thanks!
