### ISSUE TITLE
Unit testing Makie backends

### ISSUE THREAD

**Issue by c42f** [MakieOrg/Makie.jl#298]
I've been thinking about Makie testing. I'd really like it if GLMakie had a set of fast unit/conformance tests I could run during development. Ideally designed to probe the technical limits of the renderer for each atomic plotting function rather than to show off features. This is a different goal from MakieGallery which has many beautiful and useful feature demonstrations. I feel that MakieGallery could better be viewed as an extended integration test suite which could be run regularly (eg, daily) for each backend in development.

As an example of these kind of simple tests, I am thinking of the wide lines rendering test at https://github.com/JuliaPlots/MakieGallery.jl/issues/9. It's not plotting much data, but it probes difficult cases (and shows the limits of the GLMakie implementation, even after merging some fixes from https://github.com/JuliaPlots/GLMakie.jl/pull/28)

I wonder if we should really start a new package `MakieUnitTests` or something. Maybe we could even copy parts of a test suite from some other 2D vector graphics standard? For example the SVG test suite at https://github.com/web-platform-tests/wpt/tree/master/svg.

In principle each backend would need its own set of reference images, as it will suffer from different rendering artifacts during development.

**Comment by SimonDanisch** [comment]
I was planning, to simply add "examples" in GLMakie `runtests.jl` ... This should work fairly well, but I'll need to figure out where to store the reference images...

**Comment by c42f** [comment]
I'm totally fine with that for now. If we end up with multiple backends that can be dealt with later as necessary.

Perhaps we could store the reference images in git LFS on the GLMakie repo? We really should be versioning the reference images with the code (but not *in* the git repo for obvious reasons).

**Comment by c42f** [comment]
As a point of reference, when I used to work on the aqsis rendering engine (project basically defunct for lack of resources, RIP) we had a regression test suite much like you have with MakieGallery. This was in the days of svn/sourceforge so it was versioned in a separate svn repository. In this repository was the test scenes and reference images which were versioned together. Also a build script which produced a HTML page making a visual comparison between output vs reference images.

This worked quite well for that project where the trunk branch was restricted to a core set of developers who were more or less trusted to carefully run the regression tests and update the test repository separately to the main codebase. I think if we version the reference images in LFS or similar, we'll get a similar but better workflow which will work with PRs/CI as well.

**Comment by SimonDanisch** [comment]
that's actually pretty much how makiegallery works ;)
Reference images are
 stored and versioned in the repository ReferenceImages and i have a couple of tools to generate html previews ;)
I rather meant, if i break the 1:1 mapping from examples in MakieGallery to images in ReferenceImages.. But i guess there is no real downside by uploading backend specific images as well ;)

**Comment by c42f** [comment]
Well I must admit I find the current setup with a separate tests repo a little clumsy for PRs. I think that was also a little clumsy in the aqsis setup but it mattered a little less because the development process was a less fluid in those days of centralized VCSs.

In particular I'd love it if PRs fixing things in GLMakie could have tests which go with the PR itself, including reference images. I'm not sure that's possible, but I'd certainly like it ;-)

**Comment by mkborregaard** [comment]
The problem would be that all the testing data and images would have to be cloned by everyone `dev`ing the package. That's the reason at least in Plots for having the same model as MakieGallery (with PlotReferenceImages). It is quity clumsy with PRs, though, true.

**Comment by c42f** [comment]
Hmm, I thought git LFS would sort that out. I just tested this and it does allow you to have binary assets versioned without them being downloaded as part of the main repo. In particular, users without `git-lfs` installed would not get the binary assets downloaded. Users with git-lfs, can customize it by setting the `GIT_LFS_SKIP_SMUDGE=1` environment variable or with per repo config.

**Comment by asinghvi17** [comment]
I think that one approach could be having multiple reference image repos, and downloading released tarballs; then using MakieGallery's new file-based database loading to host an example database specific to each backend within the `test` folder.

**Comment by ffreyer** [comment]
Closing this as outdated/finished since the reference image test infrastructure has long moved from MakieGallery and runs as part of the pr workflow
