### ISSUE TITLE
Trouble using an observable to change the contour levels in contour3d!

### ISSUE THREAD

**Issue by ghralima** [MakieOrg/Makie.jl#2980]
I'm trying to use an observable to change the contour levels with contour3d!, and for some reason it's not working.

```julia
using GLMakie

f = Figure()
ax_01 = Axis3(f[1, 1], aspect=(0.5,0.5,1), perspectiveness=0.75)

xs = ys = LinRange(-0.5, 0.5, 100)
zs = [sqrt(x^2+y^2) for x in xs, y in ys]

niveis = Observable([0.25])
espessura = Observable(2.0)

surface!(ax_01, xs, ys, +zs)

contour3d!(ax_01, xs, ys, +zs, linewidth=espessura, color=:red2, levels = niveis)

levelslider = SliderGrid(f[2, 1], 
    (label = "Contour level", range = -0.5:0.01:0.5, startvalue = -0.25),
    (label = "Contour width", range = 1.0:0.1:3.0, startvalue = 2.0),
    height = 50
) 

valores = [v.value for v ∈ levelslider.sliders]

onany(valores[1], valores[2]) do lev, esp
    niveis[] = [lev]
    espessura[] = esp
end

f
```
This code is giving me a segmentation fault anytime I try to use the sliders. But if I comment line

```julia
    niveis[] = [lev]
```
inside onany() loop, it works, and the contour3d linewidth changes when I use the "Contour width" slider.  

When I disable the onany loop and the sliders, and use

```
niveis[] = [0.45]
```
to change the contour levels, it also doesn't work. But it works nicely when I use

```
esspessura[] = 4.0
```
to change the contour linewidth. I'm not sure about the segmentation fault, but it seems the levels keyword inside contour3d! is haveing some trouble when updating observables.

**Comment by SimonDanisch** [comment]
This should be fixed
