### ISSUE TITLE
How to use the command to close the window？

### ISSUE THREAD

**Issue by 13299118606** [MakieOrg/Makie.jl#2984]
How to use the command to close the window, we know that 
`display(GLMakie.Screen(), figure) `
will display the figure window, 

but is there any close(figure) command to close the figure window function, if you use` empty!(f)` to clear f , but the window is still **on top**, is it possible to close the window invisible only by clicking the mouse?
`GLMakie.closeall() `will close all  figure window

I have two purposes, 1 is to clean up the memory, 2 is to close the window directly through the command, just like the `close fig`  function of matlab

**Comment by asinghvi17** [comment]
```julia
screen = display(GLMakie.Screen(), fig)
sleep(5) # do something
close(screen)
```

**Comment by 13299118606** [comment]
> ```julia
> screen = display(GLMakie.Screen(), fig)
> sleep(5) # do something
> close(screen)
> ```



Thank you,  this is to hide the figure window, will it save memory?

` display(GLMakie.Screen(), fig)` will display fig
