### ISSUE TITLE
Is there an easy way to swap the x,y axes?

### ISSUE THREAD

**Issue by 13299118606** [MakieOrg/Makie.jl#2986]
Is there an easy way to swap the x,y axes?
I want to fill in the x direction (xlow, xhigh, y) instead of the y direction (x, ylow, yhigh), band! can only fill in the y direction
```
seis=rand(50,10).-0.5
f=Figure()
ax =Axis(f[1,1], xlabel = "x label", ylabel = "y label",
title = "Title")
tn,xn=size(seis)
for iy =1:xn
    band!(1:tn, 0+iy, seis1[iy,:].+iy,color=:black)
    lines!(1:tn,seis1[iy,:].+iy)
end
```

![image](https://github.com/MakieOrg/Makie.jl/assets/58963158/f3a22ced-76ee-493e-abbc-917ed0b9bb1c)
First I considered the rotation solution 
`GLMakie.rotate!(ax.scene, -0.25π)`
Only the inside of the coordinate axis will be rotated, and the coordinate axis will not be rotated
`GLMakie.rotate!(f.scene, -0.25π)`

![Snipaste_2023-05-28_23-32-30](https://github.com/MakieOrg/Makie.jl/assets/58963158/e838574f-c3b9-456b-904c-644bc57dff82)

It will only rotate the coordinate axis and the internal data of the coordinate axis are obviously not equal. No matter how I adjust it, it will not work, such as
```
cam=f.scene.camera
cam.view[] = Makie.orthographicprojection(1f0, 1f0, 1f0, 1f0,80f0,80f0)

```

**Comment by jkrumbiegel** [comment]
There's currently no direct option to flip `band`, and also not an entire `Axis` content because then the axis decorations would not be right anymore anyway.

But for this specific problem with `band` you can use the other signature with points for a workaround:

```julia
xlow = cumsum(randn(100))
xhigh = xlow .+ 1
y = 1:100

band(Point.(xlow, y), Point.(xhigh, y))
```

![image](https://github.com/MakieOrg/Makie.jl/assets/22495855/a2fe5b8c-8790-4700-86d4-b40a697def0b)

**Comment by 13299118606** [comment]
Thank you very much for your answer, this does achieve what I want
