### ISSUE TITLE
`resample_cmap` not found

### ISSUE THREAD

**Issue by guri-dominic** [MakieOrg/Makie.jl#2993]
I am getting the error below when I run the [volume_contour_scatters](https://beautiful.makie.org/dev/examples/generated/2d/volume/volume_contour_scatters/) example. The example seems to be outdated, but I managed to update some of the functions, except `resample_cmap`

```
ERROR: UndefVarError: `resample_cmap` not defined
```

I get this error whether I run `resample_cmap`, `Makie.resample_cmap`, or `GLMakie.resample_cmap`

I have the following packages installed
```
ColorSchemes   v3.21.0
GLMakie        v0.85
GeometryBasics v0.4.7
```

**Comment by DanielVandH** [comment]
Not sure why that function isn't defined for you:

```julia
julia> using GLMakie, ColorSchemes, GeometryBasics

julia> resample_cmap
resample_cmap (generic function with 1 method)

(jl_6UedLd) pkg> st
Status `C:\Users\User\AppData\Local\Temp\jl_6UedLd\Project.toml`
⌃ [35d6a980] ColorSchemes v3.21.0
⌃ [e9467ef8] GLMakie v0.8.5
⌃ [5c1252a2] GeometryBasics v0.4.7
Info Packages marked with ⌃ have new versions available and may be upgradable.
```

**Comment by SimonDanisch** [comment]
Must be some problem with the Pkg env...
