### ISSUE TITLE
WGLMakie: "Warning: Observable not found" + failing interactivity in Jupyter notebook

### ISSUE THREAD

**Issue by georgematheos** [MakieOrg/Makie.jl#2996]
I am using WGLMakie in Jupyter notebook to render simple "grid world" video game environments, in which I am testing planning algorithms for POMDPs.

I am developing interactive visualizations of the video game environments, so researchers can "play as the agent" in the environments.  I am doing this by updating an observable representing the "game state" whenever a Makie keyboard event is triggered.

Sometimes, this all seems to work correctly.

But most of the time -- and I can't tell what the difference is -- I get a warning like the following, and the interactivity does not work.

```
┌ Warning: Observable 6556190270256005279 not found :( 
└ @ JSServe ~/.julia/packages/JSServe/mXqsg/src/serialization/protocol.jl:31
┌ Warning: Observable 7507178114737402063 not found :( 
└ @ JSServe ~/.julia/packages/JSServe/mXqsg/src/serialization/protocol.jl:31
┌ Warning: Observable 15660630225243445755 not found :( 
└ @ JSServe ~/.julia/packages/JSServe/mXqsg/src/serialization/protocol.jl:31
```

I don't know what a minimal example is which produces this error; my tests of simpler uses of interactivity with WGLMakie do not seem produce this issue.

I thought the Makie devs might have an idea of what's happening, just from this warning message.  But if not, let me know and I can spend longer trying to find a minimal example of some sort which causes a similar issue.

Thanks!

**Comment by georgematheos** [comment]
It appears to me that this issue does not occur in GLMakie.

In a Jupyter notebook session where this error occurred using WGLMakie, I then added a cell at the end, containing:
```
using GLMakie
GLMakie.activate!()
display(f)
```
(`f` is the variable for the figure with the interactive visualization.)  This launched a GLMakie window, and within that window, the interactive behavior worked as intended.

**Comment by georgematheos** [comment]
These experiments with GLMakie indicate that WGLMakie _is_ updating the observables when given keyboard events -- and somehow the issue which is occurring is that WGLMakie is not updating the displayed figure in the Jupyter notebook.

(I think this because when I launch a GLMakie window, its state reflects that it has logged several actions from the initial state -- which must have been registered from the keyboard events I triggered in the WGLMakie window, even though this WGLMakie window did not visibly update.)

**Comment by SimonDanisch** [comment]
What's your JSServe & WGLMakie version?
Can you reproduce it outside Jupyter?

**Comment by georgematheos** [comment]
I just tried upgrading WGLMakie to the latest version and running the Jupyter notebook that had been giving me trouble.  It seems to work!

Since this issue had only occurred sometimes there is a chance it persists and I just didn't encounter it on these tests by chance.  I will close the issue for now and re-open if I encounter the issue again.  Thanks for the help!
