### ISSUE TITLE
Observable alpha value is not updated

### ISSUE THREAD

**Issue by blegat** [MakieOrg/Makie.jl#2998]
Thanks for this amazing package!
In the following minimal reproducing example, I am creating a slider and using its value to set the opacity/alpha value of a square.
The square starts with the starting value of the slider, that works. But when moving the slider, it does not get updated.
Is that a bug or am I not using this correctly ?
```julia
using GLMakie

function main(start=0.5)
    fig = Figure(resolution=(1200, 800))

    slider = Slider(
        fig[1, 1],
        range = LinRange(0, 1, 20),
        startvalue = start,
    )

    s = LScene(fig[2, 1], width=1200, height=600)

    mesh!(s, Rect3f(Point3f(0, 0, 0), Point3f(1, 1, 1)), color = (:black, slider.value))

    return fig
end

display(main(start))
```

**Comment by SimonDanisch** [comment]
You can't stack observables like this, the whole color attribute must be an observable, so try:
```julia
color = lift(a-> (:black, a), slider.value)
```

**Comment by jkrumbiegel** [comment]
Or `@lift((:black, $(slider.value)))`
