### ISSUE TITLE
how to plot a isosurface using volume?

### ISSUE THREAD

**Issue by crazyfireji** [MakieOrg/Makie.jl#3001]
I want to plot a isosurface like this, but it can't works
`
using GLMakie
x=1:100
f=rand(100,100,100)
f1=rand(100,100,100)
volume (x,x,x,f,algorithm=:iso,color=f1)
`

I want to get a isosurface like this
![mmexport1686541671801](https://github.com/MakieOrg/Makie.jl/assets/112403698/5c80e1b3-bc8e-4edf-b112-537f81984069)

**Comment by SimonDanisch** [comment]
Try contour, that allows you to pass levels!
