### ISSUE TITLE
CairoMakie SVG-export, colorbar broken in firefox/illustrator but not chrome

### ISSUE THREAD

**Issue by behinger** [MakieOrg/Makie.jl#3016]
The SVG-Colorbar export is mixed up when opening in firefox or illustrator (in 3 different ways depending on configuration). Chrome is fine though. Any Idea what's going on?

Edit: Julia 1.9, CairoMakie v0.10.6

MWE:
```
begin
	using CairoMakie
	using Random

rng = MersenneTwister(42)
	f = Figure()
	ax,h = heatmap(f[1,1],rand(rng,10,10),	colormap=:roma)
	Colorbar(f[1,2],h)
f
end
save("test.svg",f)
```

firefox ubuntu
![grafik](https://github.com/MakieOrg/Makie.jl/assets/10183650/cd65dcaa-a20c-4968-af77-88572b47f012)

firefox windows
![grafik](https://github.com/MakieOrg/Makie.jl/assets/10183650/97b1f5e0-4ee5-4201-ab07-47983c1f5688)

chrome windows
![grafik](https://github.com/MakieOrg/Makie.jl/assets/10183650/d92ab199-346f-4ca7-8955-6084e256ac79)

illustrator 
![grafik](https://github.com/MakieOrg/Makie.jl/assets/10183650/7836876e-0cd5-48f4-92dd-d17e587fc96b)

**Comment by jkrumbiegel** [comment]
This is very weird :) You could even inspect the file in Firefox developer tools and see which part in the svg markup might cause this?

**Comment by behinger** [comment]
the offending lines
```
<pattern id="pattern0-r03f3nzY" patternUnits="userSpaceOnUse" width="1" height="100"  patternTransform="matrix(12,0,0,-4.0575,546,417.75)">
  <use xlink:href="[#image59-r03f3nzY](view-source:XXX/test.svg#image59-r03f3nzY)"/>
</pattern>


<path style=" stroke:none;fill-rule:nonzero;fill:url(#pattern0-r03f3nzY);" d="M 546 417.75 L 558 417.75 L 558 12 L 546 12 Z M 546 417.75 "/>
```
I dont have a real clue about SVG :shrug:

I tried to understand the `patternTransform` matrix, which is the culprit: `matrix(12,0,0,-4.0575,546,417.75)` - but I dont really understand why the parameters are the way they are - here an explanation that barely helped https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform#transform_functions , because primarily I dont know what the two coordinate systems that are translated are

**Comment by behinger** [comment]
ah and my bad - I could just provide the svg ;)

![download](https://github.com/MakieOrg/Makie.jl/assets/10183650/d71b6746-0640-4d94-bad7-1e1115e5a0b9)

**Comment by asinghvi17** [comment]
I can confirm the SVG works on Mac Preview, and in Inkscape.  We draw continuous colorbars as interpolated images...the transformation is most likely from blockscene space to SVG space, which entails mostly translation and a bit of scaling.

It almost seems like the image is wrapped around its halfway point, or faulty UV coordinates in a mesh.  I would assume this is an SVG issue though.  

Could you try something like `image(Makie.peaks(); colormap = :viridis, interpolate = true)` and see if it exhibits similar errors?

**Comment by behinger** [comment]
![grafik](https://github.com/MakieOrg/Makie.jl/assets/10183650/6e60546e-fcc4-40e4-8f84-25517920e1fa)

works again in chrome but not in firefox

**Comment by jkrumbiegel** [comment]
A continuous colorbar is implemented as a 1 pixel wide image, I never thought there could be a problem with rendering that, but seemingly there is. No idea if switching to 2 for example could help. If we added linear gradients as a color-fill primitive, we could use a rect with such a fill, that would be easier.

**Comment by egavazzi** [comment]
Sorry for reviving this issue (I don't know if this is good practice), but I have the same problem. Namely that svg export kind of breaks when adding a colorbar to a plot. In inkscape, the svg nodes dissapear and the whole figure gets blurry. In a LibreOffice Impress presentation, the figure turns into a black square. In Powerpoint webapp, the figure is completely transparent except the colorbar (but only the color).

I am using Julia 1.10.2 with CairoMakie v0.11.10 on a Linux machine.

Inkscape with colorbar:
![image](https://github.com/MakieOrg/Makie.jl/assets/98973824/3779d735-40c4-4e66-be5e-2b2b39afa30a)

Inkscape without colorbar
![image](https://github.com/MakieOrg/Makie.jl/assets/98973824/88c62a28-4967-46c3-90b0-cdc342ce1204)

LibreOffice Impress (with colorbar)
![image](https://github.com/MakieOrg/Makie.jl/assets/98973824/3e4279bc-d988-4f44-ad09-44dd13ca47c3)

Powerpoint webapp (with colorbar)
![image](https://github.com/MakieOrg/Makie.jl/assets/98973824/5c488da4-49bd-4e68-8217-6fd185f64790)

**Comment by asinghvi17** [comment]
For the Inkscape issue, it looks like Inkscape doesn't know how to handle the colorbar pattern element and so rasterizes the entire SVG.  That's probably what is causing the SVG nodes to be removed.

Do you need an SVG?  Have you tried PDF export here?

**Comment by egavazzi** [comment]
PDF works nicely! (except a few nodes missing in Inkscape but my main concern was the rasterization). It does not work for presentations/slideshow which do not accept .pdf but found out that .eps works :+1:

**Comment by ederag** [comment]
Saving as `.eps` results in an empty colorbar (white) here, when dropped in libreoffice impress.
Saving as `.pdf` looks fine in the okular pdf viewer.
That pdf opened with inkscape (accepting defaults) looks fine in inkscape,
but saving (still in inkscape) as svg and dropping the result in libreoffice impress
makes a colorbar with a gradient in the horizontal direction too:
![Screenshot_20240509_112524](https://github.com/MakieOrg/Makie.jl/assets/10962809/80d01e53-7e47-46f4-82df-f53443951f63)

This seems to point to ["A continuous colorbar is implemented as a 1 pixel wide image"](https://github.com/MakieOrg/Makie.jl/issues/3016#issuecomment-1597602850)
that some software do not handle properly ?
Note that I reported an [issue to libreoffice](https://bugs.documentfoundation.org/show_bug.cgi?id=151618) a while ago (it seems tricky to solve),
with the same funny gradient depending on zoom / scroll shown in https://github.com/MakieOrg/Makie.jl/issues/3016#issuecomment-1597600995.

**Comment by j-fu** [comment]
Hi, I get similar strange behavior with the following code:
```julia
figure=Figure()
axis=Axis(figure[1,1], aspect = DataAspect())
X=0:0.1:1
Y=0:0.1:1
pts=[Point2f(x,y) for y in X, x in X]
li=LinearIndices(pts)
for j=1:length(Y)-1
    for i=1:length(X)-1
	t1=[li[i,j], li[i+1,j], li[i+1,j+1]]
	@views poly!(axis,pts[t1], strokecolor=:black, color=:red, strokewidth=1)
	t2=[li[i,j], li[i,j+1], li[i+1,j+1]]
	@views poly!(axis,pts[t2], strokecolor=:black, color=:red, strokewidth=1)
    end
end
figure
```
which gives the svg: 
![zzz](https://github.com/MakieOrg/Makie.jl/assets/9221937/6129fe3f-8ad6-4d55-a3d1-241a0088db57)

It shows on Chrome, but not on Firefox. Also, similar code gives [strange artifacts](https://j-fu.github.io/SimplexGridFactory.jl/stable/script_examples/examples2d/#Direct-specification-of-input-arrays) even on Chrome.

If I remove the `@views`, things become correct.

**Comment by asinghvi17** [comment]
I guess a quick solution for this is to set `rasterize=1` on the concerned plot....

**Comment by j-fu** [comment]
Yes, this seems to help. Thanks! 

What also "helps" is downgrading Cairo_jll.jl to 1.16, re-establishing the state where all of this worked.

What is really puzzling is the dependency of the behavior on passing views vs copies...
