### ISSUE TITLE
Fill area enclosed by a line 

### ISSUE THREAD

**Issue by pclus** [MakieOrg/Makie.jl#3018]
Hello, 

I have recently started using Makie, and looks wonderful.
However, I miss the possibility of coloring regions in simple 2d line plots.
For instance, using [Plots](https://docs.juliaplots.org/stable/) with the GR backend this is as simple as:

```julia
using Plots
gr()
n=200;
x = [ cos(2*π*i/n)+0.1*rand() for i in 1:n]
y = [ sin(2*π*i/n)+0.1*rand() for i in 1:n ]
plot(x,y,fill=:true)
```
which produces:

![image](https://github.com/MakieOrg/Makie.jl/assets/35599519/829a7c27-dfca-4950-ba8f-c912216a373a)

It would be very useful to have something as simple in Makie. 
I have looked around and did not find anything like this implemented.

Thanks!

**Comment by jkrumbiegel** [comment]
You can use `poly(Point2.(x, y))`, for some reason it doesn't auto-convert from just x and y separately.

**Comment by pclus** [comment]
Wow, that was surprisingly simple. I looked at poly, but I did not now how to use it to suit this purpose.
I guess I can close the issue now.

Thank you!
