### ISSUE TITLE
[feature request] support multi-column y with automatic legend

### ISSUE THREAD

**Issue by daviehh** [MakieOrg/Makie.jl#302]
e.g. when `x` of size `n` and one has calculated/read in y as a `n*m` matrix; Plots.jl allows for something like

```
using Plots
x = 1:10; y = rand(10,2)
plot(x,y)
```

to plot the columns of y against x, then label them as y1...yn in the legend; I can use a loop to plot `lines!(x,y[:,i])` manually but something like lines(x,y) where y can be a multi-column matrix can be helpful/make the code look cleaner. Thanks!

**Comment by mkborregaard** [comment]
sorry, I have no idea what you are requesting

**Comment by daviehh** [comment]
@mkborregaard It's quite common when the plot data is a matrix, each column corresponding to a line. For example, using Plots:

```
using Plots
xspan = 0:.01:2*pi
fs = [sin, cos, sinc]
y = [fs[i](x) for x in xspan, i in 1:size(fs,1)]
plot(xspan,y)
```
plots all columns of y against xspan, automatically using different colors and plot labels

<img width="598" alt="screen shot 2019-02-26 at 12 19 20 pm" src="https://user-images.githubusercontent.com/25255906/53432731-0f51c800-39c1-11e9-9181-7eda091c0c34.png">

in Makie, to achieve the same thing, there needs to be additional codes for color, and a loop to go through all columns:

```
using Makie

fs = [sin, cos, sinc]
colors = [:red, :green, :blue]

xspan = 0:.01:2*pi
y = [fs[i](x) for x in xspan, i in 1:size(fs,1)]

scene = Scene()

for i in 1:size(fs,1)
    lines!(scene,xspan,y[:,i],color=colors[i])
end

scene
```

<img width="433" alt="screen shot 2019-02-26 at 12 24 42 pm" src="https://user-images.githubusercontent.com/25255906/53432955-84bd9880-39c1-11e9-96bf-61c9118ea850.png">


I'm requesting something like `lines(xspan,y)` to iterate through all columns of y, with default different colors for each line, and optional automatic/user-provided legends. Thanks!

**Comment by asinghvi17** [comment]
Could you use convert_arguments?  See https://github.com/JuliaPlots/Makie.jl/issues/307#issuecomment-469116279 for now, but we should have the docs up as soon as JuliaPlots/MakieGallery.jl#13 is merged.

**Comment by daviehh** [comment]
@asinghvi17 thanks! can you give a more concrete example, e.g. an example for the figures above? not sure how to use `convert_arguments` to do the loop,

```
using Makie

fs = [sin, cos, sinc]
colors = [:red, :green, :blue]

xspan = 0:.01:2*pi
y = [fs[i](x) for x in xspan, i in 1:size(fs,1)]

scene = Scene()

for i in 1:size(fs,1)
    lines!(scene,xspan,y[:,i],color=colors[i])
end

scene
```

**Comment by asinghvi17** [comment]
You're right that it needs a recipe, I think I was thinking of the old `transform_arguments` (which no longer exists) when I said that.  Sorry!  

I'm not sure why exactly the recipe is failing, but I'll definitely look into it tomorrow.

**Comment by daviehh** [comment]
Right now, looks like it'll be simpler to define a new function, e.g.

```
using Makie
using AbstractPlotting
using Colors

function plot2d(x::AbstractRange,y::AbstractArray{<: AbstractFloat, 2};legend_desc=[], kwargs...)
    scene = Scene()
    ny = size(y,2)
    colors = distinguishable_colors(ny+1,[RGB(1,1,1)])[2:end]
    if size(legend_desc,1) != ny
        legend_desc = ["data $i" for i in 1:ny]
    end
    p=[]
    for i in 1:ny
            pli=lines!(scene, x, y[:,i], color = colors[i];kwargs...)
            push!(p,pli[end])
    end
    ls = legend(p, legend_desc, camera = campixel!, raw = true)

    # scene
    vbox(scene, ls)
end

plot2d(xspan, y, linewidth = 2)

# with user-supplied legend string 
plot2d(xspan, y, linewidth = 2, legend_desc = ["sin","cos","sinc"])
```

however, currently the legends are printed backwards, i.e. from the last column of y to the 1st. Maybe fixed when we have better documentation of `legend`: https://github.com/JuliaPlots/Makie.jl/issues/308

<img width="811" alt="screen shot 2019-03-04 at 5 28 17 pm" src="https://user-images.githubusercontent.com/25255906/53767163-e9399580-3ea2-11e9-94eb-69ce6eda3ec5.png">


<img width="811" alt="screen shot 2019-03-04 at 5 27 18 pm" src="https://user-images.githubusercontent.com/25255906/53767131-ce672100-3ea2-11e9-9686-22184c4fbfb0.png">

**Comment by asinghvi17** [comment]
Perhaps the `MultiplePlot` feature could be of use here?

**Comment by ffreyer** [comment]
Actually this has been implemented as `series`
