### ISSUE TITLE
clean up CompatHelper branches

### ISSUE THREAD

**Issue by visr** [MakieOrg/Makie.jl#3025]
Just like in GeoMakie this repo has thousands of branches, almost all by CompatHelper. I think these were created before https://github.com/MakieOrg/Makie.jl/issues/2619 was fixed.

In GeoMakie I started removing them with this code.

```bash
# Prune local references to remote branches that no longer exist
git fetch --prune

git branch -r | grep -o compathelper.* | while read -r branch; do
    git push origin --delete "$branch"
done

git fetch --prune
```

Running this locally took about 10s per branch, but from codespaces it is around 1s per branch, so after an hour it should be ready.

**Comment by SimonDanisch** [comment]
Thanks, great idea! I've run this and it worked well!
