### ISSUE TITLE
Interactive applications just "die"

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#304]
Hello, I am having troubles with the interactive applications I develop. They just "die" after a random amount of time of being used. Sometimes this random time span is a couple of seconds, sometimes minutes.

But they do "die". Here death means that the Makie window just closes. It dissappears. 

Notice that the data are not erased. If I call `display(scene)` on the window that magically close by itself then I recover the window in the exact state it was when it close.

Regardless this sudden closing is a huge problem and I have no clue how to troubleshoot it. Imagine being in a classroom and using `InteractiveChaos` and the windows close randomly. You can't do that. The same goes for producing videos.

---

To replicate the problem:

run _any_ of the example files of `InteractiveChaos`: https://github.com/JuliaDynamics/InteractiveChaos.jl/tree/master/examples and just play around with them for a while.

---

This happens on Windows 10, Julia 1.1.

**Comment by Datseris** [comment]
Suggestion:

```
screen = display(scene)

... do your thing untill it breaks

# after it broke, inspect:

screen.rendertask[]
```

**Comment by pbouffard** [comment]
FWIW I have occasionally seen this on macOS 10.14.3, Julia 1.1.0 as well.

**Comment by SimonDanisch** [comment]
Maybe related to #319 ?
