### ISSUE TITLE
WGLMakie plots "interleave" traces when updated chaotically

### ISSUE THREAD

**Issue by staticfloat** [MakieOrg/Makie.jl#3050]
- [X] are you running newest version (version from docs) ?
- [X] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [X] What platform + GPU are you on?

Reproducible on macOS and Linux.

### Issue description

When dragging sliders around crazily, one occasionally sees a flicker in the plots that can look like garbage.  Careful examination shows that it is two traces that have their vertex data interleaved with eachother.  [Here's a video](https://youtu.be/YHu-kcuIl4k) showing the problem, but a single screen grab I think gives the most information:

<img width="978" alt="Screenshot 2023-07-06 at 09 38 13" src="https://github.com/MakieOrg/Makie.jl/assets/130920/56cecdfa-4d6e-41ea-8137-3b3018508087">

Here you can clearly see that the y coordinates seem to be alternating between two different sinusoids one with a higher frequency and one with a lower frequency.  I believe this is because somehow data from one update (with frequency A) and data from another update (with frequency B) have somehow become "interleaved", and that is what is being displayed.  It is likely that the X coordinates suffer the same fate (as they're all part of the same update) but because those values are always the same, it doesn't matter much.

I briefly looked into logging the data being transferred, but I'm unsure what the best way to do this is; I imagine it is possible the issue is in Julia code, in Javascript code, or even is a race condition when updating the WGL buffers.  I'm open to suggestions on how to track this down.

### Code reproducer

```julia
using Revise
using WGLMakie, JSServe
using WGLMakie.Makie.StructArrays

function slider_test()
    fig = Figure()
    ax = Axis(fig[1, 1:2])

    # Create two sliders
    sg = SliderGrid(
        fig[2, 1],
        ((;label = name,range = LinRange(0, 2π, 50),) for name in ("frequency", "phase"))...,
    )
    sliderobservables = [s.value for s in sg.sliders]
    data = lift(sliderobservables...) do idxs...
        t = collect((0:99)/100)
        y = sin.(t .* (4*idxs[1] + 2π) .+ idxs[2])
        sleep(rand()*1.0)
        return StructArray{Point2{Float64}}((t, y))
    end

    lines!(ax, data)
    ylims!(ax, (-1, 1))
    fig
end

slider_test()
```

**Comment by SimonDanisch** [comment]
Fixed in #3113
