### ISSUE TITLE
Resize to width for embedded WGLMakie panels

### ISSUE THREAD

**Issue by kbarros** [MakieOrg/Makie.jl#3059]
With https://github.com/MakieOrg/Makie.jl/pull/3044, WGLMakie panels can automatically resize to fill an entire panel body. This behavior is opt-in, using
```julia
WGLMakie.activate!(;resize_to_body=true)
```

One common use-case will be embedded panels in VSCode. Here, it is not uncommon to have "tall, narrow" panels. In this case, it may not be desirable to have the WGLMakie panel expand to fill the entire vertical space. In general, I suspect most users will want to see their plots in something like a 1:1 aspect ratio, or similar.

Feature request: WGLMakie could use the minimum of `(body-width, body-height)` to determine the overall panel size. In case of "tall, narrow" panels, this would lead to empty vertical space below the plot. For inspiration, we could compare with the Plots.jl behavior (seems to use auto-resize via HTML/CSS, with a locked aspect ratio, and imposes a maximum image size).

Some previous discussion here: https://github.com/MakieOrg/Makie.jl/pull/3044#issuecomment-1629180047.

Also, once this is implemented, should `resize_to_body=true` be the default?

Any changes to auto-resizing will also need to be tested in Jupyter notebooks and similar, which tend to have "short, wide" panels.

**Comment by ffreyer** [comment]
@SimonDanisch Has this been added yet?

**Comment by SimonDanisch** [comment]
Yes in https://github.com/MakieOrg/Makie.jl/pull/4009
