### ISSUE TITLE
Wrong rendering of Polygon result from convert_single_argument

### ISSUE THREAD

**Issue by tobydriscoll** [MakieOrg/Makie.jl#3070]
I'm using Makie 0.19.6 and GLMakie 0.8.6 in a temp environment, on an M2 Mac in Ventura.

This code renders a square with a square hole, as expected:
```julia
using Makie, GLMakie

sq = Point2.(zip([-1,1,1,-1.],[-1,-1,1,1.]))
pol = Makie.Polygon(2sq, [sq])
poly(pol)
```
![foobar](https://github.com/MakieOrg/Makie.jl/assets/3577518/0d9a76c1-c307-45c3-b36c-f785055e1582)

This renders the same polygon, as expected:
```julia
struct Foo
    bar
end

foo = Foo(pol)
poly(foo.bar)
```
I expected this to do the same, but it renders a lone triangular patch:
```julia
Makie.convert_single_argument(foo::Foo) = foo.bar
poly(foo)
```
![foo](https://github.com/MakieOrg/Makie.jl/assets/3577518/e58949b7-8c30-4e08-b28a-9dd5d40f83f7)

**Comment by ffreyer** [comment]
You should probably use `convert_arguments(foo::Foo) = convert_arguments(foo.bar)`. `convert_single_argument` is for converting something like (xs, ys) separately.

**Comment by tobydriscoll** [comment]
Thanks for the tip, @ffreyer. But I am still confused. How am I supposed to convert the `foo` object into something that Makie wants to render? If I use
```julia
convert_arguments(foo::Foo) = (foo.bar,)
```
then I get a conversion failure error saying that "Makie needs to convert all plot input arguments to types that can be consumed by the backends (typically Arrays with Float32 elements)." But I don't know how to convert a `Polygon` object to an array of points. Makie does, of course, but I don't understand how I should access that.

To me the appeal of `convert_single_argument` is that it applies recursively. I would like to write recipes that convert an unknown type of thing to a known type and let Makie handle it from there. How is that accomplished?

**Comment by ffreyer** [comment]
Ah sorry, this should actually be
```julia
convert_arguments(PT::Type{<: Makie.Poly}, foo::Foo) = convert_arguments(PT, foo.bar)
```
the type is needed to decide between conversion pipelines of different plot types and the call to convert_arguments is for continuing with the usual conversion pipeline. 

> To me the appeal of convert_single_argument is that it applies recursively. I would like to write recipes that convert an unknown type of thing to a known type and let Makie handle it from there. How is that accomplished?

`convert_single_argument` is called from this block
https://github.com/MakieOrg/Makie.jl/blob/30687f022d3b06f99e4e7021a6c96b5ba8943392/src/conversions.jl#L40-L61

A plot call like `plot(a, b, c)` maps to a tuple `(a, b, c)` which gets passed to the `convert_arguments` pipeline. If it doesn't find a matching function it tries to call `convert_single_argument(plot_type_or_conversion_trait, a)` etc and then tries `convert_arguments` on the result again.

`convert_single_argument` already has an `Any` method
https://github.com/MakieOrg/Makie.jl/blob/30687f022d3b06f99e4e7021a6c96b5ba8943392/src/conversions.jl#L68
so you would probably need to implement your own version branching off of `convert_arguments(::Type{<: Poly}, args...)`.

**Comment by tobydriscoll** [comment]
Thanks for the help. I think I get it now...we'll see.
