### ISSUE TITLE
Changing the axis scale on contour plots breaks the alignment of the contour labels

### ISSUE THREAD

**Issue by AkchurinDA** [MakieOrg/Makie.jl#3081]
Changing the axis scale from `identity` to any other scale (e.g., `log10`, `log2`, etc.) breaks the alignment of labels on contour plots. Here is an MWE:
```julia
using CairoMakie

MeshSize = 100
xMesh = collect(10 .^ range(0, 3, MeshSize))
yMesh = collect(range(0, 10, MeshSize))
zMesh = [log10(x) * y for x in xMesh, y in yMesh]

begin
    F = Figure(resolution=72 .* (6, 6))
    A = Axis(F[1, 1],
        title="xscale=identity",
        xscale=identity,
        aspect=1, limits=(1, 1000, 0, 10))
    contour!(xMesh, yMesh, zMesh,
        labels=true, levels=0:1:30)
    F
end

begin
    F = Figure(resolution=72 .* (6, 6))
    A = Axis(F[1, 1],
        title="xscale=log10",
        xscale=log10,
        aspect=1, limits=(1, 1000, 0, 10))
    contour!(xMesh, yMesh, zMesh,
        labels=true, levels=0:1:30)
    F
end
```
The first contour plot with `xscale=identity` produces a contour plot with nicely aligned labels and the second plot with `xscale=log10` produces a contour plot with misaligned labels:
| `xscale=identity` | `xscale=log10` |
:-------------------------:|:-------------------------:
![scale-identity](https://github.com/MakieOrg/Makie.jl/assets/92001164/6f151b55-98aa-4978-a0b7-d48323aab9ff) | ![scale-log10](https://github.com/MakieOrg/Makie.jl/assets/92001164/effd11a1-72c7-49de-82b2-5b385ae94240)

**Comment by t-bltg** [comment]
Thanks for reporting, I'll have time to look for a fix in about 2 weeks.
