### ISSUE TITLE
custom `colorscale` support

### ISSUE THREAD

**Issue by t-bltg** [MakieOrg/Makie.jl#3088]
https://github.com/MakieOrg/Makie.jl/pull/2900 / https://github.com/MakieOrg/Makie.jl/pull/2493 which landed in `0.19.7` introduced some subtle bugs, ~~where it seems that the colorscale is applied multiple times in the pipeline (resulting in multiple values overlapping on the colorbar)~~.

EDIT: this is related to the inverse transform of custom `colorscale`s.

I still have to come up with an mwe, because my example is complicated.

![overlap](https://github.com/MakieOrg/Makie.jl/assets/13423344/c4e95345-b699-45b0-be37-a24e5d3a9d8d)

Currently observed on `CairoMakie` (other backends un-tested).

- [x] are you running newest version (version from docs) ?

**Comment by t-bltg** [comment]
Here is a mwe, occurs when using a custom colorscale:
```julia
using CairoMakie

main() = begin
  xs = range(0, 2π, length=100)
  ys = range(0, 2π, length=100)
  zs = [sin(x*y) for x ∈ xs, y ∈ ys]

  fig = Figure()
  ax = Axis(
    fig[1, 1];
    aspect=DataAspect(), xlabel="x", ylabel="y", ylabelrotation=0,
    xgridvisible=false, ygridvisible=false
  )
  hm = heatmap!(
    ax, xs, ys, zs; colorscale=x -> log10(1 + x)
  )
  Colorbar(fig[2, 1], hm; vertical=false, flipaxis=false)

  display(fig)
  save("colorscale.png", fig; px_per_unit=2)
  return
end

main()
```

**Comment by SimonDanisch** [comment]
I think we're re-using parts of the Axis infrastructure, so maybe this helps https://github.com/MakieOrg/Makie.jl/issues/3089?

**Comment by t-bltg** [comment]
Thanks for the reference.

I think the solution implemented in https://github.com/MakieOrg/Makie.jl/pull/3095 is more generic (works for axis scale, but also for colorscale) ?
