### ISSUE TITLE
[feature request] Polar axes in 2D

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#309]
I think this might be hard to implement, but polar axes would be really nice for some function visualizations.

**Comment by mkborregaard** [comment]
Isn't it just reinterpreting one of the axes as a radian?

**Comment by asinghvi17** [comment]
What I meant was making the axes themselves polar, like `proj = :polar` in Plots.  It's easy to implement a conversion from Cartesian to polar for the coordinates themselves, but the axis styling is another matter.  I'm not sure if it would work, but it'd go a long way to getting feature parity with `Plots`, and it is nice to have.

**Comment by asinghvi17** [comment]
so something like this (from Plots/GR examples):
![ref27](https://user-images.githubusercontent.com/32143268/53758824-d61bcb00-3e8c-11e9-95cf-dd4f6f3be808.png)

**Comment by ffreyer** [comment]
Added in #2990
