### ISSUE TITLE
a single point between two NaNs is not plotted

### ISSUE THREAD

**Issue by bjarthur** [MakieOrg/Makie.jl#3091]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?

`fig, ax, li = lines(1:5,[1,NaN,3,4,5], linewidth=10)` produces:

![foo](https://github.com/MakieOrg/Makie.jl/assets/1538268/9e1c7df2-a7da-4b65-81b1-5bc8d104c252)

in GLMakie, WGLMakie, and CairoMakie.  notice that (1,1) is not plotted.  it gets even worse with `fig, ax, li = lines(1:5,[1,NaN,3,NaN,5], linewidth=10)`:

![bar](https://github.com/MakieOrg/Makie.jl/assets/1538268/6ab1fc17-f834-4ceb-911f-4520ec8e9810)

nothing is plotted here!

i used a big linewidth to make sure it wasn't just so small i couldn't see it.

perhaps it's due to lines being butted vs rounded or squared?  if so, perhaps this is not a bug, but i don't see a way to set or get this in Makie.

the workaround is to plot points too, like `fig, ax, li = scatterlines(1:5,[1,NaN,3,4,5], linewidth=10)`:

![pooh](https://github.com/MakieOrg/Makie.jl/assets/1538268/686119d9-b13f-4ce0-9559-49607a9071b2)

```
julia> VERSION
v"1.9.2"

julia> Sys.MACHINE
"arm64-apple-darwin22.4.0"

(jl_KL1K4b) pkg> st
Status `/private/var/folders/s5/8d629n5d7nsf37f60_91wzr40000gq/T/jl_KL1K4b/Project.toml`
  [13f3f980] CairoMakie v0.10.7
  [e9467ef8] GLMakie v0.8.7
  [ee78f7c6] Makie v0.19.7
  [276b4fcb] WGLMakie v0.8.11
```

M2 GPU

**Comment by jkrumbiegel** [comment]
Hm what do other plotting packages do here? You can't draw a line between NaN and something, so to me this is completely logical behavior. So you're expecting something like a dot?

**Comment by bjarthur** [comment]
interesting.  gadfly, plots, and matplotlib all behave as makie here.  yet it seems unintuitive and inconvenient to me that a dot wouldn't be plotted.

in my case, i have experimental data for which some points are not available.  so setting them to `missing` i guess would be most accurate.  but that results in the same plotting outcome as `NaN`.  with `nothing` a large stacktrace of error messages is output.

i guess i would argue that i'm not trying to draw a line between NaN and something.  but rather, i have a line segment whose length is 0.  it starts and stops at the same point.  were a rounded instead of butted or bevelled line cap style used, a dot should be plotted.

**Comment by SimonDanisch** [comment]
> gadfly, plots, and matplotlib all behave as makie here.

If that's so, I think we should close this issue ;)
