### ISSUE TITLE
GLMakie crashes entire julia session when plotting after re-attaching in tmux

### ISSUE THREAD

**Issue by lassepe** [MakieOrg/Makie.jl#3092]
I frequently use GLMakie from within a remote tmux ssh session via x-forwarding. That generally works quite well; however, it does not survive re-attaching.

**Steps to reproduce:**

1. Connect to a ssh remote, e.g.,  `ssh <user@hostname>`
2. run `tmux` on the remote
3. Start a Julia REPL on the remote, run `using GLMakie; GLMakie.scatter([1]); GLMakie.closeall()`
4. Detach from the tmux session using `CTRL+b, d`
5. Disconnect from ssh client using `exit`
6. Re-connect to ssh client   `ssh <user@hostname>`
7. Re-attach to tmux session `tmux -u attach-session`
8. Generate another plot `scatter([1])`

Step 8 here fails reliably with
```
XIO:  fatal IO error 0 (Success) on X server "localhost:10.0"
      after 103 requests (103 known processed) with 0 events remaining.
```

I verified that the `DISPLAY` variable is set correctly upon re-attaching. I suspect, however, that maybe some socket is moved/re-created upon re-attaching which invalidates some GLMakie internal state? In fact, if I start a fresh Julia session and load GLMakie after re-attaching, things work as expected.

**Thoughts/Questions**

1. Ideally, GLMakie should be robust to this kind of re-attaching.
2. Even if GLMakie itself cannot recover, it would be desirable to not kill the REPL upon this error.
3. As a temporary workaround, is there some kind of "reset"-function that I can call to reset the internal state of GLMakie upon re-attaching? I tried just re-running `GLMakie.activate!()` but that doesn't seem to make a difference

**Comment by SimonDanisch** [comment]
Can you try `GLMakie.closeall()`?

**Comment by lassepe** [comment]
Thank you for your swift reply! :)

I did call `GLMakie.closeall() in step 3 above. I just tried again with invoking it also just before step 8. However, in both cases I see the same crash.

**Comment by SimonDanisch** [comment]
I honestly don't know what can be done from Makie's side then... Maybe google the error and see where others run into it?

**Comment by lassepe** [comment]
It seems like there was a very similar issue with R's Cairo library: https://github.com/s-u/Cairo/issues/27

There, they found a [workaround using the `XSetIOErrorHandler` ](https://github.com/s-u/Cairo/commit/df539fbd3fffa1d3ad5a9ea1e621d6358ad1a78b) so that at least the session doe snot crash. I am not sufficiently familiar with GLMakie internals to tell if such a workaround could also work around here.

**Comment by SimonDanisch** [comment]
Maybe you can try to create an MWE with just:
```julia
using GLFW
w = GLFW.Window()
```

**Comment by lassepe** [comment]
Indeed, with a plain GLFW window I see the same behavior. I'll migrate the issue over there.
