### ISSUE TITLE
mesh (and poly) includes missing points for axis limits

### ISSUE THREAD

**Issue by DanielVandH** [MakieOrg/Makie.jl#3112]
- [x] are you running newest version (version from docs) ? -- CairoMakie v0.10.7
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`) -- yes
- [x] What platform + GPU are you on? -- Windows 11, Intel(R) UHD Graphics 770 but not relevant here.

If you use `mesh` (and hence also `poly`), then points not included in the connectivity set are also used for computing the axis information. For example:

```julia
using CairoMakie
points = [Point2f(0.0, 0.0), Point2f(0.0, 1.0), Point2f(1.0, 1.0), Point2f(-10.0, -10.0), Point2f(10.0, 10.0)]
triangles = [1 2 3]
fig, ax, sc = mesh(points, triangles)
tightlimits!(ax)
fig
```

![image](https://github.com/MakieOrg/Makie.jl/assets/95613936/3c52bb85-6884-4ebb-bd4d-d30c77b66908)

`tightlimits!` did not put the axis onto $[0, 1]^2$ here as I would've hoped.

**Comment by SimonDanisch** [comment]
Ah, good point! We're just using the positions out of simplicity:
https://github.com/MakieOrg/Makie.jl/blob/master/src/layouting/data_limits.jl#L59C67-L59C67
Should be relatively easy to change that into a version that respects the faces

**Comment by SimonDanisch** [comment]
Hm, no it only comes with a vector of points and a vector of faces... If you need this in a recipe, you could also only overload `data_limits` for you recipe!

**Comment by ffreyer** [comment]
This seems like a wont-fix to me, for performance reasons. By iterating faces we would get random access into the positions arrays and access each position multiple times. Filtering out unused vertices would also be expensive. And for a normal, loaded mesh it should be just wasted time. (Somewhat related #2864)

I'd rather consider adding some utility to GeometryBasics to filter unused vertices. That way you can do that once, before plotting. Ref https://github.com/JuliaGeometry/GeometryBasics.jl/pull/173

**Comment by DanielVandH** [comment]
Given how the meshes are represented inside GeometryBasics, I would agree that fixing this is not worth the performance hit. I only noticed it at the time when dealing with `triplot`/`voronoiplot` since DelaunayTriangulation.jl does keep around some unused vertices. I think this could probably be closed.
