### ISSUE TITLE
Polar heatmap covers other plots

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#3116]
Running two examples from the docs in sequence:

```julia
using GLMakie

f = Figure()
ax = PolarAxis(f[1, 1])

# The first two arguments should be set to a sensible radial and angular range
zs = [r*cos(phi) for r in range(1, 2, length=100), phi in range(0, 4pi, length=100)]

p = surface!(ax, 0..10, 0..2pi, zs, shading = false, colormap = :coolwarm, colorrange=(-2, 2))
scatterlines!(ax, range(0, 1, length=100), range(0, 10pi, length=100), color = 1:100)
Colorbar(f[1, 2], p)
```
![image](https://github.com/MakieOrg/Makie.jl/assets/3345261/eed9990c-afb2-4209-8b17-0e0a492a2654)

Any chance that there is an easy fix for this? We are giving a short-course by the end of the month and would like to show off Makie.jl for the students.

**Comment by juliohm** [comment]
Thank you for clarifying the current behavior. I wonder if this should be considered a bug or not. As an end user I would expect that this z correction is performed automatically on the polar axis. Plots that are shown latter should appear on top of older plots.

**Comment by juliohm** [comment]
@ffreyer how would you adapt the example above with this `translate!` workaround?

**Comment by ffreyer** [comment]
`translate!(p, 0, 0, -maximum(zs))` or `sl = scatterliens!(...); translate!(sl, 0, 0, maximum(zs))` should do it
