### ISSUE TITLE
Missing docstring for Figure

### ISSUE THREAD

**Issue by ChrisRackauckas** [MakieOrg/Makie.jl#3118]
Mentioned in https://discourse.julialang.org/t/what-steps-should-the-julia-community-take-to-bring-julia-to-the-next-level-of-popularity/101389/318?u=chrisrackauckas

**Comment by SimonDanisch** [comment]
Yes, definitely something that needs a docstring! We will address this in https://github.com/MakieOrg/Makie.jl/issues/3105
