### ISSUE TITLE
center ticks in colorbar when colormap is categorical

### ISSUE THREAD

**Issue by lazarusA** [MakieOrg/Makie.jl#3119]
The current default for placing ticks on the colorbar is to space the values between the `min` and `max`, which is not ideal when the colormap is categorial. The following is a hardcoded solution that might be useful to have a more user friendly default for this case. 

```Julia
fig, ax, obj = heatmap(rand(1:3, 10, 15);
    colormap = cgrad([:black, :orange, :dodgerblue], 3, categorical=true))
cbar = Colorbar(fig[1,2], obj)
mn, mx, N = 1,3,3
δn = (mx - mn)/N
ticks_position = [mn + δn/2 + (i-1)*δn for i in 1:N]
cbar.ticks = (ticks_position, string.(mn:mx))
fig
```

**Comment by SimonDanisch** [comment]
Closed in https://github.com/MakieOrg/Makie.jl/pull/3090
