### ISSUE TITLE
Minor ticks for log-scale continue beyond axis

### ISSUE THREAD

**Issue by jqfeld** [MakieOrg/Makie.jl#3126]
- [x] are you running newest version (version from docs) ? Yes, Makie v0.19.7
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`) Yes.
- [x] What platform + GPU are you on? Linux, Kernel 6.4.7

When specifying xticks on a log-scale, the minor ticks continue beyond the limits of the axis and spill into the neighboring `Axis`.
MWE:
```julia
using GLMakie; GLMakie.activate!()
# using CairoMakie; CairoMakie.activate!() # Same problem with CairoMakie

f = Figure();
ax = Axis(f[1,1],
    xscale=log10,
    xminorticksvisible=true,
    xminorticks=IntervalsBetween(9),
    xticks=[1,10,100]
)
ax2 = Axis(f[1,2])
lines!(ax, 1..100, x -> exp(-x))
```
which results in the following graphic:
![mwe](https://github.com/MakieOrg/Makie.jl/assets/12704074/4fe0d293-b23b-46c8-8ab7-45b764d38d59)

**Comment by jqfeld** [comment]
Maybe it is helpful to know, that this problem only occurs when something is actually plotted into the `Axis`. If the last line in the MWE is commented out, the minor ticks do not spill out of the `Axis`.

**Comment by ffreyer** [comment]
This has been fixed. (Related: #2701)
