### ISSUE TITLE
Top of README is a bit crowded, logo is hard to read on dark mode

### ISSUE THREAD

**Issue by DanielVandH** [MakieOrg/Makie.jl#3156]
The top of the README is currently:

![48e5c9e94db63606d89e5c269df78022](https://github.com/MakieOrg/Makie.jl/assets/95613936/fccdd8a8-7ccc-4e30-b4ec-c50f1dece942)

Using a dark background, the Makie text is a bit hard to read. Maybe a white background/stroke on the text would help?

Also: The badges seem a bit crowded now in my opinion. I wonder if they could be put into a matrix form / split into rows? Maybe the socials could be put onto their own row to balance it out without taking so much horizontal space. Might need more room anyway if the twitter account https://twitter.com/makieplots is to be eventually moved as described in its description.

This is all just my opinion of course - could all be perfectly fine!

**Comment by DanielVandH** [comment]
I see actually that a dark mode version was added in #2899. I wonder why I'm not getting that version.

**Comment by jkrumbiegel** [comment]
Thought so, too, so I changed the alignment a bit, added a citation count badge and equalized the look of all the badges a bit. So I consider this issue closed :)
