### ISSUE TITLE
PolarAxis Grid Z-Order

### ISSUE THREAD

**Issue by daniel-frisch-kit** [MakieOrg/Makie.jl#3158]
- [x] are you running newest version (version from docs) ? → Makie v0.19.8
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on? → Ubuntu 22.04.2 LTS + GeForce GTX 1070

In `PolarAxis`, grid and minorgrid are shown in the foreground, while in the normal `Axis`, the grids are in background. I think the z-layering of `PolarAxis` should be changed to that of `Axis`. 

MWE: 
```
using CairoMakie
CairoMakie.activate!()
fig = Figure( resolution = (500,1000) )
layout = fig[1,1] = GridLayout()
pts = Circle( Point((.1,0)), .9 )

ax = PolarAxis(layout[1,1])
poly!( ax, pts, color = :yellow, strokecolor = :black, strokewidth = 1 )

ax = Axis(layout[2,1])
poly!( ax, pts, color = :yellow, strokecolor = :black, strokewidth = 1 )

fig
```

![image](https://github.com/MakieOrg/Makie.jl/assets/22419910/5597e73f-5a23-4e44-9d17-99c3d865484e)

**Comment by ffreyer** [comment]
I was wondering if this should be changed too. I'm a bit hesitant because we don't have tick lines in PolarAxis and because grid lines seem quite useful to judge curvature here. Maybe we should just add a toggle for it instead?
