### ISSUE TITLE
Bar Label Alignment

### ISSUE THREAD

**Issue by matthijscox** [MakieOrg/Makie.jl#3160]
### Feature description
Current you cannot change the alignment of the bar labels in the barplot. I noticed this when plotting 90 degree rotated bar labels, they do not align in the center of the bar anymore. 

I would either like to
* somehow automatically improve the bar label alignment for rotated labels
* make the bar label alignment a keyword argument option in the barplot

### For plot types, please add an image of how it should look like

Here's how to get non-centered rotated bar labels. You'll notice the label text is shifted to the left of the center of the bar.

```julia
using CairoMakie, Makie

tbl = (x = [1, 1, 1, 2, 2, 2, 3, 3, 3],
       height = 0.1:0.1:0.9,
       grp = [1, 2, 3, 1, 2, 3, 1, 2, 3],
       grp1 = [1, 2, 2, 1, 1, 2, 1, 1, 2],
       grp2 = [1, 1, 2, 1, 2, 1, 1, 2, 1]
       )

barplot(
        tbl.x, tbl.height,
        dodge = tbl.grp,
        color = tbl.grp,
        bar_labels = :y,
        label_rotation = π/2,
        label_offset = 15,
        axis = (xticks = (1:3, ["left", "middle", "right"]),),
    )
```

![RotatedBarLabels](https://github.com/MakieOrg/Makie.jl/assets/17245881/4d459462-c3ef-400d-9cad-63278214c0ae)

(I also noticed that the ylimit is not ideal by default, the 0.9 label falls outside the axis, but that I can change manually)

I think we can fix this if we can change the `label_aligns` ourselves, which seems to be generated automatically right now.

```
barplot(
        tbl.x, tbl.height,
        dodge = tbl.grp,
        color = tbl.grp,
        bar_labels = :y,
        label_rotation = π/2,
        label_offset = 15,
        axis = (xticks = (1:3, ["left", "middle", "right"]),),
        label_aligns = (:left, :center), # this would probably fix the misalignment
    )
```

**Comment by ffreyer** [comment]
> I would either like to
>  * somehow automatically improve the bar label alignment for rotated labels
>  * make the bar label alignment a keyword argument option in the barplot

It should be relatively easy to get both. Add a `label_align` attribute either with `automatic` as the default value, or one derived from `label_rotation` in 
https://github.com/MakieOrg/Makie.jl/blob/09036c93a2dc33ab8b806d9afbea99647bbc3695/src/basic_recipes/barplot.jl#L47-L85
and adjust the `text_attributes` function to work with those labels. Offset probably needs the same treatment. For the default align you can take inspiration from PolarAxis:
https://github.com/MakieOrg/Makie.jl/blob/09036c93a2dc33ab8b806d9afbea99647bbc3695/src/makielayout/blocks/polaraxis.jl#L258-L262
(just drop theta_0 and dir and swap out rtickangle for label_rotation)

**Comment by jkrumbiegel** [comment]
LinearAxis also has default tick align logic, we should compare ;)

**Comment by matthijscox** [comment]
I think I found the LineAxis code for calculating the tick label align. 

Although I wonder why there is a "real" tick label align and an unreal version? :)

https://github.com/MakieOrg/Makie.jl/blob/280421b14f43ab5451c1e70136a887f6df37a7b4/src/makielayout/lineaxis.jl#L91-L130

However, in the tick label alignment example above, we use symbols, but in the barplot label alignment we use numerical values. Can I assume `0 = :left, 0.5 = :center, 1.0 = :right` for horizontal align and  `0 = :top, 0.5 = :center, 1.0 = :bottom` for vertical alignment?

https://github.com/MakieOrg/Makie.jl/blob/09036c93a2dc33ab8b806d9afbea99647bbc3695/src/basic_recipes/barplot.jl#L182-L191

**Comment by ffreyer** [comment]
`Vec2f(0, 0)` is bottom left, `Vec2f(1, 1)` is top right. You can play around with something like
```julia
align = Observable(Vec2f(0, 0))
f, a, p = text("Hello", align = align)
```
to check that.

I wonder if it would make sense to add a angle to Vec2f conversion for text align... 
```julia
f = Figure()
angle = Slider(f[1,1], range = range(0, 2pi, 360)).value
align = map(angle) do angle
    s, c = sincos(angle) 
    scale = 1 / max(abs(s), abs(c)) 
    Point2f(0.5 - 0.5scale * c, 0.5 - 0.5scale * s) 
end 
a, p = text(f[2, 1], "Hello", align = align)
f
```
Or is that too niche/unclear?

**Comment by matthijscox** [comment]
Seems good to me now [in my fork](https://github.com/matthijscox/Makie.jl/tree/bar_label_alignment). Trying to see now how to add a reference test and will create a PR.

## Before (Makie v0.19.8)
![makie_label_rotations_before](https://github.com/MakieOrg/Makie.jl/assets/17245881/2c05dfbe-02c2-4262-ab64-e708e9ae3069)

## After (hopefully Makie v.19.9)
![makie_label_rotations_after](https://github.com/MakieOrg/Makie.jl/assets/17245881/2d3a07fc-93fb-406b-a830-9b0abcaf8883)

**Comment by jkrumbiegel** [comment]
Nice, although the inward flipped, diagonally rotated once seem to still align at lower left corner (unrotated) but probably should align at lower right. That's like the difference of having the y axis at the left or right side.

**Comment by jkrumbiegel** [comment]
yeah in principle that should work, you have to map the horizontal/vertical thing to the bar plots though because a horizontal axis is one where the ticks are vertical, so it corresponds to the vertical bar plot case

**Comment by jkrumbiegel** [comment]
there is also a symbol to vec2f function somewhere I think

**Comment by matthijscox** [comment]
Here's when I tried to manually replace the symbols with numbers. I feel I will have to fiddle with quite some 0.5 offsets everywhere.
![makie_label_rotations_manual_rotations](https://github.com/MakieOrg/Makie.jl/assets/17245881/aa9fbb95-d780-4e52-9a2c-d316095682aa)

```julia
function calculate_bar_label_align(al, hor::Bool, fl::Bool, rot::Number)
    if al isa Automatic
        if rot == 0 || !(rot isa Real)
            if hor
                (0.5, fl ? 0.0 : 1.0)
            else
                (fl ? 0.0 : 1.0, 0.5)
            end
        elseif rot ≈ pi/2
            if hor
                (fl ? 0.0 : 1.0, 0.0)
            else
                (0.5, fl ? 1.0 : 0.0)
            end
        elseif rot ≈ -pi/2
            if hor
                (fl ? 1.0 : 0.0, 0.5)
            else
                (0.5, fl ? 0.0 : 1.0)
            end
        elseif rot > 0
            if hor
                (fl ? 0.0 : 1.0, fl ? 0.0 : 1.0)
            else
                (fl ? 0.0 : 1.0, 0.5)
            end
        elseif rot < 0
            if hor
                (fl ? 1.0 : 0.0, fl ? 0.0 : 1.0)
            else
                (fl ? 0.0 : 1.0, 0.5)
            end
        end
    elseif al isa NTuple{2, <:Number} || al isa Vec2f || al isa Point2f
        return al
    else
        error("Align needs to be a NTuple{2, Number} or Vec2f.")
    end
end
```

**Comment by matthijscox** [comment]
Here's that same plot with the previous rotation code:
![plot_51](https://github.com/MakieOrg/Makie.jl/assets/17245881/ba02c928-02f5-434d-9b5b-c06d2822c3d0)

```julia
    function calculate_align(angle, in_y_direction::Bool, flip::Bool)
        if flip
            angle += π
        end
        if !in_y_direction
            angle += π/2
        end
        s, c = sincos(angle)
        scale = 1 / max(abs(s), abs(c))
        # (0.5, 0.0) for angle = 0, (0.0, 0.5) for angle = π/2
        align = Point2f(0.5 - 0.5scale * s, 0.5 - 0.5scale * c)
        return align
    end
```
