### ISSUE TITLE
regression in colormaps/colorbars from custom recipes in 0.19.7 (was fine on 0.19.6)

### ISSUE THREAD

**Issue by Krastanov** [MakieOrg/Makie.jl#3161]
This was found because the building of the documentation of `QuantumClifford.jl` started throwing errors.

The following works fine on 0.19.6, but breaks on 0.19.7 and newer:

```
using CairoMakie

Makie.@recipe(
function (scene)
    Makie.Theme(;
        colormap = Makie.cgrad([:lightgray,Makie.RGB(0x1b9e77),Makie.RGB(0xd95f02),Makie.RGB(0x7570b3)], 4, categorical = true),
        colorrange = (-0.5, 3.5)
    )
end,
StabilizerPlot,
stabilizer
)

function Makie.plot!(myplot::StabilizerPlot)
    s = myplot[:stabilizer][]
    Makie.heatmap!(myplot, s;
        colorrange = (0, 3),
        colormap=myplot.colormap
    )
    myplot
end

f = Figure()
ax, p = stabilizerplot(f[1,1],rand(10,10))
Colorbar(f[1, 2], p)
f
```

On recent versions of Makie it gives

```
ERROR: KeyError: key :colorscale not found
Stacktrace:
 [1] getindex(h::Dict{Symbol, Observable}, key::Symbol)
   @ Base ./dict.jl:484
 [2] getindex
   @ ~/.julia/packages/MakieCore/bttjb/src/attributes.jl:89 [inlined]
 [3] getindex(x::Combined{stabilizerplot, Tuple{Matrix{Float64}}}, key::Symbol)
   @ MakieCore ~/.julia/packages/MakieCore/bttjb/src/attributes.jl:185
 [4] getproperty
   @ ~/.julia/packages/MakieCore/bttjb/src/attributes.jl:76 [inlined]
 [5] Colorbar(fig_or_scene::GridPosition, plot::Combined{stabilizerplot, Tuple{Matrix{Float64}}}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Makie ~/.julia/packages/Makie/uAmck/src/makielayout/blocks/colorbar.jl:36
 [6] Colorbar(fig_or_scene::GridPosition, plot::Combined{stabilizerplot, Tuple{Matrix{Float64}}})
   @ Makie ~/.julia/packages/Makie/uAmck/src/makielayout/blocks/colorbar.jl:28
 [7] top-level scope
   @ REPL[7]:1
```

Fixed by modifying the recipe as:

```
function Makie.plot!(myplot::StabilizerPlot)
    s = myplot[:stabilizer][]
    hm = Makie.heatmap!(myplot, s;
        colorrange = (0, 3),
        colormap=myplot.colormap
    )
    for k in [:colorscale, :highclip, :lowclip]   # NEW LINE
        myplot[k] = hm[k]                         # NEW LINE
    end                                           # NEW LINE
    myplot
end
```

## Is this considered a regression in Makie or is this my fault?

- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
```
julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × AMD Ryzen 9 7950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 32 on 32 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
```

**Comment by SimonDanisch** [comment]
Wanted to fix this in https://github.com/MakieOrg/Makie.jl/pull/3090, but got hold up by higher priorities...

**Comment by jkrumbiegel** [comment]
> Is there a "Colorbar" API that I can make sure to obey so this does not happen in the future

I think this change was a step towards such an "API" by consolidating how color lookups work across recipes. Due to Hyrums law it's always likely that somebody somewhere depends on the specific implementation details, which is always unfortunate, but even more likely in Makie because the surface area is huge. These APIs have proven to be relatively difficult to predict because we don't know all the use cases in advance, so we sometimes have to gather experience how something works for a while before we can make it better.

**Comment by Krastanov** [comment]
I think it makes sense for me to close this issue then as me relying on internal details. Looking forward to the clearer error message from the linked pull request.
