### ISSUE TITLE
How to plot a heatmap with categorical variables

### ISSUE THREAD

**Issue by sleak75** [MakieOrg/Makie.jl#3169]
I'm trying to plot a heatmap of two categorical variables - after searching here I've simplified my example to the one in <https://github.com/JuliaPlots/AbstractPlotting.jl/pull/213>:

```
x = ["a", "b", "c"]
y = ["α", "β", "γ"]
heatmap(x, y, rand(3, 3)) 
```
And I'm getting errors like:
```
`Makie.convert_arguments` for the plot type Heatmap{Tuple{Vector{String}, Vector{String}, Matrix{Float64}}} and its conversion trait DiscreteSurface() was unsuccessful.

The signature that could not be converted was:
::Vector{String}, ::Vector{String}, ::Matrix{Float32}

Makie needs to convert all plot input arguments to types that can be consumed by the backends (typically Arrays with Float32 elements).
You can define a method for `Makie.convert_arguments` (a type recipe) for these types or their supertypes to make this set of arguments convertible (See http://docs.makie.org/stable/documentation/recipes/index.html).

Alternatively, you can define `Makie.convert_single_argument` for single arguments which have types that are unknown to Makie but which can be converted to known types and fed back to the conversion pipeline.
```
Converting `rand(3,3)` to `Float64.(rand(3,3))` didn't change anything.

What am I missing?

**Comment by bertulli** [comment]
I seem to have problems too. Maybe something broke in a recent commit?
I'm on
```
[ee78f7c6] Makie v0.19.8
[13f3f980] CairoMakie v0.10.8
```

**Comment by SimonDanisch** [comment]
this never worked😅 I think beautiful.makie.org should have some example to do this until #1347 is merged!

**Comment by SimonDanisch** [comment]
https://beautiful.makie.org/dev/examples/generated/2d/heatmaps/text_heatmap
Since it's a well known issue that categorical variables dont work right now, I'm closing this issue!
