### ISSUE TITLE
Auto limits broken with recipes on 0.19.7 and 0.19.8

### ISSUE THREAD

**Issue by palday** [MakieOrg/Makie.jl#3176]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on? Linux x86-64, nVidia, but running CairoMakie

<details><summary>version info</summary>

```julia
julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 4 on 16 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

</details>

<details><summary>MWE</summary>

Developed when diagnosing a PR in [MixedModelsMakie](https://github.com/palday/MixedModelsMakie.jl/pull/77)

```julia
using CairoMakie, Random

@recipe(CoefPlot, n) do scene
    return Attributes()
end

function Makie.plot!(ax::Axis, P::Type{<:CoefPlot}, allattrs::Makie.Attributes, n)
    plot = Makie.plot!(ax.scene, P, allattrs, n)

    if haskey(allattrs, :title)
        ax.title = allattrs.title[]
    end
    if haskey(allattrs, :xlabel)
        ax.xlabel = allattrs.xlabel[]
    else
        ax.xlabel = "Estimate and 95% confidence interval"
    end
    if haskey(allattrs, :ylabel)
        ax.ylabel = allattrs.ylabel[]
    end
    reset_limits!(ax)
    ax.yticks = 1:n
    ylims!(ax, 0, n + 1)
    return plot
end

function Makie.plot!(plot::CoefPlot{Tuple{Int}})
    n = plot[1][]
    xs = rand(MersenneTwister(42), n)
    ys = collect(1:n)
    se = 0.1
    scatter!(plot, xs, ys)
    errorbars!(plot, xs, ys, se, se; direction=:x)

    return plot
end

f = Figure()
ax = Axis(f[1,1])
coefplot!(ax, 2)
display(f)

```

</details>

<details><summary>Makie 0.19.8</summary>

![makie0 19 8](https://github.com/MakieOrg/Makie.jl/assets/1677783/e169b9dd-44b8-42d7-a4c6-13efb3d65327)

</details>

<details><summary>Makie 0.19.7</summary>

![makie0 19 7](https://github.com/MakieOrg/Makie.jl/assets/1677783/a09a7291-a0a8-49c4-b2ec-eb37ebaaf2d0)

</details>

<details><summary>Makie 0.19.6</summary>

![makie0 19 6](https://github.com/MakieOrg/Makie.jl/assets/1677783/9c7aa6d5-41c7-4515-bbae-f4a5059a7d2f)

</details>

Bisected to [#8ccb6bdd](https://github.com/MakieOrg/Makie.jl/commit/8ccb6bdd)

Possibly related to #3051

I am unable to replicate this when calling `scatter!` and `errorbars!` directly -- it seems to be some interaction with the recipe system.

**Comment by jkrumbiegel** [comment]
Hm this must be because the limits for some reason started to include the "whisker" linesegments at the ends of the errorbars, but only if this plot type is not top-level but nested in another recipe. So then it sets the limits way too large

**Comment by palday** [comment]
@jkrumbiegel why the asymmetry in the overlarge limits? (xmax is far more inappropriate than xmin)

**Comment by jkrumbiegel** [comment]
I think so, if it does what I think it does, it looks at the `space = :pixel` values and those would all be positive

**Comment by ffreyer** [comment]
The pr changed whiskers to be plotted in `space = :pixel` instead of `space = :data`, so it's probably the case that they were never ignored and neither is `space = :pixel`

**Comment by palday** [comment]
attempt at a fix in #3179, which does indeed fix the MWE here

**Comment by palday** [comment]
@ffreyer FYI I noticed that calling `vlines!` within a recipe also completely kills the axis limits

**Comment by ffreyer** [comment]
In that case `h/vspan!` probably has issues to.

For `h/vlines!` the behavior runs through the `x/yautolimits` attribute which is probably one checked on top level plots in Axis.
https://github.com/MakieOrg/Makie.jl/blob/b9f25b912f3a03dd63dc8074236f12e34e86466b/src/basic_recipes/hvlines.jl#L11-L19
For axis limits to not freak out these plots need to ignore one dimension, rather than the limits of one of the subplots. I'm not sure if there is a way to do this other than the autolimit attributes. Maybe with NaN in the data_limits Rect?

**Comment by jkrumbiegel** [comment]
> not sure if there is a way to do this other than the autolimit attributes

I don't really think so, I did want to change that at some point. Either NaN or maybe `Union{Nothing,` for each dimension?

**Comment by palday** [comment]
Could we go ahead and get a patch release with this fix? It would make teaching this week easier :heart:

**Comment by SimonDanisch** [comment]
Sorry, I really wanted to get https://github.com/MakieOrg/Makie.jl/pull/3090 into the next release, but I guess I should just tag a new release and make a new one once #3090 is ready.
Release should be ready as soon as the backends are tagged: https://github.com/MakieOrg/Makie.jl/commit/eda228a375eb9f0fd3c0e3028d59670df014f764

**Comment by palday** [comment]
@SimonDanisch thanks!

And yeah, we're not going to run out of release numbers, so release early, release often. 🚀

**Comment by palday** [comment]
@SimonDanisch @ffreyer This seems to be back in 0.20.x at least with `vlines!`

**Comment by ffreyer** [comment]
0.20.2 had some more fixes for vlines etc. If you're not on 0.20.2+ try updating

**Comment by palday** [comment]
On latest (0.20.3). :cry: Notably, this problem now occurs in the `plot!(::MyPlotType)` method and not the `plot!(::Axis, ...)` method because I was trying to work around #3514
