### ISSUE TITLE
Add option to switch argument order for plotting in `PolarAxis` (and make the swapped version default)

### ISSUE THREAD

**Issue by SuperGrobi** [MakieOrg/Makie.jl#3178]
The new `PolarAxis` currently assumes the arguments of the plot command to be ordered as `r, theta`, identifying the cartesian `x` axis with the radius and the `y` axis with the angle. Event though cartesian coordinates are usually specified in this order, many other plotting libraries take the arguments the other way around:

- https://matplotlib.org/stable/gallery/pie_and_polar_charts/polar_demo.html#polar-plot
- https://pgfplots.net/polar-axes/
- https://ggplot2.tidyverse.org/reference/coord_polar.html

apart from feeling more natural, swapping the order to `theta, r` should make the currently (partly) broken recipe `stairs` work as intended and allow for `hist` to be used without explicitly setting the `direction=:x`:

```
using GLMakie
f = Figure()
ax1 = PolarAxis(f[1, 1])
ax2 = PolarAxis(f[1, 2])

xs = LinRange(0, 2pi, 10)
ys = rand(10)
stairs!(ax1, ys, xs, step=:center)
scatter!(ax1, ys, xs)
hist!(ax2, 2pi .* rand(300), direction = :x, strokewidth = 1, bins = range(0, 2pi, length=37))
f
```

If we (as suggested by @ffreyer on slack) add an option `iso_order=false` which swaps the order, the above code could become:
```
using GLMakie
f = Figure()
ax1 = PolarAxis(f[1, 1], iso_order=false)
ax2 = PolarAxis(f[1, 2], iso_order=false)

xs = LinRange(0, 2pi, 10)
ys = rand(10)
stairs!(ax1, xs, ys, step=:center)
scatter!(ax1, xs, ys)
hist!(ax2, 2pi .* rand(300), strokewidth = 1, bins = range(0, 2pi, length=37))
f
```

in addition, we should make `iso_order=false` the default, to be compliant with the way other large plotting packages are handling things.

(I am not 100% sure on the naming of that option. GIven that `hist` uses `direction=:x` rather than something like `vertical=false`, maybe calling the option `theta=:x` (similar to ggplot) might be more in line with the general conventions?)

**Comment by t-bltg** [comment]
Conventions across the julia ecosystem.

$(\theta, r)$ order:

- `Plots`: https://docs.juliaplots.org/stable/gallery/gr/generated/gr-ref027/#gr_ref027
- `UnicodePlots`: https://github.com/JuliaPlots/UnicodePlots.jl/blob/bd10d0714bf9e04d1dd7b021c23661add24c353a/src/interface/polarplot.jl#L9
