### ISSUE TITLE
Increase resolution of `CairoMakie` preview in VSCode plot pane.

### ISSUE THREAD

**Issue by SuperGrobi** [MakieOrg/Makie.jl#3187]
I am building plots intended to be put into an A4 document intended for publication using `CairoMakie` as the backend. Following the documentation on [physical size](https://docs.makie.org/stable/documentation/figure_size/), I set up and save my figure as:
```
size_inches = (4, 3)
size_pt = 72 .* size_inches
f = Figure(resolution = size_pt)
save("mypath.pdf", f, pt_per_unit=1)
```
which works great and does exactly what I want, but the final value of `size_pt=(288, 216)` makes the preview of the plot in VSCode basically unusable for developing the figure.

When saving a figure, this line gets hit ([here](https://github.com/MakieOrg/Makie.jl/blob/b9f25b912f3a03dd63dc8074236f12e34e86466b/src/display.jl#L324)):
```
screen = getscreen(backend, scene, io, mime; visible=visible, screen_config...)
```
where `screen_config` contains the `*_per_unit` keywords. When displaying in vscode, we hit
[this line:](https://github.com/MakieOrg/Makie.jl/blob/b9f25b912f3a03dd63dc8074236f12e34e86466b/src/display.jl#L247)
```
screen = getscreen(backend, scene, io, m; visible=false)
```
where no resolution was passed in. I managed to hack around this problem by overwriting the relevant show function:
```julia
function Base.show(io::IO, m::MIME, figlike::Makie.FigureLike)
    if Makie.ALWAYS_INLINE_PLOTS[] == false && m isa Makie.MIME_TO_TRICK_VSCODE
        # We use this mime to display the figure in a window here.
        # See declaration of MIME_TO_TRICK_VSCODE for more info
        display(figlike)
        return () # this is a diagnostic vscode mime, so we can just return nothing
    end
    scene = Makie.get_scene(figlike)
    backend = Makie.current_backend()
    # get current screen the scene is already displayed on, or create a new screen
    Makie.update_state_before_display!(figlike)

    # this is new
    ppu = if hasproperty(Makie.current_default_theme(), :preview_px_per_unit)
        getproperty(Makie.current_default_theme(), :preview_px_per_unit)[]
    else
        1.0
    end

    screen = Makie.getscreen(backend, scene, io, m; visible=false, px_per_unit=ppu)
    Makie.backend_show(screen, io, m, scene)
    return screen
end
```
and putting `preview_px_per_unit` into the default theme:
```
set_theme!(preview_px_per_unit=5.0)
```
which changes the result from this:
![image](https://github.com/MakieOrg/Makie.jl/assets/49985053/cf7aad8d-669e-4025-84fe-d609e8132462)
to this:
![image](https://github.com/MakieOrg/Makie.jl/assets/49985053/45f10a45-544e-4316-b16f-6ab1efe3682d)
Which is way better.

Having an option to set the preview resolution of the plot without having to change the actual `resolution` of the figure would make the workflow of developing figures a lot smoother.
What would be the clean way to implement this feature?

**Comment by SuperGrobi** [comment]
Oh dang. I kind of tried that, but only within my custom theme:
```julia
    with_theme(CairoMakie=(px_per_unit = 5.0,)) do
        f = Figure(resolution=72 .* (4, 3))
        ax = Axis(f[1, 1])
        scatter!(ax, rand(100))
        f
    end
```
which did (now that you say it) of course not work, as the preview rendering happens outside the `with_theme`...

But hey. I once again learned something about the display system and the Makie internals. This is all very clever.

**Comment by albertomercurio** [comment]
Hello, I think I have the same problem even with @SimonDanisch suggestion.

<img width="1470" height="923" alt="Image" src="https://github.com/user-attachments/assets/b9b0c4a1-247c-448e-94a8-84e4271903cc" />

Am I doing something wrong?

**Comment by asinghvi17** [comment]
The way to do it is `CairoMakie.activate!(; px_per_unit = 5)`, or similarly for e.g. GLMakie.

**Comment by albertomercurio** [comment]
The quality changes, but not the size of the figure in VSCode plot.

<img width="1470" height="923" alt="Image" src="https://github.com/user-attachments/assets/fd2844ab-705b-40ab-add5-df8b550d60dc" />

**Comment by jkrumbiegel** [comment]
The size of the figure is the correct one irrespective of the pixel density. If you want to have the image take more space if it has higher pixel density then you have to turn the html mode off which embeds the image in a size-preserving context and enable only png. You can do that via `CairoMakie.enable_only_mime!("png")`

**Comment by albertomercurio** [comment]
Perfect, thank you!
