### ISSUE TITLE
World age problem when running example "Orbit Program"

### ISSUE THREAD

**Issue by ChenNingCong** [MakieOrg/Makie.jl#319]
When I try this orbit program example in the document[https://simondanisch.github.io/ReferenceImages/gallery//orbit_diagram/index.html](url),Julia produces a window,but when i try to drag the slider,I get this error:
`The applicable method may be too new: running in world age 35127, while current world is 35130.
Closest candidates are:
  #8(::Any) at REPL[11]:2 (method too new to be called from this world context.)
....`
I run the code in REPL and here is my versionInfo:
```Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
I use a compiled Makie,but I don't change my system image,it gives the same error when i don't load the compiled image.
After change this code in the orbit program,the program works:
```
r1r2 = async_latest(lift(tuple, r1node, r2node))
#change to r1r2 = lift(tuple, r1node, r2node)
```
remove the async_latest.
So I wonder what is the use of this function async_lastest?

**Comment by asinghvi17** [comment]
Can confirm, having the same issue here.  `async_latest`, as far as I know, reduces computation overhead by stopping computation if a new Signal is sent through the slider.
