### ISSUE TITLE
Improved line pattern support in WGLMakie

### ISSUE THREAD

**Issue by staticfloat** [MakieOrg/Makie.jl#3199]
### Feature description

It would be great to get the last checkbox of https://github.com/MakieOrg/Makie.jl/pull/3062 finished, to bring WGLMakie up to par with the other backends with respect to line styles.  In particular, dashed and dotted lines in WGLMakie would be useful for us.

I'm opening this issue to track this last work item as #3062 was merged without it being completed.

**Comment by ffreyer** [comment]
Closed by #3558 via #3650 in 0.21
