### ISSUE TITLE
Precompilation fails

### ISSUE THREAD

**Issue by theplatters** [MakieOrg/Makie.jl#3203]
Platform: GNU/Linux 6.4.12-arch1-1 EndeavourOS GPU: AMD ATI 04:00.0 

Error Message:
[18740] signal (11.1): Speicherzugriffsfehler
in expression starting at /home/franzs/.julia/packages/GLMakie/toRaR/src/precompiles.jl:13
Allocations: 29413652 (Pool: 29400602; Big: 13050); GC: 41

**Comment by theplatters** [comment]
`using GLFW; GLFW.Window()` works fine.

Maybe this is also of use (when updating the packages)

```
failed process: Process(setenv(`/usr/bin/lld -flavor gnu '' -shared -o /home/franzs/.julia/compiled/v1.9/BeyondHulten
/jl_NzRIko --whole-archive /home/franzs/.julia/compiled/v1.9/BeyondHulten/jl_GrtxkY --no-whole-archive -L/usr/lib -L/usr/lib/julia -L/usr/lib -ljulia -ljulia-internal`,["LD_LIBRARY_PATH=/usr/lib/julia:/usr/lib", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "JULIA_IMAGE_THREADS=1", 
"XDG_SESSION_TYPE=wayland", "SYSTEMD_EXEC_PID=2935", "USER=franzs", "XDG_CONFIG_DIRS=/home/franzs/.config/kdedefaults:/etc/xdg", "LC_NUMERIC=de_AT.UTF-8", "JULIA_EDITOR=code", "LC_MEASUREMENT=de_AT.UTF-8"  … 
"TERM_PROGRAM=vscode", "VSCODE_GIT_ASKPASS_MAIN=/usr/lib/code/extensions/git/dist/askpass-main.js", "XKB_DEFAULT_LAYOUT=at", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0", "MAIL=/var/spool/mail/franzs", "ORIGINAL_XDG_CURRENT_DESKTOP=KDE", "LC_NAME=de_AT.UTF-8", "XDG_SESSION_ID=2", "JOURNAL_STREAM=8:36078", "LC_IDENTIFICATION=de_AT.UTF-8"]), ProcessExited(1)) [1]
```

**Comment by SimonDanisch** [comment]
No idea... With a platform like:

> GNU/Linux 6.4.12-arch1-1 EndeavourOS GPU: AMD ATI 04:00.0

You're pretty much on your own with such low level OS/Julia problems...
You can also try to narrow it down further by disabling the precompile workload in your active Pkg environment:
```julia
# Disable precompilation for Makie & all backends
using Preferences
for uuid in ["ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a", "e9467ef8-e4e7-5192-8a1a-b1aee30e663a",
             "276b4fcb-3e11-5398-bf8b-a0c2d153d008", "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"]
    set_preferences!(Base.UUID(uuid), "precompile_workload" => false; force=true)
end
```

**Comment by chakravala** [comment]
Having the same issue on arch linux as well

**Comment by chakravala** [comment]
Looks like downgrading to `mesa-23.2.0-1-x86_64` fixes it for me @theplatters : https://archive.archlinux.org/packages/m/mesa/

**Comment by chakravala** [comment]
I've started an on going discussion reporting the mesa bug for arch linux users: https://bugs.archlinux.org/task/79626

**Comment by chakravala** [comment]
Conclusion @SimonDanisch @theplatters : the arch linux package for the `mesa` driver is now compiled with LLVM16 which seems to be the culprit for the breakage. It's still possible to use the `mesa-1:23.1.6-1` release or earlier, as well as the `mesa-23.2.0` release in the package archive for arch linux. Not sure yet how this will be resolved for future releases ...
