### ISSUE TITLE
Race condition in GLMakie / surface

### ISSUE THREAD

**Issue by pascalr0410** [MakieOrg/Makie.jl#3215]
Hello,

I try to run de folowing code with GLMakie :
```
surface(xs, ys, zConso, colormap=(:rainbow), axis=(type=Axis3, xticks =axeMois ,ylabel = "Heures", xlabel = "Mois", yticks = axeHeures, zlabel = "kWh"))
surface!(zArenh, colormap=(:reds))
surface!(zCapa, colormap=(:sun))
surface!(zZero, colormap=(:greys))

```
When I run the four lines at the same time no error but nothing apen : Makie window does not apear

WHen I run the first, wait for Makie window to apear then run the last three one, it's works like a charm.

It seem to be a race condition, surface() seem to exit before then window was ready and the next surface!() call break someting in the process in charge of drawing the result

**Comment by SimonDanisch** [comment]
only the first returns a figure, after that it mutates the figure...
The figure object is the one that overloads show etc, so only running the first one in the repl will actually open a window...
You can do:
```julia
figure, axis, surfplot_obj = surface(xs, ys, zConso, colormap=(:rainbow), axis=(type=Axis3, xticks =axeMois ,ylabel = "Heures", xlabel = "Mois", yticks = axeHeures, zlabel = "kWh"))
surface!(zArenh, colormap=(:reds))
surface!(zCapa, colormap=(:sun))
surface!(zZero, colormap=(:greys))
figure
```

**Comment by pascalr0410** [comment]
It works fine, thank's a lot !
