### ISSUE TITLE
calculus plots with Makie needs updating

### ISSUE THREAD

**Issue by waywardpidgeon** [MakieOrg/Makie.jl#3219]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [ ] What platform + GPU are you on?

AbstractPlotting is a deprecated package so I didn't load it.
Quite a few features in the introductory article on Makie for calculus need updating, e.g. lines! doesn't work and scene has no field data_lims.

I have running Julia 1.9.3 on Windows using GLMakie backend. The GPU is Intel (R) UDH Graphics 630.

**Comment by SimonDanisch** [comment]
Where? There surely is no `AbstractPlotting` in docs.makie.org...

**Comment by waywardpidgeon** [comment]
Thanks Simon. Here is the link
https://docs.juliahub.com/CalculusWithJulia/AZHbv/0.0.7/alternatives/makie_plotting.html
I have been exploring climate change modelling with Julia, but after
reading the remarks
on the GeoMakie webpage, that it is under development and would  break
often, I thought
I would experiment with Makie in the meantime. The pages headed
"Calculus Plots with Makie"

seemed useful, but it clearly needs updating as its header indicates.
I will close the issue.

In the meantime, I think I have sufficient features of GeoMakie
working but would like for example to

have the latitude bounds to focus say on NZ where I live about
(175,-41) and the south pole (0,-90).

with the ortho projection using say and xlims! and ylims!?

I guess you and your team are currently working on GeoMakie? I
appreciate its a big job.

Cheers - Kevin
Emeritus Professor Kevin A. Broughan
Department of Mathematics
University of Waikato
Hamilton 3216
New Zealand
Web http://www.math.waikato.ac.nz/~kab

**Comment by SimonDanisch** [comment]
I dont know who runs CalculusWithJUlia, but googling seems to give me a more up to date version:
https://jverzani.github.io/CalculusWithJuliaNotes.jl/alternatives/makie_plotting.html#figures

I do try to fix bugs on GeoMakie, but its maintained by quite a few others as well.
Better open issues there ;)
