### ISSUE TITLE
Poly plots a face even when the mesh has none

### ISSUE THREAD

**Issue by BambOoxX** [MakieOrg/Makie.jl#3228]
# Problem
I use `poly` to plot some meshes. Some elements are `TriangleFace` some are `QuadFace`. 
Sometimes, I have empty meshes, in terms of faces. There are some points, but they are not connected with faces. 
Nevertheless, I still call `poly(points,faces)` with an empty list of faces. 

If faces are triangular, there is no problem, however there is a sporadic bug when faces are quads. This leads me to think that the bug is hidden somewhere inside `to_triangles` though I can't be sure. This bug does not generate any error. It just plots a triangle even where the is no face in faces.

- [x] are you running newest version (version from docs) ?
Yes (fresh env)
```
  [e9467ef8] GLMakie v0.8.9
  [5c1252a2] GeometryBasics v0.4.9
  [ee78f7c6] Makie v0.19.9
```
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
Yes see MWE below
```julia
]activate --temp; add Makie; add GLMakie; add GeometryBasics
using GLMakie,GeometryBasics
points = rand(Point3f,100)
f = QuadFace{Int64}[]
m = GeometryBasics.Mesh(points,f)
poly(m)
```
Note that since the bug is sporadic, the problem may not show at some `poly` calls. Overall this leads to showing a triangular face despite `f` being empty.
![image](https://github.com/MakieOrg/Makie.jl/assets/42067365/66760248-0358-45ce-93db-6f727dff4265)

- [x] What platform + GPU are you on?
>Julia Version 1.9.0
Commit 8e63055292 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores

**Comment by BambOoxX** [comment]
Well probing a bit further it seems that the problem also happens with triangular faces, but so far I noticed this only with GLMakie. 
I tried and see if some triangular face was added somewhere between `poly` and the actual plotting functions beneath it. I checked in `draw_mesh` if some faces where present in the `data` dictionary; but none was there (even if the plot shows a triangular face).

**Comment by BambOoxX** [comment]
@SimonDanisch @ffreyer sorry to ping, but do you notice this effect as well ?

**Comment by SimonDanisch** [comment]
Hm, if you look at the final renderobject, it actually seems like it does create faces:
```julia
points = rand(Point3f,100)
f = QuadFace{Int64}[]
m = GeometryBasics.Mesh(points,f)
 s=Scene(); mesh!(s, m); screen = display(s);
renderobject = screen.renderlist[end][3]
renderobject.vertexarray.indices
1-element GLMakie.GLAbstraction.GLBuffer{NgonFace{3, OffsetInteger{-1, UInt32}}}:
 TriangleFace(OffsetInteger{-1, UInt32}(0x00000000), OffsetInteger{-1, UInt32}(0x00000000), OffsetInteger{-1, UInt32}(0xf7e7dfd0))
```
I remember that it was impossible to create an empty OpenGL buffer, so maybe its that:
https://github.com/MakieOrg/Makie.jl/blob/master/GLMakie/src/GLAbstraction/GLBuffer.jl#L11-L25

Not sure how to fix it... I guess we need to set the drawrange to 0 somehow, without making the buffer segfault...
You can also try removing the `len == 0 ?` and see if that works magically now ^^

**Comment by BambOoxX** [comment]
@SimonDanisch Thanks for the explanation, I did not investigate the `renderlist`. The funny thing is that the triangle does not always show, only sometimes which is very suprising (I like my bugs to be deterministic).

**Comment by ffreyer** [comment]
Fixed in GLMakie, CairoMakie, WGLMakie
