### ISSUE TITLE
Point light color is ignored in GLMakie

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#3238]
```julia
using GLMakie
using FileIO

GLMakie.closeall()

brain = load(assetpath("brain.stl"))

f = Figure()

ls = LScene(f[1, 1]; scenekw = (; lights = Makie.AbstractLight[PointLight(Point3f(100, 100, 100), RGBf(1, 0, 0))]))

mesh!(ls, brain, color = :white)

f
```

Gives this:

<img width="643" alt="grafik" src="https://github.com/MakieOrg/Makie.jl/assets/22495855/1f695a38-507f-4eba-8865-9b1e21fec126">

No hint of red to be seen. I've followed the tracks a bit and think the problem is that in `mesh.frag` we have

```glsl
void main(){
    vec4 color;
    // Should this be a mustache replace?
    if (fetch_pixel){
        color = get_pattern_color(image);
    }else{
        color = get_color(image, o_uv, color_norm, color_map, matcap);
    }
    {{light_calc}}
    write2framebuffer(color, o_id);
}
```

and in `surface.jl` we have

```julia
function light_calc(x::Bool)
    if x
        """
        vec3 L      = normalize(o_lightdir);
        vec3 N      = normalize(o_normal);
        vec3 light1 = blinnphong(N, o_camdir, L, color.rgb);
        vec3 light2 = blinnphong(N, o_camdir, -L, color.rgb);
        color       = vec4(ambient * color.rgb + light1 + backlight * light2, color.a);
        """
    else
        ""
    end
end
```

And then we have 

```glsl
vec3 blinnphong(vec3 N, vec3 V, vec3 L, vec3 color){
    float diff_coeff = max(dot(L, N), 0.0);

    // specular coefficient
    vec3 H = normalize(L + V);

    float spec_coeff = pow(max(dot(H, N), 0.0), shininess);
    if (diff_coeff <= 0.0 || isnan(spec_coeff))
        spec_coeff = 0.0;

    // final lighting model
    return vec3(
        diffuse * diff_coeff * color +
        specular * spec_coeff
    );
}
```

So `color` in `blinnphong` which to me should be the light color seems to be the texture color instead unless I'm misunderstanding.

**Comment by ffreyer** [comment]
No, the `color` here should be the objects color. Ambient, diffuse and specular used to act as a combined material property and light color. For more realistic/user friendly lighting we should probably split of the light color into another vec3 multiplier. Probably just `light_color * blinnphong(...);`?

**Comment by jkrumbiegel** [comment]
Yeah at least right now light color doesn't seem to have an effect at all. It was a bit difficult for me to follow the variables because of the glsl structure
