### ISSUE TITLE
Directional light as new default

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#3239]
Right now we don't have the light type directional light at all in GLMakie and WGLMakie. This is a light like the sun, like a point light at infinite distance so that all rays are parallel. This is nice because it's easy to light any object without worrying about anything but the light angle.

Therefore, I think we should add this light type to Makie and actually make it the default. Right now, the default is a point light that is placed at eye position. This is not great I think, because lighting from eye position means there aren't any visible shadow areas, which reduces the three-dimensionality of the lit surfaces. I understand that this choice was made because it was the only simple choice available. For any other position of a point light, one would probably need to take object positions and sizes into account. Not so with a directional light. A good default could be a light coming from top right of eye position.

I already tried tinkering with this a little bit and hit https://github.com/MakieOrg/Makie.jl/issues/3238 in the process. The glmakie light pipeline appeared much more hardcoded to one point and one ambient light to me than I had assumed prior given the `lights` Vector being able to hold an arbitrary number of arbitrary light types. So this might need a larger refactor. Or we add direction-ness as a boolean Switch to PointLight which would change how the Point3f it holds is interpreted, as a position or a direction.

**Comment by SimonDanisch** [comment]
>I had assumed prior given the lights Vector being able to hold an arbitrary number of arbitrary light types

Yeah it's pretty much hardcoded and the light vector was introduced mostly for RPRMakie and for some future, where we have time to implement better lighting for GLMakie

**Comment by ffreyer** [comment]
If we want to get directional lights working without rewriting a bunch of stuff we could just use a far away PointLight as an approximation. We'd probably need something like `lightposition = lookat - 1e4 * norm(eyeposition - lookat) * normalize(direction)` for that.
