### ISSUE TITLE
Polar axis broken in patch release

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#3248]
Something changed besides the order of arguments (should have been released as a minor release), which broke our recipes:

https://juliaearth.github.io/GeoStatsDocs/stable/variography/empirical.html#Varioplanes

The previous version of Makie.jl was working fine:

https://juliaearth.github.io/GeoStatsDocs/v0.44/variography/empirical.html#Varioplanes

Our recipe is here, it calls Makie.surface and Makie.lines with polar coordinates:

https://github.com/JuliaEarth/GeoStats.jl/blob/338127cf188fa7a769eb44549ad07633b23741d1/ext/variogram.jl#L119-L130

What do we need to change to reproduce the old visualization?

**Comment by juliohm** [comment]
Swapping the order of arguments doesn't solve the problem:

![image](https://github.com/MakieOrg/Makie.jl/assets/3345261/3941f77e-8e28-4c04-8b37-89dcbd956cf9)

**Comment by ffreyer** [comment]
We noted in the docs that PolarAxis is currently experimental and open to breaking changes which is why we pushed this through in a patch release.

I can reproduce the old docs example with
```julia
ax.theta_as_x[] = false
reset_limits!(ax)
```
I think that means you're missing something when swapping your arguments (maybe a transpose on z?).

**Comment by juliohm** [comment]
Thank you for the quick fix. Transposing the matrix Z did the trick. I personally like the old visualization more:

![image](https://github.com/MakieOrg/Makie.jl/assets/3345261/43d1d963-fc33-46eb-98fd-c60f16ddab04)

Hiding the grid lines makes it a bit difficult to find the radius.

**Comment by ffreyer** [comment]
I personally agree, but it's inconsistent with Axis so we adjusted that. You can tweak the recipe to have the surface plot below the grid lines with a `on(z -> translate!(surface_plot, 0, 0, -maximum(z) -100 -1), surface_z)`. (maximum to move the surface plot to 0 max z, -100 from `ax.gridz` and another -1 to avoid z-fighting).

Btw that docs page crashes for me after a short while. I'm guessing that's a problem with WGLMakie/JSServe? (ubuntu firefox)

**Comment by juliohm** [comment]
It never crashed for me, but we are considering using CairoMakie.jl in the docs to avoid heavy loading.
