### ISSUE TITLE
method calling a recipe

### ISSUE THREAD

**Issue by waywardpidgeon** [MakieOrg/Makie.jl#3250]
I want to write methods to call Makie recipies. The following example works as expected
using Makie
function test_lines(x)
	global fig=Figure()
    ax=Axis(fig[1,1])
    lines!(ax, [1,2,3],[10,2,x], strokecolor=:black)
	return 0
end
but 
function test_contour(fun)
	N = 20
	x = LinRange(-0.3, 1, N)
	y = LinRange(-1, 0.5, N)
	z = fun.(x,y)
	contour(x, y, z, levels = 3, linewidth = 1, fillrange = true)
end
displays the axis but no contour plot.
How can I call Makie recipies from methods? What am I missing here ? Thanks - Kevin

**Comment by SimonDanisch** [comment]
I'm not sure what this is about, but you should familiarize yourself with the Julia display system and how Makie displays its plots.
https://docs.makie.org/stable/tutorials/basic-tutorial/
