### ISSUE TITLE
scatter does not support all types of "Observables"

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [MakieOrg/Makie.jl#3254]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?

The `scatter` function can handle all sorts of input types, however not all are supported as "Observables" e.g. when a `slider` is used. This seems unexpected. 

For example, the following works: 

```julia
t     = [0.0 0.0 0.0]

fig1 = Figure(resolution = (1200, 800))
nSteps = 50
sl_x = Slider(fig1[2, 1], range = range(-10,10,nSteps), startvalue = 0)

tp = lift(sl_x.value) do x
  t[1] = x
  tp = Point3f(t[1],t[2],t[3])
end

ax = Axis3(fig1[1, 1], aspect = :data)
scatter!(ax, tp ,markersize=50,color=:red)
fig1
```

However, this doesn't: 
```julia
t     = [0.0 0.0 0.0] 

fig1 = Figure(resolution = (1200, 800))
nSteps = 50
sl_x = Slider(fig1[2, 1], range = range(-10,10,nSteps), startvalue = 0)

t = lift(sl_x.value) do x
  t[1] = x 
end

ax = Axis3(fig1[1, 1], aspect = :data)
scatter!(ax, t[:,1], t[:,2], t[:,3],markersize=50,color=:red)
fig1
```

Error message: 
```
ERROR: MethodError: no method matching getindex(::Observable{Float64}, ::Colon, ::Int64)
```

Does `scatter` currently only support `Point2f` or `Point3f` input types when a slider is used? Could you expand to allow for all supported `scatter` input?

**Comment by jkrumbiegel** [comment]
The error comes not from `scatter` but from `t[:,1]` etc where you index into the observable like it's an array.

**Comment by SimonDanisch** [comment]
```julia
t  = [0.0 0.0 0.0] 
t = lift(sl_x.value) do x
  t[1] = x 
end
```
This is quite confusing, since you first assign a matrix to t, then assign a new value to the first index inside the closure and then overwrite it to be an observable.

I'm not sure what you're trying to achieve, but I would recommend doing something more like this:

```julia
t = lift(sl_x.value) do x
    return [Point2f(i, x) for i in 1:x] # construct the array of points _inside_ the lift
end
scatter(t) # array of points is much easier to handle, since you just have one array.
``` 
 If you have e.g. another slider you can also do this:
```julia
sl_x = Slider(fig1[2, 1], range = range(-10,10,nSteps), startvalue = 0)
sl_y = Slider(fig1[2, 1], range = range(-10,10,nSteps), startvalue = 0)
t = lift(sl_x.value, sl_y.value) do x, y
    return [Point2f(i, y) for i in 1:x] # construct the array of points _inside_ the lift
end
scatter(t)
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@jkrumbiegel @SimonDanisch thanks for your response. The issue was indeed not with `scatter` but the fact that Observables do not seem indexible (highly annoying, I do not see why that isn't implemented).

**Comment by SimonDanisch** [comment]
Because you can put anything into an Observable, not only arrays ;) 

If Observables are annoying to work with, you can also just mutate the plot:

```julia
sl_x = Slider(fig1[2, 1], range = range(-10,10,nSteps), startvalue = 0)
sl_y = Slider(fig1[2, 1], range = range(-10,10,nSteps), startvalue = 0)
figure, axis, plot_obj = scatter(Point2f[])

onany(sl_x.value, sl_y.value) do (x, y)
     plot_obj[1] = [Point2f(i, y) for i in 1:x] # update the first argument of the plot
     plot_obj.color = rand(RGBf) # change the color or any other attribute
end
