### ISSUE TITLE
Error on valid data for `hlines!` with log scale

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#3271]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- What platform + GPU are you on?
    - Linux, no GPU

I can make a scatterplot on a log-scale for the following values:
```julia
julia> using GLMakie

julia> fig = Figure(); ax = Axis(fig[1, 1], yscale=log);

julia> scatter!(ax, [0.5, 1, 2], [0.5, 1, 2]); fig
```

However, when I add a `hlines!` to the same plot, at a value already in the plot, I get an `invalid y-limits` error:
```julia
julia> hlines!(ax, [0.5]); fig
ERROR: Found invalid y-limits (-0.6931472f0, 2.0f0) for scale log which is defined on the interval 0.0 .. Inf (open)
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] autolimits(ax::Axis, dim::Int64)
    @ Makie ~/.julia/packages/Makie/1hq9u/src/makielayout/blocks/axis.jl:967
  [3] yautolimits
    @ Makie ~/.julia/packages/Makie/1hq9u/src/makielayout/blocks/axis.jl:980 [inlined]
  [4] reset_limits!(ax::Axis; xauto::Bool, yauto::Bool, zauto::Bool)
    @ Makie ~/.julia/packages/Makie/1hq9u/src/makielayout/blocks/axis.jl:588
  [5] reset_limits!
    @ Makie ~/.julia/packages/Makie/1hq9u/src/makielayout/blocks/axis.jl:559 [inlined]
  [6] plot!(la::Axis, P::Type{Combined{Makie.hlines}}, attributes::Attributes, args::Vector{Float64}; kw_attributes::@Kwargs{})
    @ Makie ~/.julia/packages/Makie/1hq9u/src/makielayout/blocks/axis.jl:795
  [7] plot!
    @ Makie ~/.julia/packages/Makie/1hq9u/src/makielayout/blocks/axis.jl:775 [inlined]
  [8] plot!(P::Type{Combined{Makie.hlines}}, ax::Axis, args::Vector{Float64}; kw_attributes::@Kwargs{})
    @ Makie ~/.julia/packages/Makie/1hq9u/src/makielayout/blocks/axis.jl:805
  [9] plot!(P::Type{Combined{Makie.hlines}}, ax::Axis, args::Vector{Float64})
    @ Makie ~/.julia/packages/Makie/1hq9u/src/makielayout/blocks/axis.jl:803
 [10] hlines!(::Axis, ::Vararg{Any}; attributes::@Kwargs{})
    @ Makie ~/.julia/packages/MakieCore/eLhyO/src/recipes.jl:39
 [11] hlines!(::Axis, ::Vararg{Any})
    @ Makie ~/.julia/packages/MakieCore/eLhyO/src/recipes.jl:38
 [12] top-level scope
    @ REPL[47]:1
```

The value that causes the issue happens to be `log(0.5)`:
```julia

julia> log(0.5)
-0.6931471805599453
```

It seems like when calculating the limits for the hline in a log-scale plot, something about the order of calculations is wrong.

Sidenote: The horixontal line actually appears correctly in the plot. But in a Pluto notebook, the only output I have access to is the error.

**Comment by ffreyer** [comment]
Can confirm that this happens on 0.19.9 and master (0.19.10), so it's something I missed in #3084.

This is probably something that'll get fixed by adding a way for data_limits to mark a dimension as invalid. We still need to figure out how we want to do that though

**Comment by AshtonSBradley** [comment]
I am hitting this on CairoMakie also

**Comment by AshtonSBradley** [comment]
In VSCode, I can't get the plot to show once the error appears. So I can't put any vlines with for values <1 and still have a useable plot.

**Comment by AshtonSBradley** [comment]
Might be good to add a test for `vlines!(ax,0.1)` on a log scale plot

**Comment by astertaylor** [comment]
Just a quick comment: this issue is still happening with `vspan!`, at the very least.
