### ISSUE TITLE
managing colorrange and colorbar in the recipe arrows() 

### ISSUE THREAD

**Issue by Zou-Bo** [MakieOrg/Makie.jl#3273]
fig = Figure();
ax = Axis(fig[1,1], aspect = 1.0)
ar = arrows!(ax, x_range, y_range, u_matrix, v_matrix, 
    color = vec(color_matrix), 
    colorrange = (0.0, 1.0),
    colormap = :viridis, 
)
Colorbar(fig[1,2], ar)

Above is the ideal code of using arrows() recipe with colors, but it doesn't work.

First, the Colorbar() function returns an error saying: 
Multiple colormaps found for plot Arrows{Tuple{Vector{Point{2, Float32}}, Vector{Vec{2, Float32}}}}, please specify which one to use manually. Please overload Makie.extract_colormap(::Arrows{Tuple{Vector{Point{2, Float32}}, Vector{Vec{2, Float32}}}})` to allow for the automatical creation of a Colorbar.

I find that ar consists 2 plots. One is the plot of arrow lines and the other is of arrowheads. They may have different colormaps, although in most cases we set them the same.

julia> ar.plots
2-element Vector{AbstractPlot}:
 LineSegments{Tuple{Base.ReinterpretArray{Point{2, Float32}, 1, Pair{Point{2, Float32}, Point{2, Float32}}, Vector{Pair{Point{2, Float32}, Point{2, Float32}}}, false}}}
 Scatter{Tuple{Vector{Point{2, Float32}}}}

So the idea is to generate colorbar for just one of them. For example:
Colorbar(fig[1,2], ar.plots[1])

The second thing is that the colorrange keywords doesn't really make any difference, as it changes the attribute of object ar but doesn't affect the attribute of the two plots in ar. 

julia> ar.attributes[:colorrange]
Observable{Any}((0.0, 1.0))
julia> ar.plots[1].attributes[:colorrange]
Observable{Any}(MakieCore.Automatic())
julia> ar.plots[2].attributes[:colorrange]
Observable{Any}(MakieCore.Automatic())

So I need to manually modify them.
ar.plots[1].attributes[:colorrange] = (0.0, 1.0)
ar.plots[2].attributes[:colorrange] = (0.0, 1.0)

Although, I believe these functions should be implemented natively in the official methods arrow() and Colorbar().

**Comment by SimonEnsemble** [comment]
👋 
I'm getting this same error, on `CairoMakie v0.11.6`.

```julia
Multiple colormaps found for plot MakieCore.Text{Tuple{Vector{GeometryBasics.Point{2, Float32}}}}, please specify which one to use manually. Please overload `Makie.extract_colormap(::MakieCore.Text{Tuple{Vector{GeometryBasics.Point{2, Float32}}}})` to allow for the automatical creation of a Colorbar.

    error(::String)@error.jl:35
    extract_colormap_recursive(::MakieCore.Text{Tuple{Vector{GeometryBasics.Point{2, Float32}}}})@colorbar.jl:93
    (::Makie.var"#1833#1835")(::MakieCore.Text{Tuple{Vector{GeometryBasics.Point{2, Float32}}}})@none:0
    iterate(::Base.Generator, ::Vararg{Any})@generator.jl:47[inlined]
    collect(::Base.Generator{Vector{MakieCore.Plot}, Makie.var"#1833#1835"})@array.jl:834
    extract_colormap_recursive(::MakieCore.Plot{Makie.contour, Tuple{Vector{Float32}, Vector{Float32}, Matrix{Float32}}})@colorbar.jl:84
    var"#Colorbar#1837"(::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, @NamedTuple{label::String, ticks::Vector{Int64}, height::Observables.Observable{GridLayoutBase.Fixed}}}, ::Type{Makie.Colorbar}, ::GridLayoutBase.GridPosition, ::MakieCore.Plot{Makie.contour, Tuple{Vector{Float32}, Vector{Float32}, Matrix{Float32}}})@colorbar.jl:100
    var"#viz_gaussian#29"(::String, ::String, ::ColorSchemes.ColorScheme{Vector{ColorTypes.RGB{Float64}}, String, String}, ::String, ::Nothing, ::typeof(Main.var"workspace#3".viz_gaussian), ::Vector{Float64}, ::Matrix{Float64})@[Other: 22](http://localhost:1234/edit?id=7c59cfb4-bed3-11ee-21ee-03f33344ef55#)
    viz_gaussian@[Other: 1](http://localhost:1234/edit?id=7c59cfb4-bed3-11ee-21ee-03f33344ef55#)[inlined]
    top-level scope@[Local: 7](http://localhost:1234/edit?id=7c59cfb4-bed3-11ee-21ee-03f33344ef55#)[inlined]
```

this code worked fine before, but is now broken.

```julia
fig = Figure()
gcd = fig[1, 1:2] = GridLayout()
ax = Axis(gcd[1, 1])
ct = contour!(x₁, x₂, prob / max_density_Gaussian(Γ), colormap=colormap,
		colorrange=(0.0, 1.0), linewidth=2,
		levels=range(0.0, 1.0, length=8)
)
scatter!(x̄[1], x̄[2], color=colormap[end], marker=:circ, markersize=8)

Colorbar(gcd[1, 2], ct, label="normalized density", 
  ticks=[0, 1],
  height=@lift Fixed($(pixelarea(ax.scene)).widths[2])
)
colgap!(gcd, 30)
resize_to_layout!(fig)
fig
```
