### ISSUE TITLE
GLMakie: keyboard event handling

### ISSUE THREAD

**Issue by tamasgal** [MakieOrg/Makie.jl#3274]
I have a question about handling keyboard events. The code below works wonderfully except for the one which does the rotation-toggle, i.e. switch the rotation on and off. For some reason, the `rotation_enabled = !rotation_enabled` is either executed multiple times or there is some other racing condition. Most of the time, there is no reaction to the key `a` and sometimes it works.

What's going on here?

```julia
rotation_enabled = true
speed = 3

on(events(scene).keyboardbutton, priority = 20) do event
    if event.key == Makie.Keyboard.r
        frame_idx = 0
        return Consume()
    end
    if event.key == Makie.Keyboard.left
        frame_idx -= 200
        return Consume()
    end
    if event.key == Makie.Keyboard.right
        frame_idx += 200
        return Consume()
    end
    if event.key == Makie.Keyboard.a
        rotation_enabled = !rotation_enabled  # the line which behaves weirdly
        return Consume()
    end
    if event.key == Makie.Keyboard.up
        speed += 1
        return Consume()
    end
    if event.key == Makie.Keyboard.down
        speed -= 1
        return Consume()
    end
end
```

**Comment by jkrumbiegel** [comment]
you need to check for the key status as well, right now you trigger on `pressed`, `released` and `repeat`, usually you want to ignore everything but `pressed` for toggling stuff

**Comment by tamasgal** [comment]
Yes, that's exactly what I am looking for. OK, I'll search how to do it, thanks ;)

**Comment by tamasgal** [comment]
This works fine

```julia
        if ispressed(scene, Makie.Keyboard.a)
            rotation_enabled = !rotation_enabled
            return Consume()
        end
```
