### ISSUE TITLE
Stroke support for `scatter()` in WGLMakie

### ISSUE THREAD

**Issue by staticfloat** [MakieOrg/Makie.jl#3279]
### Feature description

The [WGLMakie backend page](https://docs.makie.org/stable/explanations/backends/wglmakie/index.html) states that stroke support is lacking for WGLMakie.  It would be great to add that in, as densely-plotted scatters are difficult to discern without a stroke.  We have been making due by plotting two scatters, one slightly larger than the other, but it would be nice to not have to do that.

**Comment by shaul-pollak** [comment]
That would be amazing.
In fact, the lack of stroke is the only reason I have been using CairoMakie + GTK on a remote server, and it has been a pain.
