### ISSUE TITLE
Using system fonts in Makie without copying them to AbstractPlotting?

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#328]
Trying to use a different font in master fails.  For example,

```julia
using Makie
lines([0, 1], [0, 1], font = "Blackchancery")
``` 
yields 
![p](https://user-images.githubusercontent.com/32143268/55091340-0b2fcd80-5087-11e9-921c-958d78f1fe06.png)
whose font is clearly `DejaVu Sans`.

**Comment by SimonDanisch** [comment]
Do you have that font? The search is also not super nice, so you'll need to spell it almost exactly matching the actual font name

**Comment by asinghvi17** [comment]
After installing Blackchancery, it works.  However, trying to use Calibri or some other system font does not work.

**Comment by asinghvi17** [comment]
Also what is the actual font name generally?

**Comment by ffreyer** [comment]
Closing this as outdated/fixed.
