### ISSUE TITLE
Since System upgrade precompilation of GLMakie causes  "Failed to build shader variant" error messages

### ISSUE THREAD

**Issue by s-fuerst** [MakieOrg/Makie.jl#3297]
I updated (apt dist-upgrade) my Linux Mint 21 system last friday, and can not use GLMakie since then anymore (WGLMakie works fine). When I delete the precompiled GLMakie code from the julia depot and run ` ]activate --temp; add GLMakie` I get the following error message (multiple times)
 
 ```
│  ac_rtld error(1): too much LDS (used = 47360, max = 32768)
│  LLVM failed to upload shader
│  EE ../src/gallium/drivers/radeonsi/si_state_shaders.cpp:2557 si_build_shader_variant - Failed to build shader variant (type=3)
```

I can load GLMakie, but when I create plots they are incomplete and the same error messages are shown up.

glxinfo shows the following information:
```
OpenGL renderer string: AMD Radeon RX 5700 (navi10, LLVM 15.0.7, DRM 3.48, 6.0.9-060009-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
0009-generic)`
```
 
Any idea whats going on and what I can do.  I'm a little reluctant to switch to the proprietary drivers, but might try that if no other solution is available.

**Comment by SimonDanisch** [comment]
Not much we can do about driver errors like that....
Maybe updating mesa could help: https://github.com/IrisShaders/Iris/issues/1967

**Comment by s-fuerst** [comment]
Yes, installing the MESA driver from the kisak PPA helped. Thanks a lot for this tip.
