### ISSUE TITLE
GLMakie: Crash on resizing window on Windows

### ISSUE THREAD

**Issue by f-ij** [MakieOrg/Makie.jl#3306]
I'm getting this bug when resizing a GLMakie window to particular sizes in my program.

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x153ebe3fd2e -- unknown function (ip: 00000153ebe3fd2e)
in expression starting at none:0
Allocations: 74936984 (Pool: 74889500; Big: 47484); GC: 22

**Comment by SimonDanisch** [comment]
Any details on how to reproduce this?

**Comment by f-ij** [comment]
> Any details on how to reproduce this?

Not at the moment, if I have time I will check if I can make a minimal example. My own project uses a lot of elements so it's hard to debug. I didn't check if it happens with any figure though (which I assume it doesn't, otherwise I wouldn't think it would've flown under the radar).

**Comment by ffreyer** [comment]
Closing for lack of reproducibility
