### ISSUE TITLE
Poor performance of scatter with non-scalar markersize

### ISSUE THREAD

**Issue by pablosanjose** [MakieOrg/Makie.jl#3307]
This is a performance issue. When calling `scatter` with a `markersize` that is a collection (say, a `Vector`) the performance of `display` is around ~200 times slower than with a scalar `markersize`. `meshscatter` does not have this problem, so I suspect it is a missed optimization of some kind.

Reproducer (timings and allocs are second-run)
```julia
julia> r = 10 * rand(Point3, 200000); s = rand(200000);

julia> @time display(scatter(r, markersize = 0.5));
  0.106780 seconds (58.04 k allocations: 8.244 MiB, 6.92% compilation time)

julia> @time display(scatter(r, markersize = s));
 18.634452 seconds (333.85 M allocations: 16.129 GiB, 3.90% gc time, 0.02% compilation time)

julia> @time display(meshscatter(r, markersize = s));
  0.024103 seconds (49.81 k allocations: 10.078 MiB)
```

- [x] are you running newest version (version from docs) ? Yes
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`) Yes
- [x] What platform + GPU are you on? Macbook Pro M1, macos Sonoma 14.0

**Comment by SimonDanisch** [comment]
Funny that this turns up now, where I just fixed it :D This performance "bug" has been in Makie for quite a while and I literally run into it yesterday and fixed here:
https://github.com/MakieOrg/Makie.jl/pull/3281

**Comment by SimonDanisch** [comment]
That's pretty impossible, since it's already end of day here and it will take a while to get those changes out of the beta release and then tag makie ...

**Comment by pablosanjose** [comment]
Ok, no worries! Thanks for all your work, it makes me smile every day.

**Comment by jkrumbiegel** [comment]
You could try running your demo on the beta branch? It should be mostly functional

**Comment by SimonDanisch** [comment]
That, or I just realize you can also use `marker=Circle` to avoid this... What's slow is the `BezierPath` marker, which is the default.

**Comment by pablosanjose** [comment]
That works!! And it looks exactly the same, I think? Wonderful!

**Comment by jkrumbiegel** [comment]
The default circle and Circle have a slight size difference, as Circle has radius 1 I think and the other is adjusted to look good with the other default markers and glyphs.
