### ISSUE TITLE
Create Axes2D from scratch

### ISSUE THREAD

**Issue by grero** [MakieOrg/Makie.jl#334]
In the document for Axes it says
"The axis is just a scene object, making it easy to manipulate and share between plots. Axis objects also contains the mapping you want to apply to the data and can interactively be changed. An Axis object can be created from any boundingbox and inserted into any plot."

Is there an example of how to do that? In other words, how can I, starting from an empty scene, add Axes2D objects to it? What I have in mind in something like this (pseudocode)
```julia
scene = Scene()
ax1 = Axes2D!(scene, boundingbox1, args...)
ax2 = Axes2D!(scene, boundingbox2, args...)
```
where I boundingbox1/2 would expressed in raw pixels (or fraction of the scene, or something else fancy). This would make manual layouting easier, until something automatic is created, ala matplotlib's subplot.

**Comment by SimonDanisch** [comment]
While this could work in theory, it doesn't work very well... Did you see: https://simondanisch.github.io/ReferenceImages/gallery//layouting/index.html

**Comment by grero** [comment]
Yeah, I've seen that, it is close to what I want, and I've been using that approach with some success. However, as I mentioned in #183, I'm struggling to get text to be the same size, and in general aligning different axes. I thought perhaps if I could manually create the axes, that should work. I'll just wait until something else comes along : ) In meantime, is there a way to manually set camera and such and tell Makie never to change it? I was playing around with some code, and I managed to override the camera settings to make the axes align nicely, but then once the scene was redrawn, things got a bit messed up. I'll see if I can find the code to post here.

**Comment by SimonDanisch** [comment]
scene.center = false

**Comment by grero** [comment]
Thanks! Just got a chance to try this out. So I guess my strategy for now is to manipulate the camera controls myself and set scene.center to false.
