### ISSUE TITLE
Link in documentation not working

### ISSUE THREAD

**Issue by mauricelanghinrichs** [MakieOrg/Makie.jl#3349]
Noticed a small potential bug in the docs. In the "Basic Tutorial", last section "Next steps", the link in the sentence

> You can read about the different available plotting functions with examples in the [Plotting Functions](https://docs.makie.org/stable/tutorials/basic-tutorial/#) section.

does not seem to work, i.e. it links to the same page.

**Comment by jkrumbiegel** [comment]
oh yeah that section was renamed, and seems CI didn't error due to that mismatch. needs to be fixed

**Comment by ffreyer** [comment]
Closing this because I can't find that phrase anymore
