### ISSUE TITLE
Band plot ignores alpha keyword

### ISSUE THREAD

**Issue by TomRottier** [MakieOrg/Makie.jl#3356]
```julia
    f = Figure()
    ax1 = Axis(f[1, 1], title="alpha = 0.5")
    ax2 = Axis(f[1, 2], title="color = (:red, 0.5)")
    xs = 1:10
    lower, upper = fill(-1.0, 10), fill(1.0, 10)
    band!(ax1, xs, lower, upper, color=:red, alpha=0.5)
    band!(ax2, xs, lower, upper, color=(:red, 0.5))
```

![makie_issue](https://github.com/MakieOrg/Makie.jl/assets/39778698/702ed9e0-7a70-4e43-9112-694f737c6d6d)

**Comment by bguo068** [comment]
I had a similar experience. Thanks for the workaround of putting color and alpha together as a tuple

**Comment by wsshin** [comment]
I also had this issue.  Thanks for the workaround!

**Comment by asinghvi17** [comment]
We should still fix this - people specifying color as e.g. `Cycled` won't have the option of a color tuple

**Comment by SimonDanisch** [comment]
Would just need an alpha here: https://github.com/MakieOrg/Makie.jl/blob/master/src/basic_recipes/band.jl#L14
And then needs to be added to attr here: https://github.com/MakieOrg/Makie.jl/blob/master/src/basic_recipes/band.jl#L56

**Comment by ffreyer** [comment]
Works for me in GLMakie and WGLMakie on master. Doesn't work in CairoMakie

**Comment by ffreyer** [comment]
Fixed
