### ISSUE TITLE
Weights attribute in hist functions is not Observable-aware

### ISSUE THREAD

**Issue by Petr-Hlavenka** [MakieOrg/Makie.jl#3362]
GLMakie v0.8.12 @  Julia 1.9.3 , reproducible - YES, Windows 11 22H2, Intel on CPU, 

MWE:
```
using GLMakie
vstat = rand(10, 10)

fig = Figure()
ax1 = Makie.Axis(fig[1, 1])
ax2 = Makie.Axis(fig[1, 2])
sl = Slider(fig[2, 1], range = 1:10)    #simple observable

hm = heatmap!(ax1, vstat, colormap=:viridis)

weight = lift(sl.value) do v
    return vstat[v, :]
end
hist!(ax2, 1:10, weights = weight, bins=10) # this should show slider-selected column of the vstat 
fig
```
Problem is that triggering of `weight` observable does not change the hist plot.

**Comment by Sagnac** [comment]
This seems to be a problem with the `normalization` and `scale_to` attributes as well. The plot updating is currently handled by watching `widths`, but that doesn't appear to receive updates whenever these attributes change. To fix this we can explicitly observe these attributes and trigger the callback attached to `widths`.

Note that watching `points` instead doesn't work; I've tested that and the updating of the histogram breaks in some cases.

```diff --git a/src/stats/hist.jl b/src/stats/hist.jl
index a9f56427..edb1fa88 100644
--- a/src/stats/hist.jl
+++ b/src/stats/hist.jl
@@ -187,5 +187,8 @@ function Makie.plot!(plot::Hist)
         bp[1].val = points[]
         bp.width = w
     end
+    onany(plot.normalization, plot.scale_to, plot.weights) do _, _, _
+        notify(widths)
+    end
     plot
 end
```
If this is an acceptable fix I can open a PR.

**Comment by Petr-Hlavenka** [comment]
Thank you, @Sagnac,  for the fast fix.  I can confirm it solves the problem.
Unfortunately, I have no idea how the recipe system works, so I cannot make the PR myself. I'm glad you offered to prepare the PR. 
If I may make a suggestion for the PR. I've made a quick check and it looks like the same problem exists for the `violin` and `boxplot` as well, the `density` plot seems not to be affected. Please could you target the PR to fix all the statistical plots where weights were introduced in #1816. 
Thank you very much!

**Comment by Sagnac** [comment]
I cannot reproduce the issue with `boxplot` or `violin`.

```
using GLMakie # v0.8.12
n = 1000
x = rand(1:3, n)
y = randn(n)
fig = Figure()
box_axis = Axis(fig[1,1])
violin_axis = Axis(fig[1,2])
button_attr = (label = "Weights", tellwidth = false, halign = :left, fontsize = 24)
button = Button(fig[2,2]; button_attr...)
weights = lift(_ -> rand(n), button.clicks)
boxplot!(box_axis, x, y; weights)
violin!(violin_axis, x, y; weights)
fig
```

**Comment by Sagnac** [comment]
I've gone ahead and opened a pull request with the patch. I'm unsure as to whether it's the best approach or whether a more general solution is needed, but it ultimately works and I think it's a decent starting point.

**Comment by Petr-Hlavenka** [comment]
Thank you very much for the fix!
