### ISSUE TITLE
Figure(; fontsize_theme = Theme(fontsize=18)) ignored?

### ISSUE THREAD

**Issue by ryofurue** [MakieOrg/Makie.jl#3371]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?  --> macOS 14.1.1, Apple M2 Pro

In the following code, the `fontsize_theme` is ignored.  If it isn't supposed to work
1. I'd like to submit this as a "feature request" that the theming will work as keyword arguments to `Figure()`.
2. An error message would be helpful!  I don't see any error messages.

(As to point 1, the current implementation is strange to me: even `set_theme!(fig, theme)` results in error.  Because Theme is an attribute of a Figure object (am I correct?), it's more natural if it be settable by an explicit `set_some_attribute!(object, value)` call and by a keyword argument.)

```julia
using CairoMakie

function myplot(fontsize, imgfile)
  fig = Figure(; fontsize_theme=Theme(fontsize=fontsize))
#  fig = Figure()
#  fontsize_theme = Theme(fontsize = fontsize)
#  set_theme!(fontsize_theme)
  ax = Axis(fig[1,1])
  xs = -pi:(pi/16):pi
  lines!(ax, xs, sin.(xs))
  save(imgfile, fig)
end

myplot(10, "tmp1.pdf")
myplot(50, "tmp2.pdf")

```

**Comment by jkrumbiegel** [comment]
it already works as a keyword argument to `Figure()`. Basically, `Figure` clones the current theme (modifyable by `set_theme!` or temporarily with `with_theme`) and merges in the keys it receives as keyword args at the top level. So just `Figure(; fontsize)` should work.

**Comment by ryofurue** [comment]
> So just Figure(; fontsize) should work.

I see!  Thanks.  That means that this is a feature request, not a bug report.  "Theme" is a great idea because it bundles various settings into one object, which you can carry around: So,
```julia
theme = Theme( . . .  ) # build a theme
# . . . 
fig  = Figure(; theme = theme)
```
would be nice and would go nicely along with the concept of Theme.  What do you think?

**Comment by ryofurue** [comment]
Oh and I was wondering why there was no error message when I used `fig = Figure(; font_sizetheme = . . . )` ?

**Comment by jkrumbiegel** [comment]
You can splat a `Theme` as kwargs like `Figure(; theme...)`, if you'd like a positional arg constructor please open a separate request about that. There's no error message for unknown keys because the theme is essentially unbounded currently, as we don't know what end user recipe might read what theme key. It's a bit unfortunate because of typos but no easy way around it currently.
