### ISSUE TITLE
display backend support

### ISSUE THREAD

**Issue by clouds56** [MakieOrg/Makie.jl#341]
see this issue, https://github.com/JuliaEditorSupport/julia-vscode/issues/547
could we make Makie to work with other display backend like `_vscodeserver.InlineDisplay()` in Base.Multimedia.displays?

**Comment by asinghvi17** [comment]
That should be coming with the Plotly backend, but afaik it's pretty hard with OpenGL windows (and preserving interactivity)

**Comment by clouds56** [comment]
sorry for confusing title, by backend I'm meaning
`Base.Multimedia.displays` and `AbstractPlotting.PlotDisplay()`, Makie is now appending a custom window based display backend regardless if there's usable backend in the `Base.Multimedia.displays` stack.

I'm now using these code to workaround.
```
popdisplay(AbstractPlotting.PlotDisplay())
AbstractPlotting.inline!(true)
```

**Comment by asinghvi17** [comment]
So more like a display frontend?  :P 

Also, does interactivity work?

**Comment by clouds56** [comment]
No, i don't think so, `_vscodeserver.InlineDisplay()` displays scene as images, but it do integrate well with vscode (at least when using Plots)
I hope Makie could behave in a similar way. https://github.com/JuliaPlots/Plots.jl/pull/1874
And make the dedicated interactive window an opt-in option and/or fallback frontend for user to switch to when there's already display frontend.

**Comment by asinghvi17** [comment]
If you load Makie through your startup.jl you could probably use the workaround, but in my opinion that option doesn't really make sense as a default, simply because interactive is one of the major benefits of Makie.

**Comment by felixcremer** [comment]
This should be closed.

**Comment by asinghvi17** [comment]
For reference: you can have interactive plots in the VSCode plot pane using the `WGLMakie` backend.
