### ISSUE TITLE
`contour!(...; overdraw=true)` not drawing contours on top of surface with GLMakie

### ISSUE THREAD

**Issue by anowacki** [MakieOrg/Makie.jl#3411]
If using GLMakie (but not CairoMakie), trying to draw contours on top of a surface does not work when using the `overdraw=true` argument to `contour!`.  E.g.:

```julia
using GLMakie

x = 1:10
y = 0:10:90
z = x.*y'

fig = Figure()
ax = Axis(fig[1,1])

surface!(ax, x, y, z, shading=NoShading)
contour!(ax, x, y, z, color=:black, overdraw=true)
scatter!(ax, vec(repeat(x, 1, length(y))), vec(repeat(y', length(x))), color=:black, markersize=3, overdraw=true)

fig
```

![no_contours](https://github.com/MakieOrg/Makie.jl/assets/1231209/6c586104-534c-467b-add0-a5d98454011e)

With CairoMakie all is well:

![yes_contours](https://github.com/MakieOrg/Makie.jl/assets/1231209/824c5913-2bcd-49be-9a9b-c198e7afeefa)

- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
  - macOS 12.7 and 10.15.7
  - AMD FirePro D300

**Comment by ffreyer** [comment]
Probably just missing a passthrough. Though it would be better to use `surface!(ax, x, y, zeros(size(z)), color = z, shading=NoShading)` to avoid overdraw entirely.
