### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by fredcallaway** [MakieOrg/Makie.jl#3415]
https://docs.makie.org/stable/explanations/backends/cairomakie/ has a link to https://docs.makie.org/stable/documentation/figure_size/ (with the name "figure docs"). This link doesn't go anywhere.

**Comment by jkrumbiegel** [comment]
Thanks, we should add a link check pass so that this doesn't happen in the future.

**Comment by jkrumbiegel** [comment]
I deleted those links on master, web links in docstrings are not reliable anyway and that's how it avoided the link check
