### ISSUE TITLE
`scalefactor` does not scale mouse on MacOS

### ISSUE THREAD

**Issue by jacobleft** [MakieOrg/Makie.jl#3429]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
```julia
(jl_WkIh9H) pkg> st
Status `/private/var/folders/n0/367fnn5x0rg8p83b918ltdph0000gn/T/jl_WkIh9H/Project.toml`
  [5789e2e9] FileIO v1.16.1
  [e9467ef8] GLMakie v0.9.1
  [ee78f7c6] Makie v0.20.1
```
- [x] What platform + GPU are you on?
```julia
In [9]: versioninfo()
Julia Version 1.9.4
Commit 8e5136fa297 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M2
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
```

MWE:
```julia
using FileIO
using GLMakie
brain = load(assetpath("brain.stl"))

GLMakie.activate!(;scalefactor = 1) 
# GLMakie.activate!(;scalefactor = 2) #bug

fig = Figure()
ax1 = Axis3(fig[1, 1], aspect = :equal, title = "aspect = :equal")
ax2 = Axis3(fig[1, 2], aspect = :data, title = "aspect = :data")
for ax in [ax1, ax2]
    mesh!(ax, brain, color = :gray80)
end
DataInspector(fig)
fig
```
With `scalefactor=1`, the mouse can select the bounding box at the right place:
![image](https://github.com/MakieOrg/Makie.jl/assets/88961633/5b25772f-3a90-40b8-8be5-99ace94b0189)

With `scalefactor=2`, the mouse needs to be in the **top left** quadrant to select the bounding box:
![image](https://github.com/MakieOrg/Makie.jl/assets/88961633/0dd3d46b-551b-4e5c-a27e-2951714278b6)

I can not reproduce it on Windows and have not tried it on Linux.

**Comment by ffreyer** [comment]
This is working fine for me on linux, so I guess it's mac specific

**Comment by pbouffard** [comment]
I saw something this morning and I wonder if it is related. In my case my code had opened two GLMakie windows on my primary monitor (laptop screen) but the title bars seemed to be missing, or possibly just inaccessible under the menubar. I moved the GLMakie windows to a secondary monitor, and that didn't make a difference, but I did notice that inspector tooltips would pop up on the primary monitor when I hovered over plots in these windows. The tooltips looked like they were in roughly the right place, but just on the wrong monitor.

**Comment by jacobleft** [comment]
@pbouffard Thank you for testing this issue. I was also using an external monitor.  The below results are consistently reproducible with `scalefactor=2` on my Macbook.
1. If the Makie window is opened on the built-in monitor, no scaling issue.
2. After (1), if the Makie window is dragged to the external monitor, the mouse is correctly scaled, but the font and line sizes are reduced and are rendered in low resolution (See below figure).
3. If the Makie window is opened on the external monitor, then the mouse won't scale (i.e. the original issue).
4. After (3), if the Makie window is dragged to the built-in monitor, then the scaling issue disappears.
5. After (4), if the Makie window is dragged back to the external monitor, then (2) is reproduced.
![image](https://github.com/MakieOrg/Makie.jl/assets/88961633/88e88d72-4a8f-46c9-aef7-d7d2875d28c9)
