### ISSUE TITLE
doc: broken `triplot` examples

### ISSUE THREAD

**Issue by t-bltg** [MakieOrg/Makie.jl#3440]
No example images in https://docs.makie.org/stable/reference/plots/triplot.

**Comment by j-fu** [comment]
Seems to be a problem with CairoMakie generated svg's. With 0.11.1 they are ok, after upgrade to 0.11.2 I am getting the same thing locally: blurred image in Chrome, empty space in Firefox. Inkscape shows the images properly, though.

**Comment by jkrumbiegel** [comment]
Probably the change in svg salting, maybe it breaks for plot types I didn't test

**Comment by j-fu** [comment]
Something like this. Simple lines are ok, but it fails e.g. with color interpolation on meshes.
