### ISSUE TITLE
Axes can bleed through, when ticks are given and not covering the whole data range

### ISSUE THREAD

**Issue by daviehh** [MakieOrg/Makie.jl#3446]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on? macos, apple silicon

might be a bit of an edge case, with e.g.

```julia
using GLMakie

let
    ts = 0:0.01:2π
    dat = cos.(ts)

    fig = Figure(; size=(600, 400), fontsize=20)
    ax1 = Axis(fig[1, 1])
    lines!(ax1, ts, dat)

    ax2 = Axis(fig[2, 1],
        yticks=0:0.1:0.5,
        yminorticks=IntervalsBetween(2), yminorticksvisible=true)
    lines!(ax2, ts, -dat)

    fig
end
```

the ticks of ax2 would 'bleed through' and make it into fig[1,1]

<img width="482" alt="Screenshot 2023-12-05 at 10 16 37 PM" src="https://github.com/MakieOrg/Makie.jl/assets/25255906/11e803c5-633e-4281-9e88-f80665ef81ce">

**Comment by ffreyer** [comment]
Fixed
