### ISSUE TITLE
Warning triggered by Makie itself

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#3459]
The latest CairoMakie.jl release is triggering this warning:

```julia
┌ Warning: Found `resolution` in the theme when creating a `Scene`. The `resolution` keyword for `Scene`s and `Figure`s has been deprecated. Use `Figure(; size = ...` or `Scene(; size = ...)` instead, which better reflects that this is a unitless size and not a pixel resolution. The key could also come from `set_theme!` calls or related theming functions.
└ @ Makie ~/.julia/packages/Makie/6NLuU/src/scenes.jl:220
```

We replaced the keyword `resolution` by `size` everywhere in our stack already.

**Comment by ffreyer** [comment]
Is this still a problem? I don't see any `scene.resolution` calls in CairoMakie.

**Comment by alecloudenback** [comment]
I got this same warning with CairoMakie 11.5:

<img width="917" alt="image" src="https://github.com/MakieOrg/Makie.jl/assets/711879/97524877-c059-4578-b5e6-438899077c98">

This post contains all the code to reproduce if needed: https://alecloudenback.com/posts/counting-chickens/

```julia-repl
(counting-chickens) pkg> st
Status `~/prog/alecloudenback.com/posts/counting-chickens/Project.toml`
  [13f3f980] CairoMakie v0.11.5
  [35d6a980] ColorSchemes v3.24.0
  [1313f7d8] DataFramesMeta v0.14.1
  [8e1ec7a9] SumTypes v0.5.5
```

**Comment by juliohm** [comment]
The warning is still present in the latest version.

Example in our book: https://juliaearth.github.io/geospatial-data-science-with-julia/02-geoviz.html

**Comment by asinghvi17** [comment]
I haven't seen it myself anywhere...is it possible that something in your stack is setting a theme with `resolution` given there?  Maybe even IJulia or Quarto?

**Comment by juliohm** [comment]
On our side, the packages that we maintain don't use the keyword `resolution`. We did a search on VSCode on all packages. It can be something in IJulia or Quarto, I would be surprised though.

**Comment by jkrumbiegel** [comment]
Quarto sets resolution when it detects cairomakie in the env, and they haven't switched to 0.20 handling yet as far as I know. There's an issue about it in their repo

**Comment by alecloudenback** [comment]
Found and thumbs-upped that issue: https://github.com/quarto-dev/quarto-cli/issues/7817

**Comment by juliohm** [comment]
Thank you @alecloudenback for finding the issue.

**Comment by juliohm** [comment]
Since this is not a Makie issue, I will close it.
