### ISSUE TITLE
How to change the style of border and axes in 3D graphics?

### ISSUE THREAD

**Issue by Photonico** [MakieOrg/Makie.jl#347]
Makie has the perfect ability and performance in 3-D drawing. but I have a little dissatisfaction with the style of border and axes plotting. I prefer the style of Gnuplot and MathGL.
How can I change the style or can you develop it?

Gnuplot Sample:
![Gnuplot Sample](http://gnuplot.sourceforge.net/demo_5.3/fenceplot.1.png)

MathGL Sample:
![MathGL Sample](http://mathgl.sourceforge.net/png/cont3.png)

**Comment by asinghvi17** [comment]
I'm working on that at the moment, but it's going to take a while because of finals season.  

You can currently change some aspects of the plot like the ticks, axis labels, and overall colour - but support for styling grids and frames is minimal.

**Comment by asinghvi17** [comment]
See also JuliaPlots/AbstractPlotting.jl#118

**Comment by asinghvi17** [comment]
The first one will need billboarding, though - ping @SimonDanisch on that

**Comment by ffreyer** [comment]
I got a bit distracted by the "Cont3 sample"... 

With have `Axis3` now which has a much cleaner look. Closing this as done.
