### ISSUE TITLE
Horizontal zoom center can ignore the mouse position in GLMakie (and maybe others?)

### ISSUE THREAD

**Issue by rafaqz** [MakieOrg/Makie.jl#3471]
- [x] are you running newest version (version from docs) ? yes
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`) yes, sometimes
- [x] What platform + GPU are you on? Linux/nvidia

I made this issue for Tyler: https://github.com/MakieOrg/Tyler.jl/issues/66

But then I had the same problem later using MakieDraw.jl. Both are with GLMakie.

It's hard to reproduce because it usually works, and only switches after a lot of random manipulations of the plot. But its possible to switch into a mode where vertically zooming in doesn't zoom to the mouse position, but to somewhere closer to the center of the image. Horizontal zoom position always seems to go to the mouse position.

**Comment by rafaqz** [comment]
Ok it can also happen with horizontal zoom, but it seems to be one or the other not both together

**Comment by ffreyer** [comment]
I assume this happened with Axis?

**Comment by asinghvi17** [comment]
I think this was a consequence of the float32 precision issues, since it seems to work now.
