### ISSUE TITLE
GLMakie px_per_unit doesn't work

### ISSUE THREAD

**Issue by 13299118606** [MakieOrg/Makie.jl#3472]
GLMakie v0.8.11：
I don't know if it's a bug or some setting problem.
px_per_unit doesn't work when saving image using GLmakie,
As the example,
`
fig = Figure(size = (800, 600))
`
if normal
```
save("hires.png", fig, px_per_unit = 2) # 1600 × 1200 px png
save("lores.png", fig, px_per_unit = 0.5) # 400 × 300 px png
```

But my saving results are all 800*600px. Is it a bug or a problem with my settings?

**Comment by SimonDanisch** [comment]
This feature was introduced for GLMakie in `Makie@0.20` (GLMakie@0.9).
