### ISSUE TITLE
How does GLMakie adjust the window size  through commands?

### ISSUE THREAD

**Issue by 13299118606** [MakieOrg/Makie.jl#3474]
How does GLMakie adjust the window size through commands?
GLMakie 0.9.3

I tried the latest method like this, but I can't adjust the window size.
```
f = Figure(size = (800, 600))
scatter(f[1,1],rand(50))

f.scene.events.window_area[]=Recti(0, 0, 1000,800)
f.scene.viewport[]=Recti(0, 0, 1000,800)
```

The font will become blurred and the result will be displayed as follows:
![image](https://github.com/MakieOrg/Makie.jl/assets/58963158/d1dd2cd3-c9d0-495d-90dc-d87f4b9f765b)

**Comment by jkrumbiegel** [comment]
`resize!` I think

**Comment by 13299118606** [comment]
> `resize!` I think
Thank you very much, it works
