### ISSUE TITLE
GLMakie 0.9 uses PackageCompiler to  transplant the program "display(fig)" error. however GLMakie 0.8 does not have it.

### ISSUE THREAD

**Issue by 13299118606** [MakieOrg/Makie.jl#3489]
GLMakie 0.9.3 uses PackageCompiler to transplant the program display error. GLMakie 0.8.6 does not have it

Platform windows10 x64
Target platform windows10 x64
Package version: PackageCompiler v2. 1.7

Previous version: GLMakie 0.8.6
Upgraded version: GLMakie 0.9.3

Previously, I used GLMakie 0.8.6 in the package, which worked successfully on other computers. However, after upgrading to GLMakie 0.9.3, an error occurred. The package code is as follows:

```
module SgycutguiAPP
using GLMakie
function glmakie09()
     fig= Figure(resolution=(700, 900))
     println("Create window")
     sgycutwindow = display(GLMakie.Screen(title="glmakie093"), fig)  #display(fig) has the same result
     println("display window")
end
function julia_main()::Cint
     @time  glmakie09()
     println("press any key to exit the program")
     readline()
     GLMakie.closeall()
     return 0
end
end
if abspath(PROGRAM_FILE) == @__FILE__
     julia_main()
end
```
Once the display command is used, an error like this will be displayed.
```
Create window
  SystemError: opening file "C:\\Users\\Administrator\\.julia\\packages\\GLMakie\\29Rzq\\assets\\shader\\postprocessing/fullscreen.vert": No such file or director
```

**Comment by bjarthur** [comment]
@13299118606 this might have been fixed on the very day you posted this issue.  see https://github.com/MakieOrg/Makie.jl/pull/3490.  can you please try again to see if the problem persists?

**Comment by bjarthur** [comment]
see also https://github.com/MakieOrg/Makie.jl/issues/1480#issuecomment-1846323331
