### ISSUE TITLE
[Discussion] Cool stuff with Makie

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#350]
Figured I'd open a meta-issue for discussion of cool stuff that's been done with Makie, and packages that use the Makie/AbstractPlotting ecosystem!  ]

Here's a package:

https://github.com/JuliaHolomorphic/ComplexPhasePortrait.jl

and areally cool logo made by @briochemc:
https://gist.github.com/briochemc/59a84810f70911aab6a23293aebd92c7#file-aibecs_logo-jl
(although that requires https://github.com/briochemc/WorldOceanAtlasTools.jl which is currently unregistered)

Please feel free to add more cool stuff below!

**Comment by asinghvi17** [comment]
The AIBECS logo:
![AIBECS_logo_v2](https://user-images.githubusercontent.com/32143268/57196454-09c9ae80-6f2b-11e9-9bd8-7d870d6e8b57.png)

**Comment by asinghvi17** [comment]
@SimonDanisch, if you could link to your Nextjournal Makie articles here, it would be great!

**Comment by ffreyer** [comment]
There is a discussion section for this
https://github.com/MakieOrg/Makie.jl/discussions/categories/show-and-tell
