### ISSUE TITLE
CairoMakie `display` mutates package directory

### ISSUE THREAD

**Issue by ericphanson** [MakieOrg/Makie.jl#3519]
https://github.com/MakieOrg/Makie.jl/blob/a1d85a1d9ef9ab7397f8197937622634eacb1c8d/CairoMakie/src/display.jl#L34-L56

This causes failures in https://github.com/KristofferC/PkgFsck.jl and doesn't seem like a good idea in general (e.g. I think some folks use read-only shared depots in settings like HPC).

**Comment by jkrumbiegel** [comment]
Agreed, I forgot about that but it's very old behavior and doesn't make any sense :)

**Comment by SimonDanisch** [comment]
Oh yeah,  I guess this should be a tempdir or scratch space...
