### ISSUE TITLE
WGLMakie now throws an error if no screen available

### ISSUE THREAD

**Issue by staticfloat** [MakieOrg/Makie.jl#3535]
- [X] are you running newest version (version from docs) ?
- [X] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)

Whereas previously (before the [Bonito-related changes here](https://github.com/MakieOrg/Makie.jl/commit/40f502b7838767b51abb9c0e62bdf9affa449f88)) it was valid to run tests with WGLMakie-related code on a headless machine, when running `display()`, I am now greeted with the following error on my CI machines:

```
LoadError: MethodError: no method matching wait_for_ready(::Nothing)
  Closest candidates are:
    wait_for_ready(::Bonito.Session; timeout)
     @ Bonito /cache/julia-buildkite-plugin/depots/01896b7a-d6de-46b0-9db6-7af7bf249462/packages/Bonito/UZadz/src/session.jl:21
  Stacktrace:
    [1] display(screen::WGLMakie.Screen, scene::Makie.Scene; unused::@Kwargs{})
      @ WGLMakie /cache/julia-buildkite-plugin/depots/01896b7a-d6de-46b0-9db6-7af7bf249462/packages/WGLMakie/T8XOh/src/display.jl:253
    [2] display(screen::WGLMakie.Screen, scene::Makie.Scene)
      @ WGLMakie /cache/julia-buildkite-plugin/depots/01896b7a-d6de-46b0-9db6-7af7bf249462/packages/WGLMakie/T8XOh/src/display.jl:244
    [3] display(figlike::Makie.Figure; backend::Module, inline::MakieCore.Automatic, update::Bool, screen_config::@Kwargs{})
      @ Makie /cache/julia-buildkite-plugin/depots/01896b7a-d6de-46b0-9db6-7af7bf249462/packages/Makie/fyNiH/src/display.jl:166
    [4] display(figlike::Makie.Figure)
      @ Makie /cache/julia-buildkite-plugin/depots/01896b7a-d6de-46b0-9db6-7af7bf249462/packages/Makie/fyNiH/src/display.jl:130
....
```

It would be nice to get this fixed, so that CI runs can still exercise surrounding code without erroring, even if the WGLMakie plots are not shown anywhere.

**Comment by SimonDanisch** [comment]
Ah I saw that error one time but couldn't reproduce it .. Do you happen to have an MWE?

**Comment by staticfloat** [comment]
We are now working around this by just activating `CairoMakie` in our tests.

**Comment by RomeoV** [comment]
I'm running into this issue when trying to plot a `WGLMakie` figure in a Pluto notebook that otherwise uses `CairoMakie`.
The reason is that my notebook has a large number of figures, so using `WGLMakie` makes the whole notebook quite sluggish, and we use `CairoMakie`. However, I'd like to be able to zoom into individual figures, so I've tried
```julia
display(fig; backend=WGLMakie)
```

Is that something that is generally supported?

MWE:
```julia
## cell 1
begin
	using Makie
	using CairoMakie
	using WGLMakie
	CairoMakie.activate!()
end

## cell 2
scatter(1:2, 1:2)  # works, with CairoMakie

## cell 3
display(scatter(1:2, 1:2); backend=WGLMakie)  # errors, same as issue text
```

**Comment by SimonDanisch** [comment]
I think this is a pluto issue, since it doesn't really support `display`.
I guess we'd need something like `WithBackend(figure, Backend)`, which overloads show correctly to chose the correct backend.
