### ISSUE TITLE
Dead link in GLMakie/README.md

### ISSUE THREAD

**Issue by tpgillam** [MakieOrg/Makie.jl#3539]
There is a dead link to https://github.com/MakieOrg/Makie.jl/blob/master/.github/workflows/glmakie.yaml in `GLMakie/README.md`. I'm not sure what the new link should be though I'm afraid.

( For context: I'm trying to run tests for a package that has a GLMakie dependency in github actions. I'm not trying to do anything other than run Aqua.jl on the package, but I believe this `import`s my package, and hence triggers a "no display" error. I was hoping I might find some hints in this linked file. )

**Comment by jkrumbiegel** [comment]
Thanks for the notice, the contents of that file were recently merged into this file here https://github.com/MakieOrg/Makie.jl/blob/master/.github/workflows/reference_tests.yml#L65

**Comment by tpgillam** [comment]
Thanks @jkrumbiegel ! 

FYI, In my case it ended up being sufficient to just add the following clause to my `julia-runtest` step:
```yaml
- uses: julia-actions/julia-runtest@v1
  with:
    prefix: xvfb-run
```
which I found suggested [in the julia-runtest README](https://github.com/julia-actions/julia-runtest#prefixing-the-julia-command), in case you wanted to link to it in the (GL)Makie readme.

**Comment by jkrumbiegel** [comment]
closed in https://github.com/MakieOrg/Makie.jl/commit/b8334430c67195067804ffc861496d86fdadc0e9
