### ISSUE TITLE
Issues with h/vspan and h/hspan in log space

### ISSUE THREAD

**Issue by astertaylor** [MakieOrg/Makie.jl#3545]
`vspan`, `vspan!`,  `hspan`, and `hspan!` do not work if the x-axis is log-scaled. 

`vspan!` and `hspan!` have the issue with limit transforms that was discussed in #3271 and partially fixed in #3427. It seems like #3427 fixed the limits in `vspan` and `hspan`, but not their in-place version.

 In addition,  none of the functions produce a visible band when the axes are log-scaled, independent of triggering the limit issue discussed above. The fix of the first issue should be relatively simple, since it's been fixed for `hspan` and `vspan`, but I'm unsure on how to fix the other two.

**Comment by ffreyer** [comment]
Can you post an example?

**Comment by astertaylor** [comment]
Absolutely!

Here, no band is visible: 
```
using CairoMakie

fig = Figure()
ax = Axis(fig[1,1], xscale=log10)
vspan!(ax, 1.5, 2, color=(:blue, 0.5))
fig
```
Here, it will be visible:
```
using CairoMakie

fig = Figure()
ax = Axis(fig[1,1])
vspan!(ax, 1.5, 2, color=(:blue, 0.5))
fig
```

and here, you will get a DomainError about the inputs being invalid for log10:
```
using CairoMakie

fig = Figure()
ax = Axis(fig[1,1], xscale=log10)
vspan!(ax, 0.5, 2, color=(:blue, 0.5))
fig
```

**Comment by ffreyer** [comment]
Ah, these work in GLMakie and WGLMakie but not CairoMakie
