### ISSUE TITLE
Issue using scatter and line in 3d together with Vector{Union{Float64,Missing}}

### ISSUE THREAD

**Issue by lupemba** [MakieOrg/Makie.jl#3548]
- GLMakie version = "0.9.5"
- Using new environment
- Windows + Intel(R) UHD Graphics

Example to reproduce bug

```julia
using GLMakie

x = collect(1:1.0:10)
y = collect(1:1.0:10)
z = collect(1:1.0:10)

y_with_missing = Vector{Union{Float64,Missing}}(y)
z_with_missing = Vector{Union{Float64,Missing}}(z)

scatter(x,y_with_missing,z_with_missing; axis=(;type=Axis3))
scatter(x,y,z; axis=(;type=Axis3))
```
The first scatter plot gives this which is wrong since it it more than 10 points

![image](https://github.com/MakieOrg/Makie.jl/assets/30597266/b3a02e2d-0416-408e-8d97-687e736822cc)

The second scatter plots has 10 points as I would expected for this data.
![image](https://github.com/MakieOrg/Makie.jl/assets/30597266/83054f1b-b36a-4bf6-8fcc-561dd3f432e1)

**Comment by lupemba** [comment]
Hi @SimonDanisch,

I have made an issue on the bug I showed you.

**Comment by SimonDanisch** [comment]
This ends up calling:
```julia
function convert_arguments(::PointBased, x::AbstractArray, y::AbstractVector, z::AbstractArray)
    (vec(Point3f.(x, y', z)),)
end
```
Because the more specific `Vector` methods dont apply because of the missing value. I think the fix is to restrict z to a Matrix.

**Comment by lupemba** [comment]
@SimonDanisch 
This works fine with Makie v0.21.2 + GLMakie v0.10.2
I close the issue.
