### ISSUE TITLE
`DataInspector` overcounts the point number in `stairs` plots (GLMakie)

### ISSUE THREAD

**Issue by artemsolod** [MakieOrg/Makie.jl#3549]
`DataInspector` overcounts the point number in `stairs` plots. It appears to be due to counting both vertical and horizontal bars. This makes it cumbersome to access corresponding labels from original data.

```julia
using GLMakie
(fig, _, _) = stairs(1:10; inspector_label=(self, i, p) -> "Point # $i")
DataInspector(fig)
```

Versions: Julia 1.10.0, M2 Mac OS 14.2.1, [e9467ef8] GLMakie v0.9.5

<img width="604" alt="image" src="https://github.com/MakieOrg/Makie.jl/assets/1939268/16302233-ab83-4d75-a16f-395e7fa35df9">

**Comment by Sagnac** [comment]
I think it's because it's ultimately plotting it as a line plot. As a temporary workaround you could use the position instead of the index:
```julia
fig, = stairs(1:10; inspector_label = (_, _, p) -> "Point $(round(Int, p[2]))")
DataInspector(fig)
fig
```

**Comment by ffreyer** [comment]
Yea, this isn't a bug. It's just that DataInspector doesn't try to do work for you here. Ultimately it picks the line which sets the index to the n-th endpoint of a segment. The segment you're hovering is `points[8] -> points[9]`, so it gives you 9.
