### ISSUE TITLE
Repetitive precompilation for GLMakie and GeoMakie since Julia 1.10.0

### ISSUE THREAD

**Issue by oscarvdvelde** [MakieOrg/Makie.jl#3576]
Since I installed Julia 1.10.0, when I run my code, it often needs to precompile GLMakie and sometimes other packages (e.g. GeoMakie but also CSV) even when it has already done so before. I have not updated the packages in between. 
I suspected it could be a 1.10.0 bug, but since most often it occurs with a Makie package, perhaps the issue is with the package.
I noted this redundant precompilation also on my colleague's computer.

  [e9467ef8] GLMakie v0.9.6
⌅ [61d90e0f] GeoJSON v0.7.3
  [db073c08] GeoMakie v0.6.0
  [ee78f7c6] Makie v0.20.5

**Comment by SimonDanisch** [comment]
Do you have any way to reproduce it?

**Comment by oscarvdvelde** [comment]
I tried to reproduce it today, but found no issue.

**Comment by asinghvi17** [comment]
Have you been switching environments a lot?  Some environments may have different versions of packages which cause the precompile files for Makie to become stale, meaning it has to precompile again.  I had a similar issue switching in and out of a lot of different envs...

**Comment by oscarvdvelde** [comment]
> Have you been switching environments a lot? Some environments may have different versions of packages which cause the precompile files for Makie to become stale, meaning it has to precompile again. I had a similar issue switching in and out of a lot of different envs...

I think that could be what was happening. On the other hand, a few days ago I saw a surprise recompilation of CSV when I had not installed or updated any packages or switched environments. Like Makie, I use it daily. In any case, one may close this issue as it seems not specific to Makie.
