### ISSUE TITLE
Label influences aspect of figure and adds unnecessary whitespace

### ISSUE THREAD

**Issue by vandenman** [MakieOrg/Makie.jl#3589]
- [x] are you running newest version (version from docs) ? v0.11.6
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on? A: Manjaro KDE (kernel 6.6.10-1), NVIDIA GeForce RTX 2070.

Calling `Label` seems to change the aspect ratio of a figure and adds unnecessary whitespace.

Here is a basic plot with no unnecessary whitespace.
```julia
using CairoMakie
fig = Figure()
ax = Axis(fig[1, 1])
Box(fig[1, 1], color = (:red, 0.2), strokewidth = 0)
fig
```
![image](https://github.com/MakieOrg/Makie.jl/assets/21319932/cffef7cd-2b23-4602-a306-90fec3604e43)

Now we add a label
```julia
Label(fig[0, 1], "a label")
Box(fig[0, 1], color = (:blue, 0.2), strokewidth = 0)
fig
```
![image](https://github.com/MakieOrg/Makie.jl/assets/21319932/9430bd6d-b7f8-4e70-93d9-ecc31a2f5032)

And suddenly there is whitespace left and right of the figure.

Desired behavior: `Label` should not introduce whitespace left and right of the figure.

**Comment by jkrumbiegel** [comment]
That's not a bug, you need `tellwidth = false` on the `Label` in this case. Sometimes you want things to shrink for labels, sometimes not, so it has to be manually specified if not.

https://docs.makie.org/stable/explanations/faq/#columns_or_rows_are_shrunk_to_the_size_of_text_or_another_element
