### ISSUE TITLE
Error from example '33D Mixed-Agent Ecosystem with Pathfinding'

### ISSUE THREAD

**Issue by nadeen2001** [MakieOrg/Makie.jl#3609]
I have copied an example form the 'Julia Library' line by line and I am constantly receiving this error when running the last visualization step. Please tell me how to fix it.

ERROR: MethodError: no method matching abmvideo(::String, ::StandardABM{ContinuousSpace{3, false, Float64, typeof(Agents.no_vel_update)}, Animal, typeof(Agents.Schedulers.fastest), NamedTuple{(:landfinder, :airfinder, :Δe_grass, :Δe_rabbit, :rabbit_repr, :fox_repr, :hawk_repr, :rabbit_vision, :fox_vision, :hawk_vision, :rabbit_speed, :fox_speed, :hawk_speed, :heightmap, :grass, :regrowth_chance, :water_level, :grass_level, :dt), Tuple{AStar{3, false, true, Float64, DirectDistance{3}}, AStar{3, false, true, Float64, MaxDistance{3}}, Int64, Int64, Float64, Float64, Float64, Int64, Int64, Int64, Float64, Float64, Float64, Matrix{Int64}, BitMatrix, Float64, Int64, Int64, Float64}}, MersenneTwister}, ::typeof(animal_step!), ::typeof(model_step!); figure::NamedTuple{(:resolution,), Tuple{Tuple{Int64, Int64}}}, frames::Int64, framerate::Int64, ac::typeof(animalcolor), as::Float64, static_preplot!::typeof(static_preplot!), title::String)
Stacktrace:
 [1] top-level scope
   @ c:\Users\nadee\OneDrive\tamuq-chen-secarelab-evac\3D example.jl:331

**Comment by SimonDanisch** [comment]
There doesn't seem to be any Makie method involved here and its really not clear what is being run here at all.
I'm closing this.
My guess is, this is an Agents.jl issue!

**Comment by nadeen2001** [comment]
Agents.abmvideo is a function with 0 methods meaning
