### ISSUE TITLE
Zero ticks are missing

### ISSUE THREAD

**Issue by maxfreu** [MakieOrg/Makie.jl#3620]
```julia
using CairoMakie
fig = Figure(size = mm2pt.((83, 50)))
ax = Axis(fig[1, 1])
r = rand(20,30)
colsize!(fig.layout, 1, Aspect(1, size(r)[1] / size(r)[2]))
heatmap!(ax, r; colorrange = (0, 1))
save("deleteme.pdf", fig)
```
![deleteme](https://github.com/MakieOrg/Makie.jl/assets/67329240/6f7c13da-bfed-4cc2-8d52-1d6db2817ae2)

I would expect to see zero ticks in this image. They are also missing for a simple call to heatmap.
Makie 0.20.7, CairoMakie 0.11.8, julia 1.10

**Comment by jkrumbiegel** [comment]
the heatmap cells start counting at 1 and are centered with a width of 1. So the limits start at 0.5, that's why you don't have a zero :)

**Comment by maxfreu** [comment]
Ahh yes, counting would have helped, thanks! Then the only thing is that the outermost pixels are a bit too small, because they are overlapped by the axes. But that's a minor issue and a different one...
