### ISSUE TITLE
Lines and text scale weirdly after emptying axis, adding new plot, and rescaling figure

### ISSUE THREAD

**Issue by dvbr-jntr** [MakieOrg/Makie.jl#3639]
- [X] are you running newest version (version from docs) ?  GLMakie 0.9.8, also reproduced on master
- [X] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)   Yes
- [X] What platform + GPU are you on?  Linux x86_64, integrated Intel GPU

When I create a GLMakie plot and then rescale it using `resize!` or with the mouse,
```
using GLMakie
f=Figure(size=(200,200))
ax=Axis(f[1,1])
lines!(ax,sin.(0.0:0.1:2pi))
text!(ax,10.0,0.0,text="sine wave")
resize!(current_figure(), 800, 800)
save("stretchplot1.png",f)
```
the thickness of the lines does not change. It is independent of plot size as expected:

![stretchplot1](https://github.com/MakieOrg/Makie.jl/assets/160409501/bbd0afe3-d07b-45ba-8300-61facbbe2f0c)

But if I create a plot, clear the axis, add a plot to the axis again, then rescale,
```
f=Figure(size=(200,200))
ax=Axis(f[1,1])
lines!(ax,sin.(0.0:0.1:2pi))
empty!(ax)
lines!(ax, sin.(0.0:0.1:2pi))
text!(ax,10.0,0.0,text="sine wave")
resize!(current_figure(), 800, 800)
save("stretchplot2.png",f)
```
the line thickness scales with the plot size and the text inside the plot gets fuzzy:

![stretchplot2](https://github.com/MakieOrg/Makie.jl/assets/160409501/d460ba23-4daa-48ba-9fdd-0c88419c0b6b)

Rescaling after creating the figure is a weird thing to do. I encountered this effect in a more subtle way while resizing a window with the mouse. The code above illustrates the issue more impressively. Scaling the figure down results in lines turning dotted and then disappearing. Emptying the entire figure and then adding plots does not cause the same issue. Also, markers are not affected, just lines and text.

This behavior does not occur on CairoMakie, and does not occur with GLMakie 0.8.12. I have not checked other versions in the 0.9.x series.

**Comment by ffreyer** [comment]
Seems like `scene.camera.resolution` gets disconnected by doing this.
```julia
f=Figure(size=(200,200))
screen = display(f)
ax=Axis(f[1,1])
lines!(ax,sin.(0.0:0.1:2pi))
empty!(ax)
ids = [robj.id for (_, _, robj) in screen.renderlist]
lines!(ax, sin.(0.0:0.1:2pi))
resize!(current_figure(), 800, 800)
robj = filter(x -> !(x.id in ids), last.(screen.renderlist))[1]
robj.uniforms[:resolution] # 131, 145
ax.scene.camera.resolution # 731, 745
```

**Comment by ffreyer** [comment]
I think the code here is to blame:
https://github.com/MakieOrg/Makie.jl/blob/fe320c0613dd39267eec1c3986a49a61c3d465c2/GLMakie/src/drawing_primitives.jl#L140-L192
There is some caching that got added in #3113 and mostly disabled again in #2868. The plan was probably to re-enable it in #3113 but it didn't, only resolution stuck around. With the `lift(f, plot, ...)` syntax that gets disconnected when a plot is deleted.
