### ISSUE TITLE
Recording of hist plot changes formatting

### ISSUE THREAD

**Issue by DrBurner** [MakieOrg/Makie.jl#3643]
Issue from [this forum post](https://discourse.julialang.org/t/recording-of-makie-hist-changes-output/110440):

Recording a video from a hist plot does not follow the `width` keyword.

```julia
using GLMakie

samples=rand(1:10,100)
samples_Obs = Observable(samples)

fig = Figure(size=(1000,400))
ax = Axis(fig[1,1])
my_bins = range(0.5, 10.5, 11)
hist!(ax, samples_Obs, bins=my_bins, width=0.75)

### using fig alone accepts the width=0.75
fig

### making an animation ignores the width=0.75
record(fig, "time_animation.mp4",1:100; framerate=10) do ind
    samples_Obs[] = samples[1:ind]
end
```

BTW: `width` seems to be not a keyword for [hist](https://docs.makie.org/stable/reference/plots/hist/), but it is for [barplot](https://docs.makie.org/stable/reference/plots/barplot/). Nonetheless it is working for the single figure.

**Comment by ffreyer** [comment]
Attribute validation broke width since it's not an attribute of hist.

**Comment by SimonDanisch** [comment]
```
### using fig alone accepts the width=0.75
fig
```
I'm not sure what you mean by this...
For me this errors at `hist!(...)`

**Comment by SimonDanisch** [comment]
I think this can be closed, unless I'm misunderstanding something?
But as far as I'm concerned hist is not supposed to have a width keyword and errors correctly when calling `hist!`.
