### ISSUE TITLE
Should `convert_single_argument` be in MakieCore?

### ISSUE THREAD

**Issue by musoke** [MakieOrg/Makie.jl#3645]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
```
julia> versioninfo()
Julia Version 1.10.1
Commit 7790d6f0641 (2024-02-13 20:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
Threads: 16 default, 0 interactive, 8 GC (on 16 virtual cores)
Environment:
  LD_LIBRARY_PATH = /snap/alacritty/70/usr/lib/x86_64-linux-gnu:/snap/alacritty/70/lib/x86_64-linux-gnu:/snap/alacritty/70/usr/lib/x86_64-linux-gnu/dri
  JULIA_NUM_THREADS = auto
```
```
$ nvidia-smi -L
GPU 0: NVIDIA RTX A3000 Laptop GPU (UUID: GPU-e990a63d-4550-5bf1-f637-e85571910ab0)
```

----

I am not quite sure if this is a bug report or a feature request.

The current docs [say](https://docs.makie.org/stable/explanations/recipes/):
> If you're a package developer, it's possible to add recipes without adding all of Makie.jl as a dependency. Instead, you can use the MakieCore package, which is a lightweight package which provides all the necessary elements to create a recipe, such as the @recipe macro, convert_arguments and convert_attribute functions, and even some basic plot type definitions.

`convert_single_argument` is one of the main functions that can be used in this context but it is not part of MakieCore.  This means that developers need to import the full Makie package before it can be implemented for new types.  Perhaps this is intentional - is this to discourage package developers from using `convert_single_argument` instead of `convert_arguments`?

**Comment by asinghvi17** [comment]
I think the main use of MakieCore is to define new recipes in a low dependency way - if you just want to define converts, you're probably better off with a package extension?

**Comment by musoke** [comment]
Yes, that might do the trick for me.  Is distinction made because `convert_single_argument` has wider implications than a single recipe?

**Comment by asinghvi17** [comment]
The distinction is more generally between `convert`s and recipes, which generally serve two different purposes (compatibility v/s new features).

**Comment by SimonDanisch** [comment]
Wie also want to phase out MakieCore in general with the new pkg extensions making MakieCore somewhat not needed anymore

**Comment by musoke** [comment]
Makes sense!
