### ISSUE TITLE
Strange behavior when inspecting lines in WGLMakie

### ISSUE THREAD

**Issue by kbarros** [MakieOrg/Makie.jl#3672]
This is a follow-on to https://github.com/MakieOrg/Makie.jl/issues/3503. Not an immediate blocker for us; we've moved away from WGLMakie due to multiple issues (https://github.com/SunnySuite/Sunny.jl/issues/211). GLMakie gives an overall more robust experience, and we're happy with it.

The following snippet leads to strange behavior, as shown in the movie below.

```julia
using WGLMakie
begin
    segments = Point2f[(0, 0), (0, 1), (1, 0), (1, 2)]
    color = [:red, :black, :blue, :black]
    inspector_label(_, i, _) = (@show Int(i); ["hello", "world", "nice", "day"][mod1(i, 4)])
    fig, ax, pl = linesegments(segments; color, inspector_label, linewidth=10)
    DataInspector(ax)
    display(fig; backend=WGLMakie)
end
```

https://github.com/MakieOrg/Makie.jl/assets/290205/6f84876d-7e97-4636-90e4-c6d2a9a3f9b2

**Comment by kbarros** [comment]
If anyone else encounters this, a workaround for us was to use `arrows` instead of `linesegments`. Setting `arrowsize = 0` draws just the line part of an arrow, as a cylinder. With `arrows`, the inspector pop-up works well in both GLMakie and WGLMakie.

**Comment by EdsterG** [comment]
Seems like the index returned by `pick_closest` differs between GLMake and WGLMakie and the ray tracing code has an offset that only works with GLMakie indexing.

What WGLMakie version did you record your video with?

**Comment by kbarros** [comment]
I tried again just now with the master versions of WGLMakie, Bonito, etc. There is still some strange behavior, but not as strange as before. Mousing over the red segment is now fixed: It shows a hover window with the text "hello" in the right position. Mousing over the blue segment now correctly shows a hover window with the correct text "nice". However, in the second case, the "nice" hover is in the wrong the position (it shifts leftward as the mouse position is raised vertically).

**Comment by EdsterG** [comment]
The position is due to the “wrong” index returned by `pick_closest`.

**Comment by SimonDanisch** [comment]
Yeah the shaders in WGLMakie and GLMakie work a bit different and its hard to do exactly the same thing in them for the index.
And it was also not 100% clear to me which is the better behaviour.
Maybe we should first figure out the correct behaviour for the returned index and then figure out how to change (W)GLMakie.

**Comment by EdsterG** [comment]
IMO WGLMakie has the correct behavior. When mousing over the first line it returns index 1 and mousing over the second line index 3. While GLMakie returns 2/4 respectively.

**Comment by EdsterG** [comment]
However, I don't think it really matters what behavior they have as long as they're consistent. Consistency is more important than picking the more convenient implementation detail.

**Comment by ffreyer** [comment]
It wouldn't be hard to have the index be the nearest line point either, because we already have a value for color interpolation along the line. I.e. have
```
-----------------
X    X     X    X  linepoints
-----------------
11122222233333444  picked index
```
as the output. Though maybe it's better to always get the start index of a line segment so that it is consistently given as `ps[idx], ps[idx+1]`.
