### ISSUE TITLE
Suggestions for new features needed in `boxplot`

### ISSUE THREAD

**Issue by zkk960317** [MakieOrg/Makie.jl#3673]
### Feature description
Boxplot is a common plot type in scientific plot, but it's not perfect in Makie. When I want to draw a figure as follows, I'm in trouble. 

![640](https://github.com/MakieOrg/Makie.jl/assets/105714520/19dad62c-4021-4bbe-8e0d-68da6216d88d)

Obviously, this is a combination of `scatter`, `boxplot` and `violin`,  but the keyword "side" is not provided in `boxplot` as `violin` does.

In addition, I think the `boxplot` and `violin` should have the function of "show_data".  The data should be randomly located along _x_ axis, rather than in the same position as shown in the following figure (an example for "show_outliers" in Makie document), which is not conducive to data representation.

![image](https://github.com/MakieOrg/Makie.jl/assets/105714520/20b38c59-6a61-4cd2-8c94-33700340a6e1)

**Comment by asinghvi17** [comment]
Are you looking for [raincloud plots](https://docs.makie.org/dev/reference/plots/rainclouds/)?   They do most of what you're suggesting here :)

![](https://docs.makie.org/dev/assets/reference/plots/rainclouds/code/output/example_436dd56e.png)

**Comment by ffreyer** [comment]
Closing as rainclouds is indeed pretty much what's requested
