### ISSUE TITLE
How to out put \widetilde label on Makie fig

### ISSUE THREAD

**Issue by crazyfireji** [MakieOrg/Makie.jl#3701]
I want to add a  \widetilde label or text on makie, but it doesnt work. The out put should be follow:
![image](https://github.com/MakieOrg/Makie.jl/assets/112403698/7fa23677-cf8d-4aad-8586-e54ad14819b2)

and this question:
![image](https://github.com/MakieOrg/Makie.jl/assets/112403698/ccde49e8-471c-4e56-9a1b-bdf8ac67293b)

**Comment by crazyfireji** [comment]
It doesnt work:
text(0.5,2.0,text = L"\widetilde{ww} ", fontsize=30)

**Comment by jkrumbiegel** [comment]
I think that's an issue for MathTeXEngine.jl
