### ISSUE TITLE
How to modify default setting in Makie

### ISSUE THREAD

**Issue by crazyfireji** [MakieOrg/Makie.jl#3703]
I need plot many pictures using Makie, and I want every fig's  xticksmirrored = true, xticksize=10,  and so on. Now I have to set that in every plot functions. Is there any way to set these terms to default. Thank you very much.

**Comment by jkrumbiegel** [comment]
`set_theme!` and related functions

**Comment by crazyfireji** [comment]
> `set_theme!` and related functions

No, it cant work in set_theme!(Axis...)

**Comment by jkrumbiegel** [comment]
`set_theme!(; Axis = (; xtick...`

**Comment by crazyfireji** [comment]
> set_theme!(; Axis = (; xtick...

Thank you very much, it works!!!
