### ISSUE TITLE
How to modify colors of Colorbar to adapt the values of exp-type data

### ISSUE THREAD

**Issue by crazyfireji** [MakieOrg/Makie.jl#3711]
### Feature description

I want to plot a contourf colored by the exp-type data,:(the color divided by 10^-4,10^3,10^2...) ,like the first fig, but my output is the second fig. 
This is my 

`
test=rand(1:1000,100,100)
fig = Figure(backgroundcolor=:white, 
size = (650, 550))
ax = Axis(fig[1,1])
f=contourf!(ax, test,
colormap=cgrad(:OrRd_3, scale = :exp, categorical = true),
colorscale = log10)
Colorbar(fig[1, 2], f,ticklabelsize=20, 
scale =log10, labelsize = 20)
display(fig)
`

![image](https://github.com/MakieOrg/Makie.jl/assets/112403698/643be87d-de06-4e09-85c7-7c431f1d3cd2)

![image](https://github.com/MakieOrg/Makie.jl/assets/112403698/dea29190-3118-4c1a-9307-09d62a99220f)

**Comment by crazyfireji** [comment]
Now, I have solved it by modify the ticks.
`
fig = Figure(backgroundcolor=:white, 
size = (650, 550))
ax = Axis(fig[1,1])
f=contourf!(ax, log10.(l),
colormap=cgrad(:OrRd_3, categorical = true))
f1=Colorbar(fig[1, 2], f)
f1.ticks=([0,1,2,3],["0",L"10^1",L"10^2",L"10^3"])
display(fig)
`

**Comment by Fenyutanchan** [comment]
Hi, I do not think this is a good solution...
> Now, I have solved it by modify the ticks. `fig = Figure(backgroundcolor=:white, size = (650, 550)) ax = Axis(fig[1,1]) f=contourf!(ax, log10.(l), colormap=cgrad(:OrRd_3, categorical = true)) f1=Colorbar(fig[1, 2], f) f1.ticks=([0,1,2,3],["0",L"10^1",L"10^2",L"10^3"]) display(fig)`

You handle it manually...
But it seems to be a bug...
