### ISSUE TITLE
Makie fails to compile on musl system

### ISSUE THREAD

**Issue by ii8** [MakieOrg/Makie.jl#3725]
When I try to install Makie, julia produces a long list of errors.
Here is the full log: [makieerrors.txt](https://github.com/MakieOrg/Makie.jl/files/14669385/makieerrors.txt)

I'll point out a few parts:

`Error loading shared library libiconv.so.2: No such file or directory`
It's trying to load a libiconv shared object, which doesn't exist. On musl the iconv implementation is contained in the libc object afaik, no separate library should be loaded.

`ERROR: LoadError: Failed to precompile Cairo_jll`
It tries and fails to build something called `Cairo_jll` which doesn't make a lot of sense to me because I didn't install CairoMakie.

`✗ Xorg_libX11_jll`
It also seems to want to build various X libraries which is also strange because I'm not running an X server, there isn't one installed either and I didn't install or try to use a backed that you might expect to have an X11 dependency like GLMakie. I was trying to use WGLMakie which I would think shouldn't need X or cairo.

Platform is void-linux with musl libc, x86_64
I imagine a similar thing would happen on alpine.

**Comment by asinghvi17** [comment]
The libiconv issue sounds like something for [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil), and the Libiconv binaries and Julia wrapper are built here:

https://github.com/JuliaPackaging/Yggdrasil/blob/58ba605f538af3a8cf9fb69f0e060174dbfd78b7/L/Libiconv/build_tarballs.jl

though it may be an issue with the XML wrapper lib as well, also built in Yggdrasil.

I looked at the generated code for Libiconv in https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/blob/main/src/wrappers/x86_64-linux-musl.jl and can confirm it's not pointing to `libc`.  Perhaps someone in Yggdrasil will better know how to handle this...
