### ISSUE TITLE
Inconsistent mouse-over activation of widgets in WGLMakie

### ISSUE THREAD

**Issue by kbarros** [MakieOrg/Makie.jl#3752]
The problem appears with the following code:

```julia
using WGLMakie
fig = Figure()
menu = Menu(fig[1, 1], options = ["viridis", "heat", "blues"], default = "blues")
```

In GLMakie this works fine, but in WGLMakie the interactions are inconsistent. The problem is that mousing over the Menu widget (or similarly, a Button widget) does not reliably "activate" the widget, as indicated by its color. Without activation, the widget cannot be clicked.

In the screen recording below, I am only moving the mouse position, but not attempting to click:

https://github.com/MakieOrg/Makie.jl/assets/290205/fa8de4c8-65f2-4789-b52f-e436732526c5

**Comment by jkrumbiegel** [comment]
Looks like the text is not accepted as part of the menu. Could be something about picking with text not working I guess, as the logic to group the plot objects should be the same as in glmakie

**Comment by kbarros** [comment]
Indeed, I can confirm that mousing over the non-text part of the menu seems to work well.

**Comment by bjarthur** [comment]
i've been digging into this issue as it is a serious problem for me.

if i put `println(picking_data)` [here](https://github.com/MakieOrg/Makie.jl/blob/master/WGLMakie/src/picking.jl#L7) i see `[nothing, 0x00]` when the cursor is directly over each letter, and e.g. `["9040989855524861648", 0x03]` when it is inbetween letters or nowhere near them.

similarly, deeper into the call stack, `console.log(picked_plots_array)` [here](https://github.com/MakieOrg/Makie.jl/blob/master/WGLMakie/src/wglmakie.js#L559) yields a matrix of 0s when the cursor is over numbers and non-zeros elsewhere.

these data ultimately arise from [this](https://github.com/MakieOrg/Makie.jl/blob/master/WGLMakie/src/wglmakie.js#L473-L512) javascript code, which is completely opaque to me.

i'm out of ideas at this point, but would happily spend some more time digging into this if someone can point me in the right direction.  @SimonDanisch

**Comment by kbarros** [comment]
Seems to be fixed for me also!
