### ISSUE TITLE
Makie thread safety: crashes Julia in parallel @spawn and @threads but not in @async

### ISSUE THREAD

**Issue by oscarvdvelde** [MakieOrg/Makie.jl#3753]
- [ ] are you running newest version (version from docs) ?
CairoMakie v0.11.9
- [ ] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
Yes
- [ ] What platform + GPU are you on?
Ubuntu, 32 cores, GPU:  VGA compatible controller: ASPEED Technology, Inc. ASPEED Graphics Family (rev 52)

I made a function that processes data in parallel calling a bash script. With its output, it makes a plot with several panels using CairoMakie. **My old version used `@async` and there were no issues running e.g. 24 time steps in parallel.**
I moved to `@spawn` as I now feed it chunks. The crash happens in a simple loop:
```
@sync for hms in hourminutesec
    @spawn begin
         a,b = myfunction(input, options, true)
     end
end
```

It launches the 24 processes I can track in bash with the top command. There are several scenarios of crash. The most usual is that a julia process is swelling to gigabits of virtual memory, 3200% CPU, and the REPL hangs. Alternatively, it does this and the REPL crashes after dumping a text that I cannot capture. In some occasion I was able to get this: 
```
double free or corruption (!prev)
[221604] signal (6.-6): Aborted
in expression starting at (line calling the function)
```
and similar e.g. corrupted size, malloc()

These crashes only appear when my plot option in the function is true. When set to false, it bypasses the plotting and it successfully will process hours of data in parallel.

I tried to isolated the cause of the crash within the plotting section. It calls `Figure`, 4 `Axis`, `ylims!`, `lines!`, `findmax`, `text!`, `display` and `save`.
This has been the most confusing. It seems I can safely call `fig=Figure(size=(1500,600))` but not with display(fig). On the other hand, I have once been able to create axes and display the figure, get no crash, and progressively adding more plot features in (recompiling the function and maintaining the REPL), and was surprisingly able to plot and save the full figures. However, restarting the REPL and running the script in this same "working" state hangs or kills again the REPL.

Perhaps this crash could be reproduced by placing any code for a figure in a `@spawn` loop, but I have not tried this yet.

**Comment by jkrumbiegel** [comment]
Cairomakie is not threadsafe, for example when accessing FreeType objects because FreeType is also not threadsafe.

**Comment by oscarvdvelde** [comment]
Thank you. I will try a different solution for plotting in this case.
