### ISSUE TITLE
Planned feature: interop with GeoInterface

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#376]
Through a glue package `GeoMakie.jl` we could support [`GeoInterface.jl`](https://github.com/JuliaGeo/GeoInterface.jl), which is an interface for geospatial data in Julia.  It seems to be possible with a few convert_arguments, which I will state here once I wrap my head around how to get them working.  

- convert AbstractPoint to Point2 / 3
- convert AbstractMultiPoint for PointBased to Array{Point}
- convert AbstractLineString to Array{Point}
- convert AbstractPolygon to vertices and indices (or points)
- figure out how to plot multiple series to deal with AbstractMultiLineString and AbstractMultiPolygon

- Needs a series decomposition feature, to plot _n_ geometries in one call.  Perhaps an overload of mesh?

The idea is to lead up to being able to do choropleth vis in Makie.

**Comment by philoez98** [comment]
:+1: from me. We could also adapt other packages to better support this idea. I'll be glad to help, also by making [Turf.jl](https://github.com/philoez98/Turf.jl) fully compatible with your proposal.

**Comment by asinghvi17** [comment]
This may be somewhat deprecated in favour of transitioning JuliaGeo to GeometryBasics.jl, in which case we'd move the type recipes into Makie, and let GeoMakie handle featurecollections and other geographical plotting.

**Comment by asinghvi17** [comment]
https://github.com/visr/GeoJSONTables.jl and JuliaPlots/GeoMakie.jl should go a long way towards solving this.  For info, what I plan to do there is create an argument conversion which works with GeoJSONTables that can meshify Polygons and MultiPolygons, and then you could just plot them directly.  Also in the works is argument conversion for Point, MultiPoint, Line and MultiLine which should allow you to do anything point-based with those, and a choropleth recipe which will allow you to "just plot" a FeatureCollection.

**Comment by asinghvi17** [comment]
Also, a cool thing to do would be to plot a lat/lon "axis", which is transformed to be curved with the projection.  As I see it, this could be done by essentially creating a 2D Axis with lines in pre-transform-space, and text in post-transform-space.

**Comment by asinghvi17** [comment]
Only thing remaining is the choropleth/feature collection stuff - which would be better in Makie anyway!

**Comment by asinghvi17** [comment]
Only thing remaining is the choropleth/feature collection stuff - which would be better in Makie anyway!
