### ISSUE TITLE
Makie documentation for lift incorrectly shows map description.

### ISSUE THREAD

**Issue by jamesahoward** [MakieOrg/Makie.jl#3778]
https://docs.makie.org/stable/api/

Description for `lift` is replaced with `map` description in latest Makie docs.
This also impacts REPL help mode `? lift` and the function call `methods(lift)`.

![makie_docs](https://github.com/MakieOrg/Makie.jl/assets/96961792/29047902-d776-473d-900d-8313d9fd5867)

**Comment by asinghvi17** [comment]
That's probably because `Observables` defines `const lift = map`.

**Comment by felixcremer** [comment]
This is a duplicate of #3186. We could add a specific docstring for lift.

**Comment by ffreyer** [comment]
Closing as duplicate
