### ISSUE TITLE
CairoMakie fails to precompile on macOS

### ISSUE THREAD

**Issue by mxhbl** [MakieOrg/Makie.jl#3790]
I cannot get CairoMakie to precompile on macOS. The problem is that Cairo.jl cannot compile due to [JuliaGraphics/Cairo.jl#362](https://github.com/JuliaGraphics/Cairo.jl/issues/362). Since Cairo.jl seems to be not-so-actively maintained, I thought I'd open an issue here to see if there is a way to fix it.

To reproduce the error on macOS 11.7, Julia 1.10.2, run
```
pkg> activate --temp
pkg> add CairoMakie
```
which will result in
```
PkgPrecompileError: The following 1 direct dependency failed to precompile:

CairoMakie [13f3f980-e62b-5c42-98c6-ff1f3baf88f0]

Failed to precompile CairoMakie [13f3f980-e62b-5c42-98c6-ff1f3baf88f0] to "/Users/user/.julia/compiled/v1.10/CairoMakie/jl_iR81Xh".
ERROR: LoadError: InitError: could not load library "/Users/user/.julia/artifacts/80b8948d1fa864a4974c0d4e71ddce9586311598/lib/libpangocairo-1.0.0.dylib"
dlopen(/Users/user/.julia/artifacts/80b8948d1fa864a4974c0d4e71ddce9586311598/lib/libpangocairo-1.0.0.dylib, 1): Library not loaded: @rpath/libcairo.2.dylib
  Referenced from: /Users/user/.julia/artifacts/80b8948d1fa864a4974c0d4e71ddce9586311598/lib/libpangocairo-1.0.0.dylib
  Reason: Incompatible library version: libpangocairo-1.0.0.dylib requires version 11603.0.0 or later, but libcairo.2.dylib provides version 2.0.0

```

**Comment by jkrumbiegel** [comment]
Hm as you're already linking the right issue in Cairo.jl this does not seem like something that is actionable for us in this repo (we have too many dependencies to collect their issues here I would argue). I'm going to close this issue but to get assistance you might try to get some of the binarybuilder people on Slack look into this. They are the best at solving these kinds of issues.

**Comment by mxhbl** [comment]
Alright, thanks for the pointer!

**Comment by giordano** [comment]
Fixed with https://github.com/JuliaPackaging/Yggdrasil/pull/8497.
