### ISSUE TITLE
Very old version of Makie installed recently

### ISSUE THREAD

**Issue by JuanVargas** [MakieOrg/Makie.jl#3802]
OS Linux Ubuntu 22.04.4 LTS
Julia version 1.10.2
Makie v0.15.0
GLMakie v0.4.4

ISSUE 1:
Pkg.status() tells me that there new versions for Makie, and GLMakie. I tried to get those versions with no success, as follows:

Pkg.rm("Makie")
Pkg.add("Makie")
Pkg.update()
Pkg.status()  # I see the same old version 
or
Pkg.rm("Makie")
Pkg.build("Makie")
Pkg.update()
Pkg.status()  # I see the same old version 
 
ISSUE 2: Code that was running yesterday no longer works, with no explanation or way to trace back reason.
The calls to scatter! and text! fail.

f = Figure( )
ga = f[1,1] = GridLayout()
ax = Axis(f[1, 1], limits=((0,10), (0,10)),
    title = "Semantic Feature Space",
    xlabel = "Gender",
    ylabel = "Age"
)

#scatter!(ax, 1, 2, marker=:circle, markersize=10, color=:red)
#scatter!(ax, 1, 7,  marker=:circle, markersize=10, color=:red)
#scatter!(ax, 9, 2,  marker=:circle, markersize=10, color=:blue)
#scatter!(ax, 9, 7, marker=:circle, markersize=10, color=:blue)
#text!(ax, 1, 2, text="boy")
#text!(ax, 1.1, 7, text="man")
#text!(ax, 9.1, 2, text="girl")
#text!(ax, 9.1, 7, text="woman")

ISSUE 3: Code below, taken verbatim from the Julia/Makie docs fails

using CairoMakie

f, ax, sc = scatter(1, 1, marker = 'A', markersize = 50)
text!(2, 1, text = "A", fontsize = 50, align = (:center, :center))
xlims!(ax, -1, 4)
f

error msg is that Point2f is not defined 

QUESTION 1: how can I upgrade to the "current" versions of Makie and GLMakie?
QUESTION 2: Why are the docs and tutorials not tested to ensure that the code shown there actually works?

Thank you

**Comment by asinghvi17** [comment]
It looks like you're running a really old version of Makie - so it's no surprise that current tutorials would fail there.

Have you tried `Pkg.add(PackageSpec(; name = "Makie", version = "0.20.9"))`, to see what is holding you back from upgrading?

**Comment by JuanVargas** [comment]
When I try

Pkg.add(PackageSpec(; name = "Makie", version = "0.20.9"))

I get

ERROR: UndefVarError: `PackageSpec` not defined

**Comment by JuanVargas** [comment]
* Pkg.add(name="Makie", version="0.20.9")*
   Resolving package versions...
ERROR: *Unsatisfiable requirements detected for package FreeTypeAbstraction
[663a7486]:*
 FreeTypeAbstraction [663a7486] log:
 ├─possible versions are: 0.4.0-0.10.3 or uninstalled
 ├─restricted by compatibility requirements with AbstractPlotting
[537997a7] to versions: 0.4.0-0.9.9
 │ └─AbstractPlotting [537997a7] log:
 │   ├─possible versions are: 0.9.0-0.18.3 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only
versions: 0.9.0-0.18.3
 └─restricted by compatibility requirements with Makie [ee78f7c6] to
versions: 0.10.0-0.10.3 — no versions left
   └─Makie [ee78f7c6] log:
     ├─possible versions are: 0.9.0-0.20.9 or uninstalled
     └─restricted to versions 0.20.9 by an explicit requirement, leaving
only versions: 0.20.9
Stacktrace:
  [1] propagate_constraints!(graph::Pkg.Resolve.Graph, sources::Set{Int64};
log_events::Bool)
    @ Pkg.Resolve
/opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1072
  [2] propagate_constraints! (repeats 2 times)
    @
/opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1008
[inlined]
  [3] simplify_graph!(graph::Pkg.Resolve.Graph, sources::Set{Int64};
clean_graph::Bool)
    @ Pkg.Resolve
/opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1533
  [4] simplify_graph! (repeats 2 times)
    @
/opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1532
[inlined]
  [5] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{…},
pkgs::Vector{…}, julia_version::VersionNumber, installed_only::Bool)
    @ Pkg.Operations
/opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:407
  [6] targeted_resolve(env::Pkg.Types.EnvCache, registries::Vector{…},
pkgs::Vector{…}, preserve::Pkg.Types.PreserveLevel,
julia_version::VersionNumber)
    @ Pkg.Operations
/opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1360
  [7] tiered_resolve(env::Pkg.Types.EnvCache, registries::Vector{…},
pkgs::Vector{…}, julia_version::VersionNumber, try_all_installed::Bool)
    @ Pkg.Operations
/opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1349
  [8] _resolve(io::Base.TTY, env::Pkg.Types.EnvCache,
registries::Vector{…}, pkgs::Vector{…}, preserve::Pkg.Types.PreserveLevel,
julia_version::VersionNumber)
    @ Pkg.Operations
/opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1370
  [9] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec},
new_git::Set{Base.UUID}; preserve::Pkg.Types.PreserveLevel,
platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations
/opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1387
 [10] add
    @ /opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1376
[inlined]
 [11] add(ctx::Pkg.Types.Context, pkgs::Vector{…};
preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform,
***@***.***{…})
    @ Pkg.API /opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/API.jl:278
 [12] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, ***@***.***
{})
    @ Pkg.API /opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/API.jl:159
 [13] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/API.jl:148
 [14] add
    @ /opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/API.jl:146
[inlined]
 [15] add(; name::String, uuid::Nothing, version::String, url::Nothing,
rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing,
***@***.***{})
    @ Pkg.API /opt/julia-1.10.2/share/julia/stdlib/v1.10/Pkg/src/API.jl:176
 [16] top-level scope
    @ REPL[40]:1
Some type information was truncated. Use `show(err)` to see complete types.

**Comment by SimonDanisch** [comment]
You need to remove AbstractPlotting

**Comment by JuanVargas** [comment]
Thank you for your suggestion. I did the following to get the
newer versions of Makie and GLMakie:

1.Removed all the content I had under ~/.julia
2. Launched Julia, added Makie, then GLMakie, then update

Now I have Makie v0.20.9 and GLMakie0.9.10

Will test code and go from there.

Thank you
