### ISSUE TITLE
CairoMakie depends on FFTW

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#3810]
I can't see why, seems like it was introduced 5 years ago https://github.com/MakieOrg/Makie.jl/commit/13049828d59a5890cb8884e5dbdc8b84170064f7

Noticed this as I was checking where our MKL_jll dep comes from. We would still depend on FFTW because it's pulled in via KernelDensity → FFTW → MKL_jll but we can still remove explicit FFTW from CairoMakie I think.

**Comment by asinghvi17** [comment]
Makes sense to remove it then!  It may have been to fix a compatibility issue or to ensure the version was up to date back then...

**Comment by SimonDanisch** [comment]
Yeah lets remove it!

**Comment by musoke** [comment]
fixed in 028ccb6b0dfb7c5337823265f82ef0d57e12372e
