### ISSUE TITLE
Scatter with 3 length-1 vectors plots in 2D not 3D

### ISSUE THREAD

**Issue by dlfivefifty** [MakieOrg/Makie.jl#3813]
- [X] are you running newest version (version from docs) ?
- [X] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [X] What platform + GPU are you on? Mac, Radeon Pro

In both CairoMakie and GLMakie the following produces a 2D plot instead of a 3D one:
```julia
julia> scatter([1.], [2.], [3.])
```

![display](https://github.com/MakieOrg/Makie.jl/assets/1229737/dd44f414-af94-4cc5-8f08-a1e67b79ff68)

If I call with length-2 vectors it works fine (eg  `scatter([1.,2], [2.,3], [3.,4])`).

**Comment by asinghvi17** [comment]
This is probably because the z component of the bounding box is flat.  We need better ways of determining 3D-ness...

**Comment by asinghvi17** [comment]
The LScene can't figure out the axis limits so it looks blank, but this is at least 3D now:
![iTerm2 DXA4oT](https://github.com/user-attachments/assets/f1194806-b9d7-459f-b33b-b4eee54bfd60)
