### ISSUE TITLE
Automated density legend labels do not take into account line style

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#3818]
MWE:
```julia
fig, ax = density(randn(1000); label = "test", color = (:red, 0.25), linestyle = :dash, strokecolor = :red, strokewidth = 3)
axislegend(ax)
fig
```
![image](https://github.com/MakieOrg/Makie.jl/assets/19669089/d593c443-6c78-41ba-af0f-fa0cb00211c4)

Legend entry doesn't have dashed style.

Version:
  [13f3f980] CairoMakie v0.11.10
  [ee78f7c6] Makie v0.20.9
Windows 10

**Comment by ffreyer** [comment]
Fixed
