### ISSUE TITLE
Can't enter text in textbox on WGLMakie

### ISSUE THREAD

**Issue by RomeoV** [MakieOrg/Makie.jl#3820]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?

### Problem
Can't enter any text into the textbox. Consider the following setup
```julia
using WGLMakie
fig = Makie.Figure()
txt = Textbox(fig[1,1])
```
Now, opening the figure in the browser (firefox or chromium) doesn't let me enter any text. I can click into the textbox though and "clear" the text. Other widgets work fine. The textbox also works fine in GLMakie.

### Platform
Linux (archlinux), tested with latest firefox and chromium.
Tested with
- `WGLMakie@0.9.9, Makie@0.20.9`
- `WGLMakie v0.7.4, Makie@0.18.4`
- (Had trouble building `WGLMakie@0.8`)

**Comment by RomeoV** [comment]
Interestingly, I can paste numbers into the textfield with Ctrl+V...

**Comment by RomeoV** [comment]
I'm not sure if it's related, but on mobile I can't type anything in either (same setup), but actually because the keyboard doesn't pop up in the first place.

**Comment by RomeoV** [comment]
Actually indeed it seems looking at the implementation of `Textbox` that only a few special buttons are handled?
https://github.com/MakieOrg/Makie.jl/blob/2a2a271a1bf64758cf487d7752653c3bcd7a035d/src/makielayout/blocks/textbox.jl#L235-L259

**Comment by RomeoV** [comment]
This patch would implement simple typing. Am I missing something why this doesn't need to be added?
Since in GLMakie the typing works, I assume perhaps it is also handled elsewhere, but I can't find it.

```
diff --git a/src/makielayout/blocks/textbox.jl b/src/makielayout/blocks/textbox.jl
index f679c7a92..5b70857e6 100644
--- a/src/makielayout/blocks/textbox.jl
+++ b/src/makielayout/blocks/textbox.jl
@@ -256,6 +256,12 @@ function initialize_block!(tbox::Textbox)
                     cursor_forward()
                 elseif key == Keyboard.left
                     cursor_backward()
+                else
+                    char = Char(UInt(key))
+                    if is_allowed(char, tbox.restriction[])
+                        insertchar!(char, cursorindex[] + 1)
+                        return Consume(true)
+                    end
                 end
             end
             return Consume(true)
```

**Comment by jkrumbiegel** [comment]
I don't know what would be needed for the keyboard to pop up on mobile, probably some Javascript needed there as the code just listens for keyboard events
