### ISSUE TITLE
`IntervalsBetween` cannot be used for Theming because it lives in Makie.jl

### ISSUE THREAD

**Issue by Moelf** [MakieOrg/Makie.jl#3836]
It's quite useful to have `IntervalsBetween` as part of the default theme, right now one needs to depend on Makie.jl which is a bit too large.

**Comment by asinghvi17** [comment]
Is this still an issue now that package extensions can be used, though?

**Comment by Moelf** [comment]
kind of, because the themes are usually a variable, and you can't introduce new identifiers into the namespace with Pkg extension

**Comment by asinghvi17** [comment]
Wouldn't a pattern like this solve that though?
```julia
# MyModule.jl
function mytheme end
# MyModuleMakieExt.jl
import MyModule: mytheme
mytheme() = ...
```

Also themes (at least in Makie/MakieThemes) are usually functions as far as I've seen?

**Comment by SimonDanisch** [comment]
We kind of want to remove MakieCore, so maybe we should make an issue where we collect, if there's anything important that can't be done without a MakieExt, or any other disadvantage.

**Comment by Moelf** [comment]
I don't think we can define new functions in Extension, so it would be nice to keep recipe magic macros in MakieCore

**Comment by asinghvi17** [comment]
That's also solvable by defining function stubs and importing them into the extension.

**Comment by Moelf** [comment]
yes, I mean, everything is solvable -- but at the entry-level, it increases code repetition (a bit like C++ declaration and definition).

In the end one could argue because this is developer-facing it's fine, although I think "defining plotting" is so common we want to make the common case as simple as possible

**Comment by jkrumbiegel** [comment]
Having MakieCore is not necessarily simple though, as this example also shows. It's hard to define some arbitrary boundary and it also complicates development a bit to have multiple packages where one would do.
