### ISSUE TITLE
Slider startvalue problems

### ISSUE THREAD

**Issue by tuncbkose** [MakieOrg/Makie.jl#3849]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)

In trying to use `Bonito.jl` with `WGLMakie`, I noticed that Sliders startvalue is not respected: both the following doesn't behave as expected.
```julia
using WGLMakie, Bonito
Page(exportable=true, offline=true)
WGLMakie.activate!()

App() do session
    s = Slider(1:5, startvalue=2)
    value = map(s.value) do x
        return x ^ 2
    end
    # Record states is an experimental feature to record all states generated in the Julia session and allow the slider to stay interactive in the statically hosted docs!
    return Bonito.record_states(session, DOM.div(s, value))
end

App() do session
    slider = Slider(1:10, startvalue = 2)
    slider_val = DOM.p(slider[])
    
    onjs(session, slider.value, js"""function on_update(new_val) {
        const p_element = $(slider_val)
        p_element.innerText = new_val
    }
    
    """)

    Bonito.on_document_load(session, js"""
        const p_element = $(slider_val)
        console.log("slider: ", p_element.innerText)
    """)

    return DOM.div(slider, slider_val)
end
```

The result in the static website in Firefox:
![image](https://github.com/MakieOrg/Makie.jl/assets/48298909/64f1e009-d054-4135-b090-d87a75b7fb5f)

Curiously, in Chrome, the second slider visual is also at 1, not sure why that would behave differently.

**Comment by SimonDanisch** [comment]
The problem here is that Slider doesn't error for unsupported arguments. There is currently no startvalue, but you should be able to do `slider[] = value` to set it to a value.
