### ISSUE TITLE
Changes made to `Camera3D` were not reflected in the changelog

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#3852]
`cam3d.attributes` no longer exists, it seems to be `cam3d.controls` now, which broke some end-user workflows.  Any other changes should probably also be mentioned.

**Comment by ffreyer** [comment]
That happened in 0.20 #2746

**Comment by asinghvi17** [comment]
Gotcha!  I didn't see it in the breaking section for 0.20 so probably missed that.  Will make a PR to fix at some point.
