### ISSUE TITLE
Categorical colormaps for meshes/poly or contour plots on meshes

### ISSUE THREAD

**Issue by baxmittens** [MakieOrg/Makie.jl#3863]
### Feature description
Hello,
first of all: Makie.jl is a great package. Thank you guys for your efforts.

What I would like to do is plot contours on a mesh or a poly.

```Julia
using CairoMakie
f = Figure();
ax = Axis(f[1, 1]);
cmap = cgrad(:viridis, 2, categorical = true)
verts = Makie.GeometryBasics.Point2f[(0,0),(0,1),(1,0)]
colrs = [0,0,1]
poly!(ax, verts, color = colrs, colorrange=(0,1), colormap=cmap)
Colorbar(f[2, 1], limits = (0,1), colormap = cmap, vertical = false)
f
```

It seems like Makie is converting the `color = colrs`-values to colors first and then do an interpolation of the colors for each pixel in the triangle.

![image](https://github.com/MakieOrg/Makie.jl/assets/100423479/a1e9a01c-bb36-438c-8cc2-a56e62f67d11)

I would like to have it the other way around. First do an interpolation of the `color = colrs`-values and then transform it to a color according to the colormap. 

<img width="1187" alt="image" src="https://github.com/MakieOrg/Makie.jl/assets/100423479/e05c7a6e-5821-4fe0-978f-fa6ece47c387">

Is there a way to do this in Makie right now?

Thx in advance.

Graetz max

**Comment by asinghvi17** [comment]
What you ask for will work in GLMakie but not in CairoMakie, since vector graphics standards only support interpolation over colours in meshes and not values.

**Comment by baxmittens** [comment]
Thank you for your answer.

Can you tell me how this would work or guide me to an example somewhere?

I want to achieve something like that (which is, I think, a standard way to do color plots for field results)

<img width="1046" alt="image" src="https://github.com/MakieOrg/Makie.jl/assets/100423479/656a3188-792f-4048-ac64-22326ca150b5">

For the latter, I refined the mesh to 3_066_880 elements and provided a constant color for each element, which looks okay but is not perfect.

**Comment by asinghvi17** [comment]
Hmm, in this case I would use `tricontourf` instead, if you have a known mesh.  You can create a `DelaunayTriangulation.Triangulation` from that mesh, and pass it to tricontourf.  

As you saw, GLMakie will do the interpolation correctly, but if you need a vector renderer then `tricontourf` should do the job!

**Comment by baxmittens** [comment]
Hey @asinghvi17 

thanks again for your answer.
`tricontourf` is exactly what I was looking for.
But as the name is `tricontourf`, I am a bit irritated that I cannot provide a vector with vertices and a vector with indices to that method like
```julia
vertices = Point2f[ ... ]
indices = Tuple{Int,Int,Int}[(1,2,3),(2,3,4),...]
vertexcolors = rand(Float64, length(vertices))
tricontourf(vertices, indices, color=vertexcolors)
```
That would be so easy and convenient. I looked in the recipe, but it would be hard for me to alter.
`DelaunayTriangulation.Triangulation` is such a high-level construct. Since my domain is non-convex, I would have to compute the boundary of the domain first and provide it as a closed loop (or am I wrong here?). But I know the triangulation so I would rather want to avoid that.

Maybe there is a different solution?
But if not, I think it would maybe be a useful addition to that method to support a triangulation in the notation described above.

**Comment by jkrumbiegel** [comment]
Maybe @DanielVandH could clarify

**Comment by DanielVandH** [comment]
The `tricontourf` docstring mentions this case:

```
  triangulation = DelaunayTriangulation() — The mode with which the points in xs and ys are triangulated. Passing DelaunayTriangulation() performs a Delaunay triangulation. You can also pass a preexisting triangulation as an AbstractMatrix{<:Int} with size (3, n), where each column specifies the vertex    
  indices of one triangle, or as a Triangulation from DelaunayTriangulation.jl.
```

Just make your `indices` a matrix.

**Comment by baxmittens** [comment]
Thank you very much. This is what I was looking for. Closing this for now...
