### ISSUE TITLE
Make image plotting the same orientation as in Plots.jl

### ISSUE THREAD

**Issue by logankilpatrick** [MakieOrg/Makie.jl#389]
Why does the plotting of an image not have the same orientation as in Plots.jl? Seems a little unfriendly to me. Maybe we can just rotate by default when displaying behind the scenes?

**Comment by mschauer** [comment]
See #205 for the gory discussion which let to the current compromise/solution.

**Comment by felixcremer** [comment]
This should be closed as dup of #205.
