### ISSUE TITLE
Wrap tutorial doesn't work anymore

### ISSUE THREAD

**Issue by Moelf** [MakieOrg/Makie.jl#3901]
in #3736 and #3816 we added https://docs.makie.org/v0.21/tutorials/wrap-existing-recipe

but it actually doesn't work anymore:

```julia
julia> using MakieCore, CairoMakie

julia> struct MyHist
           bincounts
           bincenters
       end

julia> function Makie.plot!(plot::Hist{<:Tuple{<:MyHist}})
           barplot!(plot, plot[1])
           plot
       end

julia> hist(h; color=:red, direction=:x)
ERROR: ArgumentError:     Conversion failed for Plot{Makie.barplot} (With conversion trait PointBased()) with args: Tuple{MyHist} .
    Plot{Makie.barplot} requires to convert to argument types Tuple{AbstractVector{<:Union{Point2, Point3}}}, which convert_arguments didn't succeed in.
    To fix this overload convert_arguments(P, args...) for Plot{Makie.barplot} or PointBased() and return an object of type Tuple{AbstractVector{<:Union{Point2, Point3}}}.`
```

@SimonDanisch @asinghvi17

**Comment by asinghvi17** [comment]
I don't think the specific example you showed should ever work - the error message is correct in this case, barplot doesn't have an overload defined for MyHist.  

You would want `barplot!(plot, @lift($(plot[1]).bincenters), @lift($(plot[1]).bincounts))` which does work (though it doesn't pass attributes down).

**Comment by Moelf** [comment]
Good point 🤔.

In this case I want to add extra keyword arguments to errorbar(MyHist), they change how the errorbars are calculated. I think in this case I have to defer these into the convert arguments, but how? Can I just add extra arguments to convert_arguments?

**Comment by asinghvi17** [comment]
`used_attributes` should do it

**Comment by asinghvi17** [comment]
See e.g. [SciMLBase's Makie ext](https://github.com/SciML/SciMLBase.jl/blob/f2a9b0c0e10802e9c9171ec2ca875f268e153dd1/ext/SciMLBaseMakieExt.jl#L33-L47) for an example.

**Comment by Moelf** [comment]
You mean I have to specify plot type?

Btw just as an FYI, this approach did work before 0.21, maybe by mistake?

**Comment by asinghvi17** [comment]
Both plot type and argument types for dispatch purposes.  So for example 
```julia
Makie.used_attributes(::Type{<: Errorbars}, h::Hist1D) = (:error_function,)
Makie.convert_attributes(::Type{<: Errorbars}, h::Hist1D; error_function = nothing) = do_something(h, error_function)
```

As for this working before 0.21: did the plot turn out correct?!  That would definitely be a mistake IMO :D

**Comment by Moelf** [comment]
plot looks correct:  https://github.com/Moelf/FHist.jl/pull/118

**Comment by Moelf** [comment]
>Makie.convert_attributes(::Type{<: Errorbars}, h::Hist1D; error_function = nothing) = do_something(h, error_function)

you meant `convert_arguments`?

**Comment by asinghvi17** [comment]
ah yes, my bad

**Comment by Moelf** [comment]
worked like a charm: https://github.com/Moelf/FHist.jl/pull/118#issuecomment-2137395849
