### ISSUE TITLE
Formatting.jl is causing warnings when installing

### ISSUE THREAD

**Issue by Yann-C-INN** [MakieOrg/Makie.jl#3902]
- [ ]  Julia 1.10.3.
- [ ] irrelevant
- [ ] Windows,11 no GPU (i think)
I installed Tidier.jl and since they are built on top of Maki-e I got a warning regarding a dependncy, Formatting.jl
Not sure if its a false-alarm or something you guys should change. i hope i am not breaking into an open door.

What I did: `]add Tidier`
What I got:  
```
dependency had output during precompilation:
┌ Formatting
│  ┌ Warning: DEPRECATION NOTICE
│  │
│  │ Formatting.jl has been unmaintained for a while, with some serious
│  │ correctness bugs compromising the original purpose of the package. As a result,
│  │ it has been deprecated - consider using an alternative, such as
│  │ `Format.jl` (https://github.com/JuliaString/Format.jl) or the `Printf` stdlib directly.
│  │
│  │ If you are not using Formatting.jl as a direct dependency, please consider
│  │ opening an issue on any packages you are using that do use it as a dependency.
│  │ From Julia 1.9 onwards, you can query `]why Formatting` to figure out which
│  │ package originally brings it in as a dependency.
```
```
 Makie → Formatting
  Tidier → TidierPlots → AlgebraOfGraphics → Makie → Formatting
  Tidier → TidierPlots → CairoMakie → Makie → Formatting
  Tidier → TidierPlots → Makie → Formatting
  TidierPlots → AlgebraOfGraphics → Makie → Formatting
```

Yann

**Comment by jkrumbiegel** [comment]
The latest Makie versions have switched to Format, so updating should fix this:

https://github.com/MakieOrg/Makie.jl/blob/f3e9013222aba5a55bb934137b8b5714b831bb8c/Project.toml#L24

**Comment by Yann-C-INN** [comment]
> The latest Makie versions have switched to Format, so updating should fix this:
> 
> https://github.com/MakieOrg/Makie.jl/blob/f3e9013222aba5a55bb934137b8b5714b831bb8c/Project.toml#L24

thanks. Is it something I fix locally simply by re-installing Makie or if another package (Tidier.jl in that case) has the previous version it will still pop this warning?

**Comment by jkrumbiegel** [comment]
Probably Tidier hasn't allowed latest AoG or Makie in its compat settings yet.

**Comment by kdpsingh** [comment]
Tagging @rdboyes for awareness on TidierPlots.
