### ISSUE TITLE
Cutting planes (volumetric visualization)

### ISSUE THREAD

**Issue by timholy** [MakieOrg/Makie.jl#3908]
### Feature description

For visualization of volumes that are complex or not very transparent, it would be nice to combine the advantages of `volume` and `volumeslices` through implementation of a "cutting plane": on one side of the plane, the volume is rendered, but on the other side it is as if that portion of the object had been cut away. One could then animate the position of the cutting plane to scan through the volume, always seeing the exposed surface. Think, for example, of progressively shaving away the surface of a [geode](https://assets3.fossilera.com/sp/615738/geodes/quartz-var-amethyst-calcite.jpg) and seeing each newly-exposed face.

### For plot types, please add an image of how it should look like

Here's one example:
https://youtu.be/IEP0mL8P7GA?feature=shared&t=60

**Comment by ffreyer** [comment]
#2783 effectively implements this, though with the goal of setting a clipping cube for Axis3. If we work out how to do it in WGLMakie and clean up the interface that pr should close this issue.
