### ISSUE TITLE
 HTTP/1.1 401 Unauthorized while building GLFW on Buster

### ISSUE THREAD

**Issue by citron** [MakieOrg/Makie.jl#391]
Hello
On Debian Buster, with JuliaPro, I am unable to install Makie. It stops at the GLFW build process.
It does not seem related to any GL misconfiguration, but to a github access problem. 
Any Idea ?

 (v1.2) pkg> build GLFW
  Building CMake → `~/.juliapro/JuliaPro_v1.2.0-1/packages/CMake/nSK2r/deps/build.log`
  Building GLFW ─→ `~/.juliapro/JuliaPro_v1.2.0-1/packages/GLFW/e257h/deps/build.log`
┌ Error: Error building `GLFW`: 
│ ERROR: LoadError: HTTP.ExceptionRequest.StatusError(401, HTTP.Messages.Response:
│ """
│ HTTP/1.1 401 Unauthorized
│ Date: Sat, 21 Sep 2019 08:23:29 GMT
│ Content-Type: text/plain; charset=utf-8
│ Transfer-Encoding: chunked
│ Server: GitHub.com
│ Status: 401 Unauthorized
│ WWW-Authenticate: Basic realm="GitHub"
│ Cache-Control: no-cache
│ X-Request-Id: 8343d4a9-87bd-4572-b730-2f8fa3b94db6
│ Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
│ X-Frame-Options: deny
│ X-Content-Type-Options: nosniff
│ X-XSS-Protection: 1; mode=block
│ Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
│ Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
│ Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com collector.githubapp.com avatars0.githubusercontent.com avatars1.githubusercontent.com avatars2.githubusercontent.com avatars3.githubusercontent.com github-cloud.s3.amazonaws.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com
│ X-GitHub-Request-Id: BC80:F941:3AF8C2B:59E0944:5D85DE00
│ 
etc.

**Comment by asinghvi17** [comment]
Looks like a curl error - GLFW is a binary dependency downloaded by GLMakie.  Are you behind a firewall by any chance?

**Comment by citron** [comment]
I am behind a firewall but nothing special. I do have full access to the web.
Also, my PC is a headless system with a GPU and RealVNC.

**Comment by asinghvi17** [comment]
Does this happen consistently when you try to install Makie?

**Comment by citron** [comment]
Yes

**Comment by bullpup** [comment]
Same happens to me...

**Comment by SimonDanisch** [comment]
This must be a https://github.com/JuliaPackaging/BinaryProvider.jl/ issue...

**Comment by ffreyer** [comment]
Closing as outdated/probably not a Makie issue.
