### ISSUE TITLE
GLMakie: `offset_bezierpath` ends in infinite recursive loop as a result of calling `scatter!`

### ISSUE THREAD

**Issue by melyso** [MakieOrg/Makie.jl#3913]
This error occurs with v10.0.3 of GLMakie, which should correspond to the latest version of Makie, with julia v1.10. I haven't tried with any other back-end.

The error does not occur with GLMakie v0.9.11 with same julia version.

I am running MacOs Monterey (12.6) on an M1 Max chip, (which I think would specify both CPU and GPU, correct me if I am wrong). The error also occured on MacOs Sonoma (14.4.1) on an intel i9 chip with AMD Radeon Pro 5500M.

The error occurs with a completely fresh environment.

Most barebones MWE:
```julia
using GLMakie

bp = BezierPath([
    MoveTo(Point(0,0)),
    EllipticalArc(Point(0, 0), 1, 1, 0, 0, 2pi),
    ClosePath()
])
atlas = Makie.TextureAtlas()
scale = 9
offset = [-0.45, -0.45]
Makie.offset_bezierpath(atlas, bp, scale, offset)
```
This leads to a `StackOverflowError`, and from inspecting the code, it seems like there is some "preparatory" version of the function that is intended to call another variant of `offset_bezierpath`, but instead ends up calling itself in an infinite loop.

This is not some strange cherrypicked example that attempts to break the code, however. The issue occurs in the following, somewhat minimal example:
```julia
using GLMakie

m = BezierPath([
    MoveTo(Point(0,0)),
    EllipticalArc(Point(0, 0), 1, 1, 0, 0, 2pi),

])

fig = Figure()
ax = Axis(fig[1,1])
sc = scatter!(ax, Vec2f.(rand(5), rand(5)), marker=m, markerspace = :data)
```
In the practical example, the error arises somewhat sporadically. For instance, if I put all code in the latter example (after the `using` statement) in a function, and then call this function, the issue does not arise. My hope is that the more barebones example will make it easier to reproduce.

**Comment by ffreyer** [comment]
Fixed
