### ISSUE TITLE
Preview not displaying in jupyter notebook anymore

### ISSUE THREAD

**Issue by jane2L** [MakieOrg/Makie.jl#392]
Hi all, 

when I used Makie six months ago (in March 2019) with Julia 1.0.0, just by loading the library in a jupyter notebook with
"using Makie"
any plotting command such as 
"scatter!(scene, ...)"
would produce a preview inside of the notebook, as well as a julia window with an interactive figure. 
<img width="643" alt="Capture d’écran 2019-09-23 à 09 55 17" src="https://user-images.githubusercontent.com/25347372/65396300-5fbec600-dde8-11e9-8972-7e9357409ea3.png">

But now that I use a julia 1.1.1 kernel, the same command does not produce any previews, it just gives an empty cell output: 
<img width="743" alt="Capture d’écran 2019-09-23 à 09 57 19" src="https://user-images.githubusercontent.com/25347372/65396313-90066480-dde8-11e9-9ba8-76ab053f9bb4.png">
The interactive figure will only open if I use the display command. What is the right way to use Makie inside of Jupyter notebook with Julia 1.1.1? I know interactivity inside of the notebook is still to come, but what about a static preview like it used to be? 

Thanks in advance!
Jeanne.

**Comment by carranco-sga** [comment]
Hello. 

I had the same problem, executing:
```julia
using Makie
AbstractPlotting.inline!(true)
``` 

returned a static plot. (However, with a warning message.)

Hope it helps,
Gabriel.

**Comment by ffreyer** [comment]
Depending on your environment you may need to with `display(fig, inline = true/false)`, though the defaults have changed over the years. Closing as outdated.
