### ISSUE TITLE
ticks in center of discrete colorbar, seems impossible

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/Makie.jl#3930]
I feel like subtracting 0.5 from the `ticks` should allow the ticks to be centered at the color band of a discrete colormap, but it doesn't work.

```
	fig = Figure()
	ax = Axis(fig[1, 1])
	Colorbar(
			fig[1, 2], 
			colormap=cgrad(ColorSchemes.acton, 5, categorical=true), 
			label="MOF rank",
			limits=(0, 5),
			ticks=1:6-0.5
		)
	fig
```

I tried `colormap=CairoMakie.Categorical(:viridis)` but how can I tell it about the number of discrete values? and it gives me an error `BoundsError: attempt to access 0-element UnitRange{Int64} at index [1]`.

<img width="444" alt="Screenshot 2024-06-04 at 1 00 32 PM" src="https://github.com/MakieOrg/Makie.jl/assets/30643894/9ea17863-29e1-4ac6-8c09-e463fd91d340">

**Comment by jkrumbiegel** [comment]
`1:6-0.5` is `1:5.5`, you want `0.5:4.5`?

**Comment by SimonEnsemble** [comment]
oh, now I'm embarrassed. thanks and sorry for hastily posting this issue.

(to be fair I had `1:6 .- 0.5` in my original example, unlike in this minimal example.)
but `collect(1:6 .- 0.5)` is not the same as `collect(1:6) .- 0.5` which is my mistake. I should have questioned this.
`CairoMakie` is working wonderfully! :)

<img width="663" alt="Screenshot 2024-06-05 at 7 57 07 AM" src="https://github.com/MakieOrg/Makie.jl/assets/30643894/afc8d379-ceb2-4df1-870e-15dfb37dbd44">
