### ISSUE TITLE
Larger than screen recording results in "rolling" effect on video 

### ISSUE THREAD

**Issue by cshenton** [MakieOrg/Makie.jl#394]
From the time series example, modified to output 4k video, run on a 2880x1800 res monitor (macOS mojave).

```julia
using Makie

 f0 = 1/2; fs = 100;
 winsec = 4; hopsec = 1/60
 nwin = round(Integer, winsec*fs)
 nhop = round(Integer, hopsec*fs)
 # do the loop
 frame_start = -winsec
 frame_time = collect((0:(nwin-1)) * (1/fs))
 aframe = sin.(2*pi*f0.*(frame_start .+ frame_time))
 scene = Scene(resolution=(3840, 2160))
 lines!(scene, frame_start .+ frame_time, aframe, )
 center!(scene)
 lineplot = scene[end]
 fix = 0
 record(scene, "output.mp4", 1:50) do i
     global frame_start
     aframe .= sin.(2*pi*f0.*(frame_start .+ frame_time))
     # append!(aframe, randn(nhop)); deleteat!(aframe, 1:nhop)
     lineplot[1] = frame_start .+ frame_time
     lineplot[2] = aframe
     AbstractPlotting.update_limits!(scene)
     AbstractPlotting.update!(scene)
     sleep(hopsec)
     frame_start += hopsec
end
```

Causes the recording to "roll" in the y axis like an old TV. No issue recording at or below native resolution.

**Comment by asinghvi17** [comment]
FWIW, I tried this code on my mac (same resolution), and didn't see this error:

![output](https://user-images.githubusercontent.com/32143268/65999102-b53f4680-e46a-11e9-9dee-246200a58bc0.gif)

**Comment by OlivierHnt** [comment]
I can reproduce the problem on my Mac, this is the output.gif file I obtain (with and without adding `glFinish()`):

![output](https://user-images.githubusercontent.com/38465572/73399523-6210bf80-42b5-11ea-917a-7f680e49f60e.gif)

**Comment by OlivierHnt** [comment]
FWIW, this issue looks fixed now. Perhaps this issue can be safely closed?
