### ISSUE TITLE
Compatibility with RecipesBase

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#395]
# My idea:

consume a RecipesBase series list, and decompose that into AbstractPlotting commands.  This would be a little annoying, since we'd effectively have to commit to a non-typestable function somewhere which takes in the seriestype as a symbol, and returns the appropriate constructor for the plot.  We would also have to do that with userplots, which is impossible with the way that AbstractPlotting and RecipesBase currently function.  

You would have to initialize with some default theme, and then proceed down the pipeline, calling recipes as required, similarly to Plots.  Unfortunately, I don't see a good way to get RecipesBase to conform to Makie requirements unless we have some form of modification which would effectively break all recipes.  It just doesn't work with both Plots and Makie.

What we could do is use the syntax, and create a new macro in some other package - I wrote down some of my ideas, but those are probably a bit too radical.

cc: @SimonDanisch @piever @mkborregaard

**Comment by ffreyer** [comment]
Since this hasn't had any discussion I assume there is some other issue that has gotten more traction and is more up-to-date.

**Comment by asinghvi17** [comment]
We implemented this before MakieLayout was a thing in MakieRecipes.jl, the code for which is still in the Makie repo.  That could be revived at some point.
