### ISSUE TITLE
Interact with GLMakie scene from the REPL?

### ISSUE THREAD

**Issue by tamasgal** [MakieOrg/Makie.jl#3955]
I am trying to interact with a 3D animation made in GLMakie from the REPL but I could not figure out a way how to create the screen and send its process to the background so that I can manipulate things during the animation.

I do not have an MWE yet but let me outline quickly what is happening:

I create a struct which holds a bunch of elements to be drawn and then I am using a function called `start_eventloop(...)` which is essentially this (simplified a bit):

```julia
function start_eventloop(rba)
    screen = display(GLMakie.Screen(start_renderloop=false, focus_on_show=true, title="RainbowAlga"), rba.scene)
    glw = screen.glscreen
    GLMakie.GLFW.SetWindowPos(glw, displayparams.pos...)
    GLMakie.GLFW.SetWindowSize(glw, displayparams.size...)

    scene = rba.scene

    while isopen(screen)
        if simparams.quit
            simparams.quit = false
            break
        end

        if simparams.loop_enabled && simparams.frame_idx > simparams.loop_end_frame_idx
            simparams.frame_idx = 0
        end

        rotation_enabled() && rotate_cam!(scene, Vec3f(0, 0.001, 0))

        t = simparams.t_offset + simparams.frame_idx

       # draw some stuff...
        for track ∈ rba.tracks
            draw!(track, t)
        end

        update_infotext!(rba)

        GLMakie.pollevents(screen)
        GLMakie.render_frame(screen)

        GLMakie.GLFW.SwapBuffers(GLMakie.to_native(screen))
   end

    GLMakie.destroy!(screen)
end
```

The problem is that whatever I try, I can't get back the REPL. I tried `@async RainbowAlga.start_eventloop(rba)` or `Threads.@spawn RainbowAlga.start_eventloop(rba)` but both are blocking the REPL.

I will work on a MWE but maybe someone has a hint already...

**Comment by tamasgal** [comment]
Thanks to @SimonDanisch for the `yield()` (which needs to be added to the `while` loop, so that the task gives other tasks time to run).

I now need to figure out how to make it more responsible, currently the while loop is is quite heavy and the REPL is laggy. The mouse/keyboard interaction with the GLMakie window is smooth though.

**Comment by SimonDanisch** [comment]
A discussion to improve this is something better suited for slack/discord/discourse ;)
