### ISSUE TITLE
Figure names on GLMakie independent figures

### ISSUE THREAD

**Issue by kjeel-dev** [MakieOrg/Makie.jl#3978]
### Feature description
GLMakie figure numbers or names like in matplotlib.pyplot.
In my team we frequently work with lots of open figures (up to 100).  It is then practical to have figure names, please see the enclosed screen shot obtained with matplotlib.pyplot. The experimental multiple windows with GLMakie seems to work fine, but the name is always "Makie", which makes it hard to navigate. Due to this we are calling matplotlib from Julia, which works fine, but GLMakie would be a better choice.

### Screen shot
![image](https://github.com/MakieOrg/Makie.jl/assets/77051914/8e8e4d9f-695c-4365-88ea-b06987500c15)

**Comment by ffreyer** [comment]
It is possible to set the window name in GLMakie:
```julia
counter = 1
display(GLMakie.Screen(title = "Makie $counter"), scatter(rand(10))); counter += 1
display(GLMakie.Screen(title = "Makie $counter"), scatter(rand(10))); counter += 1
display(GLMakie.Screen(title = "Makie $counter"), scatter(rand(10))); counter += 1
```

I agree it would be good to count up automatically. But in your case maybe it would be more effective to build a GUI for selecting different data sets? You have the option of using Menus and Sliders for that and you can have multiple axis objects side by side in a figure. That should give you the opportunity to organize things better than just having a large number of windows with different names.

**Comment by kjeel-dev** [comment]
Ok, I did not know that this was possible. Thank you for the info!
