### ISSUE TITLE
3D axis broken in GLMakie v0.10.13

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#3979]
The 3D axis is floating randomly in the latest stable release:

![image](https://github.com/MakieOrg/Makie.jl/assets/3345261/6b66265f-d9bc-4898-aae3-4659940b8975)

You can see in the screenshot that tick labels are far away from the axis. Any rotation, zoom moves the labels around.

**Comment by asinghvi17** [comment]
Is this common across all backends, and do you have an MWE?

**Comment by juliohm** [comment]
Data: https://gist.github.com/juliohm/ca6ddae1995a5916c987282875ccadae

MWE:

```julia
using GLMakie
using DelimitedFiles

X = readdlm("data.csv", ',')

xyz = Tuple.(eachrow(X))

scatter(xyz)
```

**Comment by asinghvi17** [comment]
I can replicate this on GLMakie and CairoMakie, but WGLMakie seems to give the correct result.

**Comment by asinghvi17** [comment]
GLMakie
<img width="712" alt="Screenshot 2024-06-20 at 11 36 38 AM" src="https://github.com/MakieOrg/Makie.jl/assets/32143268/86556339-226d-4ad5-9c43-2deb5bebffce">

CairoMakie
![iTerm2 OhCvv5](https://github.com/MakieOrg/Makie.jl/assets/32143268/5e568de1-f3e2-4137-b1ce-fdd580fbb096)

WGLMakie
![Screenshot 2024-06-20 at 11 37 11 AM](https://github.com/MakieOrg/Makie.jl/assets/32143268/dc0949cc-334d-42c8-a037-7712e032f108)

**Comment by ffreyer** [comment]
This is not a new issue. I checked Makie 0.21, 0.20 and 0.19 and they all have it. Weird that it's backend specific...

**Comment by asinghvi17** [comment]
Could this be a float precision issue then?  The numbers are in that range...

**Comment by ffreyer** [comment]
Seems to be 
https://github.com/MakieOrg/Makie.jl/blob/225d0ae0e7c9db3bc43b2642327ee9a8ee84fed4/CairoMakie/src/primitives.jl#L681-L685
If you add a parenthesis that include at least `model * to_ndim(...)` things work. Without them `*(a, b, c, xs...)` from Base runs, with 
`*(A::AbstractMatrix, B::AbstractMatrix, C::AbstractMatrix, x::AbstractVector)` from LinearAlegbra. The former does a foldl, i.e. it multiplies the first two matrices first, the latter goes right to left. And the first two matrices are risky in terms of Float32 precision

WGLMakie computes the matrix product of the first two matrices directly as well, but in Javascript. I'm guessing it uses double precision.

Going left to right is quite a bit faster on it's own (14.9ns vs 20.7ns) and also useful for optimizing projections like `[M1 * M2 * p for p in ps]` to `T = M1 * M2; [T * p for p in ps]`, so I think it would be best to just replace the camera matrices with `Mat4d` and convert to Mat4f as late as possible.
