### ISSUE TITLE
For raincloud plot, `jitter_width` is documented, but cannot be used

### ISSUE THREAD

**Issue by goulf-3m** [MakieOrg/Makie.jl#3981]
When I run

```
Makie.rainclouds([string(x) for x in rand(1:3, 50)], randn(50), jitter_width=0.05)
```

The error occurs

```
ERROR: Invalid attribute Scatter for plot type MakieCore.Plot{Makie.rainclouds}.
```

**Comment by ericphanson** [comment]
not sure what what you mean @asinghvi17? I think the issue is the attribute system doesn't recognize it so it throws an error

**Comment by asinghvi17** [comment]
Ah I sent this before adding context 😅 

Yeah, it's just that `jitter_width` and `side_nudge` are not listed as attributes.  I think that's because they depend on some pre-calculated thing, but `side_nudge` could just be `Makie.automatic` by default and `jitter_width` can stay as is I think.

**Comment by ericphanson** [comment]
thanks @asinghvi17 !
