### ISSUE TITLE
WGLMakie, Firefox, and large image plots

### ISSUE THREAD

**Issue by gdkrmr** [MakieOrg/Makie.jl#3991]
Firefox seems to be incapable of showing large image plots. This also counts for larger textures in 3D plots. The actual limit seems to be 623x624 or 624x623. I have also observed very high memory usage for that Firefox tab and if Firefox is very busy the size limit seems to be lower.

I suspect this is a bug in Firefox.

- See also here [1].
- Screenshot [2].

[1] https://julialang.zulipchat.com/#narrow/stream/225542-helpdesk/topic/Makie.20and.20Pluto

[2] screenshot <details> 

![image](https://github.com/MakieOrg/Makie.jl/assets/12512930/e3c15ccb-23fb-4e6e-a3f3-8578a9498900)

**Comment by SimonDanisch** [comment]
This should be fixed by #4125 (which also fixed the fastpath for image in WGLMakie).
Still, that's pretty small even without the fast path.
Any chance you're on a pretty old system, or don't have the newest drivers installed?
Have you checked another browser?

**Comment by ffreyer** [comment]
`image(rand(RGBf, 4000, 4000))` works fine for me on Win11 with WGLMakie in Firefox now, though it does take ~10s to initialize.

**Comment by SimonDanisch** [comment]
There's also `heatmap(Resampler(data))` now, to Resample to the screen size and update on zoom
