### ISSUE TITLE
GLMakie size out of control

### ISSUE THREAD

**Issue by kongdd** [MakieOrg/Makie.jl#4012]
```julia
using GLMakie

function Base.size(fig::Figure)
  m, n = collect(fig.scene.viewport[].widths)
  m, n
end

nx = 2
_size = (1305 * nx, 686 * nx)
fig = Figure(; size=_size)
fig
size(fig)
# (2610, 1372) # correct if didn't display
```

```julia
_size = (1305 * nx, 686 * nx)
fig = Figure(; size=_size)
display(fig)
size(fig)
# (2296, 940) # autosize if display
```

- GLMakie: v0.10.5
- Makie: v0.21.5
windows 10 platform

**Comment by SimonDanisch** [comment]
Your example and question is not that easy to understand, but I think this happens if the size becomes larger than your screen, then the display manager may resize the window.
Try `colorbuffer(fig; scalefactor=1, px_per_unit=1)` in that case, which shouldn't have this problem.

**Comment by SimonDanisch** [comment]
see https://docs.makie.org/stable/explanations/backends/glmakie#Window-Scaling
