### ISSUE TITLE
Recipe StackOverflowError with `[]` as function argument

### ISSUE THREAD

**Issue by mauro3** [MakieOrg/Makie.jl#4033]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on? Linux & AMD Ryzen APU

Consider this recipe just wrapping a lines plot
```
using GLMakie
@recipe(PltLine, x, y, z) do scene
    Attributes()
end
function Makie.plot!(plot::PltLine)
    lines!(plot, plot.x, plot.y)
end
pltline(1:3, 1:3, [])
```
produces
```
ERROR: LoadError: StackOverflowError:
Stacktrace:
  [1] Array
    @ ./boot.jl:477 [inlined]
  [2] Array
    @ ./boot.jl:486 [inlined]
....
```
whereas `pltline(1:3, 1:3, nothing)` works as well as `pltline(1:3,1:3, Int[])`.  This confused me quite a bit.  Note that the error which `lines(1:3, [])` produces is better, namely ` MethodError: reducing over an empty collection is not allowed`.

**Comment by mauro3** [comment]
Related #3567

**Comment by ffreyer** [comment]
Seems to be fixed
