### ISSUE TITLE
`NaN` in roation breaks entire axis

### ISSUE THREAD

**Issue by hexaeder** [MakieOrg/Makie.jl#4041]
This is not necessarily a bug because it only appears when you're using Makie wrong, so please feel free to close it. Passing `NaN` as a rotation does not make any sense, and you shouldn't do it. However, I was surprised that it does not only break the plot but also the entire axis in funny ways. See the following MWE where the axis disappears, or the second video [in this comment](https://github.com/JuliaGraphs/NetworkLayout.jl/issues/66#issuecomment-2235810977) where the axis flips upside down.

```julia
using Pkg
pkg"activate --temp"
pkg"add CairoMakie"
using CairoMakie

fig = Figure()
ax = Axis(fig[1,1])
scatter!(ax, rand(Point2f, 10))
fig # this is fine
scatter!(ax, rand(Point2f,3); rotation=[NaN, 0, 90])
fig # this isn't
```
![image](https://github.com/user-attachments/assets/82b99755-b4c1-4465-bd59-b32a523c4578)

**Comment by jkrumbiegel** [comment]
Good point, CairoMakie should throw an informative error here, it's Cairo that does weird things when it gets passed a NaN in the wrong place
