### ISSUE TITLE
Bad error message for out-of-range color

### ISSUE THREAD

**Issue by fredcallaway** [MakieOrg/Makie.jl#4047]
```
julia> scatter([Point(1,1)], color=1., colorrange=(2., 3.))
ERROR: MethodError: Cannot `convert` an object of type
  Vector{MakieCore.Automatic} to an object of type
  Union{ColorTypes.RGBA{Float32}, Vector{ColorTypes.RGBA{Float32}}}
```

Seems like a good situation to add an explicit check and useful error. (As a side note, I've found bad error messages to be a common problem with this package)

**Comment by jkrumbiegel** [comment]
> As a side note, I've found bad error messages to be a common problem with this package

Please file as many as you can, this really helps!

This issue should be fixed with https://github.com/MakieOrg/Makie.jl/pull/4048

**Comment by fredcallaway** [comment]
> Please file as many as you can, this really helps! 

I'm so glad to hear that the maintainers are interested in improving error message—I'll make sure to file reports whenever I encounter bad ones :)

**Comment by jkrumbiegel** [comment]
Fixed by https://github.com/MakieOrg/Makie.jl/pull/4048
