### ISSUE TITLE
GLib-GIO-WARNING

### ISSUE THREAD

**Issue by ValentinKaisermayer** [MakieOrg/Makie.jl#4049]
- [x] are you running newest version (version from docs) ? **Makie v0.21.5**
- [ ] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`) **No**
- [x] What platform + GPU are you on? 

```julia
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd4843 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 4 default, 0 interactive, 2 GC (on 12 virtual cores)
Environment:
  JULIA_PKG_PRECOMPILE_AUTO = 0
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

```
GLib-GIO-WARNING **: 15:01:05.983: Failed to open application manifest `C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\AppxManifest.xml' for package #0 (`Microsoft.MicrosoftEdge_44.19041.3636.0_neutral__8wekyb3d8bbwe'): error code 0x2
```

![image](https://github.com/user-attachments/assets/8992c920-0b13-4521-9332-d9dd08d78cdf)

The folder `C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe` is empty.

**Comment by SimonDanisch** [comment]
I'm not sure this is a Makie problem.

>]activate --temp; add Makie) No

So what makes you think it's Makie?

Googling for the error gives a ton of very different problems, so without some work of pinning down where this comes from, there isn't much we can do ;)

**Comment by ValentinKaisermayer** [comment]
If you have a look at the screenshot you see that the warning is emitted from at least two `...MakieExt` packages.

**Comment by ValentinKaisermayer** [comment]
Mhh... But it is also emitted from a `Plots.jl` extension. Do they have some common dependency?

**Comment by ValentinKaisermayer** [comment]
Ok, I will close it for now. Sry.
