### ISSUE TITLE
axislegend() unreasonable number of allocations

### ISSUE THREAD

**Issue by bertini97** [MakieOrg/Makie.jl#4052]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
  - linux (glibc) + no gpu in use

The profiler told me most of the allocations in my long script came from `axislegend()` and I didn't want to believe it, but upon closer benchmarking it apparently is the source of a huge number of allocations

```julia
using CairoMakie
using BenchmarkTools

fig = Figure()
ax = Axis(fig[1,1])
lines!(ax, (1:1:10), label="x")
@btime axislegend($ax)
```
```julia
4.353 ms (27570 allocations: 1.32 MiB)
```

**Comment by jkrumbiegel** [comment]
Legend code is relatively complex, so I'm not surprised it allocates quite a bit. If you're motivated to optimize things, I'm happy about a PR

**Comment by bertini97** [comment]
Ah, bummer. I hoped it was some obvious bug. Right now, I don't know where to look for. Should I close the issue?

**Comment by jkrumbiegel** [comment]
Yeah I think then it doesn't sound actionable or concrete enough.
