### ISSUE TITLE
Resolution argument doesn't work with vbox

### ISSUE THREAD

**Issue by cshenton** [MakieOrg/Makie.jl#407]
Julia 1.2 on Ubuntu 18.04, Makie master

vbox ignores the resolution argument and also the resolution of passed in subscenes.

Minimal example:
```julia
using Makie

# Plots correct size
a = scatter(rand(3), resolution = (1080, 1440))

# Plots correct size
b = scatter(rand(3), resolution = (1080, 1440))

# Plots incorrect default size
v1 = vbox(a, b)

# Also plots incorrect size
v2 = vbox(a, b, resolution=(2160, 1440))
```

**Comment by SimonDanisch** [comment]
Hm, that's a bit unfortunate... Maybe one can fix this line: https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/layouting/layouting.jl#L208

And pass the resolution of the subscenes to the Scene constructor for the parent kw argument.

You can work around this by calling vbox like this:
```julia
vbox(a, b, parent = Scene(resolution=(...)))
```

**Comment by ffreyer** [comment]
Closing this as outdated since vbox doesn't exist anymore
