### ISSUE TITLE
WGLMakie doesn't prevent `spacebar` from scrolling the screen.

### ISSUE THREAD

**Issue by EdsterG** [MakieOrg/Makie.jl#4075]
>Are you running newest version (version from docs) ?

Yes

>Can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)

Yes

>What platform + GPU are you on?

MacOS, Brave/Firefox

## Description
Pressing spacebar while interacting with a WGLMakie plot will scroll the browser window. After searching the web, I understand this behavior can be suppressed by calling `event.preventDefault()` on a keydown event, when the key is `space`.

I'm not sure which part of the repo generates the JS code for WGLMakie. Maybe @SimonDanisch or other devs can point me in the right direction, and I'll push a fix.

**Comment by SimonDanisch** [comment]
Great! Event handling on the JS side happens here : https://github.com/MakieOrg/Makie.jl/blob/509953c1de268fe5940c896c8dd85bd6f2c54307/WGLMakie/src/wglmakie.js#L277

**Comment by EdsterG** [comment]
Thanks! I pushed the fix to https://github.com/MakieOrg/Makie.jl/pull/4068. Tested and it works.

In theory we can also disable the default behavior for `Tab` but I'm ambivalent to doing that.
