### ISSUE TITLE
[WGLMakie] selected bar isn't the one directly under the mouse

### ISSUE THREAD

**Issue by EdsterG** [MakieOrg/Makie.jl#4115]
- What version of Makie are you running? `0.21.6`, `0.21.5`
- Can you reproduce the bug with a fresh environment ? `Yes`
- What platform + GPU are you on? `MacOS`

The selected bar is not always the bar right under the mouse, which can make the tooltip a little confusing. It doesn't seem to be an off-by-one bug ether. ~More like a off-by-one-half because the next bar is outlined as soon as the mouse is halfway past the first bar.~ It seems to be off by some constant offset in pixel space.

Any thoughts on where to look to find the root cause?

```
using WGLMakie
fig = Figure()
ax = Axis(fig[1,1], xreversed = true, yaxisposition = :right)
DataInspector(ax)
barplot!(ax, 1:40, 1:40, direction=:x)
fig
```

https://github.com/user-attachments/assets/6235e9df-b365-46f6-b636-2d9628f404c5

**Comment by EdsterG** [comment]
Also happens in `0.21.6`.

**Comment by asinghvi17** [comment]
Does the half-bar thing still happen on your machine?  For me it's a pure off-by-one error.

**Comment by EdsterG** [comment]
> For me it's a pure off-by-one error.

Which part of the code are you referring to?

In my description I was referring to  `idx` in `show_data`, however it doesn't seem to be an off-by-one error with `idx` because when you zoom in it works fine. If I offset `idx` by 1 it fixes the zoomed out version but is then off-by-one when you zoom in.

It seems to be off by some constant offset in pixel space, but I can't seem to find where this pixel space offset is coming from.

**Comment by EdsterG** [comment]
I initially thought it was a bug in `pick_sorted` which is how I found https://github.com/MakieOrg/Makie.jl/pull/4082, but the distance fix doesn't seem to fix this issue. It still might be a bug in `pick_sorted` but I don't see it. 😕

**Comment by ffreyer** [comment]
I did some testing on the picking "image":

```julia
# create plot
f, a, p = barplot(1:10)

# get picking "image"
x = WGLMakie.pick_native(f.scene.current_screens[1], Rect2i(f.scene.viewport[]))

# plot picking image at full fig size 
scene = Scene()
heatmap!(scene, -1..1, -1..1, last.(x), colorrange = (0, 16))
```

| plot | overlayed | pick |
| --- | --- | --- |
| ![Screenshot 2024-08-14 211439](https://github.com/user-attachments/assets/c69aa8aa-ab7b-4ce7-be79-808be13e9a4d) | ![overlay_transparent](https://github.com/user-attachments/assets/34fc7fed-b5d6-452e-9ab9-ee46866b06a8) |![overlay_cut](https://github.com/user-attachments/assets/876b8aee-75fd-4047-a9d7-579cab69fa76) |
| ![zoomed_cropped](https://github.com/user-attachments/assets/89713b1a-ab41-4189-96d0-3b1e741a0181) | ![zoomed_overlay](https://github.com/user-attachments/assets/fd09646c-3474-4bca-896e-23fdbb684043) | ![zoomed_pick](https://github.com/user-attachments/assets/1631afa1-a601-47fc-8a36-0093956c6d05) |

These all match up well with the correct indices. But the wrong indices reach DataInspector, so there is probably something wrong with the distance sorting here:
https://github.com/MakieOrg/Makie.jl/blob/9e156624877e6d5e51648c47d735dac5fd540823/WGLMakie/src/wglmakie.js#L618-L668
or with the Julia side here:
https://github.com/MakieOrg/Makie.jl/blob/9e156624877e6d5e51648c47d735dac5fd540823/WGLMakie/src/picking.jl#L47-L61

For reference, this is the GLMakie code:
https://github.com/MakieOrg/Makie.jl/blob/9e156624877e6d5e51648c47d735dac5fd540823/GLMakie/src/picking.jl#L68-L95

**Comment by EdsterG** [comment]
Thank you for the lead, I'll see what I can find.

**Comment by EdsterG** [comment]
Looks like the bug is on the JS side here:

https://github.com/MakieOrg/Makie.jl/blob/9e156624877e6d5e51648c47d735dac5fd540823/WGLMakie/src/wglmakie.js#L528-L538

Specifically, the way `picked_plots` is computed. Instead of storing all valid indices for a plot it just stores the last one it has seen.

Which then results in an incorrect `plots` array generated here:

https://github.com/MakieOrg/Makie.jl/blob/9e156624877e6d5e51648c47d735dac5fd540823/WGLMakie/src/wglmakie.js#L540-L549

and an incorrect `selected` array used by `pick_sorted`:

https://github.com/MakieOrg/Makie.jl/blob/9e156624877e6d5e51648c47d735dac5fd540823/WGLMakie/src/wglmakie.js#L634-L653
