### ISSUE TITLE
Some of the `levels` are missing from `Colorbar`

### ISSUE THREAD

**Issue by ryofurue** [MakieOrg/Makie.jl#4121]
- [x] what version of Makie are you running? (`]st -m Makie`): 0.21.5 (See below)
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`): Yes. I'm attaching an image created under this fresh env.
- [x] What platform + GPU are you on? ---macOS 14.6.1, Apple M1

When I specify the contour levels as `levels = [-5, -2, . . . ]`, some of the levels are missing from the colorbar even though those levels are plotted in `contourf`.

In the following example, levels "-2" and "2" are missing from the colorbar:
```julia
using CairoMakie

levels = [-5, -2, -1, -0.5, 0.5, 1, 2, 5]

func(x,y) = x

xs = -7.0:1.0:7.0
ys = 0.0:1.0:7.0
vals = func.(xs, ys')
fig = Figure()
ax = Axis(fig[1,1])
c = contourf!(ax, xs, ys, vals
              ,levels = levels
              ,extendlow=:auto, extendhigh=:auto)
Colorbar(fig[1,2],c; ticks=levels)
save("tmp.png", fig)
```

![tmp](https://github.com/user-attachments/assets/7670de46-f9d3-465d-909d-ac10ca5818f0)

```julia
(@v1.10) pkg> status -m Makie
Status `~/.julia/environments/v1.10/Manifest.toml`
  [ee78f7c6] Makie v0.21.5

(@v1.10) pkg>
```

**Comment by briochemc** [comment]
Is the only workaround to make a "manual" colorbar currently?
