### ISSUE TITLE
Invert zooming with mouse wheel

### ISSUE THREAD

**Issue by rapus95** [MakieOrg/Makie.jl#414]
I know, the debate about scrolling which direction should zoom in is as old as the option to zoom in itself. Thus, I'm curious, why it was decided the wait it works now, and where one can change it :D
There are two ways to think about zooming:

Current way: rotate the wheel away = push a stick which has the image at its tip = zoom out
Alternative way: rotate the wheel away = The way Google Maps, Blender and many others work ;)

**Comment by ffreyer** [comment]
Zooming in Axis and LScene works the same as `maps.google.com` now. Changing the same of the zoom speed should also allow you to flip the direction.
Closing this as done.
