### ISSUE TITLE
custom marker shape

### ISSUE THREAD

**Issue by babaq** [MakieOrg/Makie.jl#422]
Is there a way to define a custom marker shape, and use it in scatter plot?

I noticed the marker type is annotated as GeometryTypes, but it would be convenient to accept a vertices arrays defining a shape.

**Comment by SimonDanisch** [comment]
You can use meshscatter:
```julia
using Makie, GeometryTypes
m = Point2f0[(0,0), (0, 1), (0.5, 0.5), (1, 1), (1, 0)]
meshscatter(rand(4), marker=GLPlainMesh(m))
```

**Comment by babaq** [comment]
Hi @SimonDanisch , thanks for the tip. I could plot custom shape as marker now, but the shape definition seems in the world coordinates where it scales with the scatter point coordinates. is there ways to set the shape vertices in local coordinates. In my case, I am doing:
```Julia
using Makie, GeometryTypes
m = Point2f0[(0,0), (0, 1), (0.5, 0.5), (1, 1), (1, 0)]
meshscatter(rand(20:70,20),rand(20:3500,20), marker=GLPlainMesh(m),rotations=rand(0:2π,20))
```

**Comment by asinghvi17** [comment]
You could pass `markersize = 10AbstractPlotting.px` or something...

**Comment by SimonDanisch** [comment]
No you can't for meshscatter. This isn't implemented yet... But the whole `markerspace` in pixel is likely my next refactor, so hopefully solved as part of that

**Comment by SimonDanisch** [comment]
Would be nice to allow `scatter(..., marker=polygon)` in form of a recipe that uses meshscatter, and would be nice to allow pixel marker space for meshscatter

**Comment by ffreyer** [comment]
`GeometryBasics.Polygon` and `Makie.BezierPath` can be used as a marker types now to define arbitrary shapes.
