### ISSUE TITLE
CairoMakie + PDF cannot produce heatmaps

### ISSUE THREAD

**Issue by tpoisot** [MakieOrg/Makie.jl#4241]
I am trying to generate a pdf of a heatmap using `CairoMakie`. It works as a PNG no problem, but when asking for a PDF output, I get the following error:

~~~
Error showing value of type Makie.Figure
Error in conversion pipeline. xs and ys should have size ni+1, nj+1.
~~~

- [x] what version of Makie are you running? (`]st -m Makie`) - **0.19.12**
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`) - **yes**
- [x] What platform + GPU are you on? - **Linux no GPU**

**Comment by asinghvi17** [comment]
Huh, this should error no matter what.  Curious that it works in PNG, it looks like the fast path in Cairo heatmaps doesn't check for this.

What is the input to `heatmap`?  The error should also have printed `Found: xs: $(length(xs)), ys: $(length(ys)), ni: $(ni), nj: $(nj)`.

**Comment by tpoisot** [comment]
The input to heatmap is two vectors of length `i` and `j`, and a matrix of size `i, j`. The vectors are the midpoints of each grid, and they are evenly spaced. I've used the same code to generate... 1000s of pngs, probably, and it only throw this issue when I use the PDF output.

**Comment by asinghvi17** [comment]
Oh hold on - your Makie version is two breaking versions old.  Could you try with the latest Makie version (0.21.7)?

An MWE of:
```julia
using CairoMakie
save("hello.pdf", heatmap(1:10, 1:10, rand(10, 10)); backend=CairoMakie)
```

works fine for me on those versions.

**Comment by tpoisot** [comment]
My bad, you're right. I had a conflicting dependence that resulted in an old version.
