### ISSUE TITLE
CairoMakie + contour + limits! result in error

### ISSUE THREAD

**Issue by goulf-3m** [MakieOrg/Makie.jl#4276]
With Makie v0.21.9 CairoMakie v0.12.9 (confirmed in a fresh environment)

```
using CairoMakie
fig,ax,_=contour(rand(20,20))
xlims!(ax,0,10)
display(fig)
```
: raises boundserror. Seems that some internal data are filtered when setting xlims.

With `Makie@0.21.5`, it works correctly.

**Comment by ffreyer** [comment]
Not really clip plane since there are none but could be related to some changes I made for that
