### ISSUE TITLE
`nan_color` cannot be changed in `contourf()`?

### ISSUE THREAD

**Issue by himcraft** [MakieOrg/Makie.jl#4286]
- [x] what version of Makie are you running? (`]st -m Makie`)
`v0.21.9`.
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`) 
Yes.
- [x] What platform + GPU are you on?
Windows 11 with AMD GPU.

Hi all,

I want to plot a contour and change the points tagged as `NaN` to `:black`, however the attribute `nan_color=:black` seems not work. The MWE is as follows
```julia
using CairoMakie
testdata=zeros(400,400)
for i in 1:400
    for j in 1:400
        testdata[i,j]=sin(i/400*2*pi)*cos(j/400*2*pi)
        if((i-200)^2+(j-200)^2>100^2)
            testdata[i,j]=NaN
        end
    end
end
f=Figure(size=(400,400))
ax=Axis(f[1,1],xticklabelsvisible=false,yticklabelsvisible=false)
cf=contourf!(ax,testdata,nan_color=:black)
f
```
The NaN data outside of the circle is still `:transparent`, while when I check the `nan_color` attribute of `cf` it gives
```shell
julia> cf.nan_color
Observable{Any}(:black)
    0 => map(Makie.to_color)
    0 => map(Makie.to_color)
    0 => map(Makie.to_color)
```

I don't know if this is a bug or if there are some configurations I didn't notice. 

Thank you.

**Comment by jkrumbiegel** [comment]
The underlying isoband algorithm just cuts out areas with NaN, so there are no polygons we can color black. Contourf probably has this attribute by accident, because others have it.

You could set the axis background color to black?

**Comment by himcraft** [comment]
Thank you @jkrumbiegel !
This works for me.
