### ISSUE TITLE
User-defined recipes don't work with SpecApi

### ISSUE THREAD

**Issue by aplavin** [MakieOrg/Makie.jl#4295]
`SpecApi.MyRecipe` appears to be resolved by this function:
https://github.com/MakieOrg/Makie.jl/blob/02ccec36a2083c10d3b3ada510b587ec2b934ded/src/specapi.jl#L7-L13
and it only supports recipes that are defined in `Makie` itself.

For user-defined recipes to work with the SpecApi interface, they need to be added as properties to the Makie module, eg:
https://github.com/JuliaAPlavin/MakieExtra.jl/blob/00000000a40dc2bf327e1b4f1c5b6abf468d4f06/src/MakieExtra.jl#L50-L57
This is quite a hack, should be done very carefully not to mess with precompilation – would be nice to have proper support in SpecApi.

- [x] what version of Makie are you running? (`]st -m Makie`) v0.21.9
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on? any

**Comment by SimonDanisch** [comment]
Yeah I tried a few versions, to fix this, but didn't find anything reliable:(
Any ideas welcome... Global dicts, that are filled at compile times don't work with pre compilation.

**Comment by SimonDanisch** [comment]
Hm, then I'd rather do `MyRecipe(...)` ... That was actually the plan all along, but a bit too much work for the first version.
I hope to get back to that soon'ish.
