### ISSUE TITLE
Memory associated only with non-primitive plots is not garbage collected after empty!(axis)

### ISSUE THREAD

**Issue by adrianboyko** [MakieOrg/Makie.jl#4302]
- [x] what version of Makie are you running?  Makie 0.21.9 and GLMakie 0.10.9
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)  Yes
- [x] What platform + GPU are you on?  Kubuntu 24.04, Wayland, i5-4570, Mesa Intel HD Graphics 4600

The following program consumes all available memory, presumably because the large matrices are not being garbage collected. Note that `contour!` is used and that if it is changed to `heatmap!` then garbage collection works as expected and all is fine.

```julia
using GLMakie
fig::Figure = Figure()
ax::Makie.Axis = Axis(fig[1,1])
display(fig)
while true
    empty!(ax)
    big_matrix::Matrix{Float64} = zeros(10_000, 10_000)
    big_matrix[1,1] = 1
    contour!(ax, big_matrix)
end
```

**Comment by asinghvi17** [comment]
`contour` in particular has a lot of `lift` statements that aren't associated with the plot, which is probably what keeps the memory persisting.  I think we just need to add those.

**Comment by asinghvi17** [comment]
@adrianboyko could you see if #4303 fixes your issue?  You can try it out by:
```julia
]add Makie#as/contour_memory_leak MakieCore#as/contour_memory_leak GLMakie#as/contour_memory_leak
```

(to clean up, simply `]free Makie MakieCore GLMakie`)

**Comment by adrianboyko** [comment]
That's a fix, sir.
