### ISSUE TITLE
Tracking plot types that don't yet have all `lift`s linked to the plot object

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#4304]
A while ago we introduced a mechanism to track Observable pipelines (created by `lift`, `map`, `on`, and `onany`) and associate them with a plot so that they get garbage collected along with that plot.  This is done by providing the plot as the **second** argument to the function, for example `lift(f, plot::Plot, args...)`.  

Most Makie recipes have already transitioned, however some still have to add this tracking.  It's as simple as adding the `plot` (or whatever name the `plot!` function has it under) as the second argument to the lift or similar functions within `plot!`.

Specifically, 
```diff
- lift(x, y, z) do x, y, x
+ lift(plot, x, y, z) do x, y, z
...
end
```

or

```diff
- lift(some_function, x, y, z)
+ lift(some_function, plot, x, y, z)
```

I made a PR to do this for `contour` in #4303, which could be a nice reference.

- [x] contourf
- [x] hspan/vspan
- [ ] scatterlines
- [x] series
- [ ] timeseries
- [x] tricontourf
- [ ] volumeslices

All the recipes can be found in https://github.com/MakieOrg/Makie.jl/tree/master/src/basic_recipes

Inspired by #4302

**Comment by tuncbkose** [comment]
Is that to-do list accurate/up-to-date? I'm not too familiar with Makie/Julia, which is why I'm in a good first issue, but I could only find 2 untracked instances of those functions:
https://github.com/MakieOrg/Makie.jl/blob/86177428baa835d88ee733d4be57b5340de70053/src/basic_recipes/hvspan.jl#L49
and
https://github.com/MakieOrg/Makie.jl/blob/86177428baa835d88ee733d4be57b5340de70053/src/basic_recipes/timeseries.jl#L43

The rest seem already updated, for example with commit dafd4d3fa5da8f1bf354571fec52ccbd7bea078b in https://github.com/MakieOrg/Makie.jl/pull/2731.

**Comment by asinghvi17** [comment]
Contourf and tricontourf are both done, I probably included them mistakenly.  Series also looks fine.

You mentioned hvspan and timeseries already, but there are a few more:

Volumeslices

https://github.com/MakieOrg/Makie.jl/blob/86177428baa835d88ee733d4be57b5340de70053/src/basic_recipes/volumeslices.jl#L27 


Scatterlines has quite a few, the below statement and friends

https://github.com/MakieOrg/Makie.jl/blob/86177428baa835d88ee733d4be57b5340de70053/src/basic_recipes/scatterlines.jl#L39

**Comment by simonsteiger** [comment]
I'd be interested in helping out as someone with little experience in Makie's internals.

I recall looking at the [sankey recipe](https://github.com/jkrumbiegel/SankeyMakie.jl) a few weeks ago and seeing the `lift` function in there, too. I know that this recipe is not integrated with Makie yet and might be of low priority, but I have to plot sankeys too often and like Makie's layouting too much to not have a try.

Would it be correct to pass `lift(plot, x, y, z)` [there](https://github.com/jkrumbiegel/SankeyMakie.jl/blob/10bc7676fd714a03951d6f7c8f2b3dc830d58739/src/SankeyMakie.jl#L397), too?
