### ISSUE TITLE
Precompilation warnings

### ISSUE THREAD

**Issue by ufechner7** [MakieOrg/Makie.jl#4308]
- [x ] what version of Makie are you running? (`]st -m Makie`)
GLMakie v0.10.9

- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
Ubuntu 24.04 on AMD Ryzen 7840u

```
┌ GLMakie
│  WARNING: Makie.ContinuousSurface is deprecated, use VertexGrid instead.
│    likely near none:1
│  WARNING: importing deprecated binding Makie.ContinuousSurface into GLMakie.
│  , use VertexGrid instead.
│  WARNING: Makie.DiscreteSurface is deprecated, use CellGrid instead.
│    likely near none:1
│  WARNING: importing deprecated binding Makie.DiscreteSurface into GLMakie.
│  , use CellGrid instead.
│  
│  [pid 54682] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   timer              0x62d22e0->0x75755b1a12a0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
└  
```

**Comment by SimonDanisch** [comment]
As explained on discourse, the depwarns need the same treatment as this:
https://github.com/MakieOrg/Makie.jl/pull/4143

This is an easy fix for anyone and not a priority for the core devs right now, so is up for grabs.

The `waiting for IO to finish` needs an investigation by someone who has the time and has this as priority.
