### ISSUE TITLE
`voronoiplot` with a matrix creates a 3D plot

### ISSUE THREAD

**Issue by DanielVandH** [MakieOrg/Makie.jl#4335]
Using `voronoiplot` with a matrix creates a 3D plot. The 2D tessellation shown is incorrect.

```julia-repl
julia> using CairoMakie

julia> pts = rand(2, 5);

julia> voronoiplot(pts)
```
![image](https://github.com/user-attachments/assets/0a014654-5d11-4a80-93b7-0f7cce5cc143)

- [x] what version of Makie are you running? (`]st -m Makie`)

```julia-repl
(jl_SxZtlw) pkg> st -m Makie
Status `C:\Users\danjv\AppData\Local\Temp\jl_SxZtlw\Manifest.toml`
  [ee78f7c6] Makie v0.21.9
```

- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)

**Comment by asinghvi17** [comment]
It looks like an issue in `convert_arguments` for voronoiplot:

```julia-repl
julia> Makie.convert_arguments(Makie.Voronoiplot, rand(2, 5))
(Point{3, Float64}[[1.0, 1.0, 0.5306268315612478], [2.0, 1.0, 0.3057094707535708], [1.0, 2.0, 0.0386010373499962], [2.0, 2.0, 0.8346339986368071], [1.0, 3.0, 0.6964743865655425], [2.0, 3.0, 0.10789307734909603], [1.0, 4.0, 0.7161808096490242], [2.0, 4.0, 0.6060931129469319], [1.0, 5.0, 0.32697816623710696], [2.0, 5.0, 0.3249893139346661]],)
```

The offending convert is:

```julia
# For heatmap-like inputs
function convert_arguments(::Type{<:Voronoiplot}, mat::AbstractMatrix)
    return convert_arguments(PointBased(), axes(mat, 1), axes(mat, 2), mat)
end
```

I'm not sure what the idea was here - were the `mat` values supposed to be z values?

**Comment by asinghvi17** [comment]
Also, is this what you were aiming for?
```julia
voronoiplot(rand(Point2f, 5))
```
![display](https://github.com/user-attachments/assets/ddba6e31-7d6f-454b-bec2-54fc11f4c212)

**Comment by DanielVandH** [comment]
That is what I was looking for, yeah. It should be the same as plotting `voronoiplot(voronoi(triangulate(rand(2, 5))))`.

I'm not sure exactly the intention behind the `convert_arguments` is. I don't believe I wrote that one (but if I did it's probably me having no idea anyway).

**Comment by asinghvi17** [comment]
It might be easier then to declare `voronoiplot` a point-based plot?  Not sure what the z values are intended to do there to be honest.

**Comment by DanielVandH** [comment]
Looking back at the original PR, I think the intention was that it serves as a sort of nonlinear heat map

**Comment by asinghvi17** [comment]
Aha, ok.  It is doing that - see:
```julia
voronoiplot(reshape(1:8, (4, 2)); axis = (; type=Axis))
```
<img width="598" alt="Screenshot 2024-09-09 at 2 39 06 PM" src="https://github.com/user-attachments/assets/c523bb48-1c3d-4b37-b0c3-9e1cdb591f9a">
so I think we just want this to be forced to a 2d axis by default?

The other question is - do you even need a 2d nonlinear heatmap?  `surface` and `heatmap` both work on rectilinear grids (and surface even works on nonlinear grids, and doesn't have interpolation):
![hello](https://github.com/user-attachments/assets/073240a8-0f19-4a31-83af-59cdaa1b4327)


There are also no examples of `heatmap-like` behaviour in the docs, so we should add that if nothing else.

**Comment by ffreyer** [comment]
Yea I think nonlinear heatmaps were my reason for it.

> The other question is - do you even need a 2d nonlinear heatmap? surface and heatmap both work on rectilinear grids (and surface even works on nonlinear grids, and can be uninterpolated):

Didn't know un-interpolated surface works, but it always uses quads while voronoi doesn't so I think there is still a use. E.g.:
```julia
begin
    v1 = Vec2f(1, 0)
    v2 = Vec2f(cosd(60), sind(60))
    ps = Point2f[x * v1 + y * v2 for x in 1:10, y in 1:10]
    xs = first.(ps)
    ys = last.(ps)
    cs = rand(size(ps)...)
    f, a, p = surface(xs, ys, zeros(size(ps)), color = cs, interpolate = false)
    a = Axis(f[1, 2])
    # voronoiplot!(a, ps[:], color = cs)
    voronoiplot!(a, xs, ys, cs)
    f
end
```
![Screenshot 2024-09-10 015722](https://github.com/user-attachments/assets/4b983d63-1912-4401-9c2b-21ff0316c629)

Maybe it's a bit pointless to have matrix conversions but I think more is better there. So I'd say just add a `preferred_axis_type(::VoronoiPlot) = Axis`
