### ISSUE TITLE
"Edit this page" links in docs are broken

### ISSUE THREAD

**Issue by DanielVandH** [MakieOrg/Makie.jl#4340]
On e.g. https://docs.makie.org/stable/reference/plots/mesh, the `Edit this page` link is broken. The link is

https://https//github.com/MakieOrg/Makie.jl/edit/master/docs/src/reference/plots/mesh.md

The issue being that it's duplicated the `https://`

**Comment by asinghvi17** [comment]
Looks like https://github.com/LuxDL/DocumenterVitepress.jl/blob/4d92d2148cde14119bc3543cacbbc1ceb840859f/src/vitepress_config.jl#L99 is what controls this in DocumenterVitepress. 

#4341 should ideally fix it...
