### ISSUE TITLE
MultiplesTicks when multiples is 0

### ISSUE THREAD

**Issue by tuncbkose** [MakieOrg/Makie.jl#4370]
### Feature description

This may be an issue of personal taste and not very important, but right now using for example `MultiplesTicks(5, pi, "π")` leads to the ticks being `["−2π", "−1π", "0π", "1π", "2π"]`. 

I'd prefer to have just `"0"` instead of `"0π"`, which could be achievable for example with changing
https://github.com/MakieOrg/Makie.jl/blob/c463049102e775d4c31c4b891e9ac32adbca9891/src/makielayout/lineaxis.jl#L665-L671
to return something like
```julia
multiples .* m.multiple, map(x -> x[1] != '0' ? x : "0", showoff_minus(multiples) .* m.suffix)
```

Not sure if it would be worth it and whether it would be preferable for other people though.

**Comment by jkrumbiegel** [comment]
Sure that's a good idea, maybe make it a keyword arg to `MultiplesTicks` so we don't have to make it a breaking default change

**Comment by tuncbkose** [comment]
Just to make sure, would adding the keyword arg involve using `Base.kwdef`? Something like
```julia
@kwdef struct MultiplesTicks
    n_ideal::Int
    multiple::Float64
    suffix::String
    only_zero::Bool = false
end
```

Also open to suggestions on the keyword name.

**Comment by jkrumbiegel** [comment]
I would not use kwdef, just add a field and a method that adds the new field as a keyword with default. Maybe it could be called `strip_zero` or `plain_zero` or something.
