### ISSUE TITLE
Camera inside surface/mesh/etc.

### ISSUE THREAD

**Issue by gvretina** [MakieOrg/Makie.jl#4379]
It would be nice to be able to plot a sphere, by
 ```julia
fig = Figure()
ax = Axis3(fig[1,1])
mesh!(ax,Sphere(Point3f(0), 10f0), color = :blue)
 ``` 
and then place the camera inside the sphere, by 
```julia
cam = Camera3D(ax.scene)
cam.eyeposition[] = Vec3(0f0)
```
and then get a view of the sphere from the inside.

**Comment by SimonDanisch** [comment]
You probably need to reverse the faces of GeometryBasics.mesh(sphere)

**Comment by gvretina** [comment]
How would one do that?  I do not find anything in GeometryBasics to fiddle around with the faces.
Also, would the correct thing be to reverse the faces or the normals of the faces, or is this the same?
I unfortunately do not have much experience in this topic.

**Comment by SimonDanisch** [comment]
Actually this works, you just need to correct the camera code and use LScene (which has a camera):
```julia
fig = Figure()
ax = LScene(fig[1,1])
mesh!(ax,Sphere(Point3f(0), 10f0), color = :blue)
display(fig)
update_cam!(ax.scene, Vec3(0.0f0), Vec3f(0, 0, 10), Vec3f(0, 1, 0))
```
