### ISSUE TITLE
Links to examples in README.md  are broken

### ISSUE THREAD

**Issue by natschil** [MakieOrg/Makie.jl#438]
See title

**Comment by DilumAluthge** [comment]
Bump @SimonDanisch @asinghvi17

**Comment by DilumAluthge** [comment]
The links to the examples in `README.md` are broken, and the images in `README.md` are also broken.

**Comment by asinghvi17** [comment]
The structure of the example gallery has been reorganized, so I'll have to make a script to replace the links.  Will do on the plane tonight!

**Comment by felixcremer** [comment]
Should be closed.
