### ISSUE TITLE
xscale not working as expected on linesegment plots 

### ISSUE THREAD

**Issue by AUK1939** [MakieOrg/Makie.jl#4400]
- what version of Makie are you running? Makie v0.21.11
- Can you reproduce the bug with a fresh environment ? Yes
- What platform + GPU are you on? Windows 11, NVidia RTX 4500

Code to reproduce the issue is below. As you can see from the screen shots. The mouse is roughly positioned at 64 on the original scale. The tooltips show up at this location in ScatterPlots and BarPlots, but in LineSegment Plots the tooltip shows up at 8, the scaled location. 

```
# generate some data
x = reduce(vcat, [range(9, 17, length = 30) .+ i * 24 for i in 0:5])
y = cumsum(randn(length(x)))
color = repeat(1:6, inner = 30)
line_segments_x = repeat(x, inner=2)
line_segments_y = collect(Iterators.flatten(zip(y, zeros(length(y)))))

# xaxis ticks
xticks = reduce(vcat, [(10:2:16) .+ i * 24 for i in 0:5])
xticklabelrotation = pi/4

# plot the data on the custom scale in a scatter, bar and linesegment plot
f = Figure()
scatter(f[1, 1], x, y; color, axis = (; xticks, xticklabelrotation))
scatter(f[2, 1], x, y; color, axis = (; xticks, xticklabelrotation, xscale = sqrt))
DataInspector() 
f

f = Figure()
barplot(f[1, 1], x, y; color, axis = (; xticks, xticklabelrotation))
barplot(f[2, 1], x, y; color, axis = (; xticks, xticklabelrotation, xscale = sqrt))
DataInspector() 
f

f = Figure()
linesegments(f[1, 1], line_segments_x, line_segments_y; color, axis = (; xticks, xticklabelrotation))
linesegments(f[2, 1], line_segments_x, line_segments_y; color, axis = (; xticks, xticklabelrotation, xscale = sqrt))
DataInspector() 
f
```

![Screenshot 2024-09-23 140046](https://github.com/user-attachments/assets/da3be77a-ba34-42a8-ad08-dc4a25bfe90d)

![Screenshot 2024-09-23 140004](https://github.com/user-attachments/assets/72337e9b-c531-4989-a3b5-fb06b4149b76)

**Comment by EdsterG** [comment]
Tried to debug this and got stuck at `projectionview`. Is this matrix supposed to project from pixel space to input space or from pixel space to transformed dat space, or something else? @ffreyer
