### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by damianodegaspari** [MakieOrg/Makie.jl#4414]
I was reading
[Wrapping recipe tutorial](https://docs.makie.org/stable/tutorials/wrap-existing-recipe#introduction)

In the code it is written
```
struct MyHist
    bincounts
    bincenters
end
```

The terms `bincounts `and `bincenters` also appear in other code snippets below.
However the terms `barcenters` and `barcounts` are used in the explanation. 
I think one should choose one of the two options and stick to that.
If this is too insignificant to report please tell me so that I won't open similar issues in the future.

**Comment by damianodegaspari** [comment]
Ok. Two things.
1) should I change everything from `barcenters`, `barcounts`  to  `bincounts`, `bincenters` or viceversa?
2) I've never done a pull request. I think I found the relevant file in github. Is this [Developing Julia Packages](https://youtu.be/QVmU29rCjaA?t=2870) what I should do?

**Comment by jkrumbiegel** [comment]
If you do a small change in the docs you just do that in the web interface with the pencil symbol above the respective markdown file (search for some text in the repo to find the right one).

**Comment by damianodegaspari** [comment]
I tried. Everything ok with #4420?

**Comment by jkrumbiegel** [comment]
Very good, thanks :)
