### ISSUE TITLE
Issue Mackie and Plots incompatibility?!

### ISSUE THREAD

**Issue by HelenaAlamp** [MakieOrg/Makie.jl#4429]
It seems I cannot have both [Plots.jl] and [CairoMakie.jl] or [Makie.jl] all together installed in my environment. I installed [CairoMakie.jl] without any issues. Then when I tried to use [Plots.jl], and I encountered the error:

"loaderror: ffmpeg not installed properly, run `] build ffmpeg`, restart julia and try again"

 How can I solve this issue and use both Plots.jl and CairoMakie.jl plots in the same project?

Thank you for your help!

Helena A.

**Comment by asinghvi17** [comment]
Can you please post the versions of Plots, Makie and FFMPEG.jl that are causing this issue?

In Pkg-mode (activated by typing `]` in the REPL), run the following command:

```julia
st -m Plots CairoMakie Makie FFMPEG FFMPEG_jll
```

Also, which Julia version are you on?

**Comment by asinghvi17** [comment]
Please send the full output of the command, you may not have explicitly installed FFMPEG.jl but Makie declares it as a dependency (as does Plots) so Julia will automatically install it when you add either of those packages.

**Comment by asinghvi17** [comment]
I just tried this locally in a fresh environment and got the expected (and correct) version set:
```julia
(jl_DKhoMk) pkg> add Plots Makie
[...]
(jl_DKhoMk) pkg> st -m Plots CairoMakie Makie FFMPEG FFMPEG_jll
Status `/private/var/folders/9t/ch_25c2511n0cbcf8fs8b7xh0000gn/T/jl_DKhoMk/Manifest.toml`
  [c87230d0] FFMPEG v0.4.2
  [ee78f7c6] Makie v0.21.12
  [91a5bcdd] Plots v1.40.8
⌅ [b22a6f82] FFMPEG_jll v4.4.4+1
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
```

This is expected and correct, since FFMPEG v6 has some issues.

What do you see on your system?

**Comment by HelenaAlamp** [comment]
I think it is solved, since I can use both Plots and Makie.
Even though, I checked the status and it says:

Pkg.status("FFMPEG")
No Matches in `C:\Users\...\.vscode\....\Project.toml`

but now everything works
