### ISSUE TITLE
Help implementing datashader-like functionality

### ISSUE THREAD

**Issue by cjdoris** [MakieOrg/Makie.jl#443]
I'd quite like to incorporate some datashader-like functionality into Makie. Basically, I need to be able to do the following, but it's not clear that it's currently possible in Makie?

1. Draw an image with one image pixel per screen pixel.
2. Get the size of the plot area in pixels.
3. Get the limits of the axes.

Grateful if you could enlighten me on whether this is currently possible.

**Comment by asinghvi17** [comment]
You can get the pixel-area of the scene by `scene.px_area`, and the limits by `scene.limits` or `scene_limits(scene)`.  You can plot all in pixel units by using `raw=true` as a keyword argument.

**Comment by SimonDanisch** [comment]
While this is somewhat true, I'd recommend:
* get pixel area with `pixelarea(scene)`
* only ever use `scene_limits(scene)`
* `raw=true` is just removing to add cameras + axis to the scene automatically, so won't let you plot in pixelspace... You will need `Scene(camera=campixel!)` for that, which also works well with `raw=true` to not show any axis etc!

**Comment by cjdoris** [comment]
Thanks for your replies.

Maybe take a look at the examples at the bottom of https://examples.pyviz.org/heat_and_trees/Heat_and_Trees.html#heat-and-trees-gallery-heat-and-trees to see what I'm aiming for.

That is, I still want to have axes, and maybe those axes will contain points and lines and things like any other plot, but I also want to be able to draw an image in that plot, where the image is produced at exactly the right size (in pixels) for the plot, hence I need to know the limits of the axes and the size of the axes in pixels. I believe `pixelarea(scene)` is the size of the whole scene, not just the plot area?

**Comment by SimonDanisch** [comment]
Hm I guess, there are different ways of doing this... Do you want to use MakieLayout as well? And do you want to zoom in and then update the image that is displayed? Is it very important to map 1 image pixel to screen pixels, or would it just be nice?

**Comment by cjdoris** [comment]
I'm not familiar with MakieLayout, but from the quick look I've just had, yes!

The 1-1 correspondence between pixels is important: basically the image is a 2D histogram, where each pixel represents a bin, and so we get very fine-grained visualization. And yes, I want to be able to zoom in on regions of the image and have it be recomputed.

**Comment by SimonDanisch** [comment]
@jkrumbiegel, this could be kind of easy in makielayouts, no?

**Comment by jkrumbiegel** [comment]
yeah this is basically all you need:

```julia
using Makie
using MakieLayout


scene, layout = layoutscene()

ax = layout[1, 1] = LAxis(scene)

function datashader(limits, pixelarea)
    # return your heatmap data
    # here, I just calculate a sine field as a demo
    xpixels, ypixels = widths(pixelarea)
    xmin, ymin = minimum(limits)
    xmax, ymax = maximum(limits)
    
    [cos(x) * sin(y) for x in LinRange(xmin, xmax, xpixels),
                         y in LinRange(ymin, ymax, ypixels)]
end

heatmap!(ax,
	# x range of heatmap follows limits
    lift(x -> minimum(x)[1]:maximum(x)[1], ax.limits),
	# y range also follows limits
    lift(x -> minimum(x)[2]:maximum(x)[2], ax.limits),
    # content is updated when limits or px_area changes
    lift(datashader, ax.limits, ax.scene.px_area), 
    xautolimits = false, yautolimits = false)
```

This should work but for some reason doesn't perfectly, something is up with the coverage of the heatmap on the axis for me..

**Comment by cjdoris** [comment]
Just seen this, that's brilliant, works like a charm. Thanks for your help!
