### ISSUE TITLE
Barplot bar label value in stacked bar charts

### ISSUE THREAD

**Issue by tamasgal** [MakieOrg/Makie.jl#4470]
The following code produces a stacked bar chart where the bar labels show the actual `y` value instead of the original value (which is stacked):

```julia
using CairoMakie

fig, ax, plt = barplot([1,1,2,2], [5,7,3,12];
		stack=[1,2,1,2],
		color=[1,2,1,2],
		bar_labels = :y,
		label_offset = -25,
		label_size = 20,
		label_color=:grey
)
fig
```
![Image](https://github.com/user-attachments/assets/c3095805-cde2-4094-9a49-58d667b621aa)

By changing the `stack=` to `dodge=`, the actual values are shown (since those are now the `y` values, obviously 😉 

```julia
using CairoMakie

fig, ax, plt = barplot([1,1,2,2], [5,7,3,12];
		dodge=[1,2,1,2],
		color=[1,2,1,2],
		bar_labels = :y,
		label_offset = -25,
		label_size = 20,
		label_color=:grey
)
fig
```
![Image](https://github.com/user-attachments/assets/f8bb2b74-78ec-4882-ab65-8781bce87a89)

How do I show the actual values at each bar stack (basically the values which are shown in the dodge barplot)? I mean, the height of each stacked element.

I searched in the docs but could not find anything useful about the `bar_labels` keyword argument. Apparently a `hist` takes also `bar_labels = :values` (cf https://docs.makie.org/dev/reference/plots/hist#Histogram-with-labels) but that is doing basically the same and nonetheless does not work for `barplot`.

**Comment by tamasgal** [comment]
Ah, of course, after writing the issue, I figured it out: by passing the array of values to `bar_labels = ...`.

**Comment by jkrumbiegel** [comment]
Just FYI, for stacked barplots I added `label_position = :center` recently https://docs.makie.org/stable/reference/plots/barplot#label-position

**Comment by tamasgal** [comment]
Ah perfect! Thanks ☺️
