### ISSUE TITLE
Cannot use `:linestyle` in `poly!(…, cycle=[…])`

### ISSUE THREAD

**Issue by dpaetzel** [MakieOrg/Makie.jl#4544]
Hi, thank you for developing and maintaining this library! 🙂 

I'm trying to get `poly!` to cycle not over colors but over line styles (mainly to have a fall back for people with color vision deficiencies). However, that does not work (or I may be doing something wrong here).

For simplicity, I copied and adjusted the [`poly!` example from the docs](https://docs.makie.org/stable/reference/plots/poly.html#example-8e26b40).

```julia
using CairoMakie
using Makie.GeometryBasics


f = Figure()
Axis(f[1, 1])
poly!(
    [Rect(i, j, 0.75, 0.5) for i = 1:3 for j = 1:3],
    color = :white,
    strokewidth = 2,
    cycle = [:linestyle],
    linestyle = [
        :solid,
        :dash,
        :dot,
        :dashdot,
        (:dash, :loose),
        (:dot, :loose),
        (:dashdot, :loose),
        (:dash, :dense),
        (:dot, :dense),
        (:dashdot, :dense),
    ],
),
f
```

This throws the following error:

```
┌ Warning: Using a `Vector{<:Real}` as a linestyle attribute is deprecated. Wrap it in a `Linestyle`.
└ @ Makie ~/.julia/packages/Makie/6c4lt/src/conversions.jl:1079
Error showing value of type Figure:
ERROR: MethodError: Cannot `convert` an object of type Symbol to an object of type Float32

Closest candidates are:
  convert(::Type{T}, ::IntervalArithmetic.ExactReal) where T<:Real
   @ IntervalArithmetic ~/.julia/packages/IntervalArithmetic/KkeZ0/src/intervals/exact_literals.jl:111
  convert(::Type{T}, ::Unitful.Quantity) where T<:Real
   @ Unitful ~/.julia/packages/Unitful/GYzMo/src/conversion.jl:139
  convert(::Type{T}, ::Unitful.Level) where T<:Real
   @ Unitful ~/.julia/packages/Unitful/GYzMo/src/logarithm.jl:22
  ...

Stacktrace:
(long stacktrace redacted to not clutter too much)
```

I also tried to force the `Linestyle` type by applying `Makie.to_linestyle.` as well as `(Linestyle ∘ Makie.to_linestyle).` but to no avail.

- [x] what version of Makie are you running? (`]st -m Makie`)
  ```
  [ee78f7c6] Makie v0.21.14
  ```
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
  
  Yes.
- [x] What platform + GPU are you on?
  
  NixOS, not using GPU. But quite sure it has nothing to do with the platform I'm using.

**Comment by dpaetzel** [comment]
Thanks for the reply! Interestingly, I can do `poly!(…, strokecolor=1:n)` and it just works? Is it intentional that the behaviour of `strokecolor` and `linestyle` differs?

```
using CairoMakie
using Makie.GeometryBasics


f = Figure()
Axis(f[1, 1])
poly!(
    [Rect(i, j, 0.75, 0.5) for i = 1:3 for j = 1:3],
    color = :white,
    strokewidth = 2,
    strokecolor = 1:9,
),
display(f)
```

**Comment by dpaetzel** [comment]
(Something went wrong when posting my reply. I hope this won't be duplicated now; if so, I'm sorry!)

Thanks for the reply! Is it intentional that `strokecolor` and `linestyle` behave so differently? After all, I can simply do `strokecolor=1:9` and it just works?

```julia
f = Figure()
Axis(f[1, 1])
poly!(
    [Rect(i, j, 0.75, 0.5) for i = 1:3 for j = 1:3],
    color = :white,
    strokewidth = 2,
    strokecolor = 1:9,
)
display(f)
```

**Comment by dpaetzel** [comment]
To add to this further: In the end, I want to combine changing `strokecolor` with changing `linestyle`. However, building on your example, the following does not seem to work?

```julia
f = Figure(;
    palette = (;
        linestyle = [
            :solid,
            :dash,
            :dot,
            :dashdot,
            (:dash, :loose),
            (:dot, :loose),
            (:dashdot, :loose),
            (:dash, :dense),
            (:dot, :dense),
            (:dashdot, :dense),
        ],
        strokecolor = Makie.wong_colors(),
    ),
)
Axis(f[1, 1])
for rect in [Rect(i, j, 0.75, 0.5) for i = 1:3 for j = 1:3]
    poly!(rect, color = :white, strokewidth = 2, cycle = [:linestyle, :strokecolor])
end
display(f)
```

It doesn't throw an error but it does not change the strokecolor either:

![Image](https://github.com/user-attachments/assets/4efe3d1e-e711-4bb9-ad43-ce6a275fe9b1)

**Comment by jkrumbiegel** [comment]
The color doesn't change because by default the cycler goes through all values of cycle component 1 first, then all of 2, etc. You have nine rects and nine linestyles so you never see strokecolor 2. You can use `Cycle(..., covary = true)` if you want both to change at the same time:

```
f = Figure(;
    palette = (;
        linestyle = [
            :solid,
            :dash,
            :dot,
            :dashdot,
            (:dash, :loose),
            (:dot, :loose),
            (:dashdot, :loose),
            (:dash, :dense),
            (:dot, :dense),
            (:dashdot, :dense),
        ],
        strokecolor = Makie.wong_colors(),
    ),
)
Axis(f[1, 1])
for rect in [Rect(i, j, 0.75, 0.5) for i = 1:3 for j = 1:3]
    poly!(rect, color = :white, strokewidth = 2, cycle = Cycle([:linestyle, :strokecolor], covary = true))
end
display(f)
```

![Image](https://github.com/user-attachments/assets/4a847225-181f-4a6d-95a5-47dd2ccfe6f3)

**Comment by dpaetzel** [comment]
OK, I think this can be closed now. Thank you for the explanation and your patience! 🙂 (The docs explain the `covary` option [here](https://docs.makie.org/stable/explanations/theming/themes#Covarying-cycles), I don't know why I didn't find that on my own …)

PS: I'm still wondering why the interface for cycling over colors differs from the one for cycling over linestyle but I guess that is a different issue.

**Comment by jkrumbiegel** [comment]
The interface doesn't differ, or what do you mean exactly?

**Comment by dpaetzel** [comment]
Sorry for the late reply. I think what I referred to was

> Is it intentional that strokecolor and linestyle behave so differently? After all, I can simply do strokecolor=1:9 and it just works?

But I think I got it now! Thank you for your help!
