### ISSUE TITLE
Layout tutorial code errors due to gcd

### ISSUE THREAD

**Issue by simonp0420** [MakieOrg/Makie.jl#4545]
Working through the layout tutorial today on Julia 1.11.1 and encountered an error with [this](https://github.com/MakieOrg/Makie.jl/blob/4f045d7a804a4325d567951397e711be36c9d4fe/docs/src/tutorials/layout-tutorial.md?plain=1#L20) line:
```
julia> gcd = f[1:2, 2] = GridLayout()
ERROR: cannot assign a value to imported variable Base.gcd from module Main
```
I guess `gcd` wasn't automatically imported into Base when this tutorial was written?

**Comment by jkrumbiegel** [comment]
I think this only happens if you reference `gcd` before creating that variable. In a fresh session:

```julia
julia> gcd(1, 4)
1

julia> gcd = 1
ERROR: cannot assign a value to imported variable Base.gcd from module Main
Stacktrace:
 [1] top-level scope
   @ REPL[2]:
```

or 

```julia
julia> gcd
gcd (generic function with 15 methods)

julia> gcd = 1
ERROR: cannot assign a value to imported variable Base.gcd from module Main
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```

but also

```julia
julia> gcd = 1
1
```

**Comment by simonp0420** [comment]
Indeed.  Must have inadvertently referenced `gcd` in that session.  I'll close the issue.
