### ISSUE TITLE
Update `scene` `lighting` doesn't work

### ISSUE THREAD

**Issue by ThomasHaine** [MakieOrg/Makie.jl#4551]
- [ ] what version of Makie are you running? (`]st -m Makie`) v0.21.15
- [ ] what version of GLMakie are you running? (`]st -m GLMakie`) v0.10.15
- [ ] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`). Yes
- [ ] What platform + GPU are you on?  Apple M3 Pro

I can't change the `lighting` in a `scene` once it's been rendered. The MWE below works as expected for the red light source. Changing to a blue light source (from a different direction) makes no difference to the displayed image or the saved `png`. The `lscene.scene.lights` variable has been changed as expected, however. 

Based on the [docs](https://docs.makie.org/dev/explanations/scenes#Updating-the-Scene), this looks like a bug? 

```
using GLMakie

f = Figure()
rl = DirectionalLight(RGBf(1, 0, 0), Vec3f(-1, 0, 0))
lscene = LScene(f[1, 1],scenekw = (lights = [rl,],))
mesh!(Sphere(Point3f(0.0), 1.0), color = :white)
display(f)
save("redlight.png",f)
println(lscene.scene.lights)

bl = DirectionalLight(RGBf(0, 0, 1), Vec3f(0, 1, 0))
lscene.scene.lights = [bl,]
update_cam!(lscene.scene)
display(f)
save("bluelight.png",f)
println(lscene.scene.lights)
```

**Comment by ffreyer** [comment]
`FastShading` assumes you're only changing the values in lights, i.e.
```julia
lscene.scene.lights[1].color[] = RGBf(0,0,1)
lscene.scene.lights[1].direction[] = Vec3f(0,1,0)
```
That way the backend doesn't need to check the array every frame and update its version of the data every frame. It can instead just react to the Observables in the lights.

For `MultiLightShading` it does check the array every frame, though it still assumes the array itself is not replaced. I.e. you can do `scene.lights[1] = ...`, but not `scene.lights = [...]`.
