### ISSUE TITLE
PackageCompiler on GLMakie --> display(fig) --> segfault 11 on macos Sonoma 14.6.1

### ISSUE THREAD

**Issue by johnrfrank** [MakieOrg/Makie.jl#4571]
I wrote a toy app that let's you zoom on the Mandelbrot set.  It is at https://github.com/johnrfrank/MandelbrotZoom/

and you can run the app like this:

```bash
julia --project=MandelbrotZoom MandelbrotZoom/src/MandelbrotZoom.jl
```

That works just fine.  It works because it calls `wait(display(fig))`

but!

If you compile it like this:

```bash
julia -e '''
using PackageCompiler

create_app("MandelbrotZoom", "output", incremental = true)
'''
```

then you get an executable that almost works... it prints out messages up to where it calls `display(fig)` and then it does this:
```bash
...
...
Precompiling project...
  21 dependencies successfully precompiled in 135 seconds. 264 already precompiled.
✔ [02m:36s] PackageCompiler: compiling incremental system image
ld: warning: reexported library with install name '@rpath/libunwind.1.dylib' found at '/Applications/Julia-1.11.app/Contents/Resources/julia/lib/julia/libunwind.1.0.dylib' couldn't be matched with any parent library and will be linked directly
ld: warning: reexported library with install name '@rpath/libunwind.1.dylib' found at '/Applications/Julia-1.11.app/Contents/Resources/julia/lib/julia/libunwind.1.0.dylib' couldn't be matched with any parent library and will be linked directly
$
$
$ ./output/bin/MandelbrotZoom 
Draw the famous picture.
Wait for the display to be done...

[57813] signal 11 (2): Segmentation fault: 11
in expression starting at none:1
_platform_memmove at /usr/lib/system/libsystem_platform.dylib (unknown line)
Allocations: 741726 (Pool: 741663; Big: 63); GC: 3
Segmentation fault: 11
$ 


```

- [X] version of Makie and GLMakie

  [ee78f7c6] Makie v0.21.15
  [e9467ef8] GLMakie v0.10.15

- [X] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)

Yes, the segfault happens after compiling with PackageCompiler

- [X] What platform + GPU are you on?

MacBook 2021 Apple M1 Max
macos Sonoma 14.6.1 

GLFW.GetVersionString()
"3.4.0 Cocoa NSGL Null EGL OSMesa monotonic dynamic"

**Comment by SimonDanisch** [comment]
Looks like a package compiler / Julia issue to me

**Comment by JamesWrigley** [comment]
Looks a bit like this issue: https://github.com/Gnimuc/CImGui.jl/issues/146

I see that the package creates the `Figure` in the module itself: https://github.com/johnrfrank/MandelbrotZoom/blob/3bd2976d55ebdb34a0ae13402178a55dee396ed2/MandelbrotZoom/src/MandelbrotZoom.jl#L24
What if you create the figure at runtime instead?

**Comment by SimonDanisch** [comment]
Oh, didn't look at the code...
Yeah that's a no-go! Good catch!

**Comment by JamesWrigley** [comment]
BTW, why is creating a `Figure` in global scope bad? 👀

**Comment by SimonDanisch** [comment]
Because it gets run at compile time, and will get baked into the shared library with all their pointers etc. This will include references to GPU memory and c libraries, tasks etc, which all won't be valid anymore when running the binary.

**Comment by JamesWrigley** [comment]
Ahh I see, thanks.

**Comment by johnrfrank** [comment]
Thank you for the explanation!  This does fix it.  

Here's the refactoring to make it work:

https://github.com/johnrfrank/MandelbrotZoom/commit/da9ae39f29f49495eb006e58b5c78650f00f2b77
