### ISSUE TITLE
What happened to limits keyword in `image`?

### ISSUE THREAD

**Issue by dlfivefifty** [MakieOrg/Makie.jl#4580]
There seems to no longer be a keyword named `limits` for specifying the bounding box of an image. How would one do this now?

I'm trying to update ComplexPhasePortrait.jl which uses this:

https://github.com/JuliaHolomorphic/ComplexPhasePortrait.jl/blob/master/ext/ComplexPhasePortraitMakieExt.jl

**Comment by dlfivefifty** [comment]
Hmm it's possible you are right... but then how do you specify the bounding box for an image? In ComplexPhasePortrait.jl I want to plot a function on top of an image and have the axes be consistent

**Comment by SimonDanisch** [comment]
You mean the size of the image?
It should be the x and y arguments: `image((0, 1), (-5, 5), image_data)`.
