### ISSUE TITLE
Scatter points are at incorrect locations on log-log plot

### ISSUE THREAD

**Issue by ubertakter** [MakieOrg/Makie.jl#4586]
- [ ] what version of Makie are you running? (`]st -m Makie`)
- GLMakie v0.10.16
- [ ] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- Yes. Example code below was run in a fresh environment with attached results.
- [ ] What platform + GPU are you on?
- Windows 11 Enterprise - 10.0.22631 Build 22631
- Nvida RTX A1000 6GB Laptop GPU
- Julia: release 1.11.1+0.x64.w64.mingw32

Scatter points plotted on a log-log plot appear to be in incorrect locations. 

MWE:

```julia
plotConfig = Dict(
           :xscale => log10,
           :xticks => [0.01, 0.1, 1, 10, 100, 1000],
           :xminorticks => IntervalsBetween(10),
           :xminorgridvisible => true,
           :xminorticksvisible => true,
           :yscale => log10,
           :yticks => [0.01, 0.1, 1, 10, 100, 1000],
           :yminorticks => IntervalsBetween(10),
           :yminorgridvisible => true,
           :yminorticksvisible => true
)

f = Figure()
ax = Axis(f[1,1], xlabel="X", ylabel="Y"; plotConfig...)
scatter!(ax, [0.1, 0.2, 1.0], [17.0, 18.0, 19.0])
scatter!(ax, [0.1, 0.2, 1.0], [18.0, 19.0, 20.0])
xlims!(ax, 0.05, 5)
ylims!(ax, 6, 110)
```

On my machine, the results on the y-axis seem to be approximately off by one. The y-values `17, 18, 19` appear to be "one high", so `y=19` is plotted at `y=20` on the plot. Plotting the next series of values is slightly above the first series. Also note that the `x=0.2` values do not fall on the line. This is further illustrated with the series `scatter!(ax, [0.1:0.1:1.0...], fill(10.0, 10))`.

![Image](https://github.com/user-attachments/assets/1b04e2d8-552f-451a-8a29-b539e79f58a8)

**Comment by jkrumbiegel** [comment]
The scatter markers are not off, the minor tick line you're comparing to is just not at `20`. If you want 10 to 100 in steps of 10 that's 9 intervals not 10. `IntervalsBetween(10)` therefore gives you steps of size `9` so the first one is at `19`. If you put `IntervalsBetween(9)`, it matches `yminorticks = 20:10:90`.

**Comment by ubertakter** [comment]
LOL, yeah, thanks for the catch. It's been a day.
