### ISSUE TITLE
Explain arguments of `arrows`

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#464]
Please do. They interact in extremely weird ways. Like, `linewidth` is what exactly? `1` makes a tiny line and `10` makes an almost visible one. Surely not the same as the `linewidth` of a line plot.

Many parameters probably also multiply each other. Please clarify every argument and how it interacts with the others.

**Comment by Datseris** [comment]
EDIT: I now realize that markers and lines are not the same: marker size is in data units, line size is in "correct units" where the line width is independent of zoom level. Still please explain all arguments, this is still a valid question.

**Comment by ffreyer** [comment]
Closing this since all the attributes are documented now
