### ISSUE TITLE
Incorrect background Z-Order when plotting axis-in-axis

### ISSUE THREAD

**Issue by kosukesando** [MakieOrg/Makie.jl#4650]
The inner `Axis`'s background's Z-order does not get respected as expected.
```julia
let
	f=Figure()
	ax1=Axis(f[1,1],
	backgroundcolor=:red)
	lines!([0,10],[0,10],color=:white)
	ax2=Axis(f,bbox=BBox(100,200,100,200),
	backgroundcolor=:blue)
	f
end	
```
 ![Image](https://github.com/user-attachments/assets/d13ed8d8-2c7d-4955-bd30-87220e75cc58)

`translate!` can be used as a hack to get around this, but is not ideal.
```julia
let
	f=Figure()
	ax1=Axis(f[1,1],
	backgroundcolor=:red)
	l=lines!([0,10],[0,10],color=:white)
	translate!(l,0,0,-100)
	ax2=Axis(f,bbox=BBox(100,200,100,200),
	backgroundcolor=:blue)
	f
end	
```
![Image](https://github.com/user-attachments/assets/463413d4-e1c2-4837-b21f-065d1cc85436)

- CairoMakie v0.12.16

**Comment by jkrumbiegel** [comment]
This is not really a bug, nowhere is it promised that whole `Block`s like Axis will just be layered fully over previously created ones. They often have parts at different z levels, that's why translating the whole axis forward works.

**Comment by ffreyer** [comment]
#4150 aims to fix this (but probably not anytime soon)

**Comment by kosukesando** [comment]
> [#4150](https://github.com/MakieOrg/Makie.jl/pull/4150) aims to fix this (but probably not anytime soon)

I see. Thank you for your hard work.
Would this PR affect CairoMakie as well?

**Comment by kosukesando** [comment]
btw for anyone else with the same problem 
```julia
translate!(ax2.scene,0,0,10)
translate!(ax2.elements[:background],0,0,1)
```
seems to do the trick without having to go through everything plotted in the Axis.

**Comment by jkrumbiegel** [comment]
Each block has a `blockscene` that everything it owns is in. So usually this will work `translate!(ax.blockscene, 0, 0, 100)`
