### ISSUE TITLE
Streamplot on surface/mesh transform

### ISSUE THREAD

**Issue by chakravala** [MakieOrg/Makie.jl#4654]
It would be convenient to have streamplots on a surface or mesh, or a way to transform the points of the resulting streamplot with another function which changes the 2D points into 3D points of e.g. a surface.

**Comment by asinghvi17** [comment]
This is exactly what `transform_func` is designed for!   You should be able to set `streamplot_object.transformation.transform_func[]` to whichever function you'd like.  See the docs at https://docs.makie.org/dev/reference/generic/transformations#Transformation-Function.

The transformation interface is a bit tricky, so you might want to do something like:
```julia
transf = Makie.PointTrans{3 #= number of dimensions =#}() do p
    return sin.(p) # perform some transformation
end
```

and then set `streamplot_object.transformation.transform_func[] = transf`.


Please feel free to reopen the issue if this doesn't resolve your question!

**Comment by chakravala** [comment]
@asinghvi17 thank you, I have applied a transform which converts the 2D points into 3D points, but the figure remains 2 dimensional, how can I also change the figure to display as 3 dimensional?

**Comment by chakravala** [comment]
Alright, I figured out how to deal with this now:

1. create a `streamplot` but the points need to be converted to 3D from 2D with the 3rd coordinate as 0 and the `gridsize=(32,32,1)` so that there is only 1 grid size in the 3rd axis centered at 0 on that 3rd axis.
2. then apply the `transform_func` to the plot

This results in the desired plot behavior for me.

**Comment by chakravala** [comment]
Excellent, thank you. By the way, I opened another separate issue regarding updating the arrow directions of streamplot, which has now been answered also https://github.com/MakieOrg/Makie.jl/issues/4666 this completes it.
