### ISSUE TITLE
Unclear font info message

### ISSUE THREAD

**Issue by eschnett** [MakieOrg/Makie.jl#469]
I saw the message "Caching fonts, this may take a while. Needed only on first run!" while running an example for another package. I think this message is generated by Makie. It might be nice if this message was prefixed by `Makie.jl` or similar, to tell me where this message comes from.

**Comment by asinghvi17** [comment]
That message is generated by Makie, specifically by AbstractPlotting.  We're working on a refactor, and we have added this in there, but it might take a while to come out.  Thanks for catching it!

**Comment by ffreyer** [comment]
Closing this because the texture atlas is now downloaded instead of getting generated, so this doesn't pop up anymore
