### ISSUE TITLE
Improve Code Font in Documentation

### ISSUE THREAD

**Issue by ehehela** [MakieOrg/Makie.jl#4690]
I have noticed that the font used for code examples in the Makie documentation makes it difficult to distinguish between commas and periods. This issue hampers readability and understanding of the code. I suggest improving the font used in the documentation to make commas and periods more distinguishable, thereby enhancing the user experience.

Thank you for your attention and efforts!

**Comment by jkrumbiegel** [comment]
Hm yeah I actually agree it's not a great font, seems to be the VitePress default. If you can find out how to change it, I'd appreciate a PR!

**Comment by ehehela** [comment]
Sorry, I’m not sure how to change the font as I’m new to Julia. I’ve recently started learning Makie.jl, but I find the current document font tiresome and distracting.

**Comment by jkrumbiegel** [comment]
It's not a Julia thing, it would be a change in the docs' css files. You could google how to do that for vitepress sites, which is the non Julia tool we're using

**Comment by ehehela** [comment]
I found that changing the CSS code from `--vp-font-family-mono: "Space Mono", Menlo, Monaco, Consolas, "Courier New", monospace` to `--vp-font-family-mono: Consolas, "Courier New", monospace;` makes the code font clearer.

**Comment by ehehela** [comment]
Maybe we can modify this line? Shall I make a pull request?
https://github.com/MakieOrg/Makie.jl/blob/2e0aabeae002bfb930b95b2589e9f8c9272cbd09/docs/src/.vitepress/theme/style.css#L29

**Comment by jkrumbiegel** [comment]
Ok this is current "Space Mono"

<img width="521" alt="Image" src="https://github.com/user-attachments/assets/e492680c-07b3-4f19-a675-b979e56c8c9f" />

Menlo

<img width="517" alt="Image" src="https://github.com/user-attachments/assets/08061494-221d-4f08-b04b-2bf1c0848ec6" />

Monaco

<img width="513" alt="Image" src="https://github.com/user-attachments/assets/331f5f70-5d43-4808-bd1c-1306f36c3374" />

Consolas

<img width="526" alt="Image" src="https://github.com/user-attachments/assets/de3116f5-f5af-48a4-a514-25e3844ca5a7" />

I like both Menlo and Monaco more than Consolas, at least on my Macbook this renders weirdly thin. So maybe just remove "Space Mono" from the list which I agree doesn't have great comma/point separation and in general seems a bit too "unusual" for docs.

The line you found should be the right place to change this I think

**Comment by ehehela** [comment]
I have created a PR. Thank you @jkrumbiegel .
