### ISSUE TITLE
Setting axis labels and title in a plot recipe

### ISSUE THREAD

**Issue by irregular-rhomboid** [MakieOrg/Makie.jl#4692]
I'm currently writing R-style plots for GLM.jl (https://github.com/JuliaStats/GLM.jl/issues/581), and had issues setting the axis labels and title for my plots. The current brittle solution I'm using is getting the axis with `current_axis`, but this won't work if the axes are predefined before the plotting calls.

I guess my questions are the following
1. Should one set axis labels and title within a plot recipe?
2. If yes, what is the correct way to do so?

**Comment by jkrumbiegel** [comment]
Makie currently doesn't really have that option. Recipes are for plot objects which live inside `Scene`s or other plot objects and they therefore don't have the ability to specify axis metadata. Plots.jl recipes on the other hand can describe a whole figure which is where the expectation comes from I guess.

Makie has a SpecAPI which works for this use case in principle, but it's experimental and might be changed at any time so I wouldn't build functionality on top of that currently.

I think the simplest way currently is still to write normal functions that create the whole plot, or optionally plot the axis into a larger figure if a `GridPosition` or `GridSubposition` is passed as first arg.

We have internally spent quite a while already discussing this problem but haven't converged on a solution so far, there are many pros and cons to different possible solutions.

**Comment by irregular-rhomboid** [comment]
Thanks for the clarification.
