### ISSUE TITLE
Image does not respect interpolation kwarg

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#474]
https://github.com/JuliaPlots/GLMakie.jl/blob/a954fd870f35bbcf80e299433b9823dc3747fad9/src/drawing_primitives.jl#L244-L254
v/s
https://github.com/JuliaPlots/GLMakie.jl/blob/a954fd870f35bbcf80e299433b9823dc3747fad9/src/drawing_primitives.jl#L271-L278
cc @SimonDanisch @pablosanjose

**Comment by ffreyer** [comment]
It does now
