### ISSUE TITLE
GLFWError

### ISSUE THREAD

**Issue by yakir12** [MakieOrg/Makie.jl#478]
Very exciting: so if I run `VideoIO.viewcam()` from the RPI I get this error (forgive the wrong line breaks): 
```julia
ERROR: GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: GLXBadFBConfig Stacktrace:  [1] _ErrorCallbackWrapper(::Int32, ::Cstring) at /home/pi/.julia/packages/GLFW/avri6/src/callback.jl:43 
```
But, if I run it from a X forwarded ssh session connected to the rpi, then it works (albeit slow due to the slow WiFi connection)!!!

So I'm guessing I'm missing something on the RPI?

**Comment by ffreyer** [comment]
Closing this as stale and because it's more a raspberry pi/GLFW issue
