### ISSUE TITLE
Issue with irregular grid surface when a campixel child scene is created

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#479]
```julia
using Makie
scene = surface(1:10, 1:10, zeros(10, 10); color = [x for x in 1:10.0, y in 1:10.0], shading = false)
```
<img width="832" alt="before" src="https://user-images.githubusercontent.com/32143268/73115497-8571ee00-3ef4-11ea-9c53-fe09d2fb6068.png">

```julia
poprect = lift(scene.events.mouseposition) do mp
    FRect((mp .+ 5), 250, 40)
end
popup = poly!(campixel(scene), poprect, raw = true, color = :white, strokewidth = 2,
        strokecolor = :black)
scene
```

<img width="832" alt="after" src="https://user-images.githubusercontent.com/32143268/73115499-9884be00-3ef4-11ea-82be-2618c9a80af9.png">
Saving the image to png removes the weirdness...

**Comment by ffreyer** [comment]
Closing this for being outdated/not reproducible. (Why is that surface curved and so dense?)

**Comment by asinghvi17** [comment]
Hmm I'm not sure, I guess this must have been early in the development of GeoMakie though.  So it's probably a 1800x720 or something graphic on a nonlinear projection.

Will reopen if I can replicate this, but it seems unlikely.
