### ISSUE TITLE
DimensionMismatch error in 3D plots from the Makie example gallery

### ISSUE THREAD

**Issue by rlnovak** [MakieOrg/Makie.jl#488]
Hello!

I am trying WGLMakie with a Jupyter notebook and Julia 1.2. I noticed that only simple examples from the Makie example gallery work (scatter, line plots, etc.). Notably, I can't make the 3D plots work.
Every one I tried gave a "DimensionMismatch error. For example, the plot in http://juliaplots.org/MakieReferenceImages/gallery//connected_sphere/index.html throws the following error (the stacktrace is very long, so I am going to copy only the first lines. I can add the entire thing if necessary!):

DimensionMismatch("tried to assign 18 elements to 54 destinations")
Stacktrace:
 [1] throw_setindex_mismatch(::Array{Point{3,Float32},1}, ::Tuple{Int64}) at ./indices.jl:167
 [2] setindex_shape_check at ./indices.jl:218 [inlined]
 [3] setindex! at ./array.jl:800 [inlined]
 [4] setindex! at /Users/rafael/.julia/packages/ShaderAbstractions/yZ9xz/src/types.jl:45 [inlined]
 [5] setindex! at /Users/rafael/.julia/packages/ShaderAbstractions/yZ9xz/src/types.jl:58 [inlined]
 
If I run this same example from the REPL using Makie, it works fine. A similar error is also occurring with: http://juliaplots.org/MakieReferenceImages/gallery//arrows_3d/index.html

**Comment by ffreyer** [comment]
Closing this as outdated since those examples have been outdated for years. 

If this was a backend issue it's likely fixed. If it's an Obersvables synchronization issue, check the docs for "Problems With Synchronous Updates"
