### ISSUE TITLE
Adding a nullcline planes(& plane interesections) for 3d system in the vectorfield plot,streamplot3d or volume plot.

### ISSUE THREAD

**Issue by danielchen26** [MakieOrg/Makie.jl#497]
for a 3d dynamical system, it will be very convenient to add a feature to plot nullcline(planes) and their plane intersections highlighted plotting on top of the vector field(or streamplot3d, or volume plot).
for vector field like the following:
dv1 =f1(v1,v2,v3)
dv2 =f2(v1,v2,v3)
dv3 =f3(v1,v2,v3)
when plotting the vector field (dv1,dv2,dv3) the 2d nullcline planes defined as f1 =0, f2 = 0, f3 = 0(these 3 planes).

It will be nice to add an option to the vector field(or streamplot3d, or volume plot). Maybe by stating `nullcline = true`, the transparent planes and their intersections will show on top of the 3d plot.

**Comment by ffreyer** [comment]
Can this be closed?

**Comment by asinghvi17** [comment]
Seems solved to me but we can add an example to BeautifulMakie
