### ISSUE TITLE
allow for `x` axis in series.

### ISSUE THREAD

**Issue by mschauer** [MakieOrg/Makie.jl#499]
Currently in https://github.com/JuliaPlots/AbstractPlotting.jl/blob/3f43c46e156b1da2b80e36daedd435a64b1edfc4/src/basic_recipes/basic_recipes.jl#L320 the `x`-axis is fixed to `1:n`. A reasonable signature would be `x, Y` where `x` is vector like and `Y` is the matrix of the stacked `y`-values.

**Comment by felixcremer** [comment]
This is fixed.

**Comment by mschauer** [comment]
Thank you.
