### ISSUE TITLE
Piping data into plots

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#502]
For exploratory data analysis, I really like the workflow of piping the outputs of functions into a plotting command, similarly to how VegaLite does this.  I'll bring this up at Vizcon as well - it's a great improvement to some workflows which I'd like to see implemented.  It should be a fairly trivial method addition - `$(funcname)(; attributes...) = (x...) -> $(funcname)(x...; attributes...)`

**Comment by ffreyer** [comment]
Closing this since it seems like there was no further interest in pursuing this.

**Comment by asinghvi17** [comment]
AlgebraOfGraphics is the workflow I was probably going for here, if someone reads this later.
