### ISSUE TITLE
Allow global dpi change

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#506]
I think it would be good to have a global `const Ref{Float64} dpi` or something like that, which would allow exporting plots at different bitmap sizes without changing anything but the dpi value. Right now, a lot of code assumes pixels, so if I want a plot at higher resolution, all fonts will be too small because they don't grow with larger plot size. But if all values for font sizes, line widths, etc. would be multiplied with that dpi value at some late stage in the pipeline, that would enable flexible scaling.

**Comment by SimonDanisch** [comment]
We now have px_per_unit for all backends as of #3113
