### ISSUE TITLE
Polar axis plan

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#521]
- Compute datalimits (x, y) -> (r) - theta is 0-2pi no matter what
- Optimize ticks for r
- Plot circles at each tick (`lines(Circle(0f0, radius))`)
- Plot (1) linesegments going from the origin to the thetas.  Let thetas be configurable by ticks.
- All thetas in radians.
- Annotations for:
    - thetas
    - rs

- If you want different coordinates - wrap them in CoordinateTransformations.jl
- wrapper types Radii and Angles for arrays so they can be decomposed?

**Comment by garrekstemo** [comment]
I was looking for a way to make a polar plot when I found this issue. I played around with the prototype @asinghvi17 posted and added some fake data. I took some ideas from Plotly, like adding a border circle outside of the data and labeling the angles just outside this border. I'm not sure how to space the r-ticks.

It would be really nice to implement this soon. I've never contributed to a project before, but is there anything I can do to help get this moving along?

```
θdata = 0:0.1:2π
rdata = 10 .* sin.(2*θdata)

rs = range(1, round(maximum(rdata)), length = 4)
θs = 0:π/4:2π
rborder = maximum(rs) * (1.10)

f = Figure()
ax = Axis(f[1, 1], aspect = 1.0)

for r in rs
    lines!(ax, Circle(Point2f(0), r), color = :lightgray)
end

lines!(ax, Circle(Point2f(0), rborder), color = :lightgray)

radiallines = zeros(Point2f, 2 * length(θs))

for (i, θ) in enumerate(θs)
    radiallines[i*2] = Point2f(rborder * cos(θ), rborder * sin(θ))
end

linesegments!(ax, radiallines, color = :lightgray)

for r in rs
    text!("$(r)", position = (r, 0), align = (:center, :bottom))
end

for θ in θs[1 : end-1]
    offset = rborder * 0.1
    text!("$(Int64(θ * 180/π))°", position = ((rborder + offset) * cos(θ), (rborder + offset) * sin(θ)), align = (:center, :center))
end

lines!(ax, rdata .* cos.(θdata), rdata .* sin.(θdata))

hidespines!(ax)
hidedecorations!(ax)

```

![plot_4](https://user-images.githubusercontent.com/8449000/155513849-87afd515-633b-460d-bdde-d06eb90632bf.png)
