### ISSUE TITLE
Updates to plot do not cascade to colorlegend 

### ISSUE THREAD

**Issue by yakir12** [MakieOrg/Makie.jl#522]
This is from a conversation on [slack#makie](https://julialang.slack.com/archives/C8RQUU2KH/p1567521043076600).

Updating the colors of a plot does not update the properties of the plot's color-legend (colorbar). 

More specifically, if I `colorlegend!` a `surface` plot who's colors are `lift`ed from a `node`, when updating the node, the colors in the surface change, but the colrobar's limits are wrong. So it seems like the color limits for the colorbar are determined at plotting time, and then they don't get updated after the plot they are connected to does.

In this silly MWE, I change the maximal number of discrete colors which changes the colors of the surface. But the color-bar's maximum should also change, but it doesn't. It only changes if you rerun this with different starting values for the slider:

```julia
h, sl = textslider(2:10, "maximal number of discrete colors", 
                   start = 2 # change this to change the top limit of the colorbar
                  )
z = rand(10, 10)
p = surface(z, color = lift(x -> rand(1.0:x, 10, 10), sl))
cb = colorlegend(p[end], width = (30, 300))
vbox(hbox(h, p), cb)
```

**Comment by ffreyer** [comment]
Closing as outdated
