### ISSUE TITLE
Avoid collecting range in slider

### ISSUE THREAD

**Issue by yakir12** [MakieOrg/Makie.jl#523]
When supplying a slider with a range (rather than an vector), avoid converting the range to a vector if possible. 

This means that these two will take the same time to render (currently, not the case):
```julia
slider(range(0,1,length = 10^1))
slider(range(0,1,length = 10^9))
```
Basically, maintain the laziness of the input for as long as possible...

**Comment by ffreyer** [comment]
They do now
