### ISSUE TITLE
Color ignored on meshes

### ISSUE THREAD

**Issue by c42f** [MakieOrg/Makie.jl#525]
The following displays a black triangle

```julia
mesh(HomogenousMesh(vertices=Point3f0[(0,0,0), (0,1,0), (1,0,0)],
                    faces=Face{3,Int}[(1,2,3)],
                    color=[0.0,1.0,2.0]),
     shading=false)
```

whereas the following shows a colored triangle as expected

```julia
mesh(HomogenousMesh(vertices=Point3f0[(0,0,0), (0,1,0), (1,0,0)],
                    faces=Face{3,Int}[(1,2,3)]),
     color=[0.0,1.0,2.0],
     shading=false)
```

**Comment by ffreyer** [comment]
Closing this as outdated/fixed.

You can do mesh-global colors as `Makie.mesh(..., color = color)` and per-vertex colors with `Makie.mesh(..., color = vector_of_colors)` now.
