### ISSUE TITLE
Document working with NaN

### ISSUE THREAD

**Issue by SimonDanisch** [MakieOrg/Makie.jl#527]
just added NaN / Missing converts: https://github.com/JuliaPlots/AbstractPlotting.jl/commit/4acab1fe1ea6647c426e0bceb7a0d2deb785b1c7
which adds the `nan_color` kw-arg to heatmap... Would be nice to have a documentation section about working with NaNs/missing... And while doing so create tests + open issues about corner cases, so that we get consistent behaviour (e.g. pinch me to implement it in the same way for images)....
cc: @rapus95

**Comment by ffreyer** [comment]
There is some information on this in the colors documentation page and in plot docstrings. Maybe todays machinery could use some more documentation but I think that's outside the scope of this issue. Closing as done.
