### ISSUE TITLE
Provide a method to set attributes

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#530]
Provide a symbol, or list of symbols, and then recursively update the given attribute in every plot with some exclusion criterion

**Comment by ffreyer** [comment]
I don't understand what's requested here so I'm guessing this is outdated. Attributes update recursively down a plot tree, and function like `setindex!`, `getindex`, `get`, etc are defined. 

Closing this as outdated.

**Comment by asinghvi17** [comment]
Ah yeah that was pretty vague...if I end up needing this then I'll PR it or comment here.  The intent was, I think, to have a way to update the same attribute (or nested attribute) across multiple plots in `scene.plots`.
