### ISSUE TITLE
Make `meshscatter` and `scatter` the same function?

### ISSUE THREAD

**Issue by c42f** [MakieOrg/Makie.jl#544]
Is there a reason why we have both of these? Their functionality looks almost exactly the same.

Can we collapse them together by just replacing `meshscatter` with `scatter(..., marker=some_mesh)` and dispatching on the `marker` to get the correct geometry processing and shader setup?

**Comment by ffreyer** [comment]
Closing this since it hasn't gotten any more traction for a long time. `scatter` and `meshscatter` are also very different in what they do in the backend/visualization so I don't think it's a good idea to merge them.
