### ISSUE TITLE
Improving performance by improving type inference

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#553]
A flame chart reveals that the vast majority of time in `using AbstractPlotting` and time-to-first-plot is spent on type inference.  Is there a way to reduce this?  

Perhaps we could create a plot in the scope of AbstractPlotting so that precompilation could at least decrease time to first plot?

**Comment by maxfreu** [comment]
I think Makie is quite fast now, is this still an issue?

**Comment by SimonDanisch** [comment]
Yeah not much help having this issue either way ;) 
Although systematically improving inferability would still be good in general!
