### ISSUE TITLE
Plots don't clip at limits

### ISSUE THREAD

**Issue by vilim** [MakieOrg/Makie.jl#558]
There doesn't seem to be any data or drawing clipping implemented, as plotting e.g.
`lines([1, 2, 3], [1, 2, 1], limits=FRect(1, 1, 1.5., 1.5))`

results in the following
<img width="475" alt="Screenshot 2019-03-14 at 00 09 27" src="https://user-images.githubusercontent.com/3041236/54420436-471f7600-470a-11e9-87d2-b9f155a8cc14.png">

Also, it is unclear why there is still padding if limits are explicitly set, I see no reason for grid lines to extend beyond the specified plot range. 

For interactive work, setting limits as a rectangle is also quite unintuitive, as all other plotting libraries I encountered accept limits in the form (x_min, x_max), (y_min, y_max).

I would be happy to have a look myself at these issues, but I am not sure at which point this should be implemented (here or in the various backends, or parts in both?)

**Comment by ffreyer** [comment]
They do now
