### ISSUE TITLE
X axis lines undergo a weird transformation when resizing the scene on MacOS

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#559]
<img width="748" alt="Screen Shot 2019-07-24 at 2 50 08  15500PM" src="https://user-images.githubusercontent.com/32143268/61781689-6fd71b00-ae22-11e9-913c-bfc78edcd4f4.png">

**Comment by ffreyer** [comment]
Closing as outdated/fixed
