### ISSUE TITLE
Document what is Mouse.left what is Mouse.down what is DragEnum etc.

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#561]
So that other people (like me) can help development of the interactive API. At the moment it is something alien that I Can just use through example. This is not the proper way forward...

(finally found `Mouse` in `interaction/iodevices.jl`...)

**Comment by ffreyer** [comment]
At this point we have a docs section about events with some examples including mouse and keyboard interactions so I'm closing this as compelted
