### ISSUE TITLE
strokewidth in px

### ISSUE THREAD

**Issue by yakir12** [MakieOrg/Makie.jl#570]
```julia
h = scatter(rand(Point2f0, 10), marker = '●', strokecolor = :white, strokewidth = 1px, markersize = 10px)
FileIO.save("a.pdf", h)
```
which `ERROR: MethodError: no method matching Float32(::AbstractPlotting.Pixel{Int64})`

**Comment by asinghvi17** [comment]
AFAIK, strokewidth is already in user units.

**Comment by yakir12** [comment]
I guess this is also about not being able to use float px
