### ISSUE TITLE
polygons not closing properly

### ISSUE THREAD

**Issue by grero** [MakieOrg/Makie.jl#571]
I just came across this weird issue which is seemingly related to how polygons are drawn when they are given as a vector of Points. To be concrete, I'm creating a boxplot like this

```Julia
using StatsMakie, CairoMakie, AbstractPlotting
AbstractPlotting.current_backend[] = CairoMakie.CairoBackend("/tmp/testplot.pdf")
AbstractPlotting.inline!(false)
x = randn(100)
scene = boxplot(fill(1,length(x)), x, notch=true)
```

which produces the following figure

[testplot.pdf](https://github.com/JuliaPlots/CairoMakie.jl/files/3668749/testplot.pdf)

Now, this opens fine in Acrobat Reader and Preview on a Mac, but when I try to open the same figure in a more fancy vector graphic editor, in this case Graphic, the program fails to open the file, complaining about non-closed shapes. I have contacted the developer of Graphics, and he confirms that this appears to be the reason why the file does not open. Obviously, I understand if this is not a priority, since I can open the file just fine in other programs, but I thought I'd just put it here if anyone stumbles upon the same problem (or even better,  a solution : ) ). Thanks!

**Comment by ffreyer** [comment]
Seems fixed to me
