### ISSUE TITLE
Setting the font antialias policy

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#579]
Currently, the fonts in PNGs look pretty bad, probably because the antialiasing is not set to the correct type.
![image](https://user-images.githubusercontent.com/32143268/80334357-9c670a00-886e-11ea-85d9-4527bd3352bb.jpg)

**Comment by ffreyer** [comment]
I can't really tell what's wrong here... Can we close this?

**Comment by asinghvi17** [comment]
Yeah they look a lot better now, I think we added the ability to customize antialias in general at some point.
