### ISSUE TITLE
More interpolation in heatmap interpolation

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#581]
Right now, it's nowhere near the level of interpolation GLMakie has, though this may not be a bad thing.
### GLMakie:
![ref_image](https://user-images.githubusercontent.com/32143268/80310691-b0245900-87f9-11ea-8d79-4b7ced7dad26.jpg)

### CairoMakie:
![test_image](https://user-images.githubusercontent.com/32143268/80310697-b3b7e000-87f9-11ea-90db-4581a7e1fe7d.jpg)

**Comment by ffreyer** [comment]
This has been fixed
