### ISSUE TITLE
[FR] Implement a `dpi` option.

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#588]
Would be very nice to get a dpi argument to `Makie.save`.
```
Makie.save("static_billiard_plot.png", scene, dpi = 600)
```
doesn't work. But it is really a big pain to simple "increase the resolution of the scene", because I must manually adjust every single text size.

And if not, when I save it into file it really looks crappy at low resolutions...

**Comment by jkrumbiegel** [comment]
if your plot is 2d, cairomakie should be able to handle it now, and it has the argument `px_per_unit` for png scaling and `pt_per_unit` for vector scaling. Can you try that?

**Comment by Datseris** [comment]
Sure, I will try it at night, thanks for letting me know. To switch backends do I simply write `using CairoMakie` after `using Makie`?

**Comment by asinghvi17** [comment]
Yep, that should be sufficient.  You can switch between backends by using `CairoMakie.activate!()` or `GLMakie.activate!()

**Comment by asinghvi17** [comment]
We just released a new version of CairoMakie, by the way - so you should be sure to upgrade before you try this out.  (It fixes a bunch of things related to markers...)

**Comment by liuyxpp** [comment]
> if your plot is 2d, cairomakie should be able to handle it now, and it has the argument `px_per_unit` for png scaling and `pt_per_unit` for vector scaling. Can you try that?

Can you give an example how to use `pt_per_unit`? What does `pt_per_unit` mean? Thanks!

**Comment by SimonDanisch** [comment]
`px_per_unit` is now supported for all backends as of #3113
