### ISSUE TITLE
Plot output is no longer resized automatically

### ISSUE THREAD

**Issue by chakravala** [MakieOrg/Makie.jl#594]
Starting with the new v0.10 updates, the output windows of Makie in my Linux with i3 tiling window manager no longer automatically resizes the contents of the plot.

Since I am using a tiling window manager, the new window is automatically resized to fit into the screen as a new tiling window.

Previously in v0.9 and less, Makie successfully displays the plot and it is resized correctly initially.

This is no longer true, now the plot is scaled to some default size, which means it is cut off and not centered in the window. Only after redrawing the window from resizing it is the display correct.

Please fix this issue again. Regards.

**Comment by SimonDanisch** [comment]
This will be hard to fix if I can't reproduce it. 
Could you at least add a few screenshots? Also, is there a chance, that the display manager does something slightly differently, or have tested 0.9 and 0.10 side by side and you're 100% sure its the version change?

**Comment by ffreyer** [comment]
Closing this as outdated/due to lack of activity
