### ISSUE TITLE
wglmakie camera issue

### ISSUE THREAD

**Issue by zhaoyachuanl** [MakieOrg/Makie.jl#598]
when using wglmakie as the backend for a nested 3d scene. 
Only these objects whose distance from the camera less than a certain value  are visible. 
I tried to modify the 3d_camera 's property(far, near, fov)to change its visual range but it doesn't work.
when I changed the backend to glmakie, this issue was disappeared. All the objects in the nested scenes are visible.

It also happend to this example in gallery
[http://juliaplots.org/MakieReferenceImages/gallery//robot_arm/index.html]()

my env:
win10 x64 1909
julia win64 1.4.1
AbstractPlotting v0.10.6
Makie v0.10.0
GLMakie v0.1.2
WGLMakie v0.2.2

thanks for help

**Comment by Ariel1240** [comment]
👀👀👀👀👀I'm catching up pretty quickly I'm👀👀👀👀u

**Comment by ffreyer** [comment]
I think this issue is too old to act on now. The way the camera is handled on the Julia side has changed, which may have fixed the issue, and the way WGLMakie synchronizes has as well. If there are still problems with this feel free to open a new issue
