### ISSUE TITLE
Docs should show available markers and linestyles

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#612]
One thing I find extremely convient about pyplot is how it showcases the available markers and linestyles, and this result is directly obtainable by googling "pyplot marker styles". E.g.: https://matplotlib.org/3.2.1/api/markers_api.html 

I think it would be equally usefull for Makie to have this as well.

**Comment by asinghvi17** [comment]
I guess we could do this on a new page and add an example.  Will also mention that you can use arbitrary chars (but not strings).

**Comment by LeMinaw** [comment]
Note there's `available_marker_symbols()` that could be conveniant for this ([docs](https://makie.juliaplots.org/stable/abstractplotting_api.html#AbstractPlotting.available_marker_symbols-Tuple{})).

**Comment by Datseris** [comment]
Yeah I ended up finding this function eventually. It should be more exposed and definitely actuially run in the docs, so that users can see the output. However, I would argue it is better to _both_ show the output of the function (so that users know the exact input code for any marker), but also use the function for a scatterplot with all markers.

**Comment by Moelf** [comment]
also `available_marker_symbols` is not re-exported by backend, say, CarioMakie. One needs to:
```julia
CairoMakie.Makie.available_marker_symbols()
```

**Comment by musoke** [comment]
Is someone working on this issue?  Would it be helpful if I did?

**Comment by ffreyer** [comment]
The scatter docs list all the named markers now and also the categorizes of markers that exist (Char, BezierPath, Polygon, images, Circle, Rect). Closing this as completed
