### ISSUE TITLE
Saved animation garbled

### ISSUE THREAD

**Issue by grahamas** [MakieOrg/Makie.jl#632]
When I record an animation, it displays fine, but then the saved file is completely garbled.  The first frame is correct (sometimes), and then the remaining frames are unrecognizable as plots.  You can sort of see what they should be, but it's as if all the lines of pixels are offset by increasing amounts, plus some noise.

Here's an MWE:

```julia
function test_anim(fn)
    scene = Scene()
    record(scene, fn, 1:5) do n
        lines!(scene, 1:5, (1:5) .* n)
    end
end
test_anim("test.mp4")
```
(though the above also doesn't really display correctly in the first place -- not sure what's up with that.)  I've also tried .mkv, same problem.

```
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```
```
Makie v0.11.0
```

The problem persists across video players and operating systems, so I'm pretty sure it's not on the playback end (I sent test videos through facebook and the facebook web player showed the same problem).

**Comment by ArbitRandomUser** [comment]
are you using i3 WM ? , can you configure i3 to default Makie windows to Float and see if it works

**Comment by grahamas** [comment]
Good guess!  I was using i3.  Unfortunately I no longer am, so I can't test your theory.

However, now on Ubuntu (Gnome), the animation is still garbled.  Not as jaggy as before.  Now it's more like the plot is happening offscreen.  The plot also doesn't display correctly while being produced, the way it did before when produced in i3.

**Comment by ffreyer** [comment]
```julia
function test_anim(fn)
    scene = Scene()
    record(scene, fn, 1:5) do n
        lines!(scene, 1:5, (1:5) .* n)
    end
end
test_anim("test.mp4")
```
that doesn't center the plot for me. It looks fine though with `update!(scene)` after `lines!`. (On Ubuntu 18.04)

**Comment by SimonDanisch** [comment]
That's somewhat expected. `display(scene)` is when `update!` gets called, and display gets called only one time in the beginning in `record`. 
Since you add the plot afterwards, center  (update!) isn't called again.

**Comment by ffreyer** [comment]
Closing this as outdated/fixed. Axis/Axis3/LScene should update limits when plots are added now.
