### ISSUE TITLE
`Base.empty!(ax::LAxis)` ?

### ISSUE THREAD

**Issue by ericphanson** [MakieOrg/Makie.jl#643]
I've been using this locally:
```julia
function Base.empty!(ax::LAxis)
    while !isempty(ax.scene.plots)
        plot = first(ax.scene.plots)
        delete!(ax.scene, plot)
    end
end
```
and it's pretty convenient sometimes. I was wondering if it would be useful to have in AbstractPlotting? Could have `empty!` for other Makie objects too. I could make a PR if this seems desired.

**Comment by SimonDanisch** [comment]
Sounds like a good idea :)

**Comment by SimonDanisch** [comment]
This exists now!
