### ISSUE TITLE
Settings for inline display

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#652]
We can set `px_per_unit` and `pt_per_unit` for `save` calls, but they are always at their defaults if a plot is just displayed. Also, one should be able to switch between svg or png, because png can be useful when many markers are present and svg filesize balloons.

**Comment by ffreyer** [comment]
`px_per_unit` settings for displayed plots have been added in 0.20 and I think we have made a decision on svgs vs pngs at some point. Closing as completed
