### ISSUE TITLE
Close Makie window

### ISSUE THREAD

**Issue by Antomek** [MakieOrg/Makie.jl#658]
Hello everyone,

I was trying to follow the Makie tutorial and literally the first window I opened I could not close any more.
I am not using the development version (did just do `]add Makie`), and have v0.11.0.

The window is stuck to the top of the screen and I see no window border with a cross to close it, for example.
I can still interact with the plot by zooming and so forth.

My OS is macOS High Sierra. Any help is appreciated!

**Comment by pbouffard** [comment]
Duplicate: #393?
