### ISSUE TITLE
Is the type of text position attribute correct?

### ISSUE THREAD

**Issue by pauljurczak** [MakieOrg/Makie.jl#663]
The docs http://makie.juliaplots.org/dev/functions-overview.html#text states that:
```
position        Float32[0.0, 0.0]
```
but this doesn't compile:
```
text!(scene1, "label1", position = Float32[100, 100])
....
ERROR: LoadError: BoundsError: attempt to access 2-element Array{Float32,1} at index [3]
```
on the other hand, version with a tuple instead of an array works:
```
text!(scene1, "label1", position = (100, 100))
```

**Comment by ffreyer** [comment]
The suggested type here is actually `Point2f0` or `Vec2f0`. They both get printed as `Float32[...]`. Most (if not all) the 2 or 3 component vectors you see in that section are actually `Point2f0/Vec2f0` or `Point3f0/Vec3f0`.

**Comment by pauljurczak** [comment]
Documentation lists `Float32[0.0, 0.0]` as a default value, which doesn't compile. I can make a pull request, which substitutes `Float32[0.0, 0.0]` with `Vec2f0(0.0, 0.0)`. I'm not sure about other cases where `Float32[]` is used.

**Comment by ffreyer** [comment]
Closing this since the documentation no longer suggests that.

Though the printing still annoys me, maybe that's something for https://github.com/JuliaGeometry/GeometryBasics.jl/pull/173

**Comment by asinghvi17** [comment]
I believe the printing is a consequence of points being static vectors - we could fix that pretty easily up there by defining show methods...
