### ISSUE TITLE
LMenu label text as a LText object - MakieLayout.jl

### ISSUE THREAD

**Issue by errearanhas** [MakieOrg/Makie.jl#669]
In `LMenu` section of [Layoutable Example](https://jkrumbiegel.github.io/MakieLayout.jl/stable/layoutables_examples/#LMenu-1) (MakieLayout.jl docs), we can see that a menu text label has to be defined as another object `LText`. Would be better being able to just create a `LMenu` with a label already, instead of creating two separate elements.

**Comment by jkrumbiegel** [comment]
Hm yes I see your point. The way I have designed these things is to make relatively minimal implementations. Not every LMenu needs a title, or doesn't need it in the same place, so it's easier to have people assemble their own version. If you often need a menu with a title, you could just make a function for that like

```julia
function titled_menu(scene)
	layout = vbox!(
		LText(...),
		LMenu(...)
	)
end

# and then

layout[1, 2] = titled_menu(scene)
```

**Comment by ffreyer** [comment]
Closing this since it's not something we plan to change
