### ISSUE TITLE
Crash in debugger

### ISSUE THREAD

**Issue by pauljurczak** [MakieOrg/Makie.jl#672]
This code snippet runs just fine in normal (release?) mode:
```
using AbstractPlotting, GLMakie, Random

image = rand(1:4, 640, 480)
scene = Scene(resolution = (1200, 1500))

scene1 = Scene(scene, IRect(0, 0, 1200, 900))
imageNode = Node(image)
image!(scene1, imageNode, scale_plot = false, show_axis = false, interpolate = false, colormap=[:white, :blue, :green, :red])

display(scene)
```
but throws an uncaught exception in debugger (VSCode with Julia v1.4.2):

![err6](https://user-images.githubusercontent.com/4933032/89113204-42f11700-d42b-11ea-8717-6e1165e6d7f2.png)

Is it Makie problem or Julia for VSCode debugger problem?

**Comment by ffreyer** [comment]
This doesn't cause an error anymore
