### ISSUE TITLE
Unexpected behavior of colormap

### ISSUE THREAD

**Issue by pauljurczak** [MakieOrg/Makie.jl#673]
This code:
```
using AbstractPlotting, GLMakie, Random

image = rand(1:4, 64, 48)
scene = Scene(resolution = (1200, 1500))

scene1 = Scene(scene, IRect(0, 0, 1200, 900))
imageNode = Node(image)
image!(scene1, imageNode, scale_plot = false, show_axis = false, interpolate = false, colormap=[:white, :blue, :green, :red])

display(scene)
sleep(2)

imageNode[] = rand(1:3, 64, 48)
```

uses different `colormap` depending on range of values in `imageNode`. Full range `1:4` colors:

![colors1](https://user-images.githubusercontent.com/4933032/89116327-100d4a00-d450-11ea-8570-10cb8064751e.png)

partial range `1:3` colors:

![colors2](https://user-images.githubusercontent.com/4933032/89116331-1e5b6600-d450-11ea-9b7e-962edd98dbac.png)

Is this expected behavior?

**Comment by ffreyer** [comment]
This is expected. The colormap is interpolated and without setting the colorrange it will default to `extrema(data)`. So 1 maps to white, 3 to red and 2 to `0.5 * (blue + green)`.
