### ISSUE TITLE
New windows have shifted positions on Mac

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#682]
Can't find the old issue anymore, so I'm possibly re-adding this just to add it to the milestone of old mac issues.

The problem is that a window that is closed is somehow not completely closed in GLFW, or at least something remains. Then, when a new window is opened, it appears at reliably shifted position away from the old location. This behavior is similar to what happens when you open multiple windows of a program at the same time on a mac, they get shown shifted down to the right, so they don't completely overlap. This happens here as well, but with only one window visible at a time.

This probably also has to do with the issues of not being able to close windows at all on Mac.

**Comment by pbouffard** [comment]
> This probably also has to do with the issues of not being able to close windows at all on Mac.

I don't seem to have this issue. Or at least, the close button does cause the window to disappear; not sure if it frees up all resources. Though it does at least temporarily allieviate #678.

My workflow these days hinges entirely on a combination of a sysimage with Makie baked in, Revise.jl, and closing the GLMakie window while I'm doing anything other than looking at the plot ;-).
