### ISSUE TITLE
per-julia-version texture atlas cache

### ISSUE THREAD

**Issue by goretkin** [MakieOrg/Makie.jl#685]
The path to this cache: https://github.com/JuliaPlots/AbstractPlotting.jl/blob/8ba5368193991a436e26d1e78813af2e71b5efeb/src/utilities/texture_atlas.jl#L52 is shared across Julia versions. if you switch between two versions of julia in the system, then I guess you'll keep re-generating this, and possibly keep triggering this warning.

It's hard to tell from the code what the intention of the `try/catch` is. For example, can I ignore this error?

```
[ Info: You can likely ignore the following warning, if you just switched Julia versions for Makie
┌ Warning: MethodError(convert, (String, FreeTypeAbstraction.FTFont(Ptr{FreeType.LibFreeType.FT_FaceRec_} @0x0000000000000000, true, Dict{Char,FreeTypeAbstraction.FontExtent{Float32}}())), 0x0000000000006ac3)
```

**Comment by bilderbuchi** [comment]
It also looks like a weird location, that `makie` folder is the only package-specific thing that I have at that directory level. Should that live in `scratchspaces`? (no idea, now further experience)

**Comment by asinghvi17** [comment]
It definitely could live in scratchspace - that wasn't around when this was implemented and I don't think anyone got around to implementing it.

**Comment by SimonDanisch** [comment]
The per julia version isn't needed anymore, we now have our own serialization format independent of the julia version!
We could use scratchspace though, I suppose!

**Comment by ffreyer** [comment]
We're doing that now
