### ISSUE TITLE
Can not update AbstractPlotting past v0.9.21

### ISSUE THREAD

**Issue by rekabrnalla** [MakieOrg/Makie.jl#713]
In one environment that I am developing I have AbstractPlotting updated to the latest 0.12.13, but in the default @v1.5 environment, I can't get AbstractPlotting to got past v0.9.21.  

What should I do?

I'm trying to debug in Vscode but I can't get the active environment to not be the default, so I was trying to get it updated to the development package's environment, but I have been stuck with this problem for hours.

What's the debug path?

Thanks for the help.
Allan Baker

**Comment by jkrumbiegel** [comment]
In these cases you usually try to add the specific new version of the package that can't be updated. This causes Pkg to print where the compat conflicts lie. That's basically always one or more packages that have lower compat bounds than the newest version needs.

So do `]add AbstractPlotting@0.12.13` and then look at the conflict description

**Comment by ffreyer** [comment]
Closing as outdated (AbstractPlotting is deprecated).
