### ISSUE TITLE
High CPU Usage on WSL with very simple plot

### ISSUE THREAD

**Issue by Seelengrab** [MakieOrg/Makie.jl#714]
Hi,

I'm using Makie/GLMakie from WSL on Windows via a windows based X server, but this results in very high CPU Usage (100% on 4 cores) for something as simple as `lines(0:10)`. The behaviour seems to be the same as in #645, but stopping rendering altogether obviously isn's a solution here :/

My versions are:

```
(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [537997a7] AbstractPlotting v0.12.14
  [82cc6244] DataInterpolations v3.2.1
  [31a5f54b] Debugger v0.6.6
  [e9467ef8] GLMakie v0.1.11
  [ee78f7c6] Makie v0.11.1

julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

Am I doing something wrong or is this not expected to work through WSL?

**Comment by ffreyer** [comment]
Closing this since #645 is closed. This was likely fixed by #2336
