### ISSUE TITLE
Convenience function for multiple lines and sensible categorical color defaults

### ISSUE THREAD

**Issue by niclasmattsson** [MakieOrg/Makie.jl#716]
Related but not duplicates I believe: #366, #368.

Unless I've missed something basic, Makie lacks a convenience function to make a line plot of multiple columns of data like `plot(1:10, rand(10,5)` in Plots.jl. In the Plots.jl universe this is deemed so fundamental that it is [example 2 of the tutorial](https://docs.juliaplots.org/latest/tutorial/). In Makie it appears you have to write out a loop or comprehension using `lines!`, and explicitly set a categorical color scheme:

```julia
function plotlines(x,y)
    scene = Scene()
    for i = 1:size(y,2)
        lines!(scene, x, y[:,i], color=ColorSchemes.Set1_9[i])
    end
    scene
end
```

If you incorrectly assume you get an appropriate categorical color if you set `color` to an integer you get a really nasty error that dumps 100 lines of shader code into the REPL and terminates with `ERROR: program 34 not linked`. I think setting `color=i` could be a nice shorthand for using a categorical color scheme.

**Comment by filchristou** [comment]
I think something in this direction would be a good addition. 
A major advantage will be that updating such plots with observables will be easier.

**Comment by SimonDanisch** [comment]
There's series:
https://docs.makie.org/v0.18.2/examples/plotting_functions/series/index.html

**Comment by filchristou** [comment]
Oh yes. Then I assume that this issue can be closed since the initial motivation of the OP was exactly what `series` provide..
