### ISSUE TITLE
Add a simpler complete MWE of a recipe (+ MakieLayout) to docs

### ISSUE THREAD

**Issue by briochemc** [MakieOrg/Makie.jl#717]
(From a conversation I started on Slack)

I find [the complete recipe example in the docs](http://makie.juliaplots.org/dev/recipes.html) too complex for new comers (to recipes) like myself. (The animation of wiggling molecules in a 3D grid.) I think a simpler complete example would be useful, so here is one for suggestion. I also think the simple recipe example could be embedded in a MakieLayout. It could fit well just before the 3D animation IMHO. 

MWE:
```julia
using AbstractPlotting
using AbstractPlotting.MakieLayout
using GLMakie
GLMakie.activate!()

# Define the type (exports `xribbon` and `xribbon!` among many other things)
@recipe(XRibbon, μ, σ, y) do scene
    Attributes(
        color=:red,
    )
end
# What the recipe actually does
function AbstractPlotting.plot!(p::XRibbon)
    # get the observables of this version with three arguments
    μ = p[:μ]
    σ = p[:σ]
    y = p[:y]
    ribbon_left = @lift($μ - $σ)
    ribbon_right = @lift($μ + $σ)
    X = @lift([$ribbon_left; reverse($ribbon_right)]) # x coordinates ┬─ of polygon of ribbon
    Y = @lift([$y; reverse($y)])                      # y coordinates ┘
    ribbon_poly = @lift(Point2f0.(zip($X, $Y)))
    poly!(p, ribbon_poly; color=(p[:color], 0.5), strokewidth=0)
    lines!(p, μ, y; color=p[:color])
    p
end

# Make a figure with 1×2 subplots of xribbons
S, L = layoutscene()
display(S)
ax1 = L[1,1] = LAxis(S)
xribbon!(ax1, rand(10), 0.1 .+ 0.1rand(10), 1:10, color=:blue)
ax2 = L[1,2] = LAxis(S)
xribbon!(ax2, rand(20), 0.1 .+ 0.1rand(20), 1:20)
```

Output:
![simple_complete_recipe_with_Makie](https://user-images.githubusercontent.com/4486578/95535170-83749e80-0a33-11eb-8bab-ede71052e264.png)

**Comment by briochemc** [comment]
I was not sure how to make this MWE better (reduce number of `@lift`s? less lines of code? make it clearer?). This is why I submitted this as an issue rather than an unsolicited PR: for feedback! 😃

**Comment by ffreyer** [comment]
The recipes page now has a section with very slim functions and (I assume) also a simpler full example. I'm closing this as completed for now.
