### ISSUE TITLE
Feature request: nan_color kwarg for meshscatter

### ISSUE THREAD

**Issue by briochemc** [MakieOrg/Makie.jl#720]
It would be great to be able to use the `nan_color` kwarg as implemented for `heatmap` by @jkrumbiegel in response to https://github.com/JuliaPlots/Makie.jl/issues/666. 

This would allow it to be combined with a `meshscatter` recipe for irregularly spaced grids (inspired from @ffreyer in https://github.com/JuliaPlots/Makie.jl/issues/675#issuecomment-706284015), something like that:
```julia
using GeometryBasics
@recipe(EdgyHeatMap, ex, ey, z) do scene
    Attributes(
        nan_color=:lightgray,
    )
end
# What the recipe actually does
midpoints(x) = 0.5(x[1:end-1] .+ x[2:end])
positions(ex, ey) = [Point2f0(x, y) for x in ex[1:end-1] for y in ey[1:end-1]]
sizes(dxs,dys) = [Vec2f0(dx, dy) for dx in dxs for dy in dys]
mycolors(z) = z[:]
function AbstractPlotting.plot!(p::EdgyHeatMap)
    ex = p[:ex]
    ey = p[:ey]
    z = p[:z]
    # Needs to be a mesh to not get centered?
    m = Rect2D(Point2f0(0.0), Vec2f0(1)) |> normal_mesh
    # midpoints
    midxs = lift(midpoints, ex)
    midys = lift(midpoints, ey)
    # rectangle position & size
    pos = lift(positions, ex, ey)
    dxs = lift(diff, ex)
    dys = lift(diff, ey)
    sizs = lift(sizes, dxs, dys)
    # z needs to be transposed
    Z = lift(mycolors, z)
    meshscatter!(p, pos, markersize=sizs, marker=m, color=Z, shading=false)
    p
end
```

and plot nice stuff like this:

![test](https://user-images.githubusercontent.com/4486578/95862845-32580800-0daf-11eb-9e3f-b1efae1616a3.png)

but with gray `NaN`s! 😄

**Comment by briochemc** [comment]
I actually don't need this anymore since [Makie's `heatmap` started accepting irregularly spaced (rectilinear) grids](https://discourse.julialang.org/t/ann-makie-v-0-13/61522#irregular-heatmaps-3), but your PR looks really cool and I'm sure I would use it at some point, too!

**Comment by Alexander-Barth** [comment]
Maybe I misunderstand the present issue, but if you want to use grey NaNs you could do this: (with PR https://github.com/JuliaPlots/CairoMakie.jl/pull/177)

```julia
using CairoMakie
x = sqrt.(0:10:100); y = sqrt.(0:10:100);
X = [x_ for x_ in x,  y_ in y]
Y = [y_ for x_ in x,  y_ in y]
A = randn(10,10); 
A[3,5] = NaN; 
fig = heatmap(X,Y,A, nan_color = RGBf0(0.8,0.8,0.8));
save("test.png",fig)
```

![test](https://user-images.githubusercontent.com/9881475/121688439-c061cb00-cac3-11eb-820a-c2ff6874da1a.png)

**Comment by SimonDanisch** [comment]
The thing is, you can do that with the current Makie already, with the new irregular grid heatmaps:
```julia
using CairoMakie
x = sqrt.(0:10:100); y = sqrt.(0:10:100);
A = randn(10,10); 
A[3,5] = NaN; 
heatmap(x,y,A, nan_color = RGBf0(0.8,0.8,0.8))
```
![image](https://user-images.githubusercontent.com/1010467/121689710-3d417480-cac5-11eb-854c-165ee6e7cf0c.png)

**Comment by Alexander-Barth** [comment]
Thanks @SimonDanisch , I did not know that :smile: Sorry for the noise.

**Comment by SimonDanisch** [comment]
btw surface also already supports matrices as arguments ;) Just needs shading false and z set to all 0, to generate that kind of heatmap..Although it will be interpolated ;)

**Comment by Alexander-Barth** [comment]
Indeed `surface` is pretty flexible. In our case, we can have quite a few NaNs and it would be good to avoid them to spread spatially (I can give you some examples if this would be helpful). Would you consider a PR which implements the non-interpolated option for `surface` ?

**Comment by asinghvi17** [comment]
A non-interpolated surface would basically be a generated mesh, with unique vertices for each grid cell.  This is the only way to get per-face color into OpenGL, unfortunately.

We could have a short path for CairoMakie though!

**Comment by SimonDanisch** [comment]
`nan_color` is part of meshscatter these days.
