### ISSUE TITLE
Readme Precompilation: Document warnings and missing MakieGallery dependency

### ISSUE THREAD

**Issue by matu3ba** [MakieOrg/Makie.jl#737]
Stable Julia with pkg install of MakieGallery and Makie resulted in:

1. GLMakie is missing in the instructions and they could be condensed and moved up (with a hint that it takes every time 10-15 seconds to load Makie without compilation).

2. I only installed MakieGallery before to have a look into the examples and got "Warning: Package MakieGallery does not have Makie in its dependencies". 
I dont understand at all the reason for this error message, because one can separately install them from pkg. Pkg should use semantic versioning and thus not be affected.

3. "Warning: limits of scene contain non finite values: Float32[Inf, Inf, Inf] .. Float32[NaN, NaN, NaN]" does also look fishy to me.

<details><summary> log output </summary>

```
[ Info: starting from index 1
┌ Warning: Package MakieGallery does not have Makie in its dependencies:
│ - If you have MakieGallery checked out for development and have
│   added Makie as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with MakieGallery
└ Loading Makie into MakieGallery from project dependency, future warnings for MakieGallery are suppressed.
[ Info: Makie/AbstractPlotting is caching fonts, this may take a while. Needed only on first run!
┌ Warning: limits of scene contain non finite values: Float32[Inf, Inf, Inf] .. Float32[NaN, NaN, NaN]
└ @ AbstractPlotting ~/.julia/packages/AbstractPlotting/JCbJs/src/scenes.jl:525
[ Info: Precompile script has completed execution.
[ Info: PackageCompiler: creating system image object file, this might take a while...
```

</details>

**Comment by ffreyer** [comment]
Closing as outdated/fixed since MakieGallery isn't used anymore
