### ISSUE TITLE
Discussion on Makie's Documentation and addition of examples

### ISSUE THREAD

**Issue by ashwani-rathee** [MakieOrg/Makie.jl#745]
Hey Guys, I am Ashwani Rathee,undergraduate CS student at UIET,Panjab University, India
I saw this idea on:https://julialang.org/jsoc/gsoc/graphics/
```
Makie
Improve Documentation + add Examples
Makie is a new plotting library in need of tests and documentation.

One needs to go through all sections of the current documentation, make sure they are understandable and add examples to the documentation where necessary. Depending on how much time is left, there are endless opportunities to create impressive and creative plotting examples for the example database.

Expected Results: greatly improved documentations

Recommended skills: Attention to detail and a lot of experience with plotting.
Mentors: Simon Danisch
```
First came to know about https://discourse.julialang.org/t/chess-game/16417/31 from the chess game discussion.. :)
I have helped with the sciml,juliamusic websites in past and currently working on JuliaDSP website,musicprocessing.jl(upgrading to 1.x)
@SimonDanisch guide on how i can help on this documentation and examples

**Comment by jkrumbiegel** [comment]
Hey Ashwani, thanks for offering to help! I think the easiest thing to do is to read the docs and if you don't understand something, make an issue or even a PR with a better explanation. The same thing for examples you think are missing, then we can look over them together before they are merged

**Comment by ffreyer** [comment]
https://github.com/JuliaPlots/AbstractPlotting.jl/tree/master/src/stats

I think all of the plot types in there need documentation.

**Comment by ashwani-rathee** [comment]
I'll look into it later today.It's exam and festive season both at the same time here in india :) so little distracted

**Comment by ashwani-rathee** [comment]
So we need more examples for that part  and improving those 7(as they aren't well documented(just code) and don't show up on website like for websites like plotly,matplotlib,bokeh),right??

**Comment by ffreyer** [comment]
Adding them to the [plotting function overview](http://makie.juliaplots.org/stable/plotting_functions.html) with an example each would be good I think. The source of that is [here](https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/docs/src/plotting_functions.md).

**Comment by jkrumbiegel** [comment]
Yes that would be good. Alternatively, we could make a second page for higher-level plots. But that can also be shifted later.

In terms of examples, you can copy the existing structure mostly for new examples. I think it's important that examples are clear and also good-looking, so I'm not the biggest fan of plotting random lines etc. That's why you see sine curves all over the place ;)

**Comment by ashwani-rathee** [comment]
I don't even remember the time I was here whoaaaa
