### ISSUE TITLE
Component indicators

### ISSUE THREAD

**Issue by jtrakk** [MakieOrg/Makie.jl#759]
Given a complex figure, it's sometimes difficult to tell what each visual item corresponds to in the scene/layout. 

A simpler version would be just a function that adds labels to each component of the plot, e.g the x axis would get a label saying "layout[1,1].ticks" or similar. That way it will be easier to tell how to change each part of the plot.

A more complex version would be to mouse over each component in the browser and get an indication of what part of the scene/layout is under my mouse. This idea is inspired by the element inspector in browser devtools.

**Comment by ffreyer** [comment]
Closing this for lack of discussion/interest.

`DataInspector` also provides this for plots to a degree
