### ISSUE TITLE
layoutscene() name/order

### ISSUE THREAD

**Issue by jtrakk** [MakieOrg/Makie.jl#764]
I'm finding it hard to remember the order of `scene, layout = layoutscene()`. Why does it return values in the opposite order from the name?

**Comment by jkrumbiegel** [comment]
I guess it's because I'm German and it's kind of a compound word for me? I won't change this now as I don't intend layoutscene to stay the standard interface. Instead we want to integrate MakieLayout more into normal scenes

**Comment by ffreyer** [comment]
Closing as outdated since layoutscene doesn't exist anymore
