### ISSUE TITLE
Opening LMenu at the bottom of a window

### ISSUE THREAD

**Issue by yakir12** [MakieOrg/Makie.jl#769]
If an `LMenu` is located near the bottom of its window, and the list of options is not very short, opening it exposes only part of its options, preventing the user from selecting options that are further down the list.

**Comment by jkrumbiegel** [comment]
you can do `direction = :up` I think, but I could try to make this automatic given where the scene boundary is relative to the menu

**Comment by ffreyer** [comment]
Has been fixed (made automatic)
