### ISSUE TITLE
AbstractPlotting: Just how long is caching fonts supposed to take?

### ISSUE THREAD

**Issue by aliddell** [MakieOrg/Makie.jl#770]
On first run (Windows and Linux), I've encountered this message:

```
[ Info: Make/AbstractPlotting is caching fonts, this may take a while. Needed only on the first run!
```

But this has been blocking my REPL for well over an hour now. Other times I've just ^C'd out of it (and never encountered any issues) -- but I'm wondering what's going on here and why I haven't seen anyone else complain about it.

Versions are Makie 0.11.1/AbstractPlotting 0.12.18 on both Windows (Julia 1.5.2) and Linux (Julia 1.5.3).

**Comment by ffreyer** [comment]
Closing this as the font cache is now downloaded by default
