### ISSUE TITLE
LMenu(...; i_selected=...) has wrong selection

### ISSUE THREAD

**Issue by yha** [MakieOrg/Makie.jl#776]
```
scene, layout = layoutscene()
layout[1,1] = menu = LMenu(scene; options=["1","2","3"], i_selected=2)
@show menu.i_selected[] # 2
@show menu.selection[] # nothing
scene
```
The GUI shows "2" as expected.

**Comment by jkrumbiegel** [comment]
ah good point, I guess the internal ordering of the observables ignores the initial state of i_selected or at least doesn't trigger selection

**Comment by ffreyer** [comment]
This has been reworked to use `default = 2` which works as intended
