### ISSUE TITLE
errorbars buggy for large x values

### ISSUE THREAD

**Issue by cailmdaley** [MakieOrg/Makie.jl#780]
```julia
using Makie, CairoMakie

start = 4e6
errorbars(start:start+9, randn(10), randn(10))
```
<img width="700" alt="image" src="https://user-images.githubusercontent.com/13065208/101813267-20aa8c80-3ae2-11eb-957b-f78968650598.png">

Things look good for smaller values of `start`; the error bars only start getting weird around `start=1e5`.

**Comment by jkrumbiegel** [comment]
could be that this is because the coordinate transforms are done in Float32, at least that's usually what causes such "quantization" problems in Makie (GPU needs everything in Float32)
