### ISSUE TITLE
Scene window closes abruptly on Win10 without error msg

### ISSUE THREAD

**Issue by jonalm** [MakieOrg/Makie.jl#793]
I've managed to consistently reproduce an unexpected closing of the makie window on Windows 10 using this script: https://gist.github.com/jonalm/d88d7e65ea3945d9dcbaf206e546f69d. I've seen similar behavior with other makie plots using the same laptop, in particular long lived plots which uses widgets, but it is hard to  investigate the cause as the closing appears randomly, sometimes after extensive use of interaction in the plot, e.g. page scrolling (see script), and/or movement/resizing of the plot window. 

Typing `isopen(scene)` gives `true`, after the window has closed, but no error messages are reported. When I inspect the task manager while triggering the closing, I see no anomalies in cpu/gpu/memory or disk usage.

I've also tried running
```
ENV["MODERNGL_DEBUGGING"] = true
] add ModernGL#master; build ModernGL
using ModernGL; @assert ModernGL.enable_opengl_debugging
```
before running the script, but still no error messages are reported.

I have not managed to reproduce the same behavior on my macbook pro.

Version details:
OS: Windows 10
Laptop: Thinkpad E15 
GPU: intel UHD
Julia: 1.5.3
GLMakie: 0.1.20
AbstractPlotting: 0.14.2

**Comment by SimonDanisch** [comment]
Oooh, maybe this is related?
https://github.com/JuliaPlots/GLMakie.jl/pull/149

**Comment by jkrumbiegel** [comment]
> Oooh, maybe this is related?

As in "introduced by that PR"? I've been seeing this behavior for weeks or even months on my work laptop. It's also windows, also intel graphics I think. All kinds of GLMakie and AbstractPlotting versions

**Comment by SimonDanisch** [comment]
The other way around, I just merged this PR a second ago ;)

**Comment by jonalm** [comment]
how can I checkout that verison of GLMakie to check if that fixes it?

**Comment by SimonDanisch** [comment]
I'll try to get a version out tonight... I merged a couple of things into master which I need to clean up make sure they don't introduce issues

**Comment by SimonDanisch** [comment]
Try this: https://github.com/JuliaRegistries/General/pull/26770

**Comment by jonalm** [comment]
With GLMakie v0.1.22 I get this error when the display closes

```
julia> GLFWError (PLATFORM_ERROR): WGL: Failed to make context current: The requested transformation operation is not supported.
Stacktrace:
 [1] _ErrorCallbackWrapper(::Int32, ::Cstring) at C:\Users\Jon Alm Eriksen\.julia\packages\GLFW\CBo9c\src\callback.jl:43 [2] MakeContextCurrent at C:\Users\Jon Alm Eriksen\.julia\packages\GLFW\CBo9c\src\glfw3.jl:694 [inlined]
 [3] make_context_current at C:\Users\Jon Alm Eriksen\.julia\packages\GLMakie\1xFZI\src\drawing_primitives.jl:46 [inlined]
 [4] fps_renderloop(::GLMakie.Screen, ::Float64) at C:\Users\Jon Alm Eriksen\.julia\packages\GLMakie\1xFZI\src\rendering.jl:26
 [5] renderloop(::GLMakie.Screen; framerate::Float64) at C:\Users\Jon Alm Eriksen\.julia\packages\GLMakie\1xFZI\src\rendering.jl:48
 [6] renderloop(::GLMakie.Screen) at C:\Users\Jon Alm Eriksen\.julia\packages\GLMakie\1xFZI\src\rendering.jl:41
 [7] (::GLMakie.var"#44#46"{GLMakie.Screen})() at .\task.jl:356
```

**Comment by SimonDanisch** [comment]
Hm, maybe that's exactly the kind of error that got ignored previously and silently killed the renderloop... I have no idea what that means, but it indicates some driver not implementing something, which would explain why this only happens on some GPUs...Will try to google this ;)

**Comment by SimonDanisch** [comment]
Pfew, googling leads to lots of "i have the same issue, intel do something" and then no further comments or solutions, besides not using the intel GPU:
https://github.com/intel-isl/Open3D/issues/1598
