### ISSUE TITLE
UndefVarError: ObserverFunction not defined

### ISSUE THREAD

**Issue by rlrs** [MakieOrg/Makie.jl#802]
I'm trying to install GLMakie, but I get this error during precompiling AbstractPlotting:

> (@v1.5) pkg> add GLMakie
> julia> using GLMakie

> [ Info: Precompiling GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]
> ERROR: LoadError: LoadError: LoadError: UndefVarError: ObserverFunction not defined
> Stacktrace:
>  [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
>  [2] top-level scope at /home/ralars/.julia/packages/AbstractPlotting/Za7XY/src/makielayout/mousestatemachine.jl:57
>  [3] include(::Function, ::Module, ::String) at ./Base.jl:380
>  [4] include at ./Base.jl:368 [inlined]
>  [5] include(::String) at /home/ralars/.julia/packages/AbstractPlotting/Za7XY/src/makielayout/MakieLayout.jl:1
>  [6] top-level scope at /home/ralars/.julia/packages/AbstractPlotting/Za7XY/src/makielayout/MakieLayout.jl:46
>  [7] include(::Function, ::Module, ::String) at ./Base.jl:380
>  [8] include at ./Base.jl:368 [inlined]
>  [9] include(::String) at /home/ralars/.julia/packages/AbstractPlotting/Za7XY/src/AbstractPlotting.jl:1
>  [10] top-level scope at /home/ralars/.julia/packages/AbstractPlotting/Za7XY/src/AbstractPlotting.jl:241
>  [11] include(::Function, ::Module, ::String) at ./Base.jl:380
>  [12] include(::Module, ::String) at ./Base.jl:368
>  [13] top-level scope at none:2
>  [14] eval at ./boot.jl:331 [inlined]
>  [15] eval(::Expr) at ./client.jl:467
>  [16] top-level scope at ./none:3
> in expression starting at /home/ralars/.julia/packages/AbstractPlotting/Za7XY/src/makielayout/mousestatemachine.jl:57
> in expression starting at /home/ralars/.julia/packages/AbstractPlotting/Za7XY/src/makielayout/MakieLayout.jl:46
> in expression starting at /home/ralars/.julia/packages/AbstractPlotting/Za7XY/src/AbstractPlotting.jl:241
> ERROR: LoadError: Failed to precompile AbstractPlotting [537997a7-5e4e-5d89-9595-2241ea00577e] to /home/ralars/.julia/compiled/v1.5/AbstractPlotting/6fydZ_s9Isn.ji.
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
>  [3] _require(::Base.PkgId) at ./loading.jl:1030
>  [4] require(::Base.PkgId) at ./loading.jl:928
>  [5] require(::Module, ::Symbol) at ./loading.jl:923
>  [6] include(::Function, ::Module, ::String) at ./Base.jl:380
>  [7] include(::Module, ::String) at ./Base.jl:368
>  [8] top-level scope at none:2
>  [9] eval at ./boot.jl:331 [inlined]
>  [10] eval(::Expr) at ./client.jl:467
>  [11] top-level scope at ./none:3
> in expression starting at /home/ralars/.julia/packages/GLMakie/1xFZI/src/GLMakie.jl:4
> ERROR: Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to /home/ralars/.julia/compiled/v1.5/GLMakie/nfnZR_s9Isn.ji.
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
>  [3] _require(::Base.PkgId) at ./loading.jl:1030
>  [4] require(::Base.PkgId) at ./loading.jl:928
>  [5] require(::Module, ::Symbol) at ./loading.jl:923

**Comment by SimonDanisch** [comment]
Can you show `]st Observables` ?

**Comment by rlrs** [comment]
I don't have it, do I need to install something else than GLMakie first?

> (@v1.5) pkg> st
> Status `~/.julia/environments/v1.5/Project.toml`
>   [c52e3926] Atom v0.12.30
>   [634d3b9d] DrWatson v1.16.6
>   [e9467ef8] GLMakie v0.1.22
>   [e5e0dc1b] Juno v0.8.4

**Comment by SimonDanisch** [comment]
You need to install it to get the version

**Comment by rlrs** [comment]
Ah okay,

> (@v1.5) pkg> add Observables
>   Resolving package versions...
> Updating `~/.julia/environments/v1.5/Project.toml`
>   [510215fc] + Observables v0.3.3
> No Changes to `~/.julia/environments/v1.5/Manifest.toml`

Manually installing it results in this though.

> julia> using GLMakie
> [ Info: Precompiling GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]
> ERROR: LoadError: AssertionError: precompile(AbstractPlotting.backend_display, (GLBackend, Scene))
> Stacktrace:
>  [1] _precompile_() at /home/ralars/.julia/packages/GLMakie/1xFZI/src/precompile.jl:3
>  [2] top-level scope at /home/ralars/.julia/packages/GLMakie/1xFZI/src/GLMakie.jl:82
>  [3] include(::Function, ::Module, ::String) at ./Base.jl:380
>  [4] include(::Module, ::String) at ./Base.jl:368
>  [5] top-level scope at none:2
>  [6] eval at ./boot.jl:331 [inlined]
>  [7] eval(::Expr) at ./client.jl:467
>  [8] top-level scope at ./none:3
> in expression starting at /home/ralars/.julia/packages/GLMakie/1xFZI/src/GLMakie.jl:80
> ERROR: Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to /home/ralars/.julia/compiled/v1.5/GLMakie/nfnZR_s9Isn.ji.
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
>  [3] _require(::Base.PkgId) at ./loading.jl:1030
>  [4] require(::Base.PkgId) at ./loading.jl:928
>  [5] require(::Module, ::Symbol) at ./loading.jl:923
>

**Comment by rlrs** [comment]
I installed CairoMakie and precompiled it just fine, so maybe it's some issue with GL on my machine. I can make do with that, since it's seemingly just an issue for me.

**Comment by SimonDanisch** [comment]
Ok, this points to the wrong AbstractPlotting version...
Can you show `st AbstractPlotting` ?

**Comment by rlrs** [comment]
I just updated the packages (I don't know why I didn't have these versions yesterday?):

> (@v1.5) pkg> up
>    Updating registry at `~/.julia/registries/General`
>    Updating git-repo `https://github.com/JuliaRegistries/General.git`
>    Updating registry at `~/.julia/registries/JuliaPOMDP`
>    Updating git-repo `https://github.com/JuliaPOMDP/Registry`
>    Updating registry at `~/.julia/registries/SchlichtandersJuliaRegistry`
>    Updating git-repo `https://github.com/schlichtanders/SchlichtandersJuliaRegistry.jl`
>   Installed OffsetArrays ─── v1.4.4
>   Installed JuliaFormatter ─ v0.12.2
>   Installed GLMakie ──────── v0.1.23
> Updating `~/.julia/environments/v1.5/Project.toml`
>   [537997a7] ↑ AbstractPlotting v0.14.4 ⇒ v0.15.0
>   [13f3f980] ↑ CairoMakie v0.3.9 ⇒ v0.3.10
>   [e9467ef8] ↑ GLMakie v0.1.22 ⇒ v0.1.23

I'm fairly certain this fixed the errors I was getting, as now I have some GL issues:

>    Building GLMakie → `~/.julia/packages/GLMakie/mScRF/deps/build.log`
> ┌ Error: Error building `GLMakie`: 
> │ libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
> │ libGL error: failed to load driver: iris
> │ libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
> │ libGL error: failed to load driver: iris
> │ libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
> │ libGL error: failed to load driver: swrast
> │ Initialization error of GLFW
> │ ERROR: LoadError: OpenGL/GLFW wasn't loaded correctly or couldn't be initialized. 
> │ This likely means, you don't have an OpenGL capable Graphic Card,
> │ or you don't have an OpenGL 3.3 capable video driver installed.
> │ If you're on a headless server, you still need to install x-server and
> │ proper graphics drivers.
> │ If you don't have a GPU, there is also a Cairo software backend
> │ for Makie which you can use:
> │ https://github.com/JuliaPlots/CairoMakie.jl.
> │ Please check the below error and open an issue at:
> │ https://github.com/JuliaPlots/GLMakie.jl.
> │ After you fixed your OpenGL install, please run `]build GLMakie`!
> │ Otherwise, GLMakie would still load, but would be disabled as a 
> │ default backend for Makie.

which isn't really relevant for this issue, but also I fixed it with:

> export MESA_LOADER_DRIVER_OVERRIDE=i965
