### ISSUE TITLE
CairoMakie.jl has issues disabled

### ISSUE THREAD

**Issue by DilumAluthge** [MakieOrg/Makie.jl#809]
TagBot uses issue comments to trigger the creation of tags. Unfortunately, since https://github.com/JuliaPlots/CairoMakie.jl has issues disabled, TagBot cannot create issue comments, which means that TagBot cannot create tags.

Instead of disabling issues on CairoMakie.jl (which is the current setup), why not just have a GitHub Action that auto-closes issues?

cc: @christopher-dg

**Comment by DilumAluthge** [comment]
> Instead of disabling issues on CairoMakie.jl (which is the current setup), why not just have a GitHub Action that auto-closes issues?

Implemented in https://github.com/JuliaPlots/CairoMakie.jl/pull/122

**Comment by DilumAluthge** [comment]
@SimonDanisch whoops. I just realized. Once TagBot has created an issue, it continues to post comments on that issue. So we don't want to lock the TagBot issue.

**Comment by DilumAluthge** [comment]
And if anyone accidentally comments on the TagBot issue.... it'll be locked. And thus prevent TagBot from commenting in the future.

**Comment by SimonDanisch** [comment]
:D

**Comment by ffreyer** [comment]
Closing this since CairoMakie moved
