### ISSUE TITLE
thread safety issue

### ISSUE THREAD

**Issue by norci** [MakieOrg/Makie.jl#812]
Julia crashed, when Makie function was called in multiple threads.

reproduce code:
```julia
using GLMakie
# scatter(rand(1000),rand(1000)) # julia will crash without this
tasks = map(1:30) do i
    Threads.@spawn scatter(rand(1000),rand(1000))
end
scenes = fetch.(tasks)
display(scenes[1])
```

 the font of the images also has problem.
![100](https://user-images.githubusercontent.com/2986988/104348240-71c3fb00-553c-11eb-8e45-305b350b0d6a.png)

**Comment by SimonDanisch** [comment]
What backend is this?

**Comment by norci** [comment]
> What backend is this?

it's `CairoMakie`

**Comment by SimonDanisch** [comment]
The Cairo fontrendering itself may not be threadsafe

**Comment by norci** [comment]
I have tested GLMakie, it has the same problem.

The code still has bug, with my PR https://github.com/JuliaPlots/AbstractPlotting.jl/pull/597

```julia
julia> scenes = fetch.(tasks)
ERROR: TaskFailedException:
Can't represent character � with any fallback font nor DejaVu Sans!
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] find_font_for_char(::Char, ::FreeTypeAbstraction.FTFont) at C:\Users\x\Documents\GitHub\AbstractPlotting\src\utilities\texture_atlas.jl:169       
```

I have added repo code in above comment. Could you have a look? thanks.

**Comment by SimonDanisch** [comment]
Sorry, I don't have time to look into this right now. Making Makie threadsafe is a bigger project than just quickly looking into it.

**Comment by gdkrmr** [comment]
I had no problem creating heatmaps with Cairomakie using a threaded for loop. GLMakie however crashes when used on more than one thread.

**Comment by cossio** [comment]
Any updates on this?

```
using CairoMakie
tasks = map(1:30) do i
   Threads.@spawn scatter(rand(1000),rand(1000))
end
scenes = fetch.(tasks)
display(scenes[1])
```

Note that with CairoMakie I also crash Julia with the above example.

**Comment by cossio** [comment]
Another example that crashes. Start Julia with `julia -t 4`. Then:

```
using CairoMakie
function do_a_plot(name)
  fig = scatter(randn(10), randn(10))
  save(name, fig)
end
@sync for i = 1:5
  Threads.@spawn do_a_plot("/home/cossio/temp/$i $(Threads.threadid()).pdf")
end
```

**Comment by cossio** [comment]
A workaround is to use locks to make sure only one thread plots at a time. Useful if plotting is not the bottleneck.

```julia
using CairoMakie

const plotting_lock = ReentrantLock()

function do_a_plot(name)
	lock(plotting_lock) do
		fig = scatter(randn(10), randn(10))
		save(name, fig)
	end
end

@sync for i = 1:5
	Threads.@spawn do_a_plot("/home/cossio/temp/$i $(Threads.threadid()).pdf")
end
```

Thanks @jpsamaroo for clarifying the use of locks here.
