### ISSUE TITLE
Histogram with only one category

### ISSUE THREAD

**Issue by georgematheos** [MakieOrg/Makie.jl#820]
Currently, code like
```julia
hist([1, 1, 1], bins=2)
```
does not behave as I would have expected (plotting 1 bin with a full bar, and 1 bin with an empty bar).  Instead, it simply plots nothing!

**Comment by georgematheos** [comment]
I think this issue may be arising due to `NaN` appearing in a call to `barplot`.

When I do
```julia
barplot([0, 1], [0, 1])
```
it plots what I would expect.

But if I do
```julia
vals = Node([NaN, NaN])
barplot([0, 1], vals)
vals[] = [0, 1]
```
then the barplot remains empty.

**Comment by jkrumbiegel** [comment]
Yeah how can you divide a zero width range into two

**Comment by jkrumbiegel** [comment]
if you pass n bins the range of your data is divided by that, so if the range is 0 that doesn't work. you can pass edges directly though

```julia
hist([1, 1, 1], bins=[0, 1, 2])
```

**Comment by georgematheos** [comment]
Ah, awesome!  Got it--hadn't realized `bins` could be a vector.

Is the behavior where `barplot` stays empty after changing an observable from `NaN` values expected?  / if not, should I open a separate issue for it?
