### ISSUE TITLE
FR: Double click to go back to original zoom and orientation

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#827]
Often times one can get a bit lost after zooming too much and/or rotating stuff, especially when the axis is not centered on (0, 0). I would love to double click to return to the original plot, much like is Plotly and PlotlyJS.

**Comment by jkrumbiegel** [comment]
With Axis it's ctrl+click but this is not implemented for 3D plots

**Comment by KronosTheLate** [comment]
That works, thanks. I do find The current interactive controls a little unintuitive in general for Makie right now, and would love this as a more inntuitive alternative for people who are used to double click to reset for whatever reason

**Comment by lstagner** [comment]
It took me way to long to figure out how to pan and reset the plot. If the interactive controls are going to change might I suggest.
```
Click + Hold --> Pan
Double Click --> Reset
(Ctrl|Shift) + Click + Hold # 2D only
Scroll --> Zoom # 3D only
```

**Comment by RTbecard** [comment]
Are these default controls listed in the docs somewhere?  I thought I had read through most of it, but I also missed that Ctrl + click resets the zoom.

**Comment by bilderbuchi** [comment]
> Are these default controls listed in the docs somewhere? I thought I had read through most of it, but I also missed that Ctrl + click resets the zoom.

Excellent question! Also: Is there a "go back to previous viewport", like e.g. Matplotlib has on right-click (I think)?
I started looking for plot reset, and found it only via this issue (thank you!)

**Comment by KronosTheLate** [comment]
Perhaps a section in the docs on "Interacting with plots" could be nice?

**Comment by KronosTheLate** [comment]
I guess this could be bumped, and tagged with "Makie Usability"? It seems, based on this thread, that the current interaction controls are sub-optimal, and I would love a discussion to arrive at a set of controls that a majority feel comfortable with.

**Comment by ffreyer** [comment]
This has been added to Camera3D and will be added to Axis3 with #4131 where it becomes relevant. Docs for Axis and soon Axis3 exist. Camera3D documents this too, though it's probably lost in verboseness...
Closing this as done
