### ISSUE TITLE
tiny value in function surface only displays a line

### ISSUE THREAD

**Issue by NickWu198** [MakieOrg/Makie.jl#830]
my code is below:
```julia
using Makie, GLMakie
R=8.314; T=298.15; p=101325; M=1.8e-2;rho=1e3; n=100;
vx = range(8e-10; stop=5e-9, length=n)
vy = range(5e-2; stop=9e-2, length=n)
f(x,y)=exp(2*y*M/(x*rho)/(R*T))*p
surface(vx, vy, f)
```
but only display a line at last.

**Comment by ffreyer** [comment]
You can use `Axis3` for automatic scaling in 3D now. Closing as fixed.

Side note - something like this could also run into problems with Float precision but this particular example seems fine...
