### ISSUE TITLE
Update arrows directions

### ISSUE THREAD

**Issue by albert-de-montserrat** [MakieOrg/Makie.jl#836]
```julia
x = [1,2]
y = [2,2]
u = rand(2)
v = rand(2)
a = arrows(x,y,u,v,arrowsize=0)
puv = [Vec2f0(rand(), rand()) for j in 1:length(u)]
```
I'm trying to update the direction of the arrows to the new `puv`, but none of following seem to work:
```julia
a.plot[2].val = puv
a.plot[:directions] = puv
```

**Comment by ffreyer** [comment]
`a.plot[2].val = puv` sets the data without propagating updates, so you won't see changes from it. Use `a.plot[2][] = puv` instead.

I'm not sure if `a.plot[:directions] = puv` is supposed to work. It works with `a.plot[:directions][] = puv`.

**Comment by jkrumbiegel** [comment]
I think only `a.plot.directions = puv` is the supported shortcut syntax, so I'm going to close this
