### ISSUE TITLE
support `alpha` keyword arg

### ISSUE THREAD

**Issue by ssfrr** [MakieOrg/Makie.jl#84]
sometimes I find myself wanting to use the alpha channel to visualize some parameter, or just quickly tweak the transparency to improve aesthetics for a dense plot.

The first thing I tried was just adding an `alpha=0.5` keyword arg to my `scatter` call, just to see if it would work. It didn't. :)

I'm guessing that there's some way to specify the color from scratch and include the alpha channel, but the default colors are pretty good and I just want to tweak the transparency without needing to override the default colors otherwise.

**Comment by SimonDanisch** [comment]
I didn't really like the alpha keyword, but I think it does make sense how you put it! 
It should also be reasonably easy to implement! I'll try to include it soon :)

**Comment by asinghvi17** [comment]
`alpha` is implemented now IIRC.

**Comment by SimonDanisch** [comment]
It's just included, but not implemented yet :(

**Comment by jtrakk** [comment]
`transparency` and `alpha` both appear [in the docs](https://makie.juliaplots.org/stable/generated/plot-attributes.html#Plot-attributes). What is the difference?

**Comment by SimonDanisch** [comment]
uhm, alpha should be removed from the docs, since isn't implemented yet :( 
`transparency` accepts a bool, to indicate if something should be rendered transparent or not (regardless of the alpha)...The effect is, that it renders without writing to the depth buffer, which results in objects behind it being rendered.

**Comment by jkrumbiegel** [comment]
I feel like this should be renamed to `write_depth_buffer` because `transparency` promises more than it can hold.

**Comment by czimm79** [comment]
This feature has been missing for awhile, and I'd like to help. I'm pretty inexperienced with contributing but I'd like to learn.

Is there a way to get the current `color` or `colormap`, then simply rewrite `alpha=0.5` as `color=(getcurrentcolor(), 0.5)`?

**Comment by SimonDanisch** [comment]
implemented in #2900
