### ISSUE TITLE
Irregular semi-transparent gradients with CairoMakie

### ISSUE THREAD

**Issue by sfmiller940** [MakieOrg/Makie.jl#841]
I’ve been trying to make heatmaps using colormaps that go from transparent to either white or black.

The interpolation works as expected for black but it looks terrible for white.

Here’s some sample code with the result:

```
using CairoMakie, Plots.Colors

xs = LinRange(0, 10, 100)
ys = LinRange(0,10, 100)
zs = [x+im*y for x in xs, y in ys]
rings = abs.(zs) .% 3

fig = Figure();
ax1 = fig[1, 1] = Axis( fig, backgroundcolor="blue");
ax2 = fig[2, 1] = Axis( fig, backgroundcolor="blue");

cmblack = cgrad(range(HSLA(0,0,0,0), stop=HSLA(0,0,0,1), length=100));
CairoMakie.heatmap!(ax1, xs, ys, rings, colormap=cmblack, interpolate=true);

cmwhite = cgrad(range(HSLA(0,0,1,0), stop=HSLA(0,0,1,1), length=100));
CairoMakie.heatmap!(ax2, xs, ys, rings, colormap=cmwhite, interpolate=true);

fig
```

Screenshot from Juno:

![interpolation](https://user-images.githubusercontent.com/4923421/105910468-d754c480-5fdd-11eb-931d-b4fdcad87bdd.png)

Saved PNG:

![interpol](https://user-images.githubusercontent.com/4923421/105910530-f05d7580-5fdd-11eb-8e67-9300cebdfc61.png)

I noticed the comment "Set filter doesn't work!?" in [src/primitives.jl](https://github.com/JuliaPlots/CairoMakie.jl/blob/master/src/primitives.jl), so maybe this is a known issue? I'll try to investigate more in case I can help...

**Comment by jkrumbiegel** [comment]
really weird, I've tried tracing this until the point where the cairo surface is created, and it seems like the values there are correct. But both svg and png display with the white colormap are then buggy. Maybe a Cairo issue? It seems to me we're passing correct data to it

**Comment by jkrumbiegel** [comment]
oh and the filter thing relates to the fact that the collection of filters cairo offers sometimes don't do anything depending on svg or png or pdf export. for example nearest interpolation for heatmaps doesn't work in svg etc.

**Comment by ffreyer** [comment]
This has been fixed
