### ISSUE TITLE
The script test_for_precompile.jl is not compatible with the current version of Makie

### ISSUE THREAD

**Issue by ufechner7** [MakieOrg/Makie.jl#845]
The script:
ufechner@TUD277255:~$ cat /home/ufechner/.julia/packages/Makie/iTycG/test/test_for_precompile.jl
```julia
using MakieGallery, AbstractPlotting, GLMakie, Test

empty!(MakieGallery.plotting_backends)
push!(MakieGallery.plotting_backends, "Makie")
database = MakieGallery.load_database([
                    "tutorials.jl",
                    "attributes.jl",
                    "short_tests.jl"
                    ])

test_record_path = joinpath(@__DIR__, "test_recordings")
recordings = MakieGallery.record_examples(test_record_path)
@assert length(recordings) == length(database)
@info "Precompile script has completed execution."
```
uses MakieGallery which is not compatible with the current version of Makie. So it should be modified/ updated.

**Comment by crstnbr** [comment]
https://github.com/JuliaPlots/Makie.jl/issues/799 might be of help.

(Can you format the code with backticks?)

**Comment by ufechner7** [comment]
Thanks for the link to #799. Is that a solution that is good enough to replace the current file test_for_precompile.jl ?

**Comment by ffreyer** [comment]
Closing as outdated/likely fixed
