### ISSUE TITLE
Scrolling direction is inversed for zooming

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#850]
I don't know if this is only on my system, but when I scoll in the direction that zooms in in any other context I can think of, I zoom out. It might be because I am on windows - I don't suppose that this is intentional, so I am assuming that it works as it should on the system in which the feature was developed. Is it possible to invert the direction of zoom?

The direction is btw also wrong when holding x or y and zooming

Just to be completely clear, when I place my finger on the scroll-wheel and move it away from my hand/body, I currently zoom out where I expect to zoom in.

**Comment by jkrumbiegel** [comment]
This might be just because I'm developing on a MacBook, and trackpad vs mouse tends to be inverse. I guess I'm fine with changing the default or introducing a flag to go either way.

**Comment by KronosTheLate** [comment]
That explains it. Are you doing all the development yourself? I really only see you doing work on this amazing and ambitious project right now.

My (biased) vote goes towards changing the default. I also think it makes sense, as there are probably more people using a mouse/windows than those who mainly use a Macbook trackpad. But maybie one can create a flag as you mentioned, and set the default based on the OS?

**Comment by jkrumbiegel** [comment]
>  Are you doing all the development yourself?

No, the base library is almost all @SimonDanisch, it has existed for quite some time. I wrote basically everything in the `MakieLayout` submodule, like `Axis`, `Figure`, `GridLayout` etc because I wanted to have a plotting library that eliminates the annoying endless manual layout and placement fiddling https://jkrumbiegel.com/pages/2020-11-15-makielayout/

**Comment by KronosTheLate** [comment]
I think this has been fixed for some time.
