### ISSUE TITLE
Multi-level/grouped ticks? [feature request]

### ISSUE THREAD

**Issue by junyuan-chen** [MakieOrg/Makie.jl#880]
It is a common scenario to have groups of observations plotted on the same plots and we want each observation to have its own ticks.

To make it more concrete what I mean by saying multi-level/grouped ticks, please take a look at the graph below made from `Stata` module `coefplot`.
http://repec.sowi.unibe.ch/stata/coefplot/getting-started/wildcard3.pdf
There are two groups of ticks on the same axis. Alternatively, one may view them as ticks with two levels.

Maybe there could be multiple `LinearTicks` or something like that on the same axis?

This kind of ticks should also satisfy the need of making histograms and bar plots with values from different groups put adjacent to each other.
For example, I see people trying to make such bar plots here by writing recipes:
https://github.com/JuliaPlots/AbstractPlotting.jl/pull/640

But, if we have a more general implementation of ticks, then there would be no need to do such changes just for some specific types of plots.

**Comment by jkrumbiegel** [comment]
Hm I think it's quite difficult to make ticks really "multi-level", it's much easier to get a similar look by manipulating the normal ticks, or by making adjacent axes that look like one. For example:

```julia
f = Figure()
axs = [Axis(f[i, 1], ylabel = "y label") for i in 1:2]
linkxaxes!(axs...)
hidexdecorations!(axs[1], grid = false)
axs[1].bottomspinevisible = false
axs[1].yautolimitmargin = (0.2, 0.1)
axs[2].yautolimitmargin = (0.1, 0.2)
axs[2].topspinevisible = false
rowgap!(f.layout, 0)

for ax in axs
    errorbars!(ax, rand(4), 1:4, rand(4), direction = :x)
    ax.yticks = (1:4, ["Mileage", "Trunk space", "Length", "Turn Circle"])
end

f
```

<img width="618" alt="grafik" src="https://user-images.githubusercontent.com/22495855/111064580-20d97000-84b5-11eb-8d0e-7295d5fd65d6.png">

**Comment by junyuan-chen** [comment]
@jkrumbiegel Thank you so much for your prompt reply and the example!

**Comment by ffreyer** [comment]
Can this be closed as wont-fix?

**Comment by asinghvi17** [comment]
Yes, I think so.
