### ISSUE TITLE
Zoom to fit 3d scene (feature request)

### ISSUE THREAD

**Issue by pbouffard** [MakieOrg/Makie.jl#903]
Basically the same as `autolimits!` for 2d scenes in terms of what you'd like to happen, i.e. have everything in the plot visible. 

Actually ideally it would be possible to pass in a list of plot elements to include in the view, similar to 'zoom selected' in CAD programs.

For perspective scenes, I think this would mean:
1. Compute a convex hull of all the given elements
2. Rotate the camera pointing direction to the centroid of the convex hull
3. Translate the eye point forward or backward along the pointing direction so that the convex hull just fits within the view (perhaps with some margin).

I guess for orthographic scenes steps 1 and 2 would be the same but step 3 would be a field of view change rather than a translation.

**Comment by SimonDanisch** [comment]
@jkrumbiegel  just merged a new Axis3D type which kind of does this:
```julia
using GLMakie
using FileIO
brain = load(assetpath("brain.stl"))
colors = [tri[1][2] for tri in brain for i in 1:3]
mesh(
    brain,
    color = colors,
    colormap = Reverse(:Spectral),
    figure = (resolution = (1000, 800), fontsize = 14),
    axis = (
        type = Axis3,
        aspect = :data,
    )
)
```
![image](https://user-images.githubusercontent.com/1010467/113695698-71697500-96d1-11eb-9f5c-8b8fe175d6db.png)

Although yours is a bit different.
But `center!(scene)` pretty much does this for the old 3d axis:
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/scenes.jl#L492

**Comment by ffreyer** [comment]
Closing this because Axis3 exists
