### ISSUE TITLE
How to prevent slider or other elements from resizing when changes values

### ISSUE THREAD

**Issue by musm** [MakieOrg/Makie.jl#929]
Best explained in an animation:
Observe how when the number is double digits the sliders shrink. Ideally you can somehow inform elements so this resizing behavior (which looks janky/buggy) could be avoided.

![Animation](https://user-images.githubusercontent.com/4319522/116428335-cef56b00-a812-11eb-8ca3-f47bb9d2930a.gif)

**Comment by jkrumbiegel** [comment]
the labels have to be given an explicit width to avoid this. I think in the call to `labelslidergrid!` you could pass `labelkw = (width = 100,)` or something. This should probably be the default because of the behavior you show, but there would need to be some logic to pick a good value maybe

**Comment by ffreyer** [comment]
Closing this since solution was given
