### ISSUE TITLE
Mesh plots 2d instead of 3d

### ISSUE THREAD

**Issue by mschauer** [MakieOrg/Makie.jl#936]
Mesh creates a 2d plot  instead of 3d if the point arguments are `Point3f0` or 3 vectors, but the third coordinate of each point is too close to 0.

**Comment by ffreyer** [comment]
That's because cameras are picked based on the data_limits of a scene. I'm not sure if basing it of plot argument types (i.e. Point3f0) would work, since that can also be used to set z-order.

You can always use `cam3d!(scene)` (or `lscene.scene`) to force it.

**Comment by ffreyer** [comment]
This has been fixed
