### ISSUE TITLE
`lift` ignores `init` keyword argument

### ISSUE THREAD

**Issue by jhoelck** [MakieOrg/Makie.jl#940]
This issue is related to `AbstractPlotting v0.18.2`. The following minimal example
```julia
using AbstractPlotting: Observable, lift

obs = Observable(0)
inv_obs = lift(inv, obs; init=1.0)
```
returns
```julia
Observable{Float64} with 0 listeners. Value:
Inf
```
irrespective of the value assigned to `init`.

This seems to be connected to a breaking rework of `map!` in `Observables v0.4.0` (JuliaGizmos/Observables.jl#62):
Pinning `Observables` to `v0.3.3` (or `AbstractPlotting` to `v0.15.24`), the above minimal example returns
```julia
Observable{Float64} with 0 listeners. Value:
1.0
```
as [expected](https://makie.juliaplots.org/v0.18.2/abstractplotting_api.html#AbstractPlotting.lift-Tuple{Any,%20Observables.AbstractObservable,%20Vararg{Any,%20N}%20where%20N}).

**Comment by ffreyer** [comment]
Seems like init has been removed. Closing as outdated
