### ISSUE TITLE
Uniform resolution across backends

### ISSUE THREAD

**Issue by piever** [MakieOrg/Makie.jl#993]
The current situation with backends resolutions is the following.

- CairoMakie interprets `(800, 600)` as "units", so it means `600 x 450 pt` or `800 x 600 px` when embedded in a web site
- WGLMakie and GLMakie interpret `(800, 600)` as _device_ pixels, which means they end up with tiny fonts on, e.g., retina displays

Possible solution is to use the resolution in CairoMakie (expressed in units) as the default, and adjust WGLMakie and GLMakie.

- For WGLMakie, it is actually straightforward, as it is easy to give the size in CSS pixels (we have now learned exactly all the bits where code needs to change)
- For GLMakie, it is slightly trickier, but I am curious whether we can keep the meaning of `(800, 600)` as units, and, depending on the pixel size, find a `w x h` such as `(w, h)` times the pixel size on that screen has the same physical dimension as `600 x 450 pt`

This way, we would have by default consistent looks across backends. Especially a consistent font size, which now is problematic.

**Comment by piever** [comment]
Copying a comment from the slack chat, this could be further controllable by a `px_per_unit = 1` in WGLMakie (as an attribute to `Figure`), and a `device_px_per_unit` in GLMakie.

**Comment by ffreyer** [comment]
With #2544 / #3113 (0.20) all backends now use generic units that are scaled with px_per_unit
